### ISSUE TITLE
Extra fields in space hierarchy listing response

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#12169] opened 2022-03-05 12:14 UTC
### Description

Synapse includes at least two fields in the `GET …/hierarchy` space listing response that it probably shouldn't:

* `join_rules` which seems to be duplicating `join_rule`
* `allowed_room_ids`, for restricted rooms

I originally reported this in the spec since I assumed `allowed_room_ids` was actually meant to be received by clients: https://github.com/matrix-org/matrix-spec/issues/984#issuecomment-1059750228

### Steps to reproduce

- Open Element dev Console (Ctrl+Shift+I), Network tab
- List rooms of a space with restricted rooms
- Observe a `GET …/hierarchy` request and its response

### Version information

- **Homeserver**: flipdot.org

If not matrix.org:

- **Version**: 1.53.0
- **Install method**: 🤷🏼
- **Platform**: 🤷🏼

**Comment by reivilibre** [comment] 2022-03-07 14:54
Noting that this seems to be about the *Client-Server* `/hierarchy` API (though maybe it's also worth checking the Server-Server one.

**Comment by clokep** [comment] 2022-03-07 14:57
> though maybe it's also worth checking the Server-Server one

These fields are used by the Server-Server API to pass additional information. They should not be passed down via the Client-Server API.

**Comment by clokep** [comment] 2022-03-07 18:37
We debugged this a little bit and it seems to only happen for restricted rooms that the user is not in.

**Comment by clokep** [comment] 2022-03-07 18:55
I was able to reproduce this in a unit test, it seemed we did the proper thing for the `/spaces` API (which was now removed in #12073), but the `/hierarchy` API has always returned this *if the result was retrieved over federation*.

**Comment by clokep** [comment] 2022-03-07 19:21
Hopefully fixed by #12175, thanks for reporting!

**Comment by reivilibre** [comment] 2022-03-08 10:43
I can reproduce from librepush.net; will DM (may be federation-related)?

**Closed** 2022-03-08 13:09 UTC
Labels: A-Spec-Compliance, S-Tolerable, T-Defect
