### ISSUE TITLE
Upgrading un-Encrypted & public Matrix rooms result in the room becoming E2EE with no input requested from the upgrader

### ISSUE THREAD

**Issue by jahway603** [matrix-org/synapse#14719] opened 2022-12-21 14:10 UTC
### Description

After upgrading an un-Encrypted & public Matrix room, the result is the room becoming E2EE with no input requested from the upgrader & since encryption is turned on (and can never be turned off), this results in breaking any bots bridging to other services as those bridges require that the room remain un-Encrypted for those bots to continue bridging the other services to the Matrix chat room.

There is nothing prompting the person running `/upgraderoom <version-number>` if they want to keep the room un-Encrypted or to force encryption, so I propose a flag be added to the `/upgraderoom` command to do this.

This issue is similar to Issue https://github.com/matrix-org/synapse/issues/9246, but that issue does not provide any solutions. This bug was discovered when a community member upgraded a Matrix room and it broke the bridge bot due to this "uncommon" (classified by @DMRobertson) bug.

### Steps to reproduce

- Create a new Matrix room that is (1) public, (2) NOT encrypted, and (3) this specific server creates a room with version 5
- Run the `/upgraderoom 9` in this room and follow the prompts
- The resulting room is not E2EE when this is not the desired behavior as the upgrader wanted to upgrade their un-Encrypted room

### Homeserver

matrix.lrn.fm

### Synapse Version

1.67.0

### Installation Method

I don't know

### Database

No clue as not server admin

### Workers

I don't know

### Platform

No clue as not server admin

### Configuration

No clue as not server admin

### Relevant log output

```shell
No clue as not server admin
```

**Comment by jahway603** [comment] 2022-12-21 14:14
Would this Issue need to be included in Issue https://github.com/matrix-org/matrix-spec/issues/456 ?

**Comment by clokep** [comment] 2022-12-21 15:39
Duplicate of #9246, I believe.

**Comment by clokep** [comment] 2022-12-21 15:40
> Would this Issue need to be included in Issue [matrix-org/matrix-spec#456](https://github.com/matrix-org/matrix-spec/issues/456) ?

No, this is an implementation bug.

**Closed by clokep** 2022-12-21 15:39 UTC
