### ISSUE TITLE
Verifying user creates new room, does not work if "only encrypt to verified devices" is activated

### ISSUE THREAD

**Issue by witchent** [matrix-org/synapse#8408] opened 2020-09-26 08:03 UTC
### Description

If I try to verify a user with whom I share a room with already, it creates a new room where the other person has to join, and afterwards I can only verify if both users have "only encrypt to verified devices" deactivated, which seems really counter-intuitive.

This might also be a bug of the clients, but as it happens with Element Web and with Element Android I am guessing this is not the case.

### Steps to reproduce
- Join a room where other people are in.
- Try to verify a user of this room.

Edit:// Not restricted to homeserver, I just reproduced it with two accounts on matrix.org.
Will leave everything else in here anyway.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
I expect no new room to be created and the verification to work even with that setting turned on. 
The homeserver.log is completely fine, nothing unexpected in there.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- The issue was between two accounts on my own homeserver, one account on matrix.org with one of mine and between two matrix.org accounts.

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.20.1

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: x86_64 Arch linux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by auscompgeek** [comment] 2020-09-26 08:16
Not a Synapse bug.

Duplicate of https://github.com/vector-im/element-web/issues/13656

**Comment by witchent** [comment] 2020-09-26 08:21
Hm, interesting that this also affect Element Android then. Sorry, looked in the wrong repo.
Was it always the case that it creates a new room as well/is this an Element bug as well? If so I will close this issue.

**Closed** 2020-09-26 08:22 UTC
