### ISSUE TITLE
Display name limit doesn't apply to per-room display names

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#9236] opened 2021-01-27 10:37 UTC
As per [discussion](https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$iPQbTIcztGWabBc-pibIGP4E-6tFtN4Zcmk-dRYsQUI?via=matrix.org&via=privacytools.io&via=dendrite.matrix.org) in Matrix HQ, it seems like [Synapse's limit to display name length](https://github.com/matrix-org/synapse/blob/7a2e9b549defe3f55531711a863183a33e7af83c/synapse/handlers/profile.py#L43) doesn't apply to per-room display names.

**Comment by anoadragon453** [comment] 2021-01-27 10:47
This would just be adding a length check to `update_membership_locked` that would fail the request if the length was too long. Similar to where we prevent per-room profile changes entirely:

https://github.com/matrix-org/synapse/blob/6633a4015a7b4ba60f87c5e6f979a9c9d8f9d8fe/synapse/handlers/room_member.py#L358-L365

**Comment by b-thebest** [comment] 2021-03-04 09:45
Can I work on  this issue ??

**Comment by anoadragon453** [comment] 2021-03-04 10:46
@b-thebest Of course!

**Comment by b-thebest** [comment] 2021-03-04 10:51
Please assign this task to me

**Comment by arya2331** [comment] 2021-04-15 16:53
is someone still working on it? or I can do this?

**Comment by b-thebest** [comment] 2021-04-15 17:09
I am working on it

**Comment by richvdh** [comment] 2021-04-15 17:24
@b-thebest do you have any idea of when you expect to make some progress on it? I don't think it's a big job and if others are ready to pick it up it might be nice to let them do so.

**Comment by b-thebest** [comment] 2021-04-15 17:27
It was not in list of task assigned to me, that's why I was unable to do
it. I will do it now asap

**Comment by anoadragon453** [comment] 2021-05-18 15:36
Hey @b-thebest, have you been able to make any progress on this?

**Comment by b-thebest** [comment] 2021-05-18 17:32
Yes I was working on it. Sorry for being late, during past days my health conditions were not good that's why I was unable to complete it. From today I will take it on and try to complete it as soon as possible

**Comment by richvdh** [comment] 2021-05-24 13:30
As is normal in open-source projects, we don't generally "assign" issues to individual contributors, and you shouldn't consider this a prerequisite to start work on it.

**Comment by lukasdenk** [comment] 2022-01-03 10:09
@Azrenbeth Should this issue still be open? According to #10654 the issue is solved.

**Closed** 2022-01-04 11:12 UTC
Labels: Z-Help-Wanted, good first issue, S-Minor, T-Defect
