### ISSUE TITLE
Increased cpu/gc usage in event persistence workers in 1.91.0rc1

### ISSUE THREAD

**Issue by tulir** [matrix-org/synapse#16190] opened 2023-08-26 20:57 UTC
### Description

After updating to 1.91.0rc1, the CPU usage of my event persisters started growing steadily. I can't find any obvious reason for it, but the GC charts are also way up

![image](https://github.com/matrix-org/synapse/assets/4224639/98785051-ee51-4820-9ab4-2047105a212d)
![image](https://github.com/matrix-org/synapse/assets/4224639/719e5d7f-57f0-467a-bc19-c58ace915dd2)

I just restarted the workers and the CPU usage went back down to normal. Will see tomorrow if it starts climbing again

### Steps to reproduce

- Update to 1.91.0rc1
- Observe event persistence worker CPU usage increasing steadily over a few days

### Homeserver

maunium.net

### Synapse Version

1.91.0rc1

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

Custom docker image

**Comment by cremesk** [comment] 2023-08-26 21:00
I can also observe the same behavior here.

![image](https://github.com/matrix-org/synapse/assets/7526990/98eb5d47-9f42-48fa-a3a0-aaa7c44802b3)

![image](https://github.com/matrix-org/synapse/assets/7526990/ee40d526-28e9-4875-a9e5-ff1f1ccad455)

**Comment by jameskitt616** [comment] 2023-08-28 06:04
![image](https://github.com/matrix-org/synapse/assets/52933658/5e5a9bd9-8f4c-40fc-a3fa-bbfcc153d3d1)

I've got similar behaviour. But i am currently on `1.90.0` i dont exactly remember when i upgraded to which version the past days, but you can clearly see the cpu usage slowly growing over the past days.

**Comment by fir3drag0n** [comment] 2023-08-28 08:27
same problem here with docker:

![image](https://github.com/matrix-org/synapse/assets/36398628/7c638bc3-72e3-464a-92af-6234bdf6268d)

**Comment by clokep** [comment] 2023-08-28 12:08
Any particular jump in the `Per-block metrics` section of the dashboard or does it all seem to be due to increased GCs? I'm assuming the Python version was not changed during this and the jump was 1.90.0 -> 1.91.0rc1 -- is that correct?

**Comment by tulir** [comment] 2023-08-28 12:50
Python version has been 3.11 for a while now so shouldn't be any changes there

Nothing jumps out in per-block metrics

![image](https://github.com/matrix-org/synapse/assets/4224639/1adef799-9c69-48cf-9999-62cb1d8c76f9)
![image](https://github.com/matrix-org/synapse/assets/4224639/0037a18e-4642-44a1-8b71-dcfe106fb7f4)

GC from same period (restarted the two workers when I made this issue, the times went back down and started climbing again):

![image](https://github.com/matrix-org/synapse/assets/4224639/30b4eef6-9056-4950-a6a1-a34a351fa69d)
![image](https://github.com/matrix-org/synapse/assets/4224639/90155b10-398d-4faf-809a-9bd3aecfcdd3)

**Comment by MatMaul** [comment] 2023-08-29 12:25
on matrix.org, we can see a change in the GC behavior, but not a degradation with increasing CPU usage like you.

![image](https://github.com/matrix-org/synapse/assets/1643573/312e9626-dd60-42eb-bba2-ae99661c5a36)

It seems like the GC is running less often but with more objects collected on each pass.

May we know if you have presence enabled, reporters ?

**Comment by DMRobertson** [comment] 2023-08-29 12:33
Tricky to advise without being able to reproduce it on our end. If anyone is able to, it would be super useful to bisect through Synapse versions to see when this was introduced.

**Comment by DMRobertson** [comment] 2023-08-29 12:41
Sorry, I misspoke: I should have said "bisect through Synapse commits" instead of "versions".

Matrix.org is running v1.91.0rc1, except that its version string has not been updated to reflect this, and per https://github.com/matrix-org/synapse/issues/16190#issuecomment-1697346057 we do not see the same behaviour.

**Comment by cremesk** [comment] 2023-08-29 13:43
okay, I'm surprised that you guys can't see the problem on matrix.org. here it has clearly started with the version upgrade.

since I use the finished deb file from packages.matrix.org it is a bit difficult/cumbersome for me to debug which commit the issue came with.

![image](https://github.com/matrix-org/synapse/assets/7526990/b29e4cc0-0169-4579-abb1-02dc042af5f2)

![image](https://github.com/matrix-org/synapse/assets/7526990/1c683833-da5a-46fa-a32b-42fa71352985)
![image](https://github.com/matrix-org/synapse/assets/7526990/35292d62-a4bb-4873-80b4-edbbff0cee1d)

**Comment by warioishere** [comment] 2023-08-30 09:31
I also saw increasing CPU Usage and disk IO but already since 1.90 stable. Didnt upgrade to 1.91rc

after I added this to homeserver.yml I saw instantly a positiv impact. Dont know if this similar to the issue on 1.91rc

```
federation:
  destination_min_retry_interval: 10m
  destination_retry_multiplier: 5
  destination_max_retry_interval: 365d
```

![matrix-cpu-usage](https://github.com/matrix-org/synapse/assets/117512622/8d38a29d-2e29-4cd6-bd2f-459340fde9f0)

**Comment by jaywink** [comment] 2023-08-31 20:09
We're getting hit by this possibly in EMS as well for a lot of hosts, and have proceeded with a rollback out of caution. Some examples with internal host ID's:

`ecf6bc70-0bd7-11ec-8fb7-11c2f603e85f-live`, showing post-update event send time and event persister CPU rise and eventual rollback to v1.90.0:

![image](https://github.com/matrix-org/synapse/assets/1174866/2e3eff3e-b3dd-452e-8daa-27ea3f65428a)

GC for the same host:

![image](https://github.com/matrix-org/synapse/assets/1174866/353abfb3-feb7-4996-8bea-58ebd14e47cb)

Host `c2e1fb80-f9a6-11ec-b22e-319e919febc8-live` which is way less busy but also shows event send times degrading:

![image](https://github.com/matrix-org/synapse/assets/1174866/a17fc19c-e39f-46b8-b744-96c72fee0d89)

GC has the same trend:

![image](https://github.com/matrix-org/synapse/assets/1174866/e381bc18-64f9-431e-b3f0-a0a3eb9d4dd8)

It does not look like all hosts have suffered in the same way. Some hosts with an event persister have their usual metrics pattern in event send times, CPU and GC.

**Comment by jaywink** [comment] 2023-08-31 21:10
I'm also seeing this pattern on some hosts without an event persister, for example `94922e70-d385-11e9-bee2-2b7ad79f31cb-live`, increasing GC until restart on 1.90.0:

![image](https://github.com/matrix-org/synapse/assets/1174866/7aea7677-3128-4228-a3eb-3d2d4030bf51)

Event send time also regressed but CPU did not:

![image](https://github.com/matrix-org/synapse/assets/1174866/b4b4d1d1-6148-4a4e-b56d-6bd20beb0bbb)

This Synapse deployment has no workers, and on EMS we've seen quite a few deployments without workers alert on event send times regressing.

**Comment by DMRobertson** [comment] 2023-09-01 14:59
> Matrix.org is running v1.91.0rc1, except that its version string has not been updated to reflect this, and per [#16190 (comment)](https://github.com/matrix-org/synapse/issues/16190#issuecomment-1697346057) we do not see the same behaviour.

This wasn't the whole truth :disappointed:; we have a working hypothesis as to the cause.

Current thinking is that https://github.com/matrix-org/synapse/pull/16220 will fix this. If we can verify this I think we'll likely put out a bugfix release early next week.

**Comment by tulir** [comment] 2023-09-01 17:45
Cherry-picked that onto maunium.net and it seems to be fixed, gc frequency of the event persisters has stayed relatively flat around around 0.2Hz for 2 hours now

**Comment by tulir** [comment] 2023-09-02 09:37
![image](https://github.com/matrix-org/synapse/assets/4224639/3f45761d-93a4-4c87-b97d-236df8820fb6)
![image](https://github.com/matrix-org/synapse/assets/4224639/77833e95-1506-42c9-a2e2-1d8e2887f714)

**Comment by DMRobertson** [comment] 2023-09-04 12:41
Thanks for cherry-picking and confirming @tulir. Let's consider this closed by that chance. I will prepare a patch 1.91.1 patch release now.

**Closed by DMRobertson** 2023-09-04 12:41 UTC
Labels: A-Performance, A-Workers, T-Defect, X-Regression
