### ISSUE TITLE
Device lists can get badly out of sync during federation outages, breaking E2EE

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5095] opened 2019-04-25 12:02 UTC
After the matrix.org breach, there were a lot of UISIs for matrix.org<->elsewhere E2E rooms.  Circumstantially we're assuming that this servers ended up with an inconsistent view of the devices present in a room.

Possible causes are:
 * If an m.device_list_update EDU gets lost, servers will be stuck with the stale list until the next m.device_list_update from that server, which happens infrequently.
 * However, EDUs should not get lost; we should retry m.device_list_updates until we get a 200, so it seems there is a bug here.
 * If we see an unrecognised device from a server, should we not re-sync our view of that server's device list anyway?
 * In theory we re-sync our view of the device list when we see an m.device_list_update which refers to an unknown previous m.device_list_update.  But this might not be working?

(See https://github.com/vector-im/riot-web/issues/2996 for the main UISI bug)

**Comment by richvdh** [comment] 2019-05-01 07:32
For the record: https://github.com/matrix-org/synapse/issues/4877 was a significant cause of this (people were missing the unique index on device_lists_remote_cache which meant that they ended up ignoring device list updates), but it sounds like other things may have been going on too.

**Comment by cyphar** [comment] 2019-05-15 11:58
Device lists getting out of sync (resulting in broken E2EE) is a very common problem I've run into (in fact, I only have one E2EE room where this doesn't happen on a regular basis). Usually the failure scenario is `@alice:matrix.org` not being able to read messages from a few of `@bob:foo.xyz`'s devices while `@bob:foo.xyz` can read all messages from `@alice:matrix.org`. Creating new rooms doesn't help (unsurprisingly since the issue is with `matrix.org`'s view of `@bob:foo.xyz`'s devices list) -- the messages all have an unknown device ID.

While this might be a failure on the part of `foo.xyz`'s sysadmin, it's very worrying that E2EE has such a common flaw over federation. It's so significant that I'm concerned about self-hosting because of the potential to (seemingly) permanently break chats with other users.

(I saw this when I was setting up `cyphar.com` which used postgres as the database from the outset.)

**Comment by ara4n** [comment] 2019-06-12 16:35
I just reproduced this perfectly between 1.0.0 on matrix.org & arasphere.net.  Arasphere.net went down at 11am; and every message in every E2E room since that point is now UISI having turned it back on at 17:34.  The devices on arasphere.net did not change in this window however - i did not log into any new devices etc.

**Comment by ara4n** [comment] 2019-06-12 16:37
...except now some of the UISIs have gone away, presumably as the megolm session details which were cued up over federation finally got exchanged on the server coming back.

**Comment by ara4n** [comment] 2019-06-12 16:44
so the sessions which came back were from matrix.org. the ones from vector.modular.im however didn't, and are UTD & unknown message index errors.  And i guess this is not to do with device lists anyway.

**Comment by ara4n** [comment] 2019-06-12 19:16
(have filed #5441 to track an issue i mistook for this one)

**Comment by cyphar** [comment] 2019-06-13 01:22
I finally figured out the cause of the above comment and have filed a separate issue for it in #5433.

**Comment by richvdh** [comment] 2019-06-20 10:06
with #5156 done, and #5320 fixing the `device_lists_remote_cache` index, I think we've fixed most of the known causes of this issue, so I am closing it for now.

**Closed by richvdh** 2019-06-20 10:06 UTC
Labels: bug, p1
