### ISSUE TITLE
Virtual Hosting

### ISSUE THREAD

**Issue by Natureshadow** [matrix-org/synapse#8910] opened 2020-12-09 18:34 UTC
**Description:**

I would like to make my Synapse host users for several domains. I do not need much flexibility — taking the HTTP Host header, match it against a list of allowed hosts, and override the server host name with it throughout the request would be enough. In the first step, it would not even need to have specific configursation for each host (like authentication sources, etc.).

The goal is that I want multiple domains to end up on the same Synapse, so I can operate Matrix on several domains, and users on each domain can participate in federated rooms without having to servers, and two databases, receive and store all the federated events.

**Comment by clokep** [comment] 2020-12-09 18:54
I think this is a duplicate of #8885. Shout if it isn't and we can re-open!

**Closed by clokep** 2020-12-09 18:54 UTC

**Comment by Natureshadow** [comment] 2020-12-09 19:39
Oh. Sorry. I had this sitting here for a few days, and failed to scan the issue list again before submitting :o!
