### ISSUE TITLE
[Feature] Matrix/Synapse does not prevent deep linking of shared files.

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#5017] opened 2019-04-05 17:07 UTC
In a private room (1-to-1 conversation) I shared a picture and then copied the link to the uploaded picture file. I opened another browser and was able to view the image even though I wasn't signed in.

So it seems that there are no access rights for uploaded/shared files in place, which in my opinion is a (considerable) lack of security.

Would be great if you could provide an internal API for accessing files that checks access permissions upon a request.

**Comment by turt2live** [comment] 2019-04-05 17:08
Duplicate of https://github.com/matrix-org/synapse/issues/2150

**Closed by turt2live** 2019-04-05 17:08 UTC
