### ISSUE TITLE
Add info on changing HS name

### ISSUE THREAD

**Issue by jcahill** [matrix-org/synapse#2448] opened 2017-09-12 02:01 UTC
I need to change the tld of a homeserver. A blurb on migrating accounts from `user:hs.old` to `user:hs.new` would be useful.

**Comment by maxidor** [comment] 2017-09-15 01:37
No migration path, as this is not supported and will not work in a federated/decentralized environment.
It's not so much about hacking around in your database, it's about what **OHTER** servers know about you.

All the data you shared with them will become invalid on your end, you won't be able to do anything anymore, including in your own domain as signatures of events will all fail...

So.... there is no migration.

**Comment by eqyiel** [comment] 2017-09-16 01:14
Related: https://github.com/matrix-org/synapse/issues/1209 https://github.com/matrix-org/synapse/issues/2040

**Comment by aaronraimist** [comment] 2018-12-02 19:59
Yes this is basically a duplicate of #1209 since that isn't currently supported

**Comment by gerroon** [comment] 2019-03-30 19:01
Is this possible if I dont give a crap about federation?

**Comment by gerroon** [comment] 2019-03-30 19:01
Is this possible if I dont give a crap about federation?

**Comment by richvdh** [comment] 2019-09-19 18:22
closing as a dup of #1209

**Closed by richvdh** 2019-09-19 18:22 UTC
