### ISSUE TITLE
Ways to decrease size of Synapse database - state_groups_state table is too large

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#7472] opened 2020-05-12 11:21 UTC
Problem with very large size of Synapse PostgreSQL database table is very popular, and I can't find any good instructions how to decrease the size, so fill support issue here for make it available for others via googling.

Our public homeserver ru-matrix.org with about 20 local users - after 2 years of working got total size of pgsql table is 123GB!

As I understand, main tables, that store all events are `events` (8gb) and `event_json` (22gb), all other tables is generate data from it.

But in our database most size eats `state_groups_state` table, that have 274 millions of rows and 51GB size!

Is there any ways exists for reduce it size? Maybe exists some scripts for compress, deduplicate, regenerate, optimize, purge old/unused data in it?

I already try execution [synapse-compress-state](https://github.com/matrix-org/rust-synapse-compress-state) on larger rooms in my homeserver (Matrix HQ, Riot-*, KDE, etc), but the total size of  `state_groups_state` table is still large, so I can't understand what to do next. 

Comparing with real state storage table `state_events`, that have 5 millions of rows, I can't understand why `state_groups_state` so large?

Is it store many duplicates of data from `state_events`? If yes, maybe exists ways to deduplicate it?

If this is not duplicates, maybe I can purge old or rarely used data from local database, to sync it on demand from other servers via federatation?

**Comment by MurzNN** [comment] 2020-05-12 11:31
Here is statistics of table size in our Synapse database:
relation | total_size
-- | --
state_groups_state | 51 GB
event_json | 22 GB
events | 8853 MB
event_edges | 8477 MB
event_reference_hashes | 4519 MB
stream_ordering_to_exterm | 4340 MB
event_auth | 3719 MB
event_search | 3637 MB
received_transactions | 2815 MB
event_to_state_groups | 2555 MB
room_memberships | 2102 MB
current_state_delta_stream | 1306 MB
state_events | 1232 MB
current_state_events | 958 MB
cache_invalidation_stream | 850 MB
receipts_linearized | 794 MB
presence_stream | 771 MB
state_groups | 604 MB
event_forward_extremities | 347 MB
state_group_edges | 337 MB

**Comment by clokep** [comment] 2020-05-12 13:09
Maybe related to #3364.

**Comment by richvdh** [comment] 2020-05-12 14:30
I wrote a load of stuff about how state_groups_state works at https://github.com/matrix-org/synapse/wiki/State-Groups.

Honestly, `state_groups_state` being only twice the size of `event_json` doesn't sound so bad to me. I think this is probably just a duplicate of #3364.

**Closed by richvdh** 2020-05-12 14:30 UTC

**Comment by MurzNN** [comment] 2020-05-13 10:10
> Honestly, state_groups_state being only twice the size of event_json doesn't sound so bad to me.

Table `event_json` contains full data from event, including message. So we must compare not total size, but total rows, and rows in `state_groups_state` have 18 times more rows, than `event_json`. And yes, let's continue investigating this issue in #3364

**Comment by MurzNN** [comment] 2020-06-23 12:53
I have found good article with ways to compress Synapse database: https://levans.fr/shrink-synapse-database.html
