### ISSUE TITLE
Room does not appear in /sync if /join after /leave and /forget

### ISSUE THREAD

**Issue by hyossing** [matrix-org/synapse#8803] opened 2020-11-24 04:13 UTC
Hello,

Room information does not appear in /sync if join after leave and forget in a same room.

But, the room does appear in /joined_rooms.

If I restarts synapse, then the room is appeared in /sync.

Could you verify about it?

Best Regards
Hyosung Lim

**Comment by clokep** [comment] 2020-11-24 13:37
@hyossing Could you clarify the steps you're taking? It sounds like:

1. Join a room.
2. Leave a room.
3. Forget a room.
4. Re-join the room.
5. Check sync.

Is that accurate? The first step to seeing what's going on is usually to provide Synapse logs (at INFO level) around the time when you're reproducing this behavior.

**Comment by hyossing** [comment] 2020-11-25 11:15
> @clokep Yes, the steps are correct.

**Comment by hyossing** [comment] 2020-11-25 11:17
@clokep I'll upload Synapse Logs. Let you know.

**Comment by richvdh** [comment] 2020-11-25 13:27
sounds like https://github.com/matrix-org/synapse/issues/3305 to me

**Comment by richvdh** [comment] 2020-11-25 13:27
sorry, I mean #1413

**Comment by clokep** [comment] 2020-11-25 18:41
Seems to be. I'm going to close this then. @hyossing give a shout if that doesn't seem to be the same problem.

**Closed by clokep** 2020-11-25 18:41 UTC
Labels: info-needed
