### ISSUE TITLE
monthly_active_users table gets a ton of locks

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4318] opened 2018-12-21 03:04 UTC
```
 blocked_pid | blocked_user | blocking_pid | blocking_user |                 blocked_statement                 |                            current_statement_in_blocking_process
-------------+--------------+--------------+---------------+---------------------------------------------------+---------------------------------------------------------------------------------------------
       10476 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10471 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10473 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10418 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10441 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10436 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10481 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
       10475 | t2botsynapse |        10405 | t2botsynapse  | LOCK TABLE monthly_active_users in EXCLUSIVE MODE | LOCK TABLE monthly_active_users in EXCLUSIVE MODE
```

~1100 records not shown

This is with:
```
track_appservice_user_ips: true
mau_stats_only: true
```

**Comment by turt2live** [comment] 2018-12-21 03:06
Metrics-wise, it does this:
![image](https://user-images.githubusercontent.com/1190097/50322537-9f8c0200-0492-11e9-912e-b4ed9836f2ec.png)

(dip is where the upgrade to 0.34 happened)

Server is on python 2.7 at this time. Requests are failing due to the master process being effectively deadlocked waiting for the MAU transactions.

**Comment by turt2live** [comment] 2018-12-21 03:13
Previously there were limited locks on the table, and they were introduced in fixing https://github.com/matrix-org/synapse/issues/3854

**Comment by hawkowl** [comment] 2018-12-21 03:46
@turt2live if you're feeling adventurous, could you try https://github.com/matrix-org/synapse/pull/4306 and see if that reduces the locking? It makes upserts atomic on Pg9.5+.

**Comment by turt2live** [comment] 2018-12-21 04:06
https://github.com/matrix-org/synapse/pull/4306 does indeed appear to fix the issue, and theoretically would also allow for `lock=False` to be added back in as the upsert should lock the row appropriately. Then again, it might be needed still if people are using old postgres/sqlite (then again, do we really care at that point? postgres would be ancient and sqlite is sqlite).

**Comment by turt2live** [comment] 2018-12-21 04:57
Turns out I was wrong about #4306 working. #4306 adds the native upsert on `_simple_upsert` but not `_simple_upsert_txn` (which is used by the MAU stuff). Also, the native upsert always returns `true` even if the update was an update (instead of an insert). 

Out of fear of breaking the rest of synapse, I just modified the MAU stuff to use `_simple_upsert_txn_native` directly instead of fixing `_simple_upsert_txn` to use the native one too. Because the MAU stuff only invalidates some caches, it is relatively safe to let it always think that the user was inserted however this might not be okay for the rest of synapse.

Additionally, my postgres is still angry for some dumb reason:
```
2018-12-21 05:32:58.823 CET [12434] t2botsynapse@t2b_synapse ERROR:  duplicate key value violates unique constraint "monthly_active_users_users"
2018-12-21 05:32:58.823 CET [12434] t2botsynapse@t2b_synapse DETAIL:  Key (user_id)=(@redacted:t2bot.io) already exists.
2018-12-21 05:32:58.823 CET [12434] t2botsynapse@t2b_synapse STATEMENT:  INSERT INTO monthly_active_users (timestamp, user_id) VALUES (1545366778821, '@redacted:t2bot.io') ON CONFLICT (user_id) DO UPDATE SET timestamp=EXCLUDED.timestamp
```

It appears as though dropping the index and recreating it fixes it (I haven't seen it in the ~10 minutes synapse has been running), although it is questionable how there got to be such a broken index in the first place.

**Comment by turt2live** [comment] 2018-12-21 04:59
and yet another update:
Recreating the index does indeed fix the postgres problem, although the new error is:
```
2018-12-21 05:56:40.455 CET [12805] t2botsynapse@t2b_synapse ERROR:  could not serialize access due to concurrent update
2018-12-21 05:56:40.455 CET [12805] t2botsynapse@t2b_synapse STATEMENT:  INSERT INTO monthly_active_users (timestamp, user_id) VALUES (1545368200453, '@redacted:t2bot.io') ON CONFLICT (user_id) DO UPDATE SET timestamp=EXCLUDED.timestamp
```

**Comment by richvdh** [comment] 2018-12-21 10:38
I'm a bit confused about what introduced this change. @turt2live says

> Previously there were limited locks on the table, and they were introduced in fixing #3854

but the fix to #3854 (#3961) landed in 0.33.6, so unless you've just upgraded from something earlier than that (?), it doesn't really explain why it suddenly started now.

**Comment by turt2live** [comment] 2018-12-21 15:17
I was upgrading from 0.34-rc2 to develop. I think what happened was a large queue of events got drained as soon as the server came back alive. Combined with the startup routines of synapse for mau, it deadlocked.

**Comment by neilisfragile** [comment] 2018-12-21 22:37
Okay so sounds like the strategy to fix this is to wait for #3854 to land then either modify just```upsert_monthly_active_user_txn``` to call the native form, or to modify _simple_upsert_txn if the act of always returning true regardless of insert or update can be shown to be safe.

**Comment by turt2live** [comment] 2018-12-21 22:45
@neilisfragile do you mean https://github.com/matrix-org/synapse/pull/4306 ?

**Comment by richvdh** [comment] 2018-12-27 17:10
> I think what happened was a large queue of events got drained as soon as the server came back alive. 

Ok so this isn't anything specific to 0.34?

**Comment by turt2live** [comment] 2018-12-27 17:12
on retrospect, probably not. It was just a convenient time for it to all fall apart. I haven't tested or reproduced the issue on earlier versions, however. I also haven't been able to replicate the exact conditions since upgrading.

**Comment by hawkowl** [comment] 2019-01-09 14:34
I am going to close this in favour of the root cause of locks in this area, https://github.com/matrix-org/synapse/issues/4015 .

**Closed by hawkowl** 2019-01-09 14:34 UTC
Labels: bug
