### ISSUE TITLE
Support proxy server for outbound federation

### ISSUE THREAD

**Issue by sim0nx** [matrix-org/synapse#8859] opened 2020-12-02 12:13 UTC
**Description:**
In a setup where there is the synapse server (machine B) behind a reverse proxy (machine A), the two being on two different machines, and the machine running synapse not having direct internet access (but only via proxy) it should be possible to proxy the federation connections.
Just as is done e.g. for notifications.

<internet> -- reverse proxy (machine A)  -- synapse (machine B, access to internet only via proxy)

There was already an issue on this (#4198) although the implementation which resulted out of that (#6239) explicitly does not support proxy support for federation.

**Comment by clokep** [comment] 2020-12-02 12:22
Thanks for filing this! It is definitely something we should do at some point. I'm going to close this as a duplicate of #8660.

**Closed by clokep** 2020-12-02 12:22 UTC
