### ISSUE TITLE
DockerHub - Implement Latest Tag 

### ISSUE THREAD

**Issue by benyanke** [matrix-org/synapse#3477] opened 2018-07-03 05:29 UTC
Currently, there's no latest tag, which is not typical for repos.

Could I propose that the latest tag be set to build on every stable release?

**Comment by turt2live** [comment] 2018-07-03 05:37
Duplicate of https://github.com/matrix-org/synapse/issues/3407

**Closed** 2018-07-03 05:41 UTC
