### ISSUE TITLE
--no-use-pep517 needed for pip install -U matrix-synapse[all] 

### ISSUE THREAD

**Issue by echto** [matrix-org/synapse#4848] opened 2019-03-12 00:23 UTC
### Description
Tried up upgrade synapse and install fails.  

Command "/home/matrix/synapse/env/bin/python3 /home/matrix/synapse/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpcn297ioh" failed with error code 1 in /tmp/pip-install-4d7uxxg9/matrix-synapse

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

pip install -U matrix-synapse[all] 
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

Install fails with error message.

### Version information

What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.1.1

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->
pip install
- **Platform**: 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Gentoo 5.0.0-gentoo  1920 Threadripper 

-**Solution**:  Add --no-use-pep517 to the upgrade command: pip install -U matrix-synapse[all] --no-use-pep517

**Comment by richvdh** [comment] 2019-03-13 09:21
your bug report is quite hard to read - any chance you could take the time to make it more understandable?

Please could you also take the time to explain what this flag does, and why it has become necessary? Does it not rely on a particular version of `pip` which most users will not have?

**Comment by richvdh** [comment] 2019-03-15 10:20
possibly the same as #4860? Closing for now as it's far from clear what the problem is.

**Closed by richvdh** 2019-03-15 10:20 UTC

**Comment by richvdh** [comment] 2019-04-25 13:51
I guess it's related to #5096
