### ISSUE TITLE
/sync slow to notify about events when timeout=0

### ISSUE THREAD

**Issue by swedgwood** [matrix-org/synapse#15502] opened 2023-04-28 01:04 UTC
### Description

- If you query `/_matrix/client/v3/sync?since=SYNCTOKEN&timeout=TIMEOUT` (where `SYNCTOKEN` is some sync token and `TIMEOUT` is some timeout) when there isn't any new state, the response's `next_batch` will be identical to `SYNCTOKEN`.
- So, when the client is polling, it will make repeated requests to this same URL until there is new state. (Which is normal/expected behaviour as far as I know)
- Expected behaviour is:
  - If an event is sent to a room after a sync request has been sent, but before the timeout has elapsed
    - THEN, the sync request is responded **with the new events** to fairly soon after the event has sent
  - If an event is sent to a room before a sync request has been sent
    - THEN, as soon as the next sync request is sent, a sync response will be immediate and **will contain the new events**

Whilst this seems to be the most of the time, there's a scenario where it doesn't happen
- timeout=0
- At least one empty sync response has been received for the current sync token (i.e. the sync request referred to in the expected behaviour above comes after at least one empty sync response)

In this scenario, it takes about 2 minutes for the new event to show up in the sync response

Here's a script that recreates the bug (with included example output) https://gist.github.com/swedgwood/3d17193e465871518d499b584c7c574c

There's also a similar sounding issue which was marked as resolved by the author https://github.com/matrix-org/synapse/issues/14713 which they fixed by adjusting the cache time.

I'm not familiar with synapse internals, but I'd hazard to guess that something about timeout=0 changes the way caching works - so when the same sync token is used twice, the previous result is cached for the default cache time of about 2 minutes, which coincides with how long it takes for the event to show up in the sync response. 

### Steps to reproduce

- Set up a new account and join one new room
- In one session, keep syncing, with `timeout=0` until the sync response is empty, and so the response's `next_batch` provides the same sync token that was used in the request.
- Send a message to the room
- Sync again, and notice that the response is still empty, despite the new event
- Keep trying to sync over the next two minutes, and notice that the result keeps being empty, until after the 2 minutes is up, when the sync response finally has the new event

(These steps to reproduce rely on sending a message to a room, but if my caching theory is correct, then I think this should occur with any kind of state change that would cause the sync response to be non-empty)

Also see this script for reproducing this error https://gist.github.com/swedgwood/3d17193e465871518d499b584c7c574c

### Homeserver

personal homeserver

### Synapse Version

v1.82.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

single postgresql + previously ported from sqlite

### Workers

I don't know

### Platform

Running in a container on podman on Fedora CoreOS, on a VPS.

### Configuration

All defaults

### Relevant log output

```shell
Not sure what logs would be relevant.
```

**Comment by clokep** [comment] 2023-05-01 12:42
I think this is a duplicate of #15500, but I'm not really sure.

**Comment by squahtx** [comment] 2023-05-03 19:19
As a workaround, a low value of timeout, such as `1`, will sidestep the bug while still guaranteeing almost-immediate responses.

**Comment by Nathamuni** [comment] 2023-05-05 08:10
use std::time::{Duration, SystemTime};

use matrix_sdk::{
    config::{SyncSettings, TimelineLimit},
    room::Joined,
    ruma::{events::room::message::RoomMessageEventContent, RoomId},
    Client, LoopCtrl,
};

const HOMESERVER_URL: &str = "<homeserver url>";
const DEVICE_ID: &str = "TESTDEVICE";
const USERNAME: &str = "<username>";
const PASSWORD: &str = "<password>";
const ROOM_ID: &str = "<room id>";

#[tokio::main]
async fn main() {
    let client = Client::builder()
        .homeserver_url(HOMESERVER_URL)
        .build()
        .await
        .unwrap();

    client
        .login_username(USERNAME, PASSWORD)
        .device_id(DEVICE_ID)
        .initial_device_display_name(DEVICE_ID)
        .await
        .unwrap();

    let room_id: RoomId = ROOM_ID.parse().unwrap();

    for (pre_sync, timeout) in [(false, 1), (false, 0), (true, 1), (true, 0)] {
        let elapsed = fun(&client, &room_id, pre_sync, Duration::from_millis(timeout)).await;
        println!("pre_sync={} timeout={} took {}ms", pre_sync, timeout, elapsed);
    }
}

async fn fun(client: &Client, room_id: &RoomId, pre_sync: bool, timeout: Duration) -> u128 {
    if pre_sync {
        client
            .sync_once(
                SyncSettings::default()
                    .timeout(timeout)
                    .room_timeline_limit(TimelineLimit::Full),
            )
            .await
            .unwrap();
    }

    let resp = client
        .room_send(room_id, RoomMessageEventContent::text_plain("hello, world!"), None)
        .await
        .unwrap();

    let expected_event_id = &resp.event_id;
    let start = SystemTime::now();

    loop {
        let sync_response = client
            .sync_once(
                SyncSettings::default()
                    .timeout(timeout)
                    .room_timeline_limit(TimelineLimit::Full),
            )
            .await
            .unwrap();

        if let Some(event) = sync_response
            .rooms
            .join
            .get(room_id)
            .and_then(|joined_room| joined_room.timeline.events.iter().find(|ev| &ev.event_id == expected_event_id))
        {
            break;
        }
    }

    start.elapsed().unwrap().as_millis()
}
#15500 #15500 has been resolved

**Comment by vemmos** [comment] 2023-06-24 15:33
Hey! Still open right?

**Closed** 2023-08-17 09:22 UTC
Labels: A-Sync, good first issue, S-Minor, T-Defect, O-Uncommon
