### ISSUE TITLE
Federation working with some servers but not others

### ISSUE THREAD

**Issue by wrotruck** [matrix-org/synapse#9526] opened 2021-03-02 14:06 UTC
New Synapse installation is able to show public rooms and join rooms on some home servers but not others. (Can see and join on raim.ist but not on matrix.org, gitter.im or devture.com.)

Attempts to view those rooms give this error:
`Failed to find any key to satisfy VerifyJsonRequest(server=rotruck.net, key_ids=['ed25519:a_Iknt'], min_valid=1614691320799)`

Attempts directly join a room directly via it's address give this error:
`M_UNKNOWN was returned while trying to access the room.`

Direct messages work also work on some servers but not others.

It would appear to be a TLS issue but Matrix Federation Tester shows no errors:
[https://federationtester.matrix.org/#rotruck.net](url)

`return await self.transport_layer.make_query(File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/federation/transport/client.py",`
`line 172, in make_query content = await self.client.get_json(File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py",`
`line 865, in get_json response = await self._send_request_with_optional_trailing_slash(File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py",`
`line 297, in _send_request_with_optional_trailing_slash response = await self._send_request(request, **send_request_args)File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py",`
`line 542, in _send_request raise exc synapse.api.errors.`
`HttpResponseException: 401: Unauthorized`

### Steps to reproduce

- Install & configure a new server
- Create an admin user
- Log into that server with Element instance on Riot.im
- Attempt to Explore public rooms
- Attempt to directly join a public room

<!--
If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- another home server: marix.rotruck.net

If not matrix.org:

<!--
 What version of Synapse is running? 

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- Synapse 1.28:

-apt package manager from matrix.org repository
<!-- examples: package manager/git clone/pip  -->

- Ubuntu Server 20.4 LTS:
<!--
-->
The home server is running in a VM on an Unraid Server.

**Comment by ShadowJonathan** [comment] 2021-03-02 14:10
`curl https://rotruck.net/.well-known/server` and
`curl https://rotruck.net/_matrix/federation/v1/version` are returning a default-esc HTML page for me, and `rotruck.net:8448` is giving me "connection refused'.

Are you sure you set up your reverse proxy and everything correctly?

**Comment by ShadowJonathan** [comment] 2021-03-02 14:15
Ah, i see you've set everything up under `matrix.rotrick.net`, matrix doesn't know that, you need to set up the following under `rotruck.net/.well-known/matrix/server`;

```json
{
    "m.server": "matrix.rotruck.net:443"
}
```

You need to make it so that that URL returns that file, or else matrix servers cannot "see" *your* matrix server.

**Comment by wrotruck** [comment] 2021-03-02 15:44
looks like your first curl command missed "matrix" in the URL

currently the "well know matrix server" file sits as an entry in the nginx conf.  looks like this:
`        location /.well-known/matrix/server {
        default_type application/json;
               return 200 '{"m.server": "matrix.rotruck.net:443"}';
             add_header Access-Control-Allow-Origin *;
        }`

Also, in the absence of a well-know server file, shouldn't the location have been picked up by the SRV DNS record?  

It also doesn't make sense that federation would be possible with some servers but not all.

**Comment by clokep** [comment] 2021-03-02 16:13
> It would appear to be a TLS issue but Matrix Federation Tester shows no errors:

I don't see how this is related to TLS.

>  `Failed to find any key to satisfy VerifyJsonRequest(server=rotruck.net, key_ids=['ed25519:a_Iknt'], min_valid=1614700463391)`

This might indicate an issue with fetching keys to verify other servers.

Debugging on the matrix.org server it seems it is unable to connect to the server (it is unable to load https://rotruck.net/.well-known/matrix/server and fails with a timeout).

**Comment by wrotruck** [comment] 2021-03-02 17:02
I was suspecting TLS as the error seems to correspond to this section of the Federation tester JSON report:

`     "Errors": [],
      "Ed25519VerifyKeys": {
        "ed25519:a_Iknt": "xxxREDACTEDxxx"`

However, I am not knowledgeable in this area.

You marked this "Needs Info." Is there additional info you need me to supply?

**Comment by ShadowJonathan** [comment] 2021-03-02 17:24
(whoops, earlier on i tested `curl https://rotruck.net/.well-known/server`, this is missing the `/matrix/` path section)

**Comment by ShadowJonathan** [comment] 2021-03-02 17:30
@wrotruck looking at what `curl https://matrix.org/_matrix/key/v2/query/rotruck.net` returns and what @clokep said, I'd suggest waiting a moment, as matrix.org would backoff getting your server key, the `.well-known` file is in the right position, and is giving good results, but it's possible your server tried contacting `matrix.org` before you had set that up, resulting in the key being not available on the matrix.org notary server.

**Comment by richvdh** [comment] 2021-03-02 17:53
I don't know why the federation tester isn't complaining about it, but the problem is that connections to `rotruck.net:443` (and hence requests to https://rotruck.net/.well-known/matrix/server`) time out.

This looks like a configuration/deployment problem rather than a Synapse bug, so I'm going to go ahead and close this.

**Closed by richvdh** 2021-03-02 17:53 UTC
Labels: X-Needs-Info

**Comment by richvdh** [comment] 2021-03-02 17:54
> It also doesn't make sense that federation would be possible with some servers but not all.

If the well-known URI was working in the past, other servers may have cached the result. They too will stop working in due course unless you fix the problem.

**Comment by wrotruck** [comment] 2021-03-02 17:55
@ShadowJonathan For my own information, from matrix-synapse what is difference between the physical file location and the file location I entered into the configuration file?

**Comment by ShadowJonathan** [comment] 2021-03-02 17:56
The fed tester isn't complaining about it because it can still access `rotruck.net`, and the same on my local machine, i think the issue is that for a brief moment the host went down while `matrix.org` was making that `.well-known` request, caching the wrong result for a while.

It should probably resolve itself in a few hours, if it doesn't, feel free to notify `#synapse:matrix.org` instead of this channel (though you may need a matrix.org account for that)

**Comment by ShadowJonathan** [comment] 2021-03-02 17:57
> @ShadowJonathan For my own information, from matrix-synapse what is difference between the physical file location and the file location I entered into the configuration file?

File location of what exactly, sorry?

**Comment by wrotruck** [comment] 2021-03-02 18:00
Rather than have server file sitting in a directory at the web root.  I was adding the following to the conf file to achieve the same thing.

`location /.well-known/matrix/server { default_type application/json; return 200 '{"m.server": "matrix.rotruck.net:443"}'; add_header Access-Control-Allow-Origin *; `

In doing this, I was trying avoid possible file overwrite issues when a proper website is added.

**Comment by richvdh** [comment] 2021-03-02 18:02
> The fed tester isn't complaining about it because it can still access rotruck.net, and the same on my local machine, i think the issue is that for a brief moment the host went down while matrix.org was making that .well-known request, caching the wrong result for a while.

Well, it's not a transient, in that I still can't reach `rotruck.net` from the matrix.org synapse servers, nor from my home network.  It looks like an internet routing issue in `knology.net`, whoever they are. Here is a traceroute from a machine that *can* reach rotruck.net:

```
traceroute to rotruck.net (65.60.135.227), 30 hops max, 60 byte packets
 1  94.237.52.1 (94.237.52.1)  0.129 ms  0.080 ms  0.077 ms
 2  100.69.34.49 (100.69.34.49)  0.305 ms  0.344 ms  0.331 ms
 3  172.17.255.237 (172.17.255.237)  0.266 ms  0.329 ms  0.321 ms
 4  172.17.255.249 (172.17.255.249)  0.223 ms  0.225 ms  0.215 ms
 5  40ge1-3.core1.lon2.he.net (195.66.224.21)  0.698 ms  0.780 ms  0.681 ms
 6  100ge4-1.core1.nyc4.he.net (72.52.92.166)  67.833 ms  66.605 ms  66.560 ms
 7  100ge16-1.core1.ash1.he.net (184.105.223.165)  71.723 ms  71.832 ms  72.660 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
12  76-73-167-90.knology.net (76.73.167.90)  91.089 ms  90.830 ms  92.533 ms
13  static-24-96-11-205.knology.net (24.96.11.205)  92.129 ms 76-73-167-98.knology.net (76.73.167.98)  91.267 ms  91.372 ms
14  static-24-96-249-187.knology.net (24.96.249.187)  92.631 ms 76-73-166-82.knology.net (76.73.166.82)  91.503 ms  91.448 ms
15  d60-65-227-135.col.wideopenwest.com (65.60.135.227)  100.072 ms  100.700 ms  105.634 ms
16  d60-65-227-135.col.wideopenwest.com (65.60.135.227)  102.146 ms  100.472 ms  98.849 ms
17  d60-65-227-135.col.wideopenwest.com (65.60.135.227)  98.414 ms d60-65-227-135.col.wideopenwest.com (65.60.135.227) <syn,ack>  101.954 ms  100.138 ms
```

and from one that can't:

```
Selected device wlp58s0, address 10.87.83.208, port 54721 for outgoing packets
Tracing the path to rotruck.net (65.60.135.227) on TCP port 443 (https), 30 hops max
 1  10.87.80.1  2.959 ms  1.868 ms  1.321 ms
 2  * * 128.53.155.90.in-addr.arpa (90.155.53.128) 14.470 ms
 3  k-aimless.thn.aa.net.uk (90.155.53.101)  14.445 ms  14.610 ms  14.611 ms
 4  40ge1-3.core1.lon2.he.net (195.66.224.21)  18.189 ms  15.260 ms  15.190 ms
 5  100ge4-1.core1.nyc4.he.net (72.52.92.166)  80.669 ms  81.076 ms  81.329 ms
 6  100ge16-1.core1.ash1.he.net (184.105.223.165)  126.037 ms  86.166 ms  92.984 ms
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  76-73-167-90.knology.net (76.73.167.90)  105.666 ms  105.648 ms  106.539 ms
12  76-73-167-98.knology.net (76.73.167.98)  105.240 ms  107.752 ms  105.622 ms
13  static-24-96-249-187.knology.net (24.96.249.187)  105.436 ms  106.433 ms  112.064 ms
14  76-73-166-82.knology.net (76.73.166.82)  106.249 ms  105.710 ms  107.585 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
```

**Comment by ShadowJonathan** [comment] 2021-03-02 18:02
Oh, that looks to be correct, the faffing about with `.well-known` was me not being careful when manually entering `.well-known/matrix/server` into the console, and then not double-checking, sorry about that.

**Comment by wrotruck** [comment] 2021-03-02 18:15
@richvdh 
Knology.net resolves to my ISP.

So it's not a bug or a configuration issue; it's an ISP issue.

Is there a way to add a static route to go around this?

**Comment by rambip** [comment] 2021-06-15 16:33
> > It would appear to be a TLS issue but Matrix Federation Tester shows no errors:
> 
> I don't see how this is related to TLS.
> 
> > `Failed to find any key to satisfy VerifyJsonRequest(server=rotruck.net, key_ids=['ed25519:a_Iknt'], min_valid=1614700463391)`
> 
> This might indicate an issue with fetching keys to verify other servers.
> 
> Debugging on the matrix.org server it seems it is unable to connect to the server (it is unable to load https://rotruck.net/.well-known/matrix/server and fails with a timeout).

I have exactly the same issue !

I added the .well-known files.

You can tell that my configuration is legit [here](https://federationtester.matrix.org/#matrix.rambi.duckdns.org)

But I get this error:
```
2021-06-15 15:25:32,911 - synapse.http.matrixfederationclient - 639 - INFO - POST-2159 - {GET-O-149} [matrix.rambi.duckdns.org] Request failed: GET matrix://matrix.rambi.duckdns.org/_matrix/
key/v2/server/ed25519%3Aa_rsPo: DNSServerError(<Message id=29145 rCode=2 maxSize=0 flags=answer,recDes,recAv queries=[Query(b'_matrix._tcp.matrix.rambi.duckdns.org', 33, 1)]>)
2021-06-15 15:25:32,912 - synapse.crypto.keyring - 881 - WARNING - POST-2159 - Error looking up keys {'ed25519:a_rsPo': 1623767131178} from matrix.rambi.duckdns.org: Failed to send request: 
DNSServerError: <Message id=29145 rCode=2 maxSize=0 flags=answer,recDes,recAv queries=[Query(b'_matrix._tcp.matrix.rambi.duckdns.org', 33, 1)]>
2021-06-15 15:25:32,916 - synapse.federation.federation_base - 128 - WARNING - POST-2159 - Signature check failed for $b3usuy5GPlfVx6SHZ9NS2s5XyhJ2zbxuRzGRsSGsttQ: 403: event id $b3usuy5GPlf
Vx6SHZ9NS2s5XyhJ2zbxuRzGRsSGsttQ: unable to verify signature for sender matrix.rambi.duckdns.org: 401: Failed to find any key to satisfy VerifyJsonRequest(server=matrix.rambi.duckdns.org, ke
y_ids=['ed25519:a_rsPo'], min_valid=1623767131178)
```

It could also be a dns (I'm hosted on duckdns) issue.
In any case these 2 issues seems to be linked.

#5882

**Comment by rambip** [comment] 2021-06-16 08:43
Turns out it was a temporary issue, probably because matrix.org cached a wrong federation adress.

I think the following config :
```
location /.well-known/matrix/server { 
default_type application/json;
 return 200 '{"m.server": "<server adress>:443"}'; 
add_header Access-Control-Allow-Origin *;
}
```

Should be more visible in the documentation
