### ISSUE TITLE
Possibility to limit users ability to create rooms or invite users

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#9628] opened 2021-03-16 15:56 UTC
**Description:**

Case: Slack like external users on a homeserver who 1) cannot create rooms (or aliases or publish a room), 2) cannot invite users to the rooms they are in.

This is technically possible to do via a spam checker module or third-party event rules module, but the issue is lack of integration towards clients. Clients will still show a room create button for example or will just show a generic error message. It would be nice to have this as a proper feature to support customers who want more limited external user support (for example via a dedicated homeserver running for external users).

**Comment by jaywink** [comment] 2021-03-16 15:57
Relates to #1970 and #8724

**Comment by clokep** [comment] 2021-03-16 15:59
> the issue is lack of integration towards clients. Clients will still show a room create button for example or will just show a generic error message.

This makes me sound like it would need some spec changes? Or is this already possible to send to clients, just that Synapse isn't able to express it?

**Comment by jaywink** [comment] 2021-03-16 16:06
Yeah this should probably go through an MSC to make it an actual feature.

**Comment by erkinalp** [comment] 2021-03-18 18:08
With https://github.com/matrix-org/matrix-doc/pull/3059, you would set the rate limit of room creation requests from said user to zero, effectively blocking the room creation operation for the said user.

**Comment by hex-m** [comment] 2021-05-04 02:09
This is possibly a duplicate of https://github.com/matrix-org/synapse/issues/7731

**Comment by richvdh** [comment] 2021-05-06 09:53
agreed. closing as a dup.

**Closed by richvdh** 2021-05-06 09:53 UTC
Labels: T-Enhancement
