### ISSUE TITLE
`account_data` unexpectedly filtered out of /sync result

### ISSUE THREAD

**Issue by kevinrademan** [matrix-org/synapse#8749] opened 2020-11-12 14:34 UTC
### Description

The account_data and ephemeral events are not returned then when specifying a the "rooms" property of a RoomFilter while calling the /sync api endpoint

### Steps to reproduce

- GET https://b/_matrix/client/r0/sync?filter=###see below###
```
{
  "room": {
  	"rooms": ["!a:b"]
  },
  "presence": {
    "types": []
  },
  "account_data": {
    "types": []
  }
}
```

#### Expected Response

This is what get returned when you perform the same call with no rooms filter. I've manually truncated the events for the timeline and state events as they are not relevant (working as intended)

```
{
    "account_data": {
        "events": []
    },
    "to_device": {
        "events": []
    },
    "device_lists": {
        "changed": [],
        "left": []
    },
    "presence": {
        "events": []
    },
    "rooms": {
        "join": {
            "!a:b": {
                "timeline": {
                    "events": [...],
                    "prev_batch": "t95-5277_30156_0_511_6316_1_1_166_1",
                    "limited": true
                },
                "state": {
                    "events": [...]
                },
                "account_data": {
                    "events": [
                        {
                            "type": "m.fully_read",
                            "content": {
                                "event_id": "$m7zauVBF6pd9C1BBExtPgWWkWCXoGRoheBm4EzokiY4"
                            }
                        }
                    ]
                },
                "ephemeral": {
                    "events": [
                        {
                            "type": "m.receipt",
                            "content": {
                                "$V9G8_p1otbFb7sXCl9xxBUQ8S_x-NTU8RswSu5HypNs": {
                                    "m.read": {
                                        "@user1:b": {
                                            "ts": 1605183844082
                                        }
                                    }
                                },
                                "$DCUMbQjC6oK5WPQaMx75-lFog3WlF3t781tRwZoQFwU": {
                                    "m.read": {
                                        "@user2:b": {
                                            "ts": 1604571555681
                                        }
                                    }
                                },
                                "$m7zauVBF6pd9C1BBExtPgWWkWCXoGRoheBm4EzokiY4": {
                                    "m.read": {
                                        "user3:b": {
                                            "ts": 1604575454389
                                        }
                                    }
                                }
                            }
                        }
                    ]
                },
                "unread_notifications": {
                    "notification_count": 0,
                    "highlight_count": 0
                },
                "summary": {},
                "org.matrix.msc2654.unread_count": 0
            }
        },
        "invite": {},
        "leave": {}
    },
    "groups": {
        "join": {},
        "invite": {},
        "leave": {}
    },
    "device_one_time_keys_count": {},
    "org.matrix.msc2732.device_unused_fallback_key_types": [],
    "next_batch": "s5287_30156_0_511_6316_1_1_166_1"
}
```

#### Received Response

```
{
    "account_data": {
        "events": []
    },
    "to_device": {
        "events": []
    },
    "device_lists": {
        "changed": [],
        "left": []
    },
    "presence": {
        "events": []
    },
    "rooms": {
        "join": {
            "!a:b": {
                "timeline": {
                    "events": [...],
                    "prev_batch": "t95-5277_30156_0_511_6316_1_1_166_1",
                    "limited": true
                },
                "state": {
                    "events": [...]
                },
                "account_data": {
                    "events": []
                },
                "ephemeral": {
                    "events": []
                },
                "unread_notifications": {
                    "notification_count": 0,
                    "highlight_count": 0
                },
                "summary": {},
                "org.matrix.msc2654.unread_count": 0
            }
        },
        "invite": {},
        "leave": {}
    },
    "groups": {
        "join": {},
        "invite": {},
        "leave": {}
    },
    "device_one_time_keys_count": {},
    "org.matrix.msc2732.device_unused_fallback_key_types": [],
    "next_batch": "s5287_30156_0_511_6316_1_1_166_1"
}
```

### Version information
- **Homeserver**:  Local development home server
- **Version**: 1.20.1, 1.22.1 (tried upgrading, but it had no effect)
- **Install method**: Helm chart (https://github.com/dacruz21/matrix-chart)

- **Platform**: Running on kubernetes 1.19 using the matrixdotorg/synapse:v1.22.1 docker container

**Comment by clokep** [comment] 2020-11-16 18:08
I believe that this is working as intended due to the given filter:

```json
{
  "room": {
  	"rooms": ["!a:b"]
  },
  "presence": {
    "types": []
  },
  "account_data": {
    "types": []
  }
}
```

I think this says to return data only from room `!a:b`, including no `presence` types and no `account_data` types? That's my reading of the [filtering spec](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-user-userid-filter) at least. Does changing it to something like the following provide the expected result:

```json
{
  "room": {
  	"rooms": ["!a:b"]
  }
}
```

**Comment by kevinrademan** [comment] 2020-11-27 15:57
@clokep Tnx for looking into this. Changing the filter as suggested doesn't returns the data that I expect.

I just want to clear up some confusion. There is "user level account data" and "room level account data". The data I'm specifically trying to load is the m.fully_read marker which is stored in "room level account data"

With my mock filter, I would expect the sync endpoint to return all data (including the room account data) to be returned for one single room. What I however find is that doing any kind of room filter results in all "room level account data" getting excluded.

**Comment by richvdh** [comment] 2021-04-09 14:47
I can't see any immediate reason that would happen; it certainly doesn't look right.

**Comment by richvdh** [comment] 2022-07-27 14:04
wondering if this is still reproducible?  If it hasn't been seen for 18 months, it's probably time to close it.

**Comment by erikjohnston** [comment] 2022-08-24 15:06
If anyone see's this issue then please shout and we'll reopen.

**Closed** 2022-08-24 15:05 UTC
Labels: A-Sync, S-Minor, T-Defect, X-Needs-Info
