### ISSUE TITLE
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "event_auth_chains_pkey"

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#9418] opened 2021-02-16 16:34 UTC
### Description

Trying to (re-)join a room over federation which first failed due to apparently network errors on the canonical alias servers:

![image](https://user-images.githubusercontent.com/105185/108092319-e24ec200-707c-11eb-8584-9c71fb88a857.png)

Afterwards I tried joining through another alias but only got internal server errors back from my synapse. Someone kicking me and reinviting me to the room didn't help at that point:

![image](https://user-images.githubusercontent.com/105185/108092424-04e0db00-707d-11eb-9a75-e12066ea9deb.png)

```
Feb 16 17:22:59 bubu synapse[179737]: 2021-02-16 17:22:59,385 - synapse.http.server - 91 - ERROR - POST-48259 - Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7fae6a5ad1f0 method='POST' uri='/_matrix/client/r0/join/!UbCmIlGTHNIgIRZcpt%3Anheko.im' clientproto='HTTP/1.0' site='8008'>
Feb 16 17:22:59 bubu synapse[179737]: Traceback (most recent call last):
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 252, in _async_render_wrapper
Feb 16 17:22:59 bubu synapse[179737]:     callback_return = await self._async_render(request)
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 430, in _async_render
Feb 16 17:22:59 bubu synapse[179737]:     callback_return = await raw_callback_return
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/rest/client/v1/room.py", line 301, in on_POST
Feb 16 17:22:59 bubu synapse[179737]:     await self.room_member_handler.update_membership(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 333, in update_membership
Feb 16 17:22:59 bubu synapse[179737]:     result = await self.update_membership_locked(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 549, in update_membership_locked
Feb 16 17:22:59 bubu synapse[179737]:     remote_join_response = await self._remote_join(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 1091, in _remote_join
Feb 16 17:22:59 bubu synapse[179737]:     event_id, stream_id = await self.federation_handler.do_invite_join(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 1400, in do_invite_join
Feb 16 17:22:59 bubu synapse[179737]:     max_stream_id = await self._persist_auth_tree(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 2050, in _persist_auth_tree
Feb 16 17:22:59 bubu synapse[179737]:     await self.persist_events_and_notify(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 2925, in persist_events_and_notify
Feb 16 17:22:59 bubu synapse[179737]:     events, max_stream_token = await self.storage.persistence.persist_events(
Feb 16 17:22:59 bubu synapse[179737]:   File "/usr/lib/python3.9/site-packages/synapse/storage/persist_events.py", line 262, in persist_events
Feb 16 17:22:59 bubu synapse[179737]:     ret_vals = await make_deferred_yieldable(
Feb 16 17:22:59 bubu synapse[179737]: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "event_auth_chains_pkey"
Feb 16 17:22:59 bubu synapse[179737]: DETAIL:  Key (event_id)=($CujtKiU7yTlfL5hokwT_KW8Wh8BzoPB9gDtVhFmiljI) already exists.
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/metrics/background_process_metrics.py:208:run
Feb 16 17:22:59 bubu synapse[179737]: --- <exception caught here> ---
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:172:handle_queue_loop
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:324:persisting_queue
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:532:_persist_events
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:171:_persist_events_and_state_updates
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:661:runInteraction
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:744:runWithConnection
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/python/threadpool.py:250:inContext
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/python/threadpool.py:266:<lambda>
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/python/context.py:122:callWithContext
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/python/context.py:85:callWithContext
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/python/compat.py:464:reraise
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:739:inner_func
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:539:new_transaction
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/logging/utils.py:71:wrapped
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:379:_persist_events_txn
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:472:_persist_event_auth_chain_txn
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:630:_add_chain_cover_index
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:896:simple_insert_many_txn
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:274:execute_batch
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:319:_do_execute
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/synapse/storage/database.py:274:<lambda>
Feb 16 17:22:59 bubu synapse[179737]: /usr/lib/python3.9/site-packages/psycopg2/extras.py:1209:execute_batch
Feb 16 17:22:59 bubu synapse[179737]: ]]
```

### Version information

- **Homeserver**: bubu1.eu

- **Version**: 1.27.0

- **Install method**:

- **Platform**: archlinux package (bumped to 1.27)

**Comment by waclaw66** [comment] 2021-02-24 11:26
Same problem joining #synapse:matrix.org...
```
synapse.http.server: [POST-10040] Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7f57646fa970 method='POST' uri='/_matrix/client/r0/join/%23synapse%3Amatrix.org' clientproto='HTTP/1.1' site='8008'>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 252, in _async_render_wrapper
        callback_return = await self._async_render(request)
      File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 430, in _async_render
        callback_return = await raw_callback_return
      File "/usr/lib/python3.9/site-packages/synapse/rest/client/v1/room.py", line 301, in on_POST
        await self.room_member_handler.update_membership(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 333, in update_membership
        result = await self.update_membership_locked(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 549, in update_membership_locked
        remote_join_response = await self._remote_join(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/room_member.py", line 1091, in _remote_join
        event_id, stream_id = await self.federation_handler.do_invite_join(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 1400, in do_invite_join
        max_stream_id = await self._persist_auth_tree(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 2050, in _persist_auth_tree
        await self.persist_events_and_notify(
      File "/usr/lib/python3.9/site-packages/synapse/handlers/federation.py", line 2925, in persist_events_and_notify
        events, max_stream_token = await self.storage.persistence.persist_events(
      File "/usr/lib/python3.9/site-packages/synapse/storage/persist_events.py", line 262, in persist_events
        ret_vals = await make_deferred_yieldable(
    twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "event_auth_chains_pkey"
    DETAIL:  Key (event_id)=($e9U026auDHIgaZPAqlblvPupACjl7jcZDblP970dJPs) already exists.

    /usr/lib/python3.9/site-packages/synapse/metrics/background_process_metrics.py:208:run
    --- <exception caught here> ---
    /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:172:handle_queue_loop
    /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:324:persisting_queue
    /usr/lib/python3.9/site-packages/synapse/storage/persist_events.py:532:_persist_events
    /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:171:_persist_events_and_state_updates
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:661:runInteraction
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:744:runWithConnection
    /usr/lib64/python3.9/site-packages/twisted/python/threadpool.py:250:inContext
    /usr/lib64/python3.9/site-packages/twisted/python/threadpool.py:266:<lambda>
    /usr/lib64/python3.9/site-packages/twisted/python/context.py:122:callWithContext
    /usr/lib64/python3.9/site-packages/twisted/python/context.py:85:callWithContext
    /usr/lib64/python3.9/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
    /usr/lib64/python3.9/site-packages/twisted/python/compat.py:464:reraise
    /usr/lib64/python3.9/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:739:inner_func
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:539:new_transaction
    /usr/lib/python3.9/site-packages/synapse/logging/utils.py:71:wrapped
    /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:379:_persist_events_txn
    /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:472:_persist_event_auth_chain_txn
    /usr/lib/python3.9/site-packages/synapse/storage/databases/main/events.py:630:_add_chain_cover_index
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:896:simple_insert_many_txn
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:274:execute_batch
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:319:_do_execute
    /usr/lib/python3.9/site-packages/synapse/storage/database.py:274:<lambda>
    /usr/lib64/python3.9/site-packages/psycopg2/extras.py:1209:execute_batch
    ]]

```

**Comment by clokep** [comment] 2021-02-25 17:46
Sounds like this is a duplicate of #9481, I'm going to close this one since that has more debug info in it.

**Closed by clokep** 2021-02-25 17:46 UTC
Labels: S-Major, T-Defect
