### ISSUE TITLE
Outgoing federation breaks on client re-opening

### ISSUE THREAD

**Issue by n0emis** [matrix-org/synapse#7416] opened 2020-05-05 09:36 UTC
### Description
Yesterday we migrated our synapse installation (which has about 80 users) from a docker-based installation into a virtualenv. Also we upgraded the version in this progress from version 1.12.3 to 1.12.4. Since that we have had the following issue **multiple times**:
- We saw that the server stopped federating. (Only outgoing federation breaks, not incoming.) The log was showing the following error many times (for each other hs we tried to federate with): 
```
May 04 20:05:50 chaos matrix-synapse[2450]: 2020-05-04 20:05:50,798 - synapse.federation.sender.per_destination_queue - 332 - ERROR - federation_transaction_transmission_loop-23058 - TX [h-ws.de] Failed to send transaction
May 04 20:05:50 chaos matrix-synapse[2450]: Traceback (most recent call last):
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/sender/per_destination_queue.py", line 201, in _transaction_transmission_loop
May 04 20:05:50 chaos matrix-synapse[2450]:     limit
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/sender/per_destination_queue.py", line 368, in _get_device_update_edus
May 04 20:05:50 chaos matrix-synapse[2450]:     self._destination, last_device_list, limit=limit
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
May 04 20:05:50 chaos matrix-synapse[2450]:     result = result.throwExceptionIntoGenerator(g)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
May 04 20:05:50 chaos matrix-synapse[2450]:     return g.throw(self.type, self.value, self.tb)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/data_stores/main/devices.py", line 233, in get_device_updates_by_remote
May 04 20:05:50 chaos matrix-synapse[2450]:     destination, from_stream_id, query_map
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
May 04 20:05:50 chaos matrix-synapse[2450]:     result = result.throwExceptionIntoGenerator(g)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
May 04 20:05:50 chaos matrix-synapse[2450]:     return g.throw(self.type, self.value, self.tb)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/data_stores/main/devices.py", line 294, in _get_device_update_edus_by_remote
May 04 20:05:50 chaos matrix-synapse[2450]:     else {}
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
May 04 20:05:50 chaos matrix-synapse[2450]:     result = result.throwExceptionIntoGenerator(g)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
May 04 20:05:50 chaos matrix-synapse[2450]:     return g.throw(self.type, self.value, self.tb)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 524, in runInteraction
May 04 20:05:50 chaos matrix-synapse[2450]:     **kwargs
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
May 04 20:05:50 chaos matrix-synapse[2450]:     result = result.throwExceptionIntoGenerator(g)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
May 04 20:05:50 chaos matrix-synapse[2450]:     return g.throw(self.type, self.value, self.tb)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 574, in runWithConnection
May 04 20:05:50 chaos matrix-synapse[2450]:     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
May 04 20:05:50 chaos matrix-synapse[2450]:     result = inContext.theWork()
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
May 04 20:05:50 chaos matrix-synapse[2450]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
May 04 20:05:50 chaos matrix-synapse[2450]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
May 04 20:05:50 chaos matrix-synapse[2450]:     return func(*args,**kw)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
May 04 20:05:50 chaos matrix-synapse[2450]:     compat.reraise(excValue, excTraceback)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
May 04 20:05:50 chaos matrix-synapse[2450]:     raise exception.with_traceback(traceback)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
May 04 20:05:50 chaos matrix-synapse[2450]:     result = func(conn, *args, **kw)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 571, in inner_func
May 04 20:05:50 chaos matrix-synapse[2450]:     return func(conn, *args, **kwargs)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 407, in new_transaction
May 04 20:05:50 chaos matrix-synapse[2450]:     r = func(cursor, *args, **kwargs)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/logging/opentracing.py", line 709, in _trace_inner
May 04 20:05:50 chaos matrix-synapse[2450]:     return func(*args, **kwargs)
May 04 20:05:50 chaos matrix-synapse[2450]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/data_stores/main/end_to_end_keys.py", line 136, in _get_e2e_device_keys_txn
May 04 20:05:50 chaos matrix-synapse[2450]:     deleted_devices.remove((row["user_id"], row["device_id"]))
May 04 20:05:50 chaos matrix-synapse[2450]: KeyError: ('@n0emis:chaos.jetzt', 'OBAEIZMRVE')
```
- When looking in the database, we saw that the user `@n0emis:chaos.jetzt` and their device `OBAEIZMRVE` had multiple entries in the `devices` table in the database. (See the bottom most entries of the following screenshot)
![Screenshot from 2020-05-04 20-48-03](https://user-images.githubusercontent.com/22817873/81052866-82f43c80-8ec4-11ea-88f5-54cd0968383a.png)
- after deleting one of the entries (one had `display_name` == `none`) the error was fixed and outgoing federation was working again.
- *Sometimes* when a user re-opens their client or clears their client cache, their device gets duplicated. 
    - Then outgoing federation breaks again.
- We had this happen on many different clients (e.g. RiotWeb, Minivector etc...)
- We have not yet figured out a way to trigger this bug on-purpose.

We have currently setup a cronjob, which runs the following SQL-Query and notifies us via email. Any further feedback on this would be much appreciated...
```sql
select device_id, user_id, count(*)
from devices
group by device_id, user_id
HAVING count(*) > 1
```

### Version information
- **Homeserver**: matrix.chaos.jetzt
- **Version**: 1.12.4
- **Install method**: pip into a virtualenv
- **Platform**: hetzner-vm, Ubuntu 18.04.4 LTS, 4.15.0-99-generic

**Comment by auscompgeek** [comment] 2020-05-05 09:45
The `devices` table should have a `unique index` on `(device_id, user_id)`…

Was this database migrated from SQLite to Postgres?

**Comment by n0emis** [comment] 2020-05-05 09:46
No, it was always a postgres database.

**Comment by auscompgeek** [comment] 2020-05-05 09:54
I'm personally not sure how the index could disappear like that, unless if synapse was interrupted whilst creating the database maybe? Not sure.

Anyway, copypasta:
```sql
ALTER TABLE ONLY devices
    ADD CONSTRAINT device_uniqueness UNIQUE (user_id, device_id);
```

**Comment by n0emis** [comment] 2020-05-05 09:59
Ah, thanks. The constraint was somehow really missing. We'll have a look, if this fixes our problem...

**Comment by babolivier** [comment] 2020-05-05 10:15
Hey there, it looks like, for some weird reason, unique constraints are disappearing from databases (as #7399 is a report of a similar issue but with another constraint), I've opened https://github.com/matrix-org/synapse/issues/7417 to track this issue more globally.

**Comment by babolivier** [comment] 2020-05-05 12:58
Right, according to https://github.com/matrix-org/synapse/issues/7417#issuecomment-623987708, it seems to be more of a PostgreSQL/operational issue than a Synapse one. I'll keep this issue open in case the issue isn't solved by adding the constraint.

**Comment by clokep** [comment] 2020-06-24 16:06
I'm going to close this since it has been over a month -- please let us know if this is still a problem.

**Closed by clokep** 2020-06-24 16:06 UTC
Labels: info-needed
