### ISSUE TITLE
Custom config files are overwritten when they musn't be (Deb) aka "Phone-home" feature is opt-out, again

### ISSUE THREAD

**Issue by maxidorius** [matrix-org/synapse#4656] opened 2019-02-15 23:32 UTC
Updating to v0.99.1.1 updates the `/etc/matrix-synapse/conf.d/report_stats.yaml` and set the reporting to `true`, despite the file existing with a value `false` before upgrade.

Related:
- matrix-org/package-synapse-debian#26
- matrix-org/package-synapse-debian#45
- #4440

Moved to this repo as per @uhoreg request [here](https://matrix.to/#/!cApDlsILLZkmAyVoxe:matrix.org/$155027236382486kbXIn:matrix.org?via=matrix.org&via=t2bot.io&via=shareknot.de)

**Comment by maxidorius** [comment] 2019-02-16 00:21
Just to be clear: Regardless of the value of the dpkg cache, the file `/etc/matrix-synapse/conf.d/report_stats.yaml` existed before the upgrade, and was **overwritten** without my knowledge, and despite having the configuration value already set.

I can also confirmed that this also happened on a system where the dpkg cache value was `false`. The file content was also `false`. Yet it became `true` after the update.

The fact that the file is overwritten when it already exists is the issue, because then the value can be set to true due to any mistake.

**Comment by richvdh** [comment] 2019-02-18 00:22
so let me check. It sounds like there are two issues here:

1: Assuming where you say 'dpkg cache', you mean the debconf database: even though the debconf database has `matrix-synapse/report-stats` set to `false`, the setting is set to true in `report_stats.yaml` on upgrade. This is a recent regression, probably related to the `matrix-synapse-py3` packaging.

2: Also, you are complaining about `report_stats.yaml` being overwritten at all. This is *not* a regression, though I agree it is incorrect behaviour, as per #4440, and will update that bug accordingly.

**Comment by maxidorius** [comment] 2019-02-18 01:11
1. Correct.
2. Glad you agree it is incorrect behaviour.

To understand my report:
My comment was mostly based on my surprise that a config file which was manually changed (when debugging this issue) was overwritten without any kind of visible notice. Prompts do exist in debian packaging (the latest version actually triggers it for homeserver.yaml), but overwritting a config file, especially on something like "phone-home", is worrying (I'm not aware of other deb packages doing so) and troublesome (GDPR and potential the legal requirement of reporting such upload of data).

It is very possible the issue actually spans two underlying one. I would still not try to see this as two separate issues, as I personally do not. There is only one issue: a criticial config file was changed without my knowledge for no good reason from the point of view of a system administrator. How the file is handled/dealt within the internals of the package is not something I should concern myself with.

**Comment by richvdh** [comment] 2019-02-18 09:57
> There is only one issue: a critical config file was changed without my knowledge for no good reason from the point of view of a system administrator.

well, that just makes it a duplicate of #4440.

**Comment by maxidorius** [comment] 2019-02-18 15:54
#4440 is about `server_name` isn't it? That variable has completely different implications:
- Even if it is changed, the domain doesn't actually change and last time I tried, synapse wouldn't even start in such case.
- Changing the domain doesn't trigger uploading data of unknown nature to a 3rd party after making an explicit choice not to.

While I agree the fundamental issue is that configuration value is changed, the impact of this issue and #4440 are totally different, and should be reflected in terms of priority, criticality, etc.

**Comment by richvdh** [comment] 2019-02-18 16:14
they are the same problem. They were introduced together and can be fixed together. I agree `report_stats` is in many ways a larger concern, which is why i've written exactly that on #4440.

Please let's stop arguing about it now; I'm going to try to fix them.

**Comment by richvdh** [comment] 2019-02-18 17:40
> 1: Assuming where you say 'dpkg cache', you mean the debconf database: even though the debconf database has `matrix-synapse/report-stats` set to `false`, the setting is set to true in `report_stats.yaml` on upgrade. This is a recent regression, probably related to the `matrix-synapse-py3` packaging.

I've been unable to reproduce this. Here's what I tried:

* Started with a clean debian 9 system.
* Installed `matrix-synapse 0.34.0.1-0matrix1`, answering 'no' to the question about the phone home stats. `report_stats.yaml` was correctly generated:
  ```
  root@debian9:~# cat /etc/matrix-synapse/conf.d/report_stats.yaml 
  report_stats: false
  ```
* Checked the debconf database:
  ```
  root@debian9:~# debconf-show matrix-synapse
  * matrix-synapse/report-stats: false
  * matrix-synapse/server-name: localhost
  ```
* Upgraded to `matrix-synapse 0.34.0.1-0matrix2`, which installed `matrix-synapse-py3 0.99.1.1+stretch1`.
* Rechecked `report_stats.yaml`: no change.

I also tried an upgrade from 0.99.0 to 0.99.1.1. Again, `report_stats.yaml` was set correctly based on the debconf database.

Any hints on how to reproduce this?

**Comment by maxidorius** [comment] 2019-02-18 17:50
Not really. I also use Debian 9 and it triggers it, but I don't know why.

To be clear: Fixing the behaviour of when to overwrite the file is not what I'm looking for, else I would have just added to #4440. I just would like for the behaviour of writing to `conf.d` files to be gone so there is never a risk of this happening again. If that is not acceptable, let me know and I'll work around it in another way (make the file read-only, creating a directory of the same name to block any write attempts, etc)

**Comment by richvdh** [comment] 2019-02-18 17:52
> Not really. I also use Debian 9 and it triggers it, but I don't know why.

can you show the output of `debconf-show matrix-synapse-py3` ?

I'll look into how we can better handle the conf.d files under #4440.

**Comment by maxidorius** [comment] 2019-02-18 17:53
```
# debconf-show matrix-synapse-py3 
* matrix-synapse/report-stats: false
* matrix-synapse/server-name: domain.tld
```

Same output on several servers that got hit by the issue, modulo the `server-name` being their own value.

**Comment by richvdh** [comment] 2019-02-18 17:54
thanks

**Comment by richvdh** [comment] 2019-02-18 23:32
I'm afraid I'm completely mystified as to how `report_stats` is being changed to `true` even though debconf has the setting set to `false`.

Some other things which might help narrow it down:
 * does it also get overwritten when you do a `dpkg-reconfigure matrix-synapse-py3 -u` ?
 * if so, can you share the output of `DEBCONF_DEBUG=developer dpkg-reconfigure matrix-synapse-py3 -u`?

**Comment by maxidorius** [comment] 2019-02-18 23:35
I am not able to run any commands that will restart synapse at this point, like `dpkg-reconfigure`.

**Comment by maxidorius** [comment] 2019-02-24 22:16
Given that #4440 has been closed and supposedly fixed by #4696, I have updated the issue name to reflect the actual problem at hand here: files under `/etc/matrix-synapse/conf.d/` are being overwritten which breaks Debian conventions/rules.

[This specific line](https://github.com/matrix-org/synapse/pull/4696/files#diff-7cfcadaededf04d61f1ecd0d89d46b3cR123) fo #4696 is perpetuating the issue of involving custom config files, including files that might have been prefixed with things like `zz-` to workaround current synapse behaviour.

**Please stop changing files that are not part of the package.** If you want to include a default config for `server_name` and `report_stats`, do so in the `homeserver.yaml` directly in `postinst`, or even better, via an extra file `homeserver-dpkg-auto.yaml` per example which would not be in `conf.d`.

I've had a working around for this problem and now even that workaround will be broken because files which do not belong to the package will be overwritten.

**Comment by richvdh** [comment] 2019-02-24 22:50
they won't be overwritten, because the debconf database will be updated according to the current value in the files before they are updated.

**Comment by abeluck** [comment] 2019-05-27 14:11
This bug hit us today to.

We are shipping out matrix server with a complete homeserver.yaml. Yet we get errors on startup:

```
May 27 14:04:10 ip-10-55-2-135 matrix-synapse[5876]:     raise ValueError("Invalid server name '%s'" % server_name)
May 27 14:04:10 ip-10-55-2-135 matrix-synapse[5876]: ValueError: Invalid server name 'None'
```

Turns out this is caused by the auto generated files in `conf.d/`.

I do not see any options in `homeserver.yaml` to disable reading config from `conf.d`. Nor do I see any way to disable this postinst placing of files in `conf.d`

**Comment by richvdh** [comment] 2019-05-28 10:40
@abeluck please show the output of

```
debconf-show matrix-synapse-py3
```

**Comment by abeluck** [comment] 2019-05-28 12:52
```console
$ sudo debconf-show matrix-synapse-py3
  matrix-synapse/report-stats: false
  matrix-synapse/server-name:
```

**Comment by richvdh** [comment] 2019-05-28 13:11
@abeluck you'll either need to set `matrix-synapse/server-name` to the correct value (eg with `dpkg-reconfigure matrix-synapse-py3`) or stop the package recreating the file in `conf.d` (eg, by creating a blank file as a placeholder, or commenting out the `server_name` line in the file it creates).

I think this bug as reported has been resolved.

**Comment by abeluck** [comment] 2019-05-28 14:40
Here is the output, **after** I deleted the files in `conf.d`. Do you need it before as well?

```console
# DEBCONF_DEBUG=developer /opt/venvs/matrix-synapse/lib/manage_debconf.pl read
debconf (developer): frontend started
debconf (developer): Trying to find a templates file..
debconf (developer): Trying /opt/venvs/matrix-synapse/lib/manage_debconf.pl.templates
debconf (developer): Trying /usr/share/debconf/templates/manage_debconf.pl.templates
debconf (developer): Couldn't find a templates file.
debconf (developer): frontend running, package name is 
debconf (developer): starting /opt/venvs/matrix-synapse/lib/manage_debconf.pl read
debconf (developer): <-- SET matrix-synapse/server-name my.servername.example.com
debconf (developer): --> 0 value set
debconf (developer): <-- SET matrix-synapse/report-stats False
debconf (developer): --> 0 value set
```

> That said, I'm somewhat surprised that the correct server_name isn't being read from /etc/matrix-synapse/homeserver.yaml

Me too. `server_name` is definitely set in `homeserver.yaml`. But it seems synapse chooses the "last" occurrence, and because it loads the extra config files after the main one, it grabs the empty one.

> you'll either need to set matrix-synapse/server-name to the correct value (eg with dpkg-reconfigure matrix-synapse-py)

That's not ideal, as this is part of an automated ansible install, and `dpkg-reconfigure` is interactive.

> stop the package recreating the file in conf.d (eg, by creating a blank file as a placeholder, or commenting out the server_name line in the file it creates).

I will try the former. Currently I just deleted the files, but perhaps simply truncating them will be upgrade-proof.

**Comment by uhoreg** [comment] 2019-05-28 18:07
> >    you'll either need to set matrix-synapse/server-name to the correct value (eg with dpkg-reconfigure matrix-synapse-py)

> That's not ideal, as this is part of an automated ansible install, and dpkg-reconfigure is interactive.

You should be able to set the value in the debconf database by doing something like (untested):

```
echo matrix-synapse-py3 matrix-synapse/server-name string your.server.name | debconf-set-selections
```

before you install the package.

**Comment by richvdh** [comment] 2019-05-28 22:22
oh, I think I'd failed to understand your description.

> AFAIK if I simply delete the files in conf.d, it will work until an upgrade, in which case they will be replaced... which isn't ideal.

Have you tested this? If things are working correctly, the deleted files will be created, but using the config from `homeserver.yaml`.

As @uhoreg says, the best choice for an automated install is probably to set the server-name before installing via `debconf-set-selections`.

**Comment by richvdh** [comment] 2019-05-29 08:20
I think the issue as reported is resolved.

**Closed by richvdh** 2019-05-29 08:20 UTC
