### ISSUE TITLE
Animated WEBPs are thumbnailed as JPEGs, removing animation

### ISSUE THREAD

**Issue by hiddeninthesand** [matrix-org/synapse#11899] opened 2022-02-03 06:32 UTC
### Description

Title says it all. Similar to #11840, all WEBPs are thumbnailed as JPEGs by synapse, leaving them with missing properties, in this case animation. Expected behavior is to be thumbnailed as a GIF, or even as another animated WEBP for file size reasons.

### Steps to reproduce

- Send an animated WEBP
- Be met with a still image thumbnail

### Version information

- **Homeserver**:

Homeserver was matrix.org

- **Version**: 1.52.0rc1 (b=matrix-org-hotfixes,6705391ee)

- **Install method**: Not sure what they do.

- **Platform**: Not sure.

**Comment by aaronraimist** [comment] 2022-02-03 09:51
Related: https://github.com/matrix-org/synapse/issues/1278

**Comment by clokep** [comment] 2022-02-03 13:09
I think this is pretty much a duplicate of #11840 or #1278 depending on how you look at it.

**Closed by clokep** 2022-02-03 13:09 UTC
