### ISSUE TITLE
Presence events contain User ID as sender rather than content.user_id

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#2361] opened 2017-07-12 05:39 UTC
Found another inconsistency between Synapse and the spec while working on ruma-client. Synapse sends events like this:

```json
{
    "content": {
        "currently_active": true,
        "last_active_ago": 66841020,
        "presence": "online"
    },
    "type": "m.presence",
    "sender": "@someuser:matrix.org"
}
```

where the user ID is in the sender field. According to the spec however, this information should be in the `user_id` field inside the events content: https://matrix.org/docs/spec/client_server/r0.2.0.html#m-presence
(both in r0.2.0 and HEAD)

**Comment by florianjacob** [comment] 2018-08-21 22:29
duplicate of https://github.com/matrix-org/matrix-doc/issues/650 (and fixed with post r0.3.0 release of the client spec :tada: )

**Comment by turt2live** [comment] 2018-08-21 22:39
Yup, the corrected event behaviour should arrive in r0.4.0 which is coming very soon now :)

**Closed by turt2live** 2018-08-21 22:39 UTC
