### ISSUE TITLE
Cannot join room, AssertionError.

### ISSUE THREAD

**Issue by Heidistein** [matrix-org/synapse#14728] opened 2022-12-23 08:52 UTC
### Description

When I try yo join a room (just any) I get a error 500.
The logs say there is an assertion error:
`assert room_id not in self._federation_event_handler.room_queues`

The comments from the source:
```
        # This shouldn't happen, because the RoomMemberHandler has a
        # linearizer lock which only allows one operation per user per room
        # at a time - so this is just paranoia.
        assert room_id not in self._federation_event_handler.room_queues
```

I do not know for how long this is broken, because I don't join rooms often. What I did recently was setup a bunch of workers, I can imagine this could be a source of the problem.

### Steps to reproduce

- Setup workers
- Join a room

### Homeserver

matrix.beetjevreemd.nl

### Synapse Version

1.74.0

### Installation Method

Other (please mention below)

### Database

Single PostgreSQL on the same server, since start. No restores.

### Workers

Multiple workers

### Platform

Fedora 36, in a VM. Has 4 cores, 16 GB RAM.

### Configuration

I have no oddities, except my workers configuration
I went complete over the top with the workers, having:

 - synapse-federation_sender@federation_sender3.service - Synapse federation_sender3
 - synapse-worker@stream_typing1.service - Synapse stream_typing1
 - synapse.service - Synapse Matrix homeserver
 - synapse-federation_sender@federation_sender8.service - Synapse federation_sender8
 - synapse-worker@sync2.service - Synapse sync2
 - synapse-worker@client2.service - Synapse client2
 - synapse-worker@stream_receipts1.service - Synapse stream_receipts1
 - synapse-worker@stream_to_device1.service - Synapse stream_to_device1
 - synapse-federation_sender@federation_sender4.service - Synapse federation_sender4
 - synapse-federation_sender@federation_sender7.service - Synapse federation_sender7
 - synapse-worker@stream_account_data1.service - Synapse stream_account_data1
 - synapse-worker@federation1.service - Synapse federation1
 - synapse-federation_sender@federation_sender9.service - Synapse federation_sender9
 - synapse-worker@stream_presence1.service - Synapse stream_presence1
 - synapse-worker@client1.service - Synapse client1
 - synapse.target - Synspase homeserver
 - synapse-federation_sender@federation_sender1.service - Synapse federation_sender1
 - synapse-worker@federation2.service - Synapse federation2
 - synapse-worker@sync1.service - Synapse sync1
 - synapse-federation_sender@federation_sender6.service - Synapse federation_sender6
 - synapse-worker@event_persister2.service - Synapse event_persister2
 - synapse-worker@event_persister1.service - Synapse event_persister1
 - synapse-federation_sender@federation_sender5.service - Synapse federation_sender5
 - synapse-federation_sender@federation_sender2.service - Synapse federation_sender2

homeserver.yaml relevant section:
```
listeners:

  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1']

    resources:
      - names: [federation, client]
        compress: false

  - port: 9093
    bind_address: '127.0.0.1'
    type: http
    resources:
     - names: [replication]

worker_app: synapse.app.homeserver
daemonize: false

send_federation: false

federation_sender_instances:
    - federation_sender1
    - federation_sender2
    - federation_sender3
    - federation_sender4
    - federation_sender5
    - federation_sender6
    - federation_sender7
    - federation_sender8
    - federation_sender9


instance_map:
    event_persister1:
        host: localhost
        port: 11101
    event_persister2:
        host: localhost
        port: 11102
    stream_typing1:
        host: localhost
        port: 11111
    stream_to_device1:
        host: localhost
        port: 11121
    stream_account_data1:
        host: localhost
        port: 11131
    stream_receipts1:
        host: localhost
        port: 11141
    stream_presence1:
        host: localhost
        port: 11151

stream_writers:
    events:
      - event_persister1
      - event_persister2
    typing:
      - stream_typing1
    to_device:
      - stream_to_device1
    account_data:
      - stream_account_data1
    receipts:
      - stream_receipts1
    presence:
      - stream_presence1
```
the workers & haproxy config:
[workers.tar.gz](https://github.com/matrix-org/synapse/files/10293727/workers.tar.gz)

### Relevant log output

```shell
Dec 23 09:20:00 slank.platypusnet.org synapse[59829]: 2022-12-23 09:20:00,826 - synapse.replication.http.membership - 92 - INFO - POST-515 - remote_join: @dexter:beetjevreemd.nl into room: !prsKNofAcxGLYvnUPq:libera.chat
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: 2022-12-23 09:20:01,000 - synapse.http.matrixfederationclient - 299 - INFO - POST-515 - {GET-O-28267} [libera.chat] Completed request: 200 OK in 0.17 secs, got 493 bytes - GET matrix://libera.chat/_matrix/federation/v1/m
ake_join/%21prsKNofAcxGLYvnUPq%3Alibera.chat/%40dexter%3Abeetjevreemd.nl?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6&ver=org.matrix.msc2176&ver=7&ver=8&ver=9&ver=org.matrix.msc3787&ver=10&ver=org.matrix.msc2716v4
Dec 23 09:20:01 slank.platypusnet.org synapse-federation1[59878]: synapse.federation.transport.server.federation: [PUT-2399] Received txn 1671739103771 from stax.xyz. (PDUs: 0, EDUs: 1)
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: 2022-12-23 09:20:01,005 - synapse.http.matrixfederationclient - 299 - INFO - POST-514 - {GET-O-28266} [libera.chat] Completed request: 200 OK in 0.28 secs, got 493 bytes - GET matrix://libera.chat/_matrix/federation/v1/m
ake_join/%21prsKNofAcxGLYvnUPq%3Alibera.chat/%40dexter%3Abeetjevreemd.nl?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6&ver=org.matrix.msc2176&ver=7&ver=8&ver=9&ver=org.matrix.msc3787&ver=10&ver=org.matrix.msc2716v4
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: 2022-12-23 09:20:01,007 - synapse.http.server - 124 - ERROR - POST-514 - Failed handle request via 'ReplicationRemoteJoinRestServlet': <SynapseRequest at 0x7fc6da9277c0 method='POST' uri='/_synapse/replication/remote_joi
n/%21prsKNofAcxGLYvnUPq%3Alibera.chat/%40dexter%3Abeetjevreemd.nl/gymtOmZZMs' clientproto='HTTP/1.1' site='9093'>
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: Traceback (most recent call last):
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:     result = current_context.run(gen.send, result)
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:   File "/usr/lib64/python3.10/site-packages/synapse/util/caches/response_cache.py", line 246, in cb
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:     return await callback(*args, **kwargs)
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:   File "/usr/lib64/python3.10/site-packages/synapse/replication/http/membership.py", line 94, in _handle_request
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:     event_id, stream_id = await self.federation_handler.do_invite_join(
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:   File "/usr/lib64/python3.10/site-packages/synapse/handlers/federation.py", line 586, in do_invite_join
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]:     assert room_id not in self._federation_event_handler.room_queues
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: AssertionError
Dec 23 09:20:01 slank.platypusnet.org synapse-stream_presence1[59881]: synapse.replication.http.federation: [POST-8041] Got 'm.presence' edu from stax.xyz
Dec 23 09:20:01 slank.platypusnet.org synapse[59829]: 2022-12-23 09:20:01,017 - synapse.access.http.9093 - 460 - INFO - POST-514 - 127.0.0.1 - 9093 - {@dexter:beetjevreemd.nl} Processed request: 0.287sec/0.006sec (0.014sec, 0.002sec) (0.006sec/0.001sec/1) 55B 500 "POST /_sy
napse/replication/remote_join/%21prsKNofAcxGLYvnUPq%3Alibera.chat/%40dexter%3Abeetjevreemd.nl/gymtOmZZMs HTTP/1.1" "Synapse/1.74.0" [0 dbevts]
Dec 23 09:20:01 slank.platypusnet.org synapse-client2[59875]: synapse.http.client: [POST-48] Received response to POST http://127.0.0.1:9093/_synapse/replication/remote_join/%21prsKNofAcxGLYvnUPq%3Alibera.chat/%40dexter%3Abeetjevreemd.nl/gymtOmZZMs: 500
Dec 23 09:20:01 slank.platypusnet.org synapse-client2[59875]: synapse.http.server: [POST-48] <SynapseRequest at 0x7f7fac5803d0 method='POST' uri='/_matrix/client/r0/join/%23hamradio%3Alibera.chat' clientproto='HTTP/1.1' site='10032'> SynapseError: 500 - Internal server erro
r
Dec 23 09:20:01 slank.platypusnet.org synapse-client2[59875]: synapse.access.http.10032: [POST-48] ::ffff:127.0.0.1 - 10032 - {@dexter:beetjevreemd.nl} Processed request: 0.398sec/0.002sec (0.026sec, 0.000sec) (0.006sec/0.016sec/7) 55B 500 "POST /_matrix/client/r0/join/%23h
amradio%3Alibera.chat HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36.0 (KHTML, like Gecko) Chrome/106.0.5249.199 Safari/537.36.0" [0 dbevts]
```

**Comment by squahtx** [comment] 2023-01-09 11:09
Duplicate of #14581

**Closed by squahtx** 2023-01-09 11:09 UTC
