### ISSUE TITLE
Error is returned `Could not find event`  after logging in therefore unable to continue to access to any rooms.

### ISSUE THREAD

**Issue by cnguyen2049** [matrix-org/synapse#13015] opened 2022-06-09 22:16 UTC
### Description

Unable to access rooms because of an error thrown after login.

```
Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2.
```

### Steps to reproduce

- Use any client (ios/web/etc) to login
- Error is returned `Could not find event`  

### Homeserver

matrix.radiation.io

### Synapse Version

1.60.0

### Platform

Self hosted on Digital Ocean

### Relevant log output

```shell
{
  "formatVersion": 1,
  "appVersion": "0.2.29",
  "items": [
    {
      "s": 1654620287487,
      "d": 237,
      "v": {
        "l": "Platform init"
      },
      "l": 4,
      "c": [
        {
          "s": 236,
          "d": 0,
          "v": {
            "l": "change theme",
            "id": "element-light"
          },
          "l": 4
        }
      ]
    },
    {
      "s": 1654620301105,
      "d": 429,
      "v": {
        "l": "sync",
        "status": "InitialSync",
        "stopping": true
      },
      "l": 7,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 1,
          "d": 83,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/user/%40cnguyen%3Amatrix.radiation.io/filter?",
            "method": "POST",
            "status": 200
          },
          "l": 4
        },
        {
          "s": 84,
          "d": 345,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2",
            "method": "GET",
            "status": 404,
            "errcode": "M_NOT_FOUND"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    },
    {
      "s": 1654620300022,
      "d": 1512,
      "v": {
        "l": "login",
        "id": "2636284892344372",
        "appVersion": "0.2.29"
      },
      "l": 6,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 1,
          "d": 473,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/login?",
            "method": "POST",
            "status": 200
          },
          "l": 4
        },
        {
          "s": 474,
          "d": 328,
          "v": {
            "l": "inspectAccount"
          },
          "l": 4,
          "c": [
            {
              "s": 5,
              "d": 323,
              "v": {
                "t": "network",
                "url": "https://matrix.radiation.io/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device?",
                "method": "GET",
                "status": 404,
                "errcode": "M_NOT_FOUND"
              },
              "l": 6,
              "e": {
                "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
                "name": "HomeServerError",
                "message": "No dehydrated device available on GET https://matrix.radiation.io/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device?"
              }
            }
          ]
        },
        {
          "s": 817,
          "d": 3,
          "v": {
            "l": "storage migration",
            "oldVersion": 0,
            "version": 16
          },
          "l": 4,
          "c": [
            {
              "s": 0,
              "d": 0,
              "v": {
                "l": "v1"
              },
              "l": 4
            },
            {
              "s": 0,
              "d": 0,
              "v": {
                "l": "v2"
              },
              "l": 4
            },
            {
              "s": 0,
              "d": 1,
              "v": {
                "l": "v3"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v4"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v5"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v6"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v7"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v8"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v9"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 0,
              "v": {
                "l": "v10"
              },
              "l": 4
            },
            {
              "s": 1,
              "d": 1,
              "v": {
                "l": "v11"
              },
              "l": 4
            },
            {
              "s": 2,
              "d": 0,
              "v": {
                "l": "v12"
              },
              "l": 4
            },
            {
              "s": 2,
              "d": 0,
              "v": {
                "l": "v13",
                "restored": false
              },
              "l": 4
            },
            {
              "s": 2,
              "d": 0,
              "v": {
                "l": "v14"
              },
              "l": 4
            },
            {
              "s": 2,
              "d": 0,
              "v": {
                "l": "v15"
              },
              "l": 4
            },
            {
              "s": 2,
              "d": 1,
              "v": {
                "l": "v16",
                "countWithoutSession": 0,
                "countWithSession": 0
              },
              "l": 4
            }
          ]
        },
        {
          "s": 822,
          "d": 261,
          "v": {
            "l": "createIdentity",
            "keys": {
              "curve25519": "Bq+sxtyAZ845CUYFU0qPcy/q8FtMw5TNHDx4QUYzBB4",
              "ed25519": "rfseFZ0F0mQne9aGEtCMaaJ1T29I+FVNAubTZfvMYks"
            }
          },
          "l": 4,
          "c": [
            {
              "s": 26,
              "d": 235,
              "v": {
                "l": "uploadKeys",
                "identity": true,
                "otks": true,
                "serverOTKCount": 100
              },
              "l": 4,
              "c": [
                {
                  "s": 6,
                  "d": 227,
                  "v": {
                    "t": "network",
                    "url": "https://matrix.radiation.io/_matrix/client/r0/keys/upload?",
                    "method": "POST",
                    "status": 200
                  },
                  "l": 4
                }
              ]
            }
          ]
        },
        {
          "s": 1083,
          "d": 429,
          "v": {
            "l": "wait first sync"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    },
    {
      "s": 1654699843037,
      "d": 0,
      "v": {
        "l": "pagehide, closing logs",
        "t": "navigation"
      },
      "l": 4
    },
    {
      "s": 1654700011435,
      "d": 389,
      "v": {
        "l": "Platform init"
      },
      "l": 4,
      "c": [
        {
          "s": 389,
          "d": 0,
          "v": {
            "l": "change theme",
            "id": "element-light"
          },
          "l": 4
        }
      ]
    },
    {
      "s": 1654700011856,
      "d": 353,
      "v": {
        "l": "sync",
        "status": "InitialSync",
        "stopping": true
      },
      "l": 7,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 0,
          "d": 143,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/user/%40cnguyen%3Amatrix.radiation.io/filter?",
            "method": "POST",
            "status": 200
          },
          "l": 4
        },
        {
          "s": 144,
          "d": 209,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2",
            "method": "GET",
            "status": 404,
            "errcode": "M_NOT_FOUND"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    },
    {
      "s": 1654700011826,
      "d": 384,
      "v": {
        "l": "load session",
        "id": "2636284892344372",
        "appVersion": "0.2.29",
        "keys": {
          "curve25519": "Bq+sxtyAZ845CUYFU0qPcy/q8FtMw5TNHDx4QUYzBB4",
          "ed25519": "rfseFZ0F0mQne9aGEtCMaaJ1T29I+FVNAubTZfvMYks"
        }
      },
      "l": 6,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 30,
          "d": 354,
          "v": {
            "l": "wait first sync"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    },
    {
      "s": 1654700015698,
      "d": 296,
      "v": {
        "l": "sync",
        "status": "InitialSync",
        "stopping": true
      },
      "l": 7,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 1,
          "d": 47,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/user/%40cnguyen%3Amatrix.radiation.io/filter?",
            "method": "POST",
            "status": 200
          },
          "l": 4
        },
        {
          "s": 49,
          "d": 247,
          "v": {
            "t": "network",
            "url": "https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2",
            "method": "GET",
            "status": 404,
            "errcode": "M_NOT_FOUND"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    },
    {
      "s": 1654700015679,
      "d": 315,
      "v": {
        "l": "load session",
        "id": "2636284892344372",
        "appVersion": "0.2.29",
        "keys": {
          "curve25519": "Bq+sxtyAZ845CUYFU0qPcy/q8FtMw5TNHDx4QUYzBB4",
          "ed25519": "rfseFZ0F0mQne9aGEtCMaaJ1T29I+FVNAubTZfvMYks"
        }
      },
      "l": 6,
      "e": {
        "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
        "name": "HomeServerError",
        "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
      },
      "c": [
        {
          "s": 19,
          "d": 296,
          "v": {
            "l": "wait first sync"
          },
          "l": 6,
          "e": {
            "stack": "$s@https://hydrogen.element.io/assets/index.0e9d90da.js:1:5308\nan/this._promise<@https://hydrogen.element.io/assets/index.0e9d90da.js:1:6315\n",
            "name": "HomeServerError",
            "message": "Could not find event $8ny4WCh2OJgfop19n-JHCGjWjMe1OF-NrhJ7hbQ6n0c on GET https://matrix.radiation.io/_matrix/client/r0/sync?timeout=0&filter=2"
          }
        }
      ]
    }
  ]
}
```

**Comment by DMRobertson** [comment] 2022-06-10 00:02
Maybe #12864?

**Comment by richvdh** [comment] 2022-06-10 09:07
Duplicate of #12864

**Closed by richvdh** 2022-06-10 09:07 UTC
