### ISSUE TITLE
message search support for non-english user

### ISSUE THREAD

**Issue by xylonx** [matrix-org/synapse#14827] opened 2023-01-12 14:04 UTC
**Description:**

As coded below, I find now the message analyzer is 'english' only. 

https://github.com/matrix-org/synapse/blob/e9a4343cb2daa55503bb2a2d1431d83bf9773e68/synapse/storage/databases/main/search.py#L86
https://github.com/matrix-org/synapse/blob/e9a4343cb2daa55503bb2a2d1431d83bf9773e68/synapse/storage/databases/main/search.py#L470

But there are also many non-english users like me in matrix community.

Is it possible to make the analyzer configurable to split non-english sentences for better searching experience or pass the search requests to third-party full-text search engine like `elasticsearch`?

**Comment by clokep** [comment] 2023-01-12 14:09
I think this is essentially a duplicate of #10559 and/or #901.

**Comment by DMRobertson** [comment] 2023-01-12 16:30
https://github.com/matrix-org/synapse/issues/14608 has some more links and exploration of elasticsearch.

**Closed by DMRobertson** 2023-01-12 16:30 UTC
