### ISSUE TITLE
Failure to start synapse

### ISSUE THREAD

**Issue by itzzenxx** [matrix-org/synapse#15586] opened 2023-05-14 14:46 UTC
### Description

When upgrading to the latest commit for matrix-org/synapse (def4804) 
from commit (c34791e) I run into what seems like a database issue, however running `update_synapse_database` will also return this error.

### Steps to reproduce

- Install and setup a synapse 1.82.0 (c34791e) homeserver:
- Attempt to upgrade to the latest commit in this repo
- Error occurs when attempting to run synapse

### Homeserver

plus.st

### Synapse Version

1.83.0 (b=develop,def480443)

### Installation Method

Other (please mention below)

### Database

PostgreSQL

### Workers

Single process

### Platform

Distro: Arch Linux

No vms or containers are used

### Configuration

No unusual settings are turned on

### Relevant log output

```shell
May 14 14:28:11 plus.st matrix-synapse[278525]: 2023-05-14 14:28:11,441 - root - 350 - WARNING - main - ***** STARTING SERVER *****
May 14 14:28:11 plus.st matrix-synapse[278525]: 2023-05-14 14:28:11,441 - root - 351 - WARNING - main - Server /opt/matrix-synapse/synapse/app/homeserver.py version 1.83.0 (b=develop,def480442)
May 14 14:28:11 plus.st matrix-synapse[278525]: 2023-05-14 14:28:11,458 - synapse.app._base - 215 - ERROR - main - Exception during startup
May 14 14:28:11 plus.st matrix-synapse[278525]: Traceback (most recent call last):
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/app/homeserver.py", line 352, in setup
May 14 14:28:11 plus.st matrix-synapse[278525]:     hs.setup()
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/server.py", line 337, in setup
May 14 14:28:11 plus.st matrix-synapse[278525]:     self.datastores = Databases(self.DATASTORE_CLASS, self)
May 14 14:28:11 plus.st matrix-synapse[278525]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/databases/__init__.py", line 74, in __init__
May 14 14:28:11 plus.st matrix-synapse[278525]:     prepare_database(
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/prepare_database.py", line 141, in prepare_database
May 14 14:28:11 plus.st matrix-synapse[278525]:     _upgrade_existing_database(
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/prepare_database.py", line 535, in _upgrade_existing_database
May 14 14:28:11 plus.st matrix-synapse[278525]:     database_engine.execute_script_file(cur, absolute_path)
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/engines/_base.py", line 149, in execute_script_file
May 14 14:28:11 plus.st matrix-synapse[278525]:     cls.executescript(cursor, f.read())
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/engines/postgres.py", line 228, in executescript
May 14 14:28:11 plus.st matrix-synapse[278525]:     cursor.execute(f"COMMIT; BEGIN TRANSACTION; {script}")
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/database.py", line 417, in execute
May 14 14:28:11 plus.st matrix-synapse[278525]:     self._do_execute(self.txn.execute, sql, parameters)
May 14 14:28:11 plus.st matrix-synapse[278525]:   File "/opt/matrix-synapse/synapse/storage/database.py", line 469, in _do_execute
May 14 14:28:11 plus.st matrix-synapse[278525]:     return func(sql, *args, **kwargs)
May 14 14:28:11 plus.st matrix-synapse[278525]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 14:28:11 plus.st matrix-synapse[278525]: psycopg2.errors.DuplicateColumn: column "event_stream_ordering" of relation "current_state_events" already exists
May 14 14:28:11 plus.st matrix-synapse[278525]: **********************************************************************************
May 14 14:28:11 plus.st matrix-synapse[278525]:  Error during initialisation:
May 14 14:28:11 plus.st matrix-synapse[278525]:      Traceback (most recent call last):
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/app/homeserver.py", line 352, in setup
May 14 14:28:11 plus.st matrix-synapse[278525]:          hs.setup()
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/server.py", line 337, in setup
May 14 14:28:11 plus.st matrix-synapse[278525]:          self.datastores = Databases(self.DATASTORE_CLASS, self)
May 14 14:28:11 plus.st matrix-synapse[278525]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/databases/__init__.py", line 74, in __init__
May 14 14:28:11 plus.st matrix-synapse[278525]:          prepare_database(
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/prepare_database.py", line 141, in prepare_database
May 14 14:28:11 plus.st matrix-synapse[278525]:          _upgrade_existing_database(
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/prepare_database.py", line 535, in _upgrade_existing_database
May 14 14:28:11 plus.st matrix-synapse[278525]:          database_engine.execute_script_file(cur, absolute_path)
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/engines/_base.py", line 149, in execute_script_file
May 14 14:28:11 plus.st matrix-synapse[278525]:          cls.executescript(cursor, f.read())
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/engines/postgres.py", line 228, in executescript
May 14 14:28:11 plus.st matrix-synapse[278525]:          cursor.execute(f"COMMIT; BEGIN TRANSACTION; {script}")
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/database.py", line 417, in execute
May 14 14:28:11 plus.st matrix-synapse[278525]:          self._do_execute(self.txn.execute, sql, parameters)
May 14 14:28:11 plus.st matrix-synapse[278525]:        File "/opt/matrix-synapse/synapse/storage/database.py", line 469, in _do_execute
May 14 14:28:11 plus.st matrix-synapse[278525]:          return func(sql, *args, **kwargs)
May 14 14:28:11 plus.st matrix-synapse[278525]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 14:28:11 plus.st matrix-synapse[278525]:      psycopg2.errors.DuplicateColumn: column "event_stream_ordering" of relation "current_state_events" already exists
May 14 14:28:11 plus.st matrix-synapse[278525]:  
May 14 14:28:11 plus.st matrix-synapse[278525]:  
May 14 14:28:11 plus.st matrix-synapse[278525]:  There may be more information in the logs.
May 14 14:28:11 plus.st systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
```
```


### Anything else that would be useful to know?

Synapse was installed using poetry which was installed via pipx

**Comment by MatMaul** [comment] 2023-05-15 12:05
We don't really support deployment tracking `develop`, this is a bit dangerous.

What is probably happening is that we had a trouble with this change at first, it got [reverted](https://github.com/matrix-org/synapse/commit/5350b5d04da8aca80b60a6b4970020d13d789501) and you probably updated before the revert, so the previous delta did apply already.
You can check that `74/01membership_tables_event_stream_ordering.sql` was applied by looking at `SELECT * FROM applied_schema_deltas;`.

In this case you should be able to remove the added columns by doing the following queries.
# **PLEASE DO A DATABASE BACKUP BEFORE !!**
```
ALTER TABLE current_state_events DROP COLUMN event_stream_ordering;
ALTER TABLE local_current_membership DROP COLUMN event_stream_ordering;
ALTER TABLE room_memberships DROP COLUMN event_stream_ordering;
```

If you are not able to track down this kind of trouble on your own, we really do not recommend that you track `develop`.

I am closing since it is not a bug.

**Closed by MatMaul** 2023-05-15 12:05 UTC

**Comment by itzzenxx** [comment] 2023-05-16 05:45
This fixed the issue, thank you!
