### ISSUE TITLE
synapse takes a long time to restart

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8117] opened 2020-08-18 18:30 UTC
for example:

```
2020-08-18 17:21:25,829 - root - 296 - WARNING - None - ***** STARTING SERVER *****
2020-08-18 17:21:25,829 - root - 297 - WARNING - None - Server /home/synapse/src/synapse/app/homeserver.py version 1.19.0 (b=HEAD,0cbe4889d)
2020-08-18 17:21:25,829 - root - 298 - INFO - None - Server hostname: matrix.org
2020-08-18 17:21:25,829 - root - 299 - INFO - None - Instance name: master
2020-08-18 17:21:25,829 - synapse.app.homeserver - 375 - INFO - None - Setting up server
2020-08-18 17:21:25,829 - synapse.server - 248 - INFO - None - Setting up.
2020-08-18 17:21:26,221 - synapse.storage.databases - 50 - INFO - None - Preparing database 'master'...
2020-08-18 17:21:51,790 - synapse.storage.prepare_database - 325 - INFO - None - Upgrading schema to v58
2020-08-18 17:21:51,791 - synapse.storage.prepare_database - 402 - INFO - None - Applying schema 58/13remove_presence_allow_inbound.sql
2020-08-18 17:21:57,079 - synapse.storage.databases - 60 - INFO - None - Starting 'main' data store
2020-08-18 17:22:37,987 - synapse.config.appservice - 87 - INFO - None - Loaded application service: ApplicationService: 
....
```

and then we're off. why did it take over a minute to get going?

**Comment by clokep** [comment] 2020-08-18 18:38
I think this is a duplicate of #7968.

**Closed by clokep** 2020-08-18 18:38 UTC

**Comment by richvdh** [comment] 2020-08-19 10:25
thank you. I could have sworn I'd filed it, but couldn't find it.
