### ISSUE TITLE
Joining #Python:matrix.org and some other channels fails with `Invalid ID: 'matrix.org'` in logs and 500 Internal server error

### ISSUE THREAD

**Issue by jonaharagon** [matrix-org/synapse#5599] opened 2019-07-02 17:37 UTC
### Description

Joining some channels like #Python:matrix.org or #newrooms:matrix.org fail with a 500 Internal server error in Riot and a massive stack trace.

### Steps to reproduce

- Join #Python:matrix.org from a homeserver other than matrix.org

Pasting in the first 9 lines alone was far too much text for my laptop or GitHub to handle but I've attached the full logs here. The very first lines are related to this issue.

[homeserver.log.zip](https://github.com/matrix-org/synapse/files/3351602/homeserver.log.zip)

### Version information

- **Homeserver**: `chat.privacytools.io`

This does seem to affect other homeservers, `@tleydxdy:mt.tlebear.win` reported the same issue when I asked about it in `#synapse`, but it doesn't affect matrix.org

- **Version**: 1.0.0

- **Install method**: Apt package

- **Platform**: Ubuntu 18.04 in LXC container, 16 GB RAM (~2.8 in use), 35% disk space used, quad-core Xeon CPU.

**Comment by tleydxdy** [comment] 2019-07-02 17:46
adding a few preliminary info:
#Python:matrix.org doesn't have any other useable alias, the only other one belongs to a dead (fed tester) homeserver
joining with https://riot.im/app/#/room/!AvljWqLSmaPoBcJquf:matrix.org?via=some_server (tried librem.one and kde.org, both are in the room) gives "unknown room"
my homeserver and myself (mt.tlebear.win) both appares in the room state. 
joining with librem.one produces internal server error too.

**Comment by aaronraimist** [comment] 2019-07-02 23:17
For searchability the (truncated) error messages are:
```
2019-07-02 16:41:36,633 - synapse.http.server - 112 - ERROR - POST-1697124- Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7faa2f29cc50 method='POST' uri='/_matrix/client/r0/join/%23Python%3Amatrix.org' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 162, in _handle_json_response
    defer.returnValue(body)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [200, {'state': [{'auth_events': [['$1416421240761ezAAU:matrix.org', {'sha256': 'Wvsrc92M44SLQ3pcLg5XkGM5fs0fu9loo4Wxzh54Ydk'}], ['$148287937227ydmFn:dawninglight.net', {'sha256': 'ViMw/BNQ9TBiZdmvJLz0gu12LrSJ7xtngZcFqXtxPG8'}], ['$1416421240705siUCi:matrix.org', {'sha256': '4mM6NHUoJLkNUPpHFukEerCnKoU5zZ52/MYufHHa9S4'}]], 'content': {'aliases': ['#python:dawninglight.net']}, 'depth': 1424, 'event_id': '$148289335737FZuuq:dawninglight.net', 'hashes':.....

raceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 641, in put_json
    defer.returnValue(body)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [200, {'state': [{'auth_events': [['$1416421240761ezAAU:matrix.org', {'sha256':.....

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 276, in send_join
    defer.returnValue(response)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [200, {'state': [{'auth_events': [['$1416421240761ezAAU:matrix.org', {'sha256':......

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 527, in _try_destination_list
    res = yield callback(destination)
synapse.api.errors.SynapseError: 400: Invalid ID: 'matrix.org'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 293, in on_POST
    third_party_signed=content.get("third_party_signed", None),
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 335, in update_membership
    require_consent=require_consent,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 515, in _update_membership
    requester, remote_room_hosts, room_id, target, content
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 1043, in _remote_join
    content,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/federation.py", line 1166, in do_invite_join
    target_hosts, event, event_format_version,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 548, in _try_destination_list
    raise RuntimeError("Failed to %s via any server" % (description, ))
RuntimeError: Failed to send_join via any server
```

Each of those `twisted.internet.defer._DefGen_Return:` lines has about 4 million characters on them

**Comment by Lrizika** [comment] 2019-07-02 23:23
Trying to join #Python:matrix.org via matrix.recursiv.com (the first server I found in the room state that's online and federating) returns a 403 Forbidden: No create event in auth events

```
2019-07-02 23:05:15,248 - synapse.access.http.8008 - 233 - INFO - POST-2185 - 159.203.35.189 - 8008 - Received request: POST /_matrix/client/r0/join/%21AvljWqLSmaPoBcJquf%3Amatrix.org?server_name=matrix.recursiv.com&access_token=<redacted>
2019-07-02 23:05:15,249 - synapse.http.servlet - 212 - WARNING - POST-2185 - Unable to parse JSON: Expecting value: line 1 column 1 (char 0)
2019-07-02 23:05:15,250 - synapse.metrics - 372 - INFO -  - Collecting gc 0
2019-07-02 23:05:15,274 - synapse.http.matrixfederationclient - 401 - INFO - POST-2185 - {GET-O-2729} [matrix.recursiv.com] Sending request: GET matrix://matrix.recursiv.com/_matrix/federation/v1/make_join/%21AvljWqLSmaPoBcJquf%3Amatrix.org/%40testuser%3Alrizika.com?ver=1&ver=2&ver=3&ver=4&ver=5; timeout 20.000000s
2019-07-02 23:05:15,328 - synapse.access.http.8008 - 233 - INFO - GET-2186 - 192.241.214.14 - 8008 - Received request: GET /_matrix/federation/v1/query/profile?user_id=%40lrizika%3Alrizika.com&field=avatar_url
2019-07-02 23:05:15,331 - synapse.federation.transport.server - 147 - INFO - GET-2186 - Request from librem.one
2019-07-02 23:05:15,340 - synapse.access.http.8008 - 302 - INFO - GET-2186 - 192.241.214.14 - 8008 - {librem.one} Processed request: 0.011sec/0.001sec (0.006sec, 0.000sec) (0.000sec/0.005sec/1) 60B 200 "GET /_matrix/federation/v1/query/profile?user_id=%40lrizika%3Alrizika.com&field=avatar_url HTTP/1.1" "Synapse/0.99.3" [0 dbevts]
2019-07-02 23:05:15,367 - synapse.http.matrixfederationclient - 433 - INFO - POST-2185 - {GET-O-2729} [matrix.recursiv.com] Got response headers: 403 Forbidden
2019-07-02 23:05:15,369 - synapse.http.matrixfederationclient - 517 - WARNING - POST-2185 - {GET-O-2729} [matrix.recursiv.com] Request failed: GET matrix://matrix.recursiv.com/_matrix/federation/v1/make_join/%21AvljWqLSmaPoBcJquf%3Amatrix.org/%40testuser%3Alrizika.com?ver=1&ver=2&ver=3&ver=4&ver=5: HttpResponseException("403: b'Forbidden'",)
2019-07-02 23:05:15,372 - synapse.http.server - 85 - INFO - POST-2185 - <XForwardedForRequest at 0x7f3a146cb7f0 method='POST' uri='/_matrix/client/r0/join/%21AvljWqLSmaPoBcJquf%3Amatrix.org?server_name=matrix.recursiv.com&access_token=<redacted>' clientproto='HTTP/1.1' site=8008> SynapseError: 403 - No create event in auth events
2019-07-02 23:05:15,374 - synapse.access.http.8008 - 302 - INFO - POST-2185 - 159.203.35.189 - 8008 - {@testuser:lrizika.com} Processed request: 0.125sec/0.001sec (0.012sec, 0.000sec) (0.008sec/0.012sec/3) 66B 403 "POST /_matrix/client/r0/join/%21AvljWqLSmaPoBcJquf%3Amatrix.org?server_name=matrix.recursiv.com&access_token=<redacted> HTTP/1.1" "python-requests/2.21.0" [0 dbevts]
2019-07-02 23:05:15,374 - synapse.metrics - 372 - INFO -  - Collecting gc 0
```

**Comment by neilisfragile** [comment] 2019-07-03 15:57
This is really strange. I can't reproduce, but looking at the backtrace it seems to be related to a very old event 
```
$1416421240719brFce:matrix.org | !AvljWqLSmaPoBcJquf:matrix.org | {"outlier":0}     | {"auth_events":[],"content":{"aliases":["#Python:matrix.org"]},"depth":2,"event_id":"$1416421240719brFce:matrix.org","hashes":{"sha256":"yfONlq2DqwW5FFVhZBMVxIEH04/oH2zf2b/ztDKpB4A"},
"origin":"matrix.org","origin_server_ts":1411148782694,"prev_events":[["$1416421240710vbKvD:matrix.org",{"sha256":"T9cMEqMIgDUa7brea4Zt8lM5v5teJs8C9yYbNRuYQk0"}]],"prev_state":[],"room_id":"!AvljWqLSmaPoBcJquf:matrix.org","sender":"matrix.org","signatures":{"matrix.org"
:{"ed25519:auto":"WNcCXxN0XNkdu/DuY7BzGAS6vCXSYGMN8arhTrjOs97+7KxrAhb9zcYVMJo1q5QcNdR9wAKjmWMH8KUyCVsRDw"}},"state_key":"matrix.org","stream_ordering":7195,"type":"m.room.aliases","unsigned":{"age_ts":1416421240719}}
```
It has no auth events, and a sender of ```matrix.org```

So while I can't reproduce and in fact wonder if the true bug is being obscured, the best I can suggest is to upgrade the room to v4.

**Comment by strufkin** [comment] 2019-09-25 14:18
just got same issue with `#Python:matrix.org` today and unable to join via any alias


`2019-09-25 17:03:15,948 - synapse.federation.federation_client - 538 - WARNING - POST-107143 - Failed to send_join via matrix.org
Traceback (most recent call last):
  File "/home/deployer/projects/synapseenv/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
`

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deployer/projects/synapseenv/env/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 522, in _try_destination_list
    res = yield callback(destination)
synapse.api.errors.SynapseError: 400: Invalid ID: 'matrix.org'
2019-09-25 17:04:32,075 - synapse.http.server - 79 - INFO - POST-107256 - <XForwardedForRequest at 0xa360a14c method='POST' uri='/_matrix/client/r0/join/%23Python%3Amatrix.org' clientproto='HTTP/1.1' site=8008> SynapseError: 502 - Failed to send_join via any server

`

**Comment by JuniorJPDJ** [comment] 2020-02-27 23:26
I've got this on #synapse:matrix.org and #facebook:maunium.net
I workarounded this by joining with ?via=other_server.org
eg. facebook with matrix.org and synapse with anarchy.community
I needed to use room id, not alias

**Comment by ilmari** [comment] 2020-06-23 00:59
I'm seeing this when trying to join `#perl:matrix.org`. The offending event in this case is an `m.room.aliases` event from October 2014 with `"sender":"matrix.org"`:

(300kB of state events in `StopIteration` truncated)
```
2020-06-22 23:40:53,064 - synapse.http.federation.matrix_federation_agent - 242 - INFO - POST-4329334- Connecting to jki.re:8080
2020-06-22 23:40:53,387 - synapse.federation.federation_client - 496 - WARNING - POST-4329334- Failed to send_join via jki.re
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'state': [...]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'state': [...]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'state': [...]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_client.py", line 477, in _try_destination_list
    res = await callback(destination)
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_client.py", line 661, in send_request
    room_version=room_version,
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_client.py", line 375, in _check_sigs_and_hash_and_fetch
    deferreds = self._check_sigs_and_hashes(room_version, pdus)
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_base.py", line 79, in _check_sigs_and_hashes
    deferreds = _check_sigs_on_pdus(self.keyring, room_version, pdus)
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_base.py", line 189, in _check_sigs_on_pdus
    for p in pdus
  File "/usr/lib/python3/dist-packages/synapse/federation/federation_base.py", line 189, in <listcomp>
    for p in pdus
  File "/usr/lib/python3/dist-packages/synapse/types.py", line 133, in get_domain_from_id
    raise SynapseError(400, "Invalid ID: %r" % (string,))
synapse.api.errors.SynapseError: 400: Invalid ID: 'matrix.org'
```

```json
{
    "auth_events": [
        [
            "$1416421133431GSvId:matrix.org",
            {
                "sha256": "YmuSWF3OtK8D+hMx5+218us3i2tURsEiuB286RAeJqg"
            }
        ]
    ],
    "content": {
        "aliases": [
            "#Perl:matrix.org",
            "#perl:matrix.org"
        ]
    },
    "depth": 191,
    "event_id": "$1416421135318IkLdw:matrix.org",
    "hashes": {
        "sha256": "XrLibT4C3tJhVOLo3RMpMsmpNtCaIvO44/fX+KuPvHM"
    },
    "origin": "matrix.org",
    "origin_server_ts": 1412695786954,
    "prev_events": [
        [
            "$1416421135304DHWtS:matrix.org",
            {
                "sha256": "5U9k/dOmF+ocSR32giYbTEOV9eHklrL4nfyqQWlO/tw"
            }
        ]
    ],
    "prev_state": [
        [
            "$1416421134445Btarx:matrix.org",
            {
                "sha256": "0kGmXtUmD5oXMmsGw8n7x9qqL6w5aV1vt9EW/DwGz6c"
            }
        ]
    ],
    "room_id": "!rAnyijhRxzFRfdjSHl:matrix.org",
    "sender": "matrix.org",
    "signatures": {
        "jki.re": {
            "ed25519:auto": "/pAp2/CwvYmLUWTkS5QcEPT0/AiZRtriZ2G3broPjOKkFgFBulTYIEKaZKWjrsTH0sRIZdgcqlZWm0Qov3ZeCQ"
        },
        "matrix.org": {
            "ed25519:auto": "IAbaFIyftKpDK0M/vHdrBeK2W/t4pUUbCTI5PtHZXuUvVP5QQ3HDzgs9fVOd10+SAc+eA1jtYlKkEsN0m+6CCQ"
        }
    },
    "state_key": "matrix.org",
    "stream_ordering": 11825,
    "type": "m.room.aliases",
    "unsigned": {
        "age": 175687531043
    }
}
```

**Comment by ilmari** [comment] 2020-12-08 13:09
As a workaround for #perl:matrix.org, @leonerd upgraded the room, which at least would let new users join the room, even if they can't see the history from before the upgrade if their server wasn't already in the room.

**Comment by DMRobertson** [comment] 2022-11-23 13:21
From what I can see:
- this error only arose when trying to join a v1/v2 room
- the resident Synapse was serving up invalid state events in the /send_join response, which the joining Synapse (rightly) complained about
- the error message comes from here (or somewhere like it in an older version of the source) https://github.com/matrix-org/synapse/blob/70a4317692adcf7f1dacb201cda2188c8495bfa9/synapse/federation/federation_base.py#L212-L217

I suggest we consider this WONTFIX and advise anyone seeing this to upgrade to a newer room version.

**Closed by DMRobertson** 2022-11-23 13:21 UTC
Labels: A-Federated-Join, S-Major, T-Defect, O-Uncommon
