### ISSUE TITLE
Request: please mirror docker images to ghcr.io or ECR public

### ISSUE THREAD

**Issue by williamkray** [matrix-org/synapse#15270] opened 2023-03-15 17:39 UTC
Docker as a company has taken several moves that leave me concerned about their friendliness to open source projects, and clearly have an aggressive approach to handling their customers. I would feel much safer knowing that matrix.org published images to multiple "official" locations, perhaps including ghcr.io (a feature built into this repository) or ECR public (hosted by AWS and mirroring many images already) so that I can pull from a different source if/when Dockerhub decides to change their policies again.

**Comment by williamkray** [comment] 2023-03-15 17:42
for reference, dockerhub's latest move adds fees to open source projects. matrix.org may not be affected by this _this time_, but as an end user i would prefer not to continue to use their services, and redundancy is always a good idea.

https://news.ycombinator.com/item?id=35166317

**Comment by reivilibre** [comment] 2023-03-15 18:26
(likely duplicate of #10977)

**Closed** 2023-03-15 18:34 UTC
