### ISSUE TITLE
Rooms can't be publicly joined if nobody from the originating homeserver is in them

### ISSUE THREAD

**Issue by mashedkeyboard** [matrix-org/synapse#12486] opened 2022-04-16 22:55 UTC
### Description

Some particularly strange behaviour when using federated rooms... best illustrated by the steps below:

### Steps to reproduce

- User A, from homeserver a, creates room 1 as a public room.
- User B, from homeserver b, joins room 1.
- User A leaves room 1.
- User B is still in room 1, and any user on homeserver b can peek room 1. User B can send messages into room 1 as normal.
- User A cannot rejoin room 1, and no new users on homeserver a can either; they all get an error `{"errcode":"M_UNKNOWN","error":"No known servers"}` on trying to do so. Room 1 is not visible in homeserver a's list of public rooms, either.
- Users on any homeserver other than a cannot join room 1 either; they would get an error `{"errcode":"M_NOT_FOUND","error":"Not an active room on this server"}`.
- Attempting to create a new room with the same name on homeserver a results in an error, as `_matrix/client/r0/directory/room/#1:a.homeserver` returns `{"room_id":"!theId:a.homeserver","servers":["a.homeserver"]}`
- If user B invites user A back to room 1, user A can join room 1 just fine(!)

I hope it goes without saying that this is rather bizarre behaviour 😅

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: mashed.cloud, but also replicated on another different server

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.56.0

- **Install method**: package manager (Matrix.org debian packages)
<!-- examples: package manager/git clone/pip  --> 

- **Platform**: Ubuntu Linux 20.04.4 (Linux 5.4.0-107-generic on x86_64) running on a virtual private server
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by mashedkeyboard** [comment] 2022-04-16 23:28
**Workaround:**

- User B sends an invite to the room to user C, from homeserver a.
- User C joins the room successfuly from the invite.
- User A can now join the room without being invited.

So it looks like the process of inviting someone from homeserver a might "reset" the way that homeserver a sees the room? I'm not really sure how this works from a technical perspective, though.

**Comment by dinosmm** [comment] 2022-04-16 23:37
We've replicated this on my own homeserver too, exactly the same behaviour (also on 1.56.0, installed from deb packages, ubuntu 20.04).

In addition to the original post, it seems that user A cannot rejoin the room until another user from the same homeserver is invited and joins. Then, user A can immediately rejoin the room, with an invite or just by using the room name/link.

**Comment by DMRobertson** [comment] 2022-04-20 12:05
Related: https://github.com/matrix-org/synapse/issues/9555 https://github.com/matrix-org/synapse/issues/1533

**Comment by DMRobertson** [comment] 2022-04-21 10:50
> User A cannot rejoin room 1, and no new users on homeserver a can either; they all get an error `{"errcode":"M_UNKNOWN","error":"No known servers"}` on trying to do so. Room 1 is not visible in homeserver a's list of public rooms, either.

It's important to understand here exactly how you try to rejoin the room from homeserver a. Are you trying to join via an alias, e.g. `#roomname:server-a`?

**Comment by reivilibre** [comment] 2022-04-21 13:29
At a first guess I'd say you're trying to join using the Room ID, but haven't told it any known servers in the room.
A homeserver can't join a room it doesn't know about unless it knows where it can find out about the room.
In matrix.to URLs that use room IDs (`!blahblah:blah`), this is what the `?via` parameter(s) is/are about, e.g. https://matrix.to/#/!EIcIdEmAuTlbfObBIr:librepush.net?via=librepush.net&via=element.io.
Otherwise, using a room alias (`#blahblah:blah`) is best because the server name within the alias is a known server that knows about the room.

As the comment above this one says, knowing how exactly you're rejoining the room is important. If you're not typing in the room ID manually, it's possibly a client bug.

**Comment by mashedkeyboard** [comment] 2022-04-23 00:25
Yes, joining via a room alias just like that. As a user, it makes little sense for the room to continue to have that alias assigned to it on other homeservers if the homeserver that the alias belongs to has left, at least to my thinking; would it not make more sense either for Synapse to "forward" requests for that room to another server still in the room, or for the room's ID to update to another homeserver when it leaves?

The latter of those two options might be a spec change rather than a Synapse change, though, I guess.

**Comment by byanes** [comment] 2022-04-28 11:46
Seeing something similar to this, joining room via room alias.

User A, creates room and invites user B to join
User A leaves the room before User B has joined
User B tries to join the room

The error being thrown: {"errcode":"M_UNKNOWN","error":"No known servers"}

**Comment by aaronraimist** [comment] 2022-06-25 03:30
Maybe I am misunderstanding but the title of the issue seems to be a bit misleading. The problem actually seems to be: Aliases on a homeserver stop working when all users from that homeserver leave the room.

The room isn't unjoinable. Users can still join by using an alias on another server, receiving an invite, or using the room ID if you know the appropriate `via` servers.

One solution would be to automatically delete aliases when all users from a homeserver have left a room https://github.com/matrix-org/synapse/issues/1201

Alternatively https://github.com/matrix-org/synapse/issues/9555#issuecomment-792716769 points out that Synapse could continue to handle alias queries even after it has left the room. It's true the homeserver could provide the room ID but it wouldn't be able to give an up to date list of servers that are in the room to join through. This also wouldn't work once https://github.com/matrix-org/synapse/issues/4720 has been implemented.

**Comment by richvdh** [comment] 2022-06-27 11:30
I think this is just a duplicate of #9555?

**Closed by richvdh** 2022-06-27 11:30 UTC
Labels: A-Federated-Join, S-Minor, T-Defect
