### ISSUE TITLE
we select servers for joins based on the list returned by /directory (or at random?) rather than preferring the one in the alias which is being joined

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3812] opened 2018-09-06 15:58 UTC
surely if we trust a server to resolve an alias we should also trust/prefer it to seed your copy of the room

**Comment by ara4n** [comment] 2018-09-06 16:01
related to https://github.com/matrix-org/synapse/issues/2418

**Comment by richvdh** [comment] 2018-09-06 22:31
just a dupe of #2418 I think.

**Closed by richvdh** 2018-09-06 22:31 UTC
