### ISSUE TITLE
URL preview doesn't keep gif mime type

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/synapse#11879] opened 2022-02-01 15:39 UTC
### Description

https://github.com/vector-im/element-web/issues/20838

### Related

#1278

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.51

- **Install method**: matrix-docker-ansible-deploy
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2022-02-01 16:05
I think this is essentially a duplicate of #1278. Synapse currently thumbnails gifs to pngs.

**Closed by clokep** 2022-02-01 16:05 UTC

**Comment by HarHarLinks** [comment] 2022-02-01 16:11
But @clokep the image plays back in Element as a gif correctly, which leads me to believe it isn't the thumbnailer bug?
