### ISSUE TITLE
Synapse receiving improper federation traffic

### ISSUE THREAD

**Issue by dakotawhitevalley** [matrix-org/synapse#7425] opened 2020-05-05 16:35 UTC
### Description
After leaving various federated rooms, homeserver.log is still showing federation traffic from other homeservers.

### Steps to reproduce
- Join any room from the Matrix.org room list
- Leave it

### `homeserver.log` snippets:
```
2020-05-05 12:27:07,176 - synapse.federation.transport.server - 406 - INFO - PUT-928 - Received txn 1585878971193 from [redacted]. (PDUs: 0, EDUs: 1)
2020-05-05 12:27:07,194 - synapse.access.http.8008 - 302 - INFO - PUT-928 - [redacted] - 8008 - {[redacted]} Processed request: 0.020sec/0.001sec (0.005sec, 0.000sec) (0.002sec/0.011sec/3) 12B 200 "PUT /_matrix/federation/v1/send/1585878971193 HTTP/1.1" "Synapse/1.12.2" [0 dbevts]
2020-05-05 12:27:07,254 - synapse.federation.transport.server - 406 - INFO - PUT-929 - Received txn 1588117400422 from [redacted]. (PDUs: 0, EDUs: 1)
2020-05-05 12:27:07,277 - synapse.access.http.8008 - 302 - INFO - PUT-929 - [redacted] - 8008 - {[redacted]} Processed request: 0.026sec/0.000sec (0.001sec, 0.002sec) (0.002sec/0.018sec/4) 12B 200 "PUT /_matrix/federation/v1/send/1588117400422 HTTP/1.1" "Synapse/1.12.4" [0 dbevts]
2020-05-05 12:27:07,890 - synapse.federation.transport.server - 406 - INFO - PUT-930 - Received txn 1588117402383 from [redacted]. (PDUs: 0, EDUs: 1)
2020-05-05 12:27:07,902 - synapse.access.http.8008 - 302 - INFO - PUT-930 - [redacted] - 8008 - {[redacted]} Processed request: 0.014sec/0.000sec (0.001sec, 0.000sec) (0.001sec/0.008sec/2) 12B 200 "PUT /_matrix/federation/v1/send/1588117402383 HTTP/1.1" "Synapse/1.12.4" [0 dbevts]
```

### Version information
- **Version**:
```
{
    "python_version": "3.6.9",
    "server_version": "1.12.4"
}
```
- **Install method**: `pip`

- **Platform**:
Running on Ubuntu Server 18.04 LTS on a Dell Optiplex 790, baremetal.
Experienced this issue when running in a VM as well.

**Comment by anoadragon453** [comment] 2020-05-12 10:17
Hmm, EDUs. Could be presence updates?

**Comment by richvdh** [comment] 2020-05-12 14:11
suggests that the other end hasn't got the memo that you've left the room. I don't think we can do much about that without logs from the other end or even any clues as to which server they are coming from, so I'm going to close it for now.

If you can reproduce it and supply logs from both sides, or if the transactions are coming from matrix.org, then we can reopen.

**Closed by richvdh** 2020-05-12 14:11 UTC
Labels: bug, p3

**Comment by dakotawhitevalley** [comment] 2020-05-12 14:26
@richvdh I only censored the server names because I wasn't sure if they were allowed to be posted here. That log has an innumerable amount of servers that I continuously get traffic from, and `matrix.org` is most definitely in there.

I am only in one federated room on a friend's server at the moment, I've left every room/direct message from all servers I was previously in, matrix.org included, and still all of the other server traffic comes pouring in.

![image](https://user-images.githubusercontent.com/4442088/81703293-61ea9900-943a-11ea-8865-02f070b7c705.png)

![image](https://user-images.githubusercontent.com/4442088/81703696-ef2ded80-943a-11ea-9191-7f003d033ba7.png)

**Comment by richvdh** [comment] 2020-05-12 14:40
ok if you let us know your server name we can look on the matrix.org side

**Comment by dakotawhitevalley** [comment] 2020-05-12 14:42
@richvdh `matrix.rdash.in`

Thanks for taking a look, I'd love to know what you find...

**Comment by richvdh** [comment] 2020-05-12 14:56
it appears that `@eaburdick3:matrix.rdash.in` is still a member of `!QtykxKocfZaZOUrTwp:matrix.org` (a historical version of Matrix HQ) and `!iNmaIQExDMeqdITdHH:matrix.org` (a historical version of (I think) `#riot:matrix.org`).

**Comment by dakotawhitevalley** [comment] 2020-05-12 14:59
That is my account, but I am most definitely **not** in those rooms at the moment. I left everything over 2 months ago.

**Comment by richvdh** [comment] 2020-05-12 15:08
your memberships of `!iNmaIQExDMeqdITdHH:matrix.org` as seen by the rest of the federation:

```
              event_id               |      to_timestamp      | membership 
-------------------------------------+------------------------+------------
 $15459396183ohpmX:matrix.rdash.in   | 2018-12-27 19:40:18+00 | join
 $15459397267MfkcY:matrix.rdash.in   | 2018-12-27 19:42:06+00 | join
 $1547961617271vFkhU:matrix.rdash.in | 2019-01-20 05:20:17+00 | join
 $15490918659daxaH:matrix.rdash.in   | 2019-02-02 07:17:45+00 | join
 $154956563922BCvQV:matrix.rdash.in  | 2019-02-07 18:53:59+00 | join
 $154956606143uxzQh:matrix.rdash.in  | 2019-02-07 19:01:01+00 | leave
 $155776503813lvoqX:matrix.rdash.in  | 2019-05-13 17:30:38+01 | join
 $15589304255pjOKY:matrix.rdash.in   | 2019-05-27 05:13:45+01 | leave
 $15611319370eSWSP:matrix.rdash.in   | 2019-06-21 16:45:36+01 | join
```

so basically your leave didn't get through. Without logs we can't do much about it. I suggest you re-join, re-leave, and if that doesn't solve the problem, open a new bug with logs of the leave. Also worth using a matrix.org account to watch what happens from that side.

**Comment by dakotawhitevalley** [comment] 2020-05-12 15:11
@richvdh Will it even let me rejoin the room if it's a historical version? I thought once the "tombstone" is set, that room becomes dead now?

**Comment by dakotawhitevalley** [comment] 2020-05-12 16:56
Attempting to join either of those room IDs results in:

![image](https://user-images.githubusercontent.com/4442088/81722876-075c3780-9450-11ea-9975-17988dfce50d.png)

**Comment by anoadragon453** [comment] 2020-05-22 15:14
@dakotawhitevalley This implies that your server doesn't know which servers to join the room through. While `matrix.org` is in the room ID, room IDs are technically opaque strings and are designed not to be parsed. However, one can hint when joining a room which servers to join through.

It's not intuitive, as this is more of a developer workaround, but in Riot when attempting to join the room, you can append `?via=domain1.com&via=domain2.com...` to the URL to join via those servers.

So, a complete URL in your case may look like:

```
https://riot.im/develop/#/room/!iNmaIQExDMeqdITdHH:matrix.org?via=matrix.org
```

Checking this myself, this seems to be the old, non-upgraded Riot Web/Desktop room. Riot will hide these rooms when you join the upgraded version of the room. So, I assume you left the upgraded version of the room, but are still in the old version.

Probably something to mention to the Riot team.
