### ISSUE TITLE
If a user offline, why not tell us his "status_msg"?

### ISSUE THREAD

**Issue by calvindc** [matrix-org/synapse#5336] opened 2019-06-04 03:22 UTC
Line 733 of the file "presence.py", if the user take the initiative to offline,and but his “status_msg” is not null,others won't konw it. After careful consideration I have,you should delete the row 
"msg = status_msg if presence != PresenceState.OFFLINE else None".

**Comment by ShadowJonathan** [comment] 2020-09-18 09:39
Looks relevant to #2245, would this be a duplicate?

**Comment by clokep** [comment] 2020-09-18 11:59
Seems to be a duplicate of #2245.

**Closed by clokep** 2020-09-18 11:59 UTC
