### ISSUE TITLE
Ghost encrypted sessions, both verified and unverified

### ISSUE THREAD

**Issue by Yajo** [matrix-org/synapse#9292] opened 2021-02-02 09:02 UTC
### Description

Quoting from https://github.com/vector-im/element-web/issues/16214#issue-789179345:

> On a 1-to-1 room, the other person has 2 cross-verified sessions. This is how he sees his own profile:
> 
> ![imagen](https://user-images.githubusercontent.com/973709/105050771-090dde80-5a66-11eb-8461-4ebb944e83fd.png)
> 
> However, he appears to me like with 3 verified sessions + 1 unverified session. This is how I see him:
> 
> 
> ![imagen](https://user-images.githubusercontent.com/973709/105045204-8d109800-5a5f-11eb-88fe-7e5f55818578.png)
> 
> Of course, the unverified session and one of the desktop ones are wrong. But I see no way to remove them.

I've been told this is usually caused by a homeserver bug, so I hope I can help/be helped here 😄 

### Steps to reproduce

I have no idea on how to get to this situation. It must have been some sort of out-of-sync/network
Describe how what happens differs from what you expected.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: box.recallstack.icu

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:     1.23.1~ynh1

- **Install method**: Yunohost package
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by erikjohnston** [comment] 2021-02-04 11:55
Thanks for reporting! I think this is a duplicate of https://github.com/matrix-org/synapse/issues/8631

**Closed by erikjohnston** 2021-02-04 11:55 UTC

**Comment by Yajo** [comment] 2021-02-05 17:41
Indeed, and the workaround there worked for me. Thanks!
