### ISSUE TITLE
Synapse application logs sometimes log HTTP status codes as text.

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#7017] opened 2020-03-02 11:43 UTC
`event_creator1.log-20200228` at `2020-02-28 00:45:13,117 - synapse.access.http.8095` the HTTP status code appears as `HTTPStatus.FORBIDDEN` instead of 403.

**Comment by erikjohnston** [comment] 2020-03-02 11:46
This was a `POST /_matrix/client/r0/rooms/:room_id/leave` request

**Comment by anoadragon453** [comment] 2020-03-26 11:37
Is this perhaps due to this line:

https://github.com/matrix-org/synapse/blob/d907e8f599554a3ff1b65bf7eb22aeb1e63e5f21/synapse/api/errors.py#L241

Where it's not passing arguments to `SynapseError` correctly?

**Comment by richvdh** [comment] 2020-03-27 16:10
what do you mean? how is it not passing arguments correctly?

**Comment by anoadragon453** [comment] 2020-03-31 15:24
@richvdh Ah, I had a brain fart and forgot how `**kwargs` worked.

I've been able to reproduce this by trying to log in as a deactivated user. Log line:

```
2020-03-31 16:21:10,130 - synapse.access.http.8008 - 281 - INFO - POST-237 - 127.0.0.1 - 8008 - {None} Processed request: 0.005sec/0.000sec (0.002sec, 0.000sec) (0.001sec/0.001sec/2) 76B HTTPStatus.FORBIDDEN "POST /_matrix/client/r0/login HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" [0 dbevts]
```

Looks like it's caused by this line:

https://github.com/matrix-org/synapse/blob/e8e2ddb60ae11db488f159901d918cb159695912/synapse/api/errors.py#L190

Which hands `SynapseError` an `http_client.FORBIDDEN` instead of a simple `403`. Changing this line to use a simple `403` instead returns the same line to the client, but produces the correct log line:

```
2020-03-31 16:23:21,907 - synapse.access.http.8008 - 281 - INFO - POST-8 - 127.0.0.1 - 8008 - {None} Processed request: 0.004sec/0.000sec (0.000sec, 0.001sec) (0.001sec/0.001sec/2) 76B 403 "POST /_matrix/client/r0/login HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" [0 dbevts]
```

So a PR to find/replace all instances of `http_client.FORBIDDEN` inbound.

**Comment by anoadragon453** [comment] 2020-03-31 15:51
Actually a better solution might be to have the logger consistently print these objects, as there's lots of instances of `http_client.*` and there's not much to prevent us accidentally using these again in the future.

**Comment by anoadragon453** [comment] 2020-04-03 13:26
Fixed by https://github.com/matrix-org/synapse/pull/7188

**Closed by anoadragon453** 2020-04-03 13:26 UTC
Labels: bug, p2
