### ISSUE TITLE
Self-destruct server

### ISSUE THREAD

**Issue by Dryusdan** [matrix-org/synapse#9274] opened 2021-01-30 17:52 UTC
**Description:**

Live is live and some instance going down. A simple shutdown will generate a lot of non-transmission errors, but all messages in the rooms will be sent to a non-existent instance.
The idea is to propose an API / binary call that, like Mastodon (with the self-destruct https://docs.joinmastodon.org/admin/tootctl/#self-destruct ) will, at the very least, remove the users present in all the rooms and then unsubscribe from all the rooms to reduce the traffic to dead instances.

A question comes to my mind, if an instance dies, if someone recovers the domain and recreates an instance, is he going to recover the content of the old server via the federation or not?

**Comment by richvdh** [comment] 2021-01-30 17:58
I think this is basically a duplicate of #3765?

**Comment by Dryusdan** [comment] 2021-01-30 18:16
Yes. I don't find this issue in my search :/
So, there are no way actually to decommissionning a server ?

**Comment by clokep** [comment] 2021-02-01 14:00
>  So, there are no way actually to decommissionning a server ?

I think you want to leave all rooms that all users are in. This could probably be done by using the [admin API to deactivate a user](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#id4) for every user on the homeserver.

I'm going to close this as a dup of #3765 based on your agreement that they're the same!

**Closed by clokep** 2021-02-01 14:00 UTC
