### ISSUE TITLE
apt update/upgrade Configuration file '/etc/matrix-synapse/homeserver.yaml'  ==> Modified (by you or by a script) since installation.

### ISSUE THREAD

**Issue by xekon** [matrix-org/synapse#11238] opened 2021-11-02 23:57 UTC
**Description:**
would it be possible to support a local configuration, eg: 
homeserver.yaml.local

the values defined in .local would overwrite anything specificed in the main homeserver.yaml

This way I can leave homeserver.yaml untouched and will not be prompted what to do when updating the server.
(or if there is another way to accomplish the same result, please let me know, thank you.)

when I perform an apt update of my synapse install.
I am always prompted:

Setting up matrix-synapse-py3 (1.46.0+focal1) ...
```
Configuration file '/etc/matrix-synapse/homeserver.yaml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** homeserver.yaml (Y/I/N/O/D/Z) [default=N] ?
```

**Comment by reivilibre** [comment] 2021-11-04 10:06
There is already such a place: the whole directory `/etc/matrix-synapse/conf.d/` will have configuration files loaded.
You'll notice that, after setting up, there will already be one file in there which contains your server's name. You're free to add more files there so you can avoid changing the main configuration file.

**Comment by reivilibre** [comment] 2021-11-04 10:07
Closing because I think this answers your question, otherwise can re-open

**Closed by reivilibre** 2021-11-04 10:07 UTC

**Comment by xekon** [comment] 2021-11-08 21:44
There actually does not seem to be a way for me to re-open this, unless you meant for me to open a new issue.

**Comment by reivilibre** [comment] 2021-11-09 09:43
> LITERALLY all the guides have you editing the main homeserver.yaml file

That's a pity. In some ways, this is because the Debian/Ubuntu package is a little special in that you benefit a lot by splitting out the configuration so the original file is left untouched, but if you install any other way then you probably don't care much about that.

Thanks for writing it up! I'm sure others will find that information useful.

**Comment by richvdh** [comment] 2021-11-09 11:38
this is a duplicate of https://github.com/matrix-org/synapse/issues/8159.
