### ISSUE TITLE
Can't reject/accept invite from IRC bridge on matrix.org HS

### ISSUE THREAD

**Issue by sniffah** [matrix-org/synapse#2261] opened 2017-06-07 23:36 UTC
Hi,

I run my own HS, and have an invite stuck from the IRC freenode bridge on the matrix.org HS, when trying to reject the invite I see the following in my local logs

```
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.access.http.8008: [POST-3197] 217.15.160.254 - 8008 - Received request: POST /_matrix/client/r0/rooms/!EqDfunoadlqPmOLeyd%3Amatrix.org/leave?access_token=<redacted>
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.util.async: [POST-3197] Acquired linearizer lock 'member' for key ('!EqDfunoadlqPmOLeyd:matrix.org',)
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.util.async: [POST-3197] Acquired linearizer lock 'state_resolve_lock' for key frozenset([321892L, 227127L])
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.state: [POST-3197] Resolving state for !EqDfunoadlqPmOLeyd:matrix.org with 2 groups
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.state: [POST-3197] Resolving conflicted state for '!EqDfunoadlqPmOLeyd:matrix.org'
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.state: [POST-3197] Asking for 2 conflicted events
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.state: [POST-3197] Asking for 0 auth events
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.state: [POST-3197] Failed to resolve state
                                                     Traceback (most recent call last):
                                                       File "/usr/lib/python2.7/site-packages/synapse/state.py", line 556, in _resolve_with_state
                                                         conflicted_state, auth_events
                                                       File "/usr/lib/python2.7/site-packages/synapse/state.py", line 603, in _resolve_state_events
                                                         auth_events
                                                       File "/usr/lib/python2.7/site-packages/synapse/state.py", line 640, in _resolve_auth_events
                                                         event_auth.check(event, auth_events, do_sig_check=False, do_size_check=False)
                                                       File "/usr/lib/python2.7/site-packages/synapse/event_auth.py", line 91, in check
                                                         "Room %r does not exist" % (event.room_id,)
                                                     SynapseError: 403: Room '!EqDfunoadlqPmOLeyd:matrix.org' does not exist
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.util.async: [POST-3197] Releasing linearizer lock 'state_resolve_lock' for key frozenset([321892L, 227127L])
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.util.async: [POST-3197] Releasing linearizer lock 'member' for key ('!EqDfunoadlqPmOLeyd:matrix.org',)
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.http.server: [POST-3197] <XForwardedForRequest at 0x7f6362912fc8 method=POST uri=/_matrix/client/r0/rooms/!EqDfunoadlqPmOLeyd%3Amatrix.org/leave?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 403 - Room '!EqDfunoadlqPmOLeyd:matrix.org' does not exist
Jun 08 01:24:18 guinness.unixpimps.net synapse[649]: synapse.access.http.8008: [POST-3197] 217.15.160.254 - 8008 - {@sniffy:unixpimps.net} Processed request: 4ms (2ms, 0ms) (0ms/0) 102B 403 "POST /_matrix/client/r0/rooms/!EqDfunoadlqPmOLeyd%3Amatrix.org/leave?access_token=<redacted> HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Riot/0.10.1 Chrome/56.0.2924.87 Electron/1.6.8 Safari/537.36"
```

I've got 0.21 of synapse locally on Arch Linux, but doubt that's where the bug lies.

Apologies if this bug duplicates another one.

Br, Ian J

**Comment by richvdh** [comment] 2018-11-07 11:18
Looks like a duplicate of #3021 / #1987

**Closed by richvdh** 2018-11-07 11:18 UTC
Labels: stuck-invite
