### ISSUE TITLE
Presence status does not update correctly

### ISSUE THREAD

**Issue by erikgieseler** [matrix-org/synapse#13601] opened 2022-08-23 13:13 UTC
### Description

Hello,

Since the update to Synapse 1.64 or 1.65, we have the problem that the status of a user in Element no longer updates correctly. The users are using Element version 1.11.3. The problem cannot be reproduced correctly, for one user the status is updated correctly after approx. 1-5 minutes after logging out, but another user is still shown as online even though he has already closed Element for 30 minutes. If you delete the cache in Element, the status is displayed correctly, but not permanently. 
Has something been changed in the presence handling that could cause this behaviour?

Greetings Erik

### Steps to reproduce

- User 1 is online
- User 2 sees that User 1 is online
- User 1 closes Element
- Wait 10 minutes
- User 2 sees that User 1 is still online although User 1 has Element not opened

### Homeserver

chat.slawinski.de

### Synapse Version

1.65

### Platform

Server: Ubuntu 20.04 LTS
Client: macOS, iOS and Android

### Relevant log output

```shell
I will attach the log file.
```

**Comment by erikgieseler** [comment] 2022-08-23 13:14
[homeserver.log](https://github.com/matrix-org/synapse/files/9402800/homeserver.log)

**Comment by DMRobertson** [comment] 2022-08-23 13:39
Sanity check: when this was working, which version of Element were your users using? (I.e. could this be a client-side problem?)

**Comment by DMRobertson** [comment] 2022-08-23 13:46
If it is a server-side change, possibly https://github.com/matrix-org/synapse/pull/13313 to blame?

**Comment by erikgieseler** [comment] 2022-08-23 14:42
When the problem was first noticed, our iMacs had different versions of Element from 1.10.15 to 1.11.13 installed. After that, I installed 1.11.13 on all iMacs. Even with this, the problem persisted. I am pretty sure that the problem did not exist with Synapse 1.62. Regardless of the desktop version, the same problem also exists under Android.

**Comment by markiceman** [comment] 2022-08-25 15:13
I have the same problem after upgrade Synapse from 1.61 to 1.64. You must clean cache in Element and status is OK, but after some time it stops updating correctly again.

**Comment by erikjohnston** [comment] 2022-08-25 16:14
If this is a synapse bug then it sounds like we're not correctly proxying the presence update down the `/sync` streams. Which is logic that #13313 changed

**Comment by lsrmg** [comment] 2022-08-26 08:38
I've got the same problem after updating to synapse 1.63 or 1.64 using element 11.2 and 11.3, it takes some time to notice the wrong status so I can't tell for sure which version it was.

The problem is still present with synapse 1.65 + element 11.3

**Comment by erikgieseler** [comment] 2022-09-01 11:07
Any news on this?

**Comment by lsrmg** [comment] 2022-09-01 11:55
I can confirm, that it’s working correctly after cleaning the cache, but it stops working after a short period of time. I also noticed that some users stuck on the „yellow“ away bubble, I didn’t see this status ever before.

I tested this with multiple users on Element 1.11.3. And today on Element 1.11.4

**Comment by markiceman** [comment] 2022-09-20 13:57
Any news?

One question for all with this problem: Do you have synapse i worker mode or in moholith mode?

**Comment by lsrmg** [comment] 2022-09-20 13:58
I have 3 generic workers

**Comment by markiceman** [comment] 2022-09-20 14:05
I have 9 workers in large installation.

And I have another, very small installation in monlith mode. In this installation all looks like OK.

**Comment by erikgieseler** [comment] 2022-09-20 14:09
moholith mode here

**Comment by markiceman** [comment] 2022-09-20 22:57
> moholith mode here

How many users?

**Comment by erikgieseler** [comment] 2022-09-21 19:26
20 - 30 users

**Comment by richvdh** [comment] 2022-09-22 15:53
@MatMaul says he has reproduced this and will investigate

**Comment by erikgieseler** [comment] 2022-10-10 06:44
The problem still exists with 1.68

**Comment by markiceman** [comment] 2022-10-11 07:44
I found a lot of messages in postgresql main log:

2022-10-11 09:17:05.946 CEST [1756] synapse_user@synapse ERROR:  could not serialize access due to concurrent delete
2022-10-11 09:17:05.946 CEST [1756] synapse_user@synapse STATEMENT:  DELETE FROM presence_stream WHERE stream_id < 222660131 AND user_id = ANY(ARRAY[ .... ])

**Comment by anoadragon453** [comment] 2022-10-13 14:46
> ERROR: could not serialize access due to concurrent delete

This is fine - it just means that two writes to the database were attempted at once. Synapse will automatically retry the query that didn't make it.

**Comment by erikgieseler** [comment] 2022-10-18 06:21
The problem still exists with 1.69

**Comment by MatMaul** [comment] 2022-11-04 09:31
This should be fixed by #14243 and available in 1.71 release, closing.

**Closed by MatMaul** 2022-11-04 09:31 UTC
Labels: A-Presence, S-Major, T-Defect, X-Regression, O-Occasional

**Comment by korneyda** [comment] 2023-02-09 19:19
This problem was repeated in the version 1.76
