### ISSUE TITLE
Unable to join/leave a remote room over federation under certain condition

### ISSUE THREAD

**Issue by liyuntao** [matrix-org/synapse#3369] opened 2018-06-08 02:52 UTC
Assuming we have two servers over federation, which is local and remote.

There's a local user called A, send an invite to remote user called B. Before B accept/reject the invitation.  A kicked B out of the room. Since the kick event will not be sent to remote server, and B is not member of the room currently(after being kicked), a notification bar of invention will always appear on the B's client side (result of replay invite event?)  and cannot disappear. Whichever button you clicked would lead to an error.

**Comment by richvdh** [comment] 2018-06-08 08:13
B should be able to reject the invite, though he will then need to clear his client cache due to https://github.com/matrix-org/synapse/issues/2181.

**Comment by liyuntao** [comment] 2018-06-08 12:05
I've just tried several times in webclient under Chrome's Incognito mode. (Can Incognito mode eliminate the impact of the client-side cache?)

Currently On B's client side, calling leave API will result 200. But the invention notice cannot disappear immediately.

Finally the invention-notice disappeared several minutes, or after I restart the remote server(User B's local server), seems affected by server-side cache.

**Comment by richvdh** [comment] 2018-06-08 12:12
> I've just tried several times in webclient under Chrome's Incognito mode. (Can Incognito mode eliminate the impact of the client-side cache?)

Not entirely, no. You'd have to reject the invite and then start a new client under incognito mode.

Sounds like a duplicate of #2181

**Comment by liyuntao** [comment] 2018-06-08 12:12
### Steps to reproduce

* @user01:serverA invite @user02:serverB
* @user01:serverA kick @user02:serverB
* @user02:serverB reject the invention(calling /_matrix/client/api/v1/rooms/:roomId/leave )
* @user02:serverB refresh the page. Invention notice still there.

**Closed by richvdh** 2018-06-08 12:12 UTC

**Comment by richvdh** [comment] 2018-06-08 12:16
refreshing the page doesn't clear the cache.
