### ISSUE TITLE
Outbound connection tries to use ipv6 address on a ipv4 call

### ISSUE THREAD

**Issue by attilakinali** [matrix-org/synapse#2072] opened 2017-03-27 23:23 UTC
Hi,

I just installed matrix-synapse and tried a few things. First thing I noticed is, that it doesn't bind to IPv6 adresses (well, yes, known bug). The other is, that it actually tries to use IPv6 adresses:
2017-03-28 00:19:39,361 - synapse.http.matrixfederationclient - 183 - WARNING - POST-158- {GET-O-1} Sending request failed to matrix.org: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: InvalidAddressError - InvalidAddressError: IPv4 port write() called with IPv6 address
2017-03-28 00:19:39,361 - synapse.http.outbound - 209 - INFO - POST-158- {GET-O-1} [matrix.org] Result: InvalidAddressError - InvalidAddressError: IPv4 port write() called with IPv6 address

**Comment by ara4n** [comment] 2017-04-12 16:46
It should bind fine to ipv6 addresses if you tell it to bind to one, which will probably fix the other issue here too.

**Comment by jython234** [comment] 2017-04-18 00:21
Also try using twisted 17, this solved all my ipv6 problems with synapse.

**Comment by nasedil** [comment] 2018-03-28 12:24
After updating twisted to 17.1.0 I get that error too.

**Comment by jython234** [comment] 2018-03-28 15:10
@nasedil you're using the latest synapse right?

**Comment by nasedil** [comment] 2018-04-30 12:28
Probably not, I've installed matrix-synapse in January 2018.  I cannot figure out how to find the version of the installed synapse.

**Comment by neilisfragile** [comment] 2018-05-01 15:40
+1 to upgrade
We've landed some ipv6 fixes since Jan, be worth seeing if you reproduce on latest stable

**Comment by richvdh** [comment] 2019-07-17 15:25
I'd be surprised if this is still an issue. Please reopen if it is.

**Closed by richvdh** 2019-07-17 15:25 UTC
