### ISSUE TITLE
Unable to disable e2e encryption by default

### ISSUE THREAD

**Issue by plinss** [matrix-org/synapse#9120] opened 2021-01-14 19:42 UTC
### Description

I'm trying to disable the e2e encryption in new rooms and private chats.

Changing the configuration doesn't seem to have any effect.

### Steps to reproduce

- Add `encryption_enabled_by_default_for_room_type: off` to homeserver.yaml
- restart synapse
- invite a user to private chat
- note encryption is enabled and there is no way to create an unencrypted private chat
- alternatively, create a new room
- note that while there is UI to enable encryption, it's still selected by default

FWIW I tried both `off` and `"off"`.

Also, the phrasing in the comments of homeserver.yaml is a bit vague. Does `"off": this option will take no effect` mean encryption will be off by default or does it meant "this setting has no effect and hard-coded defaults will be used". If the latter, how does one disable encryption in private rooms?

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- Homeserver: matrix.startupstack.tech

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.25.0","python_version":"3.7.3"}

- **Install method**: apt-get via https://packages.matrix.org
<!-- examples: package manager/git clone/pip  -->



- **Platform**: Debian 10.7 amd64 VM
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2021-01-14 19:52
That setting is passed to clients as a hint, it is up to the client to decide what time of room is created. (I'm guessing that the client doesn't use it for private chats though, only for new rooms?)

I suspect this is a duplicate of #4401.

**Closed by clokep** 2021-01-14 19:52 UTC

**Comment by artenaki** [comment] 2021-07-26 21:42
You can create an unencrypted private chat in a client that doesn't support encryption (such as Quaternion). And then you can use that unencrypted room in any other client, such as Element.

I hope that support for creating unencrypted private chats will not be removed. Encryption works horribly in Matrix. At the moment, for example, in Element Android it is almost impossible to read encrypted messages from other sessions, despite verification.
