### ISSUE TITLE
Trying to upload long images causes internal server error

### ISSUE THREAD

**Issue by tulir** [matrix-org/synapse#5311] opened 2019-06-01 18:44 UTC
### Steps to reproduce
- Upload an image that is much larger horizontally than vertically (or vice versa), such as the one at https://img.mau.lu/J4Zyj.png
- Receive internal server error

![image](https://user-images.githubusercontent.com/4224639/58752330-b446da00-84b5-11e9-9448-e2f020465d8c.png)

(it also occasionally gets stuck in the uploading stage in riot, but I wasn't able to reproduce that properly)

### Version information
- **Version**: 0.99.5.2
- **Install method**: pip or docker
- **Platform**: ubuntu or docker

### Traceback
```
2019-06-01 21:36:39,064 - synapse.http.server - 112 - ERROR - POST-1362 - Failed handle request via 'UploadResource': <XForwardedForRequest at 0x7f9ad6749400 method='POST' uri='/_matrix/media/v1/upload?filename=image.png' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "synapse/git/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/git/synapse/rest/media/v1/upload_resource.py", line 95, in _async_render_POST
    content_length, requester.user
  File "synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/git/synapse/rest/media/v1/media_repository.py", line 176, in create_content
    None, media_id, media_id, media_type,
  File "synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/git/synapse/rest/media/v1/media_repository.py", line 615, in _generate_thumbnails
    t_width, t_height, t_type,
  File "synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "synapse/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "synapse/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "synapse/git/synapse/util/logcontext.py", line 636, in g
    return f(*args, **kwargs)
  File "synapse/git/synapse/rest/media/v1/thumbnailer.py", line 94, in scale
    scaled = self.image.resize((width, height), Image.ANTIALIAS)
  File "synapse/lib/python3.7/site-packages/PIL/Image.py", line 1814, in resize
    im = im.resize(size, resample, box)
  File "synapse/lib/python3.7/site-packages/PIL/Image.py", line 1819, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

**Comment by squahtx** [comment] 2021-10-11 14:35
There's a duplicate of this issue at #10721. Since that copy has more discussion, let's close this one and track the issue over there.

**Closed by squahtx** 2021-10-11 14:35 UTC
Labels: z-bug, z-p2, z-media-repository
