### ISSUE TITLE
Root causing performance issues

### ISSUE THREAD

**Issue by enckse** [matrix-org/synapse#2114] opened 2017-04-10 12:45 UTC
We're noticing some slowness on our synapse server, I'm trying to track it down but uncertain what the best place to start looking is. I'll supply the initial things that sort of "concern" me but may not matter at all.

1. Lots of timeouts/refusals/errors/etc. logged in journal (pretty often/consistently)
```
Apr 10 08:37:30 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-32} Sending request failed to matrix.matthughes.info: PUT matrix://matrix.matthughes.info/_matrix/federation/v1/send/1491827370297/: DNSLookupError - DNSLookupError: no 
Apr 10 08:37:31 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-354} Sending request failed to hira.io: PUT matrix://hira.io/_matrix/federation/v1/send/1491827370592/: ConnectionRefusedError - ConnectionRefusedError: Connection refus
Apr 10 08:37:32 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-336} Sending request failed to jersey.sandcats.io: PUT matrix://jersey.sandcats.io/_matrix/federation/v1/send/1491827370574/: TimeoutError - TimeoutError: 
Apr 10 08:37:33 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-436} Sending request failed to puiterwijk.org: PUT matrix://puiterwijk.org/_matrix/federation/v1/send/1491827370674/: ConnectionRefusedError - ConnectionRefusedError: Co
Apr 10 08:37:33 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-327} Sending request failed to matrix.sjemm.net: PUT matrix://matrix.sjemm.net/_matrix/federation/v1/send/1491827370565/: TimeoutError - TimeoutError: 
Apr 10 08:37:34 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-263} Sending request failed to krtdex.ddns.net: PUT matrix://krtdex.ddns.net/_matrix/federation/v1/send/1491827370501/: DNSLookupError - DNSLookupError: no results for h
Apr 10 08:37:34 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-403} Sending request failed to 91.216.245.111: PUT matrix://91.216.245.111/_matrix/federation/v1/send/1491827370641/: ConnectionRefusedError - ConnectionRefusedError: Co
Apr 10 08:37:36 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-404} Sending request failed to matrix.gitnote.eu: PUT matrix://matrix.gitnote.eu/_matrix/federation/v1/send/1491827370642/: DNSLookupError - DNSLookupError: no results f
Apr 10 08:37:36 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-274} Sending request failed to setkeh.com: PUT matrix://setkeh.com/_matrix/federation/v1/send/1491827370512/: TimeoutError - TimeoutError: 
Apr 10 08:37:36 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-373} Sending request failed to plebeianparty.com: PUT matrix://plebeianparty.com/_matrix/federation/v1/send/1491827370611/: TimeoutError - TimeoutError: 
Apr 10 08:37:36 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-297} Sending request failed to synapse.terraex.de: PUT matrix://synapse.terraex.de/_matrix/federation/v1/send/1491827370535/: ConnectionRefusedError - ConnectionRefusedE
Apr 10 08:37:37 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-73} Sending request failed to takios.de: PUT matrix://takios.de/_matrix/federation/v1/send/1491827370338/: ConnectionRefusedError - ConnectionRefusedError: Connection re
Apr 10 08:37:37 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-315} Sending request failed to skryking.com: PUT matrix://skryking.com/_matrix/federation/v1/send/1491827370553/: TimeoutError - TimeoutError: 
Apr 10 08:37:39 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-352} Sending request failed to matrixsoup.pw: PUT matrix://matrixsoup.pw/_matrix/federation/v1/send/1491827370590/: ConnectionRefusedError - ConnectionRefusedError: Conn
Apr 10 08:37:40 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-389} Sending request failed to home.everets.org: PUT matrix://home.everets.org/_matrix/federation/v1/send/1491827370627/: ConnectionRefusedError - ConnectionRefusedError
Apr 10 08:37:40 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-292} Sending request failed to sigwinch.uk: PUT matrix://sigwinch.uk/_matrix/federation/v1/send/1491827370530/: ConnectionRefusedError - ConnectionRefusedError: Connecti
Apr 10 08:37:41 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-349} Sending request failed to sbfl.eu: PUT matrix://sbfl.eu/_matrix/federation/v1/send/1491827370587/: ConnectionRefusedError - ConnectionRefusedError: Connection refus
Apr 10 08:37:42 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-303} Sending request failed to oddvar.org: PUT matrix://oddvar.org/_matrix/federation/v1/send/1491827370541/: ConnectionRefusedError - ConnectionRefusedError: Connection
Apr 10 08:37:42 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-258} Sending request failed to stvn.cc: PUT matrix://stvn.cc/_matrix/federation/v1/send/1491827370496/: ConnectionRefusedError - ConnectionRefusedError: Connection refus
Apr 10 08:37:43 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-105} Sending request failed to ictrek.nl: PUT matrix://ictrek.nl/_matrix/federation/v1/send/1491827370370/: ConnectError - ConnectError: No route to host
Apr 10 08:37:44 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-271} Sending request failed to kattfest.se: PUT matrix://kattfest.se/_matrix/federation/v1/send/1491827370509/: ConnectionRefusedError - ConnectionRefusedError: Connecti
Apr 10 08:37:44 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-125} Sending request failed to connectical.com: PUT matrix://connectical.com/_matrix/federation/v1/send/1491827370390/: ConnectionRefusedError - ConnectionRefusedError: 
Apr 10 08:37:45 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-402} Sending request failed to matrix.v42.dk: PUT matrix://matrix.v42.dk/_matrix/federation/v1/send/1491827370640/: DNSLookupError - DNSLookupError: no results for hostn
Apr 10 08:37:46 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-284} Sending request failed to timopheym.ddns.net: PUT matrix://timopheym.ddns.net/_matrix/federation/v1/send/1491827370522/: DNSLookupError - DNSLookupError: no results
Apr 10 08:37:47 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-264} Sending request failed to gouv2.fr: PUT matrix://gouv2.fr/_matrix/federation/v1/send/1491827370502/: ConnectionRefusedError - ConnectionRefusedError: Connection ref
Apr 10 08:37:48 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-268} Sending request failed to tesla.haapa.la: PUT matrix://tesla.haapa.la/_matrix/federation/v1/send/1491827370506/: TimeoutError - TimeoutError: 
Apr 10 08:37:49 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-376} Sending request failed to matrix.m1ndfuck.de: PUT matrix://matrix.m1ndfuck.de/_matrix/federation/v1/send/1491827370614/: DNSLookupError - DNSLookupError: no results
Apr 10 08:37:49 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-311} Sending request failed to nogaems.tk: PUT matrix://nogaems.tk/_matrix/federation/v1/send/1491827370549/: DNSLookupError - DNSLookupError: no results for hostname lo
Apr 10 08:37:50 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-326} Sending request failed to matrix.dnel.co.uk: PUT matrix://matrix.dnel.co.uk/_matrix/federation/v1/send/1491827370564/: DNSLookupError - DNSLookupError: no results f
Apr 10 08:37:50 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-259} Sending request failed to overlordalyx.com: PUT matrix://overlordalyx.com/_matrix/federation/v1/send/1491827370497/: ConnectionRefusedError - ConnectionRefusedError
Apr 10 08:37:51 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-408} Sending request failed to matrix.irreverent.space: PUT matrix://matrix.irreverent.space/_matrix/federation/v1/send/1491827370646/: ConnectionRefusedError - Connecti
Apr 10 08:37:51 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-261} Sending request failed to matrix.yrk.io: PUT matrix://matrix.yrk.io/_matrix/federation/v1/send/1491827370499/: ConnectError - ConnectError: No route to host
Apr 10 08:37:51 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-359} Sending request failed to rocket.chat: PUT matrix://rocket.chat/_matrix/federation/v1/send/1491827370597/: ConnectionRefusedError - ConnectionRefusedError: Connecti
Apr 10 08:37:52 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-272} Sending request failed to lovely.beer: PUT matrix://lovely.beer/_matrix/federation/v1/send/1491827370510/: DNSLookupError - DNSLookupError: no results for hostname 
Apr 10 08:37:54 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-286} Sending request failed to chat.salamander.tech: PUT matrix://chat.salamander.tech/_matrix/federation/v1/send/1491827370524/: DNSLookupError - DNSLookupError: no res
Apr 10 08:37:56 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-412} Sending request failed to chat.jfrost.net: PUT matrix://chat.jfrost.net/_matrix/federation/v1/send/1491827370650/: DNSLookupError - DNSLookupError: no results for h
Apr 10 08:37:56 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-119} Sending request failed to im.aurabindo.in: PUT matrix://im.aurabindo.in/_matrix/federation/v1/send/1491827370384/: TimeoutError - TimeoutError: 
Apr 10 08:37:57 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-432} Sending request failed to amagineer.com: PUT matrix://amagineer.com/_matrix/federation/v1/send/1491827370670/: ConnectionRefusedError - ConnectionRefusedError: Conn
Apr 10 08:37:57 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-282} Sending request failed to matrix.queertoo.org: PUT matrix://matrix.queertoo.org/_matrix/federation/v1/send/1491827370520/: ConnectionRefusedError - ConnectionRefuse
Apr 10 08:37:58 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-361} Sending request failed to miui-germany.de: PUT matrix://miui-germany.de/_matrix/federation/v1/send/1491827370599/: ConnectionRefusedError - ConnectionRefusedError: 
Apr 10 08:38:00 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-322} Sending request failed to matrix.atfg.org: PUT matrix://matrix.atfg.org/_matrix/federation/v1/send/1491827370560/: NoRouteError - NoRouteError: Network is unreachab
Apr 10 08:38:02 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-430} Sending request failed to synapse.agarri.ga: PUT matrix://synapse.agarri.ga/_matrix/federation/v1/send/1491827370668/: DNSLookupError - DNSLookupError: no results f
Apr 10 08:38:03 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-262} Sending request failed to timepath.xyz: PUT matrix://timepath.xyz/_matrix/federation/v1/send/1491827370500/: ConnectError - ConnectError: No route to host
```

2. I stumbled upon #1760 and ran the query to see what we had > 10 and we have like maybe 5-10 in the 10 - 100 range (mostly matrix-hq/matrix-dev/etc - not "our" local rooms). I didn't want to run deletes (as referenced in the issue) without understanding what the implications were?

Given those and the fact that there is a slowness, is there some good way for us to track this down? I would love to chat in the matrix rooms about this but the slowness is a pretty good reason for me to open this as a ticket. I know this is a pretty vague issue but I'd like to track down our performance issue(s) and maybe that would help others as well.

*When I reference slowness I mean rooms take time to load, messages sit before sending, I've stood over someone and watched them send a message and it takes several seconds (30+ in some cases) to send out. This is on the https://riot.im/app/ and riot android client

**Comment by enckse** [comment] 2017-04-10 13:03
I'm also seeing a lot of postgres errors for device uniqueness

```
Apr 10 08:49:45 synapse postgres[26]: ERROR:  duplicate key value violates unique constraint "device_uniqueness"
```

**Comment by jython234** [comment] 2017-04-10 21:31
I also notice the slowness too with my homeserver. A lot of strange stuff happens, such as messages taking way too long to send, images and other media sit for minutes without finishing sending. Sometimes my friend will send me a message (from matrix.org homeserver account) to me and I will never get it for another 30 minutes. I'm not sure what causes the problem.

**Comment by richvdh** [comment] 2017-04-11 11:01
please do run the queries mentioned at #1760. If you have busy rooms with large numbers of forward extremities, clearing them out will significantly reduce the amount of work synapse has to do for every single event received (locally or over federation) in those rooms, so that alone can make all the difference.

Please also upgrade to synapse 0.20.0 if you're on an older version: it should improve a number of things related to performance.

> Lots of timeouts/refusals/errors/etc. logged in journal (pretty often/consistently)
```
Apr 10 08:37:30 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-32} Sending request failed to matrix.matthughes.info: PUT matrix://matrix.matthughes.info/_matrix/federation/v1/send/1491827370297/: DNSLookupError - DNSLookupError: no 
Apr 10 08:37:31 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-354} Sending request failed to hira.io: PUT matrix://hira.io/_matrix/federation/v1/send/1491827370592/: ConnectionRefusedError - ConnectionRefusedError: Connection refus
Apr 10 08:37:32 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-336} Sending request failed to jersey.sandcats.io: PUT matrix://jersey.sandcats.io/_matrix/federation/v1/send/1491827370574/: TimeoutError - TimeoutError: 
```

Errors sending to offline homeservers are not a cause for concern. Synapse 0.20 should spend less time trying to contact homeservers which are known to be offline, thanks to https://github.com/matrix-org/synapse/pull/2050.

> I'm also seeing a lot of postgres errors for device uniqueness
```
Apr 10 08:49:45 synapse postgres[26]: ERROR:  duplicate key value violates unique constraint "device_uniqueness"
```

Those are also normal.

**Comment by richvdh** [comment] 2017-04-11 11:02
(If #1760 doesn't make sense, please comment there rather than forking new issues)

**Comment by enckse** [comment] 2017-04-11 11:56
Acknowledged and thank you. We will upgrade the server once the arch package is updated to v0.20.0 and I will run those queries now. I mainly was just seeing a variety of things and wasn't sure if they correlated to some issues that were closed/opened/etc.

Feel free to close this issue if you'd prefer, otherwise I can update it once we upgrade as well

**Comment by jython234** [comment] 2017-04-11 11:58
I couldn't run the queries at the time, but I did leave all the big rooms I
was in (Matrix HQ, etc) and that improved performance a ton. It's really
snappy now, so I think this is the problem. I too will run the queries and
see what happens.

**Comment by richvdh** [comment] 2017-04-11 11:58
@enckse: ok, thanks. do let us know how you get on.

**Comment by enckse** [comment] 2017-04-17 12:57
just as a follow-up, currently (after upgrading to v0.20.0) performance generally seems to have improved a lot

**Comment by ara4n** [comment] 2017-04-18 21:08
@enckse, @storrgie was just saying in #riot that the server is still struggling with lots of federation traffic timeouts in the logs.  If you can share logs with me and/or @richvdh then we can dig in further to see what it's spasming on.  Just to confirm: did you ever run the queries to clean out the extremities from #1760?  0.20 does not fix these retrospectively.

**Comment by enckse** [comment] 2017-04-19 11:34
It's unfair to say "Riot is slow due to federation timeouts" based on the cursory glance I had while doing something else the other day and not drilling down into it - it would be misleading. Next time we have performance issues I will actually take a look but switching contexts (for me) and being like "Yeah this might be slow I guess" and seeing timeouts is not a reasonable analysis

I will keep an eye on this

**Comment by enckse** [comment] 2017-04-19 11:43
I'll add that my reason for saying it would be misleading ^ is

* I ssh'd into the host and even that took some time (was something going on with our provider? I didn't check anything else nor validate this question at all)
* I only briefly looked at the journalctl outputs and saw the timeouts going on, nothing else (but I wasn't looking for anything else)
* I was not using riot at the time and the initial report was an entirely user-based issue that was not riot
* I did run the queries but it was at version < 0.20, I haven't gone back to them

So, from the project's perspective the only guidance I would ask for is should I immediately circle back around to run the queries in #1760 or, at this point, see if we run into future problems before doing something? How would you like me to proceed in providing some useful information here?

**Comment by richvdh** [comment] 2017-04-19 19:13
From my pov the best approach for getting a useful insight into whether performance issues exist, and if so what's causing them would be to get an instance of prometheus set up and collecting metrics from synapse, as per https://github.com/matrix-org/synapse/blob/master/docs/metrics-howto.rst. 

As for #1760 - it's certainly worth running the select query to see if it flags up any problems; 0.20 fixes one particular root cause of extremity proliferation, but as Matthew says, won't fix existing instances. And more may continue to accumulate until room state on your server converges with that in the rest of the federation.

**Comment by enckse** [comment] 2017-04-19 21:46
Acknowledge on metrics, may take a bit more work so we will get to it when we can. 

Re-ran select from #1760 and only had once > 10 (29 - IRC Bridge) which I cleared out. It was worse < 0.20 certainly (we had like 5-10 in the > 10 range).

**Comment by enckse** [comment] 2017-04-21 14:40
Metrics are setup, if there is something I'll want to be looking for please let me know and I can start tracking things

**Comment by enckse** [comment] 2017-04-28 18:05
Happy to open another issue if need but during federation we're also seeing these errors for some servers, if it matters and/or is unrelated and/or is another issue

```
Apr 28 11:09:00 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123191} Sending request failed to matrix.slimroms.org: PUT matrix://matrix.slimroms.org/_matrix/federation/v1/se
Apr 28 11:09:00 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123198} Sending request failed to matrix.peg.nu: PUT matrix://matrix.peg.nu/_matrix/federation/v1/send/149312893
Apr 28 11:09:03 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123183} Sending request failed to axiom.valence.blue: PUT matrix://axiom.valence.blue/_matrix/federation/v1/send
Apr 28 11:09:04 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123189} Sending request failed to xndr.de: PUT matrix://xndr.de/_matrix/federation/v1/send/1493128932089/: Conne
Apr 28 11:09:06 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123184} Sending request failed to matrix.doravel.me: PUT matrix://matrix.doravel.me/_matrix/federation/v1/send/1
Apr 28 11:09:07 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123195} Sending request failed to esko.bar: PUT matrix://esko.bar/_matrix/federation/v1/send/1493128932095/: Tim
Apr 28 11:09:07 synapse synapse[19]: synapse.http.matrixfederationclient: [] {PUT-O-123167} Sending request failed to matrix.flinkservr.de: PUT matrix://matrix.flinkservr.de/_matrix/federation/v1/
Apr 28 11:09:08 synapse synapse[19]: synapse.crypto.keyring: [PUT-3323330] Request from perlsite.co.uk: no supported signature keys
Apr 28 11:09:08 synapse synapse[19]: synapse.crypto.keyring: [] Got Exception when downloading keys for perlsite.co.uk: SynapseError 400: Not signed with a supported algorithm
                                     Traceback (most recent call last):
                                       File "/usr/lib/python2.7/site-packages/synapse/crypto/keyring.py", line 124, in handle_key_deferred
                                         _, key_id, verify_key = yield verify_request.deferred
                                     SynapseError: 400: Not signed with a supported algorithm
Apr 28 11:09:08 synapse synapse[19]: synapse.federation.federation_base: [PUT-3323330] Signature check failed for $1416420911472pnYfW:perlsite.co.uk
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [PUT-3323330] Request from localhost: no supported signature keys
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [] Got Exception when downloading keys for localhost: SynapseError 400: Not signed with a supported algorithm
                                     Traceback (most recent call last):
                                       File "/usr/lib/python2.7/site-packages/synapse/crypto/keyring.py", line 124, in handle_key_deferred
                                         _, key_id, verify_key = yield verify_request.deferred
                                     SynapseError: 400: Not signed with a supported algorithm
Apr 28 11:09:09 synapse synapse[19]: synapse.federation.federation_base: [PUT-3323330] Signature check failed for $1416420910943cDMHw:localhost
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [PUT-3323330] Request from perlsite.co.uk: no supported signature keys
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [] Got Exception when downloading keys for perlsite.co.uk: SynapseError 400: Not signed with a supported algorithm
                                     Traceback (most recent call last):
                                       File "/usr/lib/python2.7/site-packages/synapse/crypto/keyring.py", line 124, in handle_key_deferred
                                         _, key_id, verify_key = yield verify_request.deferred
                                     SynapseError: 400: Not signed with a supported algorithm
Apr 28 11:09:09 synapse synapse[19]: synapse.federation.federation_base: [PUT-3323330] Signature check failed for $1416420971894EBkmq:perlsite.co.uk
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [PUT-3323330] Request from perlsite.co.uk: no supported signature keys
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [] Got Exception when downloading keys for perlsite.co.uk: SynapseError 400: Not signed with a supported algorithm
                                     Traceback (most recent call last):
                                       File "/usr/lib/python2.7/site-packages/synapse/crypto/keyring.py", line 124, in handle_key_deferred
                                         _, key_id, verify_key = yield verify_request.deferred
                                     SynapseError: 400: Not signed with a supported algorithm
Apr 28 11:09:09 synapse synapse[19]: synapse.federation.federation_base: [PUT-3323330] Signature check failed for $1416420910579Luior:perlsite.co.uk
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [PUT-3323330] Request from 192.168.1.7: no supported signature keys
Apr 28 11:09:09 synapse synapse[19]: synapse.crypto.keyring: [] Got Exception when downloading keys for 192.168.1.7: SynapseError 400: Not signed with a supported algorithm
                                     Traceback (most recent call last):
                                       File "/usr/lib/python2.7/site-packages/synapse/crypto/keyring.py", line 124, in handle_key_deferred
                                         _, key_id, verify_key = yield verify_request.deferred
                                     SynapseError: 400: Not signed with a supported algorithm
Apr 28 11:09:09 synapse synapse[19]: synapse.federation.federation_base: [PUT-3323330] Signature check failed for $1416420911262iitPd:192.168.1.7
Apr 28 11:09:09 synapse synapse[19]: synapse.federation.federation_client: [PUT-3323330] Failed to get set(['$1416420911472pnYfW:perlsite.co.uk', '$1416420911262iitPd:192.168.1.7', '$1416420971894
```

**Comment by richvdh** [comment] 2019-12-18 15:01
it seems like a bunch of the issues raised here were fixed, and those that remain may no longer be relevant. I don't think there's much more here that is worth spending time on.

**Closed by richvdh** 2019-12-18 15:01 UTC
