### ISSUE TITLE
Element-web's change to sync based presence breaks synapse process

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#16039] opened 2023-07-31 09:13 UTC
### Description

Prior issue over at element-web which has been closed as being a synapse issue rather than element-web's: https://github.com/vector-im/element-web/issues/25874

Since element-web switched to doing presence using /sync vs using the presence API my synapse is using extremely high amounts of CPU due to presence requests happening. It also seems to kill both fed senders from the amount of work they have to do (I assume it is just the metrics endpoint timing out since kubernetes doesnt see them as broken).

![image](https://github.com/matrix-org/synapse/assets/1374914/665c8a5a-dee1-4f68-b172-f30bdb06d9eb)
![image](https://github.com/matrix-org/synapse/assets/1374914/0aa55b88-06fb-4cc7-a5f2-929b097f91d1)

The suspicion it being caused by the element-web change is because the peaks align perfectly with the time I start my element-web clients.

### Steps to reproduce

- I believe just opening develop.element.io is enough.

### Homeserver

matrix.midnightthoughts.space

### Synapse Version

{"server_version":"1.87.0","python_version":"3.11.4"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Postgresql 15 server with active + standby replication nodes

### Workers

Single process

### Platform

The server is running on a mixed arch (x86_64+arm64) kubernetes cluster.

### Configuration

The config is at https://git.nordgedanken.dev/kubernetes/gitops/src/branch/main/apps/production/synapse-midnightthoughts.yaml#L30-L41 mainly there are 4 (3 non working) appservices 

### Relevant log output

```shell
Attached as a file as the log is too long for a comment
```

### Anything else that would be useful to know?

There is an element-web rageshake available hooked to the other issue.

The pasted log is the last hour. Specifically interesting is the high amount of replication around presence_set_state.

**Comment by MTRNord** [comment] 2023-07-31 09:14
[synapse-logs-2023-07-31 11 12 12.txt](https://github.com/matrix-org/synapse/files/12213436/synapse-logs-2023-07-31.11.12.12.txt)

**Comment by realtyem** [comment] 2023-07-31 12:20
Hey there, did you happen to catch how long ago this started?

**Comment by MTRNord** [comment] 2023-07-31 12:31
It got especially bad after the 25.7.23 where it made a major overall increase:

![image](https://github.com/matrix-org/synapse/assets/1374914/bd9baccf-e6bb-4b6f-a32a-311944482755)
![image](https://github.com/matrix-org/synapse/assets/1374914/11d3125b-4840-4c56-8fc0-7fead6eee7e4)

Interesting enough the major peaks for cpu usage seem to be on the sync rather than presence. But I am not sure if thats because it includes the presence into it since it was set via sync?

![image](https://github.com/matrix-org/synapse/assets/1374914/a953bcf9-315f-47dd-8ab9-b3549b197bc4)

Because in terms of request amount the peaks are presence replication and not sync:

![image](https://github.com/matrix-org/synapse/assets/1374914/baea030e-cd53-454c-aa54-a52f95a32076)

Also worth noting is that fed sender seems to heavily be doing a single DB op now:

![image](https://github.com/matrix-org/synapse/assets/1374914/bd739e31-0b72-476a-8c28-5117871ff0cc)

Not sure if that one is related or not.

If needed I could hook up the tracing too and export a trace maybe.

**Comment by MTRNord** [comment] 2023-07-31 12:34
Also that db op seems to miss cache quite a lot:

![image](https://github.com/matrix-org/synapse/assets/1374914/c91b3578-b854-4d09-9466-c498836bbde4)

**Comment by MTRNord** [comment] 2023-07-31 12:36
And I guess part of the issue seems that the fed sender worker is not sending presence out anymore?

![image](https://github.com/matrix-org/synapse/assets/1374914/fb1ad5f9-d9ea-4701-873d-92f7b08e6c46)

**Comment by MTRNord** [comment] 2023-07-31 12:40
Since I have a sliding sync proxy too #15980 may be related too?

**Comment by HarHarLinks** [comment] 2023-07-31 15:15
this might also be not just simply be the different api used, but could be due to a conflict between different clients. i've noticed some strange behaviour with element desktop nightly idling on windows (yellow activity indicator) and then going online from schildichat android 1.6.5.sc70-test5 F-Droid which leads to the activity indicator to oscillate between yellow and green.

**Comment by cremesk** [comment] 2023-08-02 06:05
i see exactly the same problem on envs.net. that's why I temporarily disabled presence.

**Comment by davidmehren** [comment] 2023-08-02 08:09
We also noticed significantly increased CPU usage of the federation-sender and generic workers along with about 10x the database load after https://github.com/matrix-org/matrix-react-sdk/pull/11223 was merged and landed in Element-Nightly.

![image](https://github.com/matrix-org/synapse/assets/5023650/3b577d67-0de3-4a9a-8e62-c063187d97ed)

**Comment by t3chguy** [comment] 2023-08-02 08:10
Sounds like Synapse may have a special-case for no `set_presence` even though the spec says parameter omission should be same as `online`

> If this parameter is omitted then the client is automatically marked as online when it uses this API.

**Comment by t3chguy** [comment] 2023-08-02 08:11
@HarHarLinks that was also reported as https://github.com/vector-im/element-web/issues/25900

**Comment by DMRobertson** [comment] 2023-08-02 09:28
> Sounds like Synapse may have a special-case for no `set_presence` even though the spec says parameter omission should be same as `online`

This is not the case as far as I can see: https://github.com/matrix-org/synapse/blob/d0c4257f14addbf0c9072c2e34ae1c8294716ed5/synapse/rest/client/sync.py#L123-L128

**Comment by rda0** [comment] 2023-08-02 09:36
We also noticed significantly increased CPU usage of the presence and generic workers (serving `^/_matrix/client/(r0|v3)/sync$` + `(^|&)since=` and `^/_matrix/client/(api/v1|r0|v3)/events$`), increased nginx request rate and db transactions.

- Since: 01.08.23 13:20 UTC (15:20 local time)
- Synapse 1.87.0
- no sliding sync proxy

![Firefox_Screenshot_2023-08-02T09-29-34 314Z](https://github.com/matrix-org/synapse/assets/6731714/5c2d2c05-4e34-4b4a-aa54-3075f0589b29)

![Firefox_Screenshot_2023-08-02T09-29-09 041Z](https://github.com/matrix-org/synapse/assets/6731714/3096e7c6-4510-464b-bdf6-a05954dd8221)

![Firefox_Screenshot_2023-08-02T09-29-04 714Z](https://github.com/matrix-org/synapse/assets/6731714/17672e3c-aaf5-4516-94bc-dccf6ebe53e2)

**Comment by actx-1** [comment] 2023-08-03 23:53
> this might also be not just simply be the different api used, but could be due to a conflict between different clients. i've noticed some strange behaviour with element desktop nightly idling on windows (yellow activity indicator) and then going online from schildichat android 1.6.5.sc70-test5 F-Droid which leads to the activity indicator to oscillate between yellow and green.

I've noticed the same thing here. Specifically, when I have one instance of Element idle while I'm using another one, they seem to argue about whether I'm online or away, and get constant sync requests returned only containing presence updated by the other instance. Closing the idle instance stopped the activity indicator flickering.

**Comment by t3chguy** [comment] 2023-08-04 07:39
This isn't an issue with Element Web. Any client sending `set_presence=unavailable` running at the same time as one not setting `set_presence` or sending `set_presence=online` will flip-flop like this as Synapse will keep toggling the user's presence at each alternating `/sync` call - this is a bug and not conforming to the spec. See https://github.com/matrix-org/synapse/issues/16057

**Comment by seal61** [comment] 2023-08-04 11:04
Even after I updated element to 1.11.38 where this issue should be fixed I still see a lot of those errors in the synapse log, that could be related to presence:

`
tail /var/log/synapse/homeserver.log
2023-08-04 12:51:21,199 - synapse.storage.txn - 722 - WARNING - GET-41319781 - [TXN OPERROR] {update_presence-680f10} could not serialize access due to concurrent update
 0/5
`

Any ideas how to solve this without disabling presence at all?

**Comment by MTRNord** [comment] 2023-08-04 14:50
One observation I made since ele-web reverted the change on their side is that synapse seems to not free the resources fully up until you restart it. Both memory stayed high and cpu only partially dropped. The federation-sender workers only recovered after a restart (I assume that cleared the pending queue for replication)

**Comment by clokep** [comment] 2023-08-09 11:23
I believe this is a duplicate of #16057.

**Closed by clokep** 2023-08-09 11:23 UTC
Labels: S-Minor, T-Defect, O-Frequent
