### ISSUE TITLE
Member of room can't send messages

### ISSUE THREAD

**Issue by Erko21** [matrix-org/synapse#13414] opened 2022-07-28 14:56 UTC
### Description

Member of room can't send messages
Other members don't see him as a member

### Steps to reproduce

I have created a room with two members(m1, m2) + me.
m1 received two invites(accepted both of them). One of room was without members - m1 left it
m1 can't write messages he receives errors.
m2 and me can't see him in the room

### Homeserver

private server from synapse container

### Synapse Version

1.63.1

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

-hardware
-vm

### Relevant log output

```shell
matrix-synapse-1  | 2022-07-28 14:29:11,730 - synapse.handlers.message - 1294 - WARNING - PUT-62784 - Denying new event <FrozenEventV3 event_id=$RLsZFZwZw78wwffDkNzT_9RnOfo7a1Xm_IK2Obhix2Y, type=m.room.encrypted, state_key=None, outlier=False> because 403: User @7mp4km4:matrix.kryptr.li not in room !PvoFWesunwIyODNJsk:matrix.kryptr.li (<FrozenEventV3 event_id=$5FXE9pd0whNuHjRT4_cbfUSSC0HpkqNES3kg-Dw2enk, type=m.room.member, state_key=@7mp4km4:matrix.kryptr.li, outlier=False>)
matrix-synapse-1  | 2022-07-28 14:29:11,732 - synapse.http.server - 167 - INFO - PUT-62784 - <XForwardedForRequest at 0x7f0cd65b2cd0 method='PUT' uri='/_matrix/client/r0/rooms/!PvoFWesunwIyODNJsk:matrix.kryptr.li/send/m.room.encrypted/5e195ed3-f961-43d5-a224-9bea3ccedd4c' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - User @7mp4km4:matrix.kryptr.li not in room !PvoFWesunwIyODNJsk:matrix.kryptr.li (<FrozenEventV3 event_id=$5FXE9pd0whNuHjRT4_cbfUSSC0HpkqNES3kg-Dw2enk, type=m.room.member, state_key=@7mp4km4:matrix.kryptr.li, outlier=False>)
```

**Comment by erikjohnston** [comment] 2022-07-29 10:22
Can we get more logs, including the join request from `m1` please? It looks like he failed to join the room entirely.

**Comment by Erko21** [comment] 2022-08-01 11:59
Logs are not available now(
But he receive two invites.
Accepted both of them and one of the room was empty(so he left it), but he can't write in it

**Comment by reivilibre** [comment] 2022-08-03 10:11
I don't think this is possible to diagnose without logs showing everything that happened at the time (not just 2 lines about the failed join), sorry.

Are you able to reproduce it again and obtain some logs when doing so?

**Comment by H-Shay** [comment] 2022-09-20 21:07
I am closing this issue as we are unable to investigate this issue due to lack of information. If more information becomes available we can reopen.

**Closed by H-Shay** 2022-09-20 21:07 UTC
Labels: X-Needs-Info
