### ISSUE TITLE
synapse allows you to omit the `from` param to /messages, which is non-spec-compliant

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5538] opened 2019-06-24 13:41 UTC
Per https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-rooms-roomid-messages, `from` is mandatory, but apparently riot-android does not (always?) set it.

**Comment by ShadowJonathan** [comment] 2021-02-24 16:09
(Updated spec link, for reference: https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-rooms-roomid-messages)

**Comment by deepbluev7** [comment] 2021-07-16 10:48
Duplicate of #1445, I'd say.

**Comment by clokep** [comment] 2021-12-14 17:24
See also [MSC3567](https://github.com/matrix-org/matrix-doc/pull/3567) which looks to standardize the behavior in Synapse.

**Comment by clokep** [comment] 2022-01-18 13:06
This is now spec compliant.

**Closed by clokep** 2022-01-18 13:06 UTC
Labels: A-Spec-Compliance, S-Tolerable, T-Defect
