### ISSUE TITLE
room destruction

### ISSUE THREAD

**Issue by webmind** [matrix-org/synapse#5189] opened 2019-05-14 19:17 UTC
Ability to destroy rooms, especially private one to one chats.

I would be nice to have the ability for room admins to destroy the rooms in a way that all the information is destroyed. The messages and the meta data (when messages are sent for instance).

**Comment by Half-Shot** [comment] 2019-05-14 19:23
@webmind When everyone leaves a room, the room cannot be rejoined. To do what you want, the best way is to redact all the messages (using a bulk redact script/bot) and kick everyone from the room and then leave it.

By design Matrix rooms cannot be destroyed, and (of course) there is no way to force deleting across all participating servers though you can do a redaction.

**Comment by aaronraimist** [comment] 2019-05-16 16:53
https://github.com/matrix-org/matrix-doc/issues/1882 is the issue tracking this

See also https://github.com/matrix-org/matrix-doc/issues/447 and https://github.com/matrix-org/matrix-doc/pull/1763 is somewhat related

**Comment by richvdh** [comment] 2019-05-16 18:18
closing as a dup of existing issues

**Closed by richvdh** 2019-05-16 18:18 UTC
