### ISSUE TITLE
email pushers should not be associated with devices

### ISSUE THREAD

**Issue by c-cal** [matrix-org/synapse#15890] opened 2023-07-07 14:59 UTC
### Description

According to https://github.com/matrix-org/synapse/blob/release-v1.87/synapse/handlers/deactivate_account.py#L134-L137 email pushers should not be associated with devices.

Rational : mail notifications should continue to be sent even after the device that set up the pusher has been deleted (ie: after a logout, for example).

But https://github.com/matrix-org/synapse/blob/release-v1.87/synapse/handlers/register.py#L1010-L1017 track device id at user registration,

and https://github.com/matrix-org/synapse/blob/release-v1.87/synapse/push/pusherpool.py#L97-L190 do not filter pusher kind (ie: "email") to decide whether or not to tracks device id.

### Steps to reproduce

- add an email address
- setup email notif
- logout
- login
- => email notif are disable

### Homeserver

matrix.org

### Synapse Version

1.87

### Installation Method

Docker (matrixdotorg/synapse)

### Database

-

### Workers

Single process

### Platform

-

### Relevant log output

```shell
-
```

**Comment by reivilibre** [comment] 2023-07-18 14:32
Thanks for your report and sorry for the problem, but this is a duplicate of #3696 so I will close in favour of that one.

**Closed by reivilibre** 2023-07-18 14:32 UTC
