### ISSUE TITLE
Federated /publicRooms shows me the old and new "Synapse Admins" room

### ISSUE THREAD

**Issue by jaller94** [matrix-org/synapse#11557] opened 2021-12-10 12:26 UTC
### Description

When searching for "Synapse" in the federated "Explore rooms" list of matrix.org, I see "Synapse Admins" twice.

### Steps to reproduce

- Be on vector.modular.im (seems to be fine on matrix.org)
- (maybe not needed: Be a member in both the old and new room)
- Click on "Explore rooms" in Element
- Search for "Synapse" on the matrix.org room list

![Screenshot](https://user-images.githubusercontent.com/10872136/145572902-d25c0daa-910f-454d-bfdf-8ed498f9ed8e.png)

On my Matrix.org account I don't see the old "Synapse Admins" room. But on that account I'm also not in either of the rooms.

### Version information

- **Homeserver**: vector.modular.im

If not matrix.org:

- **Version**: "1.47.1"

- **Install method**: EMS

- **Platform**: EMS

**Comment by aaronraimist** [comment] 2021-12-13 18:45
Duplicate of https://github.com/matrix-org/synapse/issues/10075

**Closed** 2021-12-13 18:59 UTC
