### ISSUE TITLE
Delete file attachments if message is removed.

### ISSUE THREAD

**Issue by ufgkirk** [matrix-org/synapse#8638] opened 2020-10-23 09:08 UTC
**Delete file attachments if message is removed.:**
In some cases, such as direct messages, a user may want to send an image file or other attachment privately.

After deleting the message in Matrix, the client no longer shows the image/file and says "Message deleted", however the image server link (/_matrix/media/v1/download/....) remains available.

This becomes very obvious in a situation such as when I send a message to a bridge, and the whole media server link is readily available.  Removing this file once posted seems impossible in the current implementation.

It would both save server disk space, and enable better privacy, if the file could be deleted when the message is removed.  At the very least, removing access through the API makes sense, especially in case the user dragged a sensitive file into their client by accident.

**Comment by ufgkirk** [comment] 2020-10-23 09:09
Possibly related to: #890, #8519, #3479.

**Comment by clokep** [comment] 2020-10-23 11:14
I *think* this is a duplicate of #1263, but I'm not 100% sure what you mean by "if a message is removed". I think you mean redacted though.

**Comment by ufgkirk** [comment] 2020-10-24 02:37
When I say "message is removed" I mean I click the "..." menu in Element and I click "Remove".  Then the message says "Message Removed".  If the technical term in the protocol for this is "redacting" the message, then yes that is what I mean, you may be correct this is a duplicate of #1263.

**Comment by clokep** [comment] 2020-10-26 11:28
👍  Yeah this is described as "redacted" in the protocol. I'll close this in favor of #1263.

**Closed by clokep** 2020-10-26 11:28 UTC
Labels: info-needed
