### ISSUE TITLE
Room properties disappearing

### ISSUE THREAD

**Issue by waclaw66** [matrix-org/synapse#9808] opened 2021-04-14 09:10 UTC
### Description

There are disappering room properties like name, alias, avatar or topic. It happened last time to me on my own homeserver on room Element Android. Other users reported it too.

![obrazek](https://user-images.githubusercontent.com/15554561/114685120-df392080-9d11-11eb-9a50-dfe7be1ad56c.png)

### Steps to reproduce

- unknown

### Version information

- **Homeserver**: own homeserver

- **Version**: Synapse 1.31.0

- **Install method**: pip

- **Platform**: Fedora 33

**Comment by waclaw66** [comment] 2021-04-15 15:04
Element Android room properties have been restored after room update due to a new version

![obrazek](https://user-images.githubusercontent.com/15554561/114891743-6ec2fa00-9e0c-11eb-8777-a81b348239fa.png)

Nevertheless Element Web caches those old empty values, cache clear helped afterwards.

**Comment by babolivier** [comment] 2021-04-28 10:13
Hi, and sorry for the delay in responding to this issue. Could you please tell me where your screenshots come from? Is it the response to an HTTP request (e.g. `/publicRooms`), the result of a database query (if so, on which table), etc?

**Comment by waclaw66** [comment] 2021-04-28 13:32
Hi, it's database query from `room_stats_state` table. First picture shows when room has been corrupted and second when room has been updated due to a new Element Android release.
Seems there's some event in federation which corrupts rooms properties.

> 
> 
> Hi, and sorry for the delay in responding to this issue. Could you please tell me where your screenshots come from? Is it the response to an HTTP request (e.g. `/publicRooms`), the result of a database query (if so, on which table), etc?

**Comment by richvdh** [comment] 2021-05-06 09:51
this sounds like a "state reset", making this a duplicate of #8629.

**Closed by richvdh** 2021-05-06 09:51 UTC
Labels: P3, S-Minor, T-Defect
