### ISSUE TITLE
Can not log in with a specific account

### ISSUE THREAD

**Issue by chagai95** [matrix-org/synapse#12429] opened 2022-04-10 11:03 UTC
### Description
I am trying to log in to my account and I can not do this from any client anymore (Android/web or desktop), I think the reason is I'm getting 504s because I have too many rooms?

### Steps to reproduce

Just logging in to my account

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 

If not matrix.org:
mx.chagai.website
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
1.56.0
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
docker via Ansible playbook
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
CentOS 8 GB RAM, old hardware.


Some logs:
Synapse logs:
```
-- Logs begin at Sun 2022-04-10 09:12:05 CEST. --
Apr 10 12:31:02 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:02,258 - synapse.api.auth - 485 - WARNING - GET-61726 - Invalid macaroon in auth: <class 'synapse.api.auth._InvalidMacaroonException'>
Apr 10 12:31:02 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:02,268 - synapse.api.auth - 485 - WARNING - GET-61727 - Invalid macaroon in auth: <class 'synapse.api.auth._InvalidMacaroonException'>
Apr 10 12:31:02 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:02,271 - synapse.api.auth - 485 - WARNING - POST-61729 - Invalid macaroon in auth: <class 'synapse.api.auth._InvalidMacaroonException'>
Apr 10 12:31:02 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:02,281 - synapse.api.auth - 485 - WARNING - GET-61730 - Invalid macaroon in auth: <class 'synapse.api.auth._InvalidMacaroonException'>
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:08,931 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5630 - [TXN OPERROR] {set_appservice_stream_type_pos-89ce8} could not serialize access due to concurrent update
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:08,952 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5630 - [TXN OPERROR] {set_appservice_stream_type_pos-89cee} could not serialize access due to concurrent update
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:31:08,964 - synapse.storage.txn - 623 - WARNING - as-sender-whatsapp-2006 - [TXN OPERROR] {complete_appservice_txn-89cf0} could not serialize access due to concurrent update
Apr 10 12:31:08 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:33:53 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:33:53,362 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9119 - {PUT-O-50246} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547792855: HttpResponseException('403: Forbidden')
Apr 10 12:33:53 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:33:53,362 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9119 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:35:17 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:35:17,664 - synapse.storage.txn - 623 - WARNING - as-sender-signal-1125 - [TXN OPERROR] {complete_appservice_txn-8a6aa} could not serialize access due to concurrent update
Apr 10 12:35:17 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:35:17 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:35:17,890 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5682 - [TXN OPERROR] {set_appservice_stream_type_pos-8a6b8} could not serialize access due to concurrent update
Apr 10 12:35:17 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:35:32 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:35:32,870 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5688 - [TXN OPERROR] {set_appservice_stream_type_pos-8a833} could not serialize access due to concurrent update
Apr 10 12:35:32 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:35:54 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:35:54,883 - synapse.logging.context - 81 - WARNING - PUT-62280 - Re-starting finished log context PUT-62280
Apr 10 12:36:27 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:36:27,672 - synapse.storage.txn - 623 - WARNING - as-sender-telegram-1540 - [TXN OPERROR] {complete_appservice_txn-8ac8e} could not serialize access due to concurrent update
Apr 10 12:36:27 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:36:37 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:36:37,503 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9245 - {PUT-O-50556} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547792969: HttpResponseException('403: Forbidden')
Apr 10 12:36:37 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:36:37,581 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9245 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:37:43 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:37:43,405 - synapse.storage.txn - 623 - WARNING - as-sender-signal-1129 - [TXN OPERROR] {complete_appservice_txn-8b356} could not serialize access due to concurrent update
Apr 10 12:37:43 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:37:44 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:37:44,642 - synapse.storage.txn - 623 - WARNING - as-sender-telegram-1541 - [TXN OPERROR] {complete_appservice_txn-8b380} could not serialize access due to concurrent update
Apr 10 12:37:44 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:37:45 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:37:45,201 - synapse.storage.txn - 623 - WARNING - as-sender-whatsapp-2040 - [TXN OPERROR] {complete_appservice_txn-8b391} could not serialize access due to concurrent update
Apr 10 12:37:45 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:37:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:37:52,225 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9329 - {PUT-O-50692} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547793041: HttpResponseException('403: Forbidden')
Apr 10 12:37:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:37:52,225 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9329 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:40:14 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:14,813 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5741 - [TXN OPERROR] {set_appservice_stream_type_pos-8c03b} could not serialize access due to concurrent update
Apr 10 12:40:14 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:40:15 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:15,569 - synapse.storage.txn - 623 - WARNING - as-sender-whatsapp-2049 - [TXN OPERROR] {complete_appservice_txn-8c056} could not serialize access due to concurrent update
Apr 10 12:40:15 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:40:36 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:36,826 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5744 - [TXN OPERROR] {set_appservice_stream_type_pos-8c204} could not serialize access due to concurrent update
Apr 10 12:40:36 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:40:43 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:43,550 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5749 - [TXN OPERROR] {set_appservice_stream_type_pos-8c32f} could not serialize access due to concurrent update
Apr 10 12:40:43 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:40:55 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:55,761 - synapse.storage.txn - 623 - WARNING - as-sender-signal-1131 - [TXN OPERROR] {complete_appservice_txn-8c3f3} could not serialize access due to concurrent update
Apr 10 12:40:55 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:40:57 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:40:57,173 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5756 - [TXN OPERROR] {set_appservice_stream_type_pos-8c41a} could not serialize access due to concurrent update
Apr 10 12:40:57 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:43:19 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:43:19,362 - synapse.storage.txn - 623 - WARNING - PUT-62812 - [TXN OPERROR] {update_presence-8caf8} could not serialize access due to concurrent delete
Apr 10 12:43:19 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:43:22 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:43:21,843 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5782 - [TXN OPERROR] {set_appservice_stream_type_pos-8cb46} could not serialize access due to concurrent update
Apr 10 12:43:22 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:45:13 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:12,646 - synapse.http.server - 690 - WARNING - GET-62855 - Not sending response to request <XForwardedForRequest at 0x7f95c0940100 method='GET' uri='/_matrix/client/r0/sync?filter=1&set_presence=offline&since=s1841893_16086075_999_1044483_174935_883_40141_1550655_1&timeout=30000' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:13 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,785 - synapse.http.server - 690 - WARNING - GET-62864 - Not sending response to request <XForwardedForRequest at 0x7f95cf899520 method='GET' uri='/_matrix/client/r0/sync?timeout=30000&since=s1841893_16086086_999_1044483_174935_883_40141_1550655_1&filter=2&set_presence=offline' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:13 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,921 - synapse.http.server - 690 - WARNING - GET-62870 - Not sending response to request <XForwardedForRequest at 0x7f95a5373af0 method='GET' uri='/_matrix/client/v3/sync?timeout=30000&since=s1841894_16086086_999_1044483_174935_883_40141_1550655_1&filter=2&set_presence=offline' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:14 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,923 - synapse.http.server - 690 - WARNING - GET-62863 - Not sending response to request <XForwardedForRequest at 0x7f95aaa51490 method='GET' uri='/_matrix/client/r0/sync?timeout=30000&since=s1841893_16086086_999_1044483_174935_883_40141_1550655_1&filter=2&set_presence=offline' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:14 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,973 - synapse.http.server - 690 - WARNING - GET-62844 - Not sending response to request <XForwardedForRequest at 0x7f95bba2c790 method='GET' uri='/_matrix/client/r0/sync?timeout=30000&since=s1841894_16086086_999_1044484_174935_883_40141_1550655_1&filter=2&set_presence=offline' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:14 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,975 - synapse.http.server - 690 - WARNING - GET-62847 - Not sending response to request <XForwardedForRequest at 0x7f95c1b250a0 method='GET' uri='/_matrix/client/r0/sync?filter=1&set_presence=offline&since=s1841894_16086086_999_1044484_174935_883_40141_1550655_1&timeout=30000' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:14 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:13,977 - synapse.http.server - 690 - WARNING - GET-62846 - Not sending response to request <XForwardedForRequest at 0x7f95b1bdaa90 method='GET' uri='/_matrix/client/r0/sync?timeout=30000&since=s1841894_16086086_999_1044484_174935_883_40141_1550655_1&filter=2&set_presence=offline' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:15 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:15,043 - synapse.http.server - 690 - WARNING - GET-62869 - Not sending response to request <XForwardedForRequest at 0x7f95aed1db80 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&since=s1841894_16086086_999_1044483_174935_883_40141_1550655_1&timeout=30000' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:15 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:15,080 - synapse.http.server - 690 - WARNING - GET-62860 - Not sending response to request <XForwardedForRequest at 0x7f95a9268760 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=30000&since=s1841894_16086089_999_1044484_174936_883_40141_1550655_1' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:45:25 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:25,040 - synapse.storage.txn - 623 - WARNING - as-sender-telegram-1553 - [TXN OPERROR] {complete_appservice_txn-8d08f} could not serialize access due to concurrent update
Apr 10 12:45:25 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:45:26 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:25,757 - synapse.storage.txn - 623 - WARNING - as-sender-whatsapp-2069 - [TXN OPERROR] {complete_appservice_txn-8d0a6} could not serialize access due to concurrent update
Apr 10 12:45:26 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:45:26 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:26,046 - synapse.storage.txn - 623 - WARNING - as-sender-whatsapp-2069 - [TXN OPERROR] {complete_appservice_txn-8d0a6} could not serialize access due to concurrent update
Apr 10 12:45:26 localhost.localdomain matrix-synapse[25257]: 1/5
Apr 10 12:45:30 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:30,435 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9396 - {PUT-O-51235} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547793101: HttpResponseException('403: Forbidden')
Apr 10 12:45:30 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:30,435 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9396 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:45:51 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:50,892 - synapse.storage.txn - 623 - WARNING - as-sender-signal-1137 - [TXN OPERROR] {complete_appservice_txn-8d1c8} could not serialize access due to concurrent update
Apr 10 12:45:51 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:45:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:51,548 - synapse.storage.txn - 623 - WARNING - as-sender-telegram-1554 - [TXN OPERROR] {complete_appservice_txn-8d1ce} could not serialize access due to concurrent update
Apr 10 12:45:52 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:45:56 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:56,893 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9450 - {PUT-O-51315} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547793149: HttpResponseException('403: Forbidden')
Apr 10 12:45:56 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:45:56,894 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9450 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:46:44 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:46:44,761 - synapse.http.server - 690 - WARNING - POST-62928 - Not sending response to request <XForwardedForRequest at 0x7f95d5af3fa0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site='8008'>, already disconnected.
Apr 10 12:47:05 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:05,429 - synapse.http.matrixfederationclient - 682 - WARNING - federation_transaction_transmission_loop-9504 - {PUT-O-51459} [public.cat] Request failed: PUT matrix://public.cat/_matrix/federation/v1/send/1649547793197: HttpResponseException('403: Forbidden')
Apr 10 12:47:05 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:05,430 - synapse.federation.sender.per_destination_queue - 357 - WARNING - federation_transaction_transmission_loop-9504 - TX [public.cat] Received 403 response to transaction: 403: Forbidden
Apr 10 12:47:45 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:45,128 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:45 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:45,132 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:45 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:45,134 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:45 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:45,134 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:47 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:47,560 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:47 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:47,561 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:47 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:47,562 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:52,271 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:52,273 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:52,275 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:52,275 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:47:52 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:47:52,276 - synapse.logging.context - 81 - WARNING - PUT-63016 - Re-starting finished log context PUT-63016
Apr 10 12:48:49 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:48:49,579 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5833 - [TXN OPERROR] {set_appservice_stream_type_pos-8d8f0} could not serialize access due to concurrent update
Apr 10 12:48:49 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:52:10 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:52:09,573 - synapse.logging.context - 81 - WARNING - PUT-63421 - Re-starting finished log context PUT-63421
Apr 10 12:52:10 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:52:10,973 - synapse.logging.context - 81 - WARNING - PUT-63421 - Re-starting finished log context PUT-63421
Apr 10 12:52:25 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:52:25,270 - synapse.storage.txn - 623 - WARNING - notify_interested_services_ephemeral-5875 - [TXN OPERROR] {set_appservice_stream_type_pos-8dfd3} could not serialize access due to concurrent update
Apr 10 12:52:25 localhost.localdomain matrix-synapse[25257]: 0/5
Apr 10 12:53:49 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:53:48,890 - synapse.rest.media.v1._base - 276 - WARNING - GET-63555 - Failed to write to consumer: <class 'Exception'> Consumer asked us to stop producing
Apr 10 12:53:53 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:53:53,279 - synapse.rest.media.v1._base - 276 - WARNING - GET-63557 - Failed to write to consumer: <class 'Exception'> Consumer asked us to stop producing

```

Element web logs:
[Untitled-2.log](https://github.com/matrix-org/synapse/files/8458795/Untitled-2.log)

**Comment by squahtx** [comment] 2022-04-11 10:53
The only relevant line in the logs above is
```
Apr 10 12:46:44 localhost.localdomain matrix-synapse[25257]: 2022-04-10 10:46:44,761 - synapse.http.server - 690 - WARNING - POST-62928 - Not sending response to request <XForwardedForRequest at 0x7f95d5af3fa0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site='8008'>, already disconnected.
```

Looks like a duplicate of https://github.com/matrix-org/synapse/issues/7721, which should be better in the next Synapse release or the one after.

Retrying should allow you to log in, as long as the `get_users_who_share_room_with_user` and `get_users_in_room` caches are big enough.

**Comment by squahtx** [comment] 2022-04-11 10:54
Do you happen to know how many rooms that account is in?

**Closed by squahtx** 2022-04-11 10:53 UTC

**Comment by chagai95** [comment] 2022-04-12 07:34
Thx for clarifying, a bit less than 1500. @squahtx

**Comment by chagai95** [comment] 2022-06-14 11:06
This might have been this:
https://github.com/matrix-org/synapse/issues/12971#issuecomment-1154980831
