### ISSUE TITLE
M_UNKNOWN error in client when using LDAP auth

### ISSUE THREAD

**Issue by bennabiy** [matrix-org/synapse#2685] opened 2017-11-16 16:34 UTC
### Description

from Synapse Support  Channel:
FedoraUser
hi friends
we are encountering strange issue
and we've found workaround which we don't understand
we're using LDAP auth which fails due to python error 'ValueError: too many values to unpack'
this is due to function auth_handler.validate_login is expected to provide two values, but it provides one
values are canonical_user_id and callback, but we only receive canonical_user_id
so, if we change code not to expect two, and later hard code callback to None auth works
now, we have no idea what would be the consequence of hard-coding callback... it's probably used somewhere :)

### Steps to reproduce

- enable auth provider against LDAP (mxisd, ldap3-auth etc)
- try to log in
- M_UNKNOWN error in client, even though logs show auth successful.

Describe how what happens differs from what you expected.

2017-11-16 10:52:48,422 - synapse.http.server - 139 - ERROR - POST-355- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fffe8356ed0>: <SynapseRequest at 0x7fffe7e77098 method=POST uri=/_matrix/client/r0/login? clientproto=HTTP/1.0 site=8008>
Traceback (most recent call last):
  File "/mtx/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 257, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/login.py", line 154, in on_POST
    result = yield self._do_other_login(login_submission)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/mtx/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/login.py", line 224, in _do_other_login
    login_submission,
ValueError: too many values to unpack

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?
another homeserver (local)
If not matrix.org:
- **Synapse/0.25.0**:        What version of Synapse is running? 
- **pip**: package manager/git clone/pip      
- **LX zone on smartos - debian 8**:       Tell us about the environment in which your homeserver is operating
                      - distro, hardware, if it's running in a vm/container, etc.

**Comment by bennabiy** [comment] 2017-11-16 16:39
As a patch submitted, (granted FedoraUser is using repo packaging, and I am using PIP, so file location is different, but...)
`-packages/synapse/rest/client/v1/login.py	2017-11-16 11:14:13.608068638 +0100
+++ login.py	2017-11-16 11:14:00.915911999 +0100
@@ -220,11 +220,13 @@
 
         auth_handler = self.auth_handler
 
-        canonical_user_id, callback = yield auth_handler.validate_login(
+        canonical_user_id = yield auth_handler.validate_login(
             identifier["user"],
             login_submission,
         )
 
+        callback = None
+
         device_id = yield self._register_device(
             canonical_user_id, login_submission,
         )`

**Comment by bennabiy** [comment] 2017-11-16 16:40
bah, I do not know how to strip it of formatting

**Comment by turt2live** [comment] 2017-11-16 16:55
This looks like a duplicate of https://github.com/matrix-org/synapse/issues/2678

**Comment by richvdh** [comment] 2017-11-16 17:04
yes dup #2678 thanks

**Closed by richvdh** 2017-11-16 17:04 UTC
