### ISSUE TITLE
Errors after migrating from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by jakemoroni** [matrix-org/synapse#6588] opened 2019-12-22 04:38 UTC
Hello,

After following the procedure in the documentation to migrate from SQLite to PostgreSQL, I'm getting the following errors once the server is started (with some numbers redacted/edited because I'm not sure if they're sensitive):

`synapse.push.pusherpool - 261 - WARNING - start_pushers-0- Pusher incorrectly configured user=@xxxxxxxxx:jakemoroni.com, appid=im.vector.app.ios.voip.prod, pushkey=abunchoflettersandnumbers=: data can not be null for HTTP pusher`

`synapse.storage.data_stores.main.pusher - 51 - WARNING - start_pushers-0- Invalid JSON in data for pusher 61555: \asldkfjnasdflkjansfdlakjsdfnalsdkjfn, Expecting value: line 1 column 1 (char 0)`

I get these errors for basically every user on my server.

I'm not sure if this will cause issues, so I've reverted back to SQLite for now.

Running Synapse 1.7.2 on Ubuntu 16.04, with PostgreSQL 9.5.

**Comment by richvdh** [comment] 2019-12-22 22:03
I think this is a duplicate of #5312

**Closed by richvdh** 2019-12-22 22:03 UTC
