### ISSUE TITLE
Postgres logs fill up with 'duplicate key value violates' ERRORS

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1842] opened 2017-01-20 19:43 UTC
So far today 250K `duplicate key value violates unique constraint device_uniqueness` on matrix.org. surely this isn't as intended?

**Comment by hiberno** [comment] 2017-01-25 12:04
I can confirm this issue on my homeserver setup.

**Comment by thallian** [comment] 2017-03-03 15:34
Same here. It seems like this also makes the memory usage of my postgre instance grow to 1.5 GB (from ~400 MB) but I have to take a closer look.

**Comment by kroeckx** [comment] 2017-04-16 21:43
I'm still seeing this with 0.20.0. It seems to be related to a `/_matrix/client/unstable/keys/upload/` call.

**Comment by ara4n** [comment] 2017-08-18 12:24
https://github.com/epiphyte/synapse-tools/tree/master/sane has a workaround for this:

```
CREATE RULE device_unique_rule AS ON
    INSERT TO devices WHERE (
        EXISTS (
            SELECT 1
            FROM devices                                                     
            WHERE ((devices.user_id = new.user_id) AND (devices.device_id = new.device_id))))
    DO INSTEAD NOTHING;
```

although it looks like we should be fixing the schema properly rather than patching it.

**Comment by enckse** [comment] 2017-08-18 19:57
Author of "patch" here - I don't disagree that this is a workaround and maybe some other means is necessary and/or preferred but letting postgres spit out errors to the journal log was less ideal (hence comments/concerns I raised in #2114)

**Comment by f0x52** [comment] 2019-01-23 23:55
Still occurs with latest synapse, and in other user_directory related tables with the same user.

```python
Jan 23 19:14:45 leviathan python[26292]: 2019-01-23 19:14:45,927 - synapse.metrics.background_process_metrics - 203 - ERROR - user_directory.notify_new_event-74 - Background process 'user_directory.notify_new_event' threw an exception
Jan 23 19:14:45 leviathan python[26292]: Traceback (most recent call last):
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 201, in run
Jan 23 19:14:45 leviathan python[26292]:     yield func(*args, **kwargs)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 114, in process
Jan 23 19:14:45 leviathan python[26292]:     yield self._unsafe_process()
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator

Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 114, in process
Jan 23 19:14:45 leviathan python[26292]:     yield self._unsafe_process()
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 160, in _unsafe_process
Jan 23 19:14:45 leviathan python[26292]:     yield self._handle_deltas(deltas)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 364, in _handle_deltas
Jan 23 19:14:45 leviathan python[26292]:     yield self._handle_new_user(room_id, state_key, profile)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 455, in _handle_new_user
Jan 23 19:14:45 leviathan python[26292]:     yield self.store.add_profiles_to_user_dir(room_id, {user_id: profile})
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 326, in runInteraction
Jan 23 19:14:45 leviathan python[26292]:     *args, **kwargs
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 23 19:14:45 leviathan python[26292]:     result = result.throwExceptionIntoGenerator(g)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Jan 23 19:14:45 leviathan python[26292]:     return g.throw(self.type, self.value, self.tb)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 375, in runWithConnection
Jan 23 19:14:45 leviathan python[26292]:     inner_func, *args, **kwargs
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
Jan 23 19:14:45 leviathan python[26292]:     result = inContext.theWork()
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Jan 23 19:14:45 leviathan python[26292]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
Jan 23 19:14:45 leviathan python[26292]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
Jan 23 19:14:45 leviathan python[26292]:     return func(*args,**kw)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Jan 23 19:14:45 leviathan python[26292]:     compat.reraise(excValue, excTraceback)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
Jan 23 19:14:45 leviathan python[26292]:     raise exception.with_traceback(traceback)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Jan 23 19:14:45 leviathan python[26292]:     result = func(conn, *args, **kw)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 371, in inner_func
Jan 23 19:14:45 leviathan python[26292]:     return func(conn, *args, **kwargs)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 247, in _new_transaction
Jan 23 19:14:45 leviathan python[26292]:     r = func(txn, *args, **kwargs)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/user_directory.py", line 124, in _add_profiles_to_user_dir_txn
Jan 23 19:14:45 leviathan python[26292]:     txn.executemany(sql, args)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 91, in executemany
Jan 23 19:14:45 leviathan python[26292]:     self._do_execute(self.txn.executemany, sql, *args)
Jan 23 19:14:45 leviathan python[26292]:   File "/home/synapse/synapse/env3/lib/python3.7/site-packages/synapse/storage/_base.py", line 118, in _do_execute
Jan 23 19:14:45 leviathan python[26292]:     sql, *args
Jan 23 19:14:45 leviathan python[26292]: psycopg2.IntegrityError: duplicate key value violates unique constraint "user_directory_search_user_idx"
Jan 23 19:14:45 leviathan python[26292]: DETAIL:  Key (user_id)=(@freenode_REDACTED:matrix.org) already exists.
```

**Comment by richvdh** [comment] 2019-01-23 23:57
These messages are expected; they are due to the upsert implementation. https://github.com/matrix-org/synapse/pull/4306 should fix them.

@f0x52 your issue is unrelated.

**Comment by richvdh** [comment] 2019-01-29 11:21
#4306 has now landed but we are still seeing these. Turns out they are actually coming from `store_device` which does an INSERT on the device table. We should probably convert it to use an upsert.

**Comment by mathilde-blc** [comment] 2019-06-16 00:12
still happing on v1.0.0

**Comment by peterhoeg** [comment] 2019-06-17 02:40
It was happening for me to on a database that was migrated from sqlite to pg. I had to manually clear out the offending entries and the index was then successfully built. My approach was a bit heavy-handed (I simply cleared out the tables) which I understand *can* be a problem depending on your setup.

**Comment by richvdh** [comment] 2019-09-02 15:55
closing in favour of #5961

**Comment by turt2live** [comment] 2019-09-02 17:10
I assume you actually meant to close this

**Closed by turt2live** 2019-09-02 17:10 UTC
