### ISSUE TITLE
duplicate key value violates unique constraint "redactions_event_id_key"

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#10138] opened 2021-06-07 22:14 UTC
### Description

My server seems to get stuck on one redaction event. It constantly does show up in my workers log.

### Steps to reproduce

No steps known.

Log snippet that keeps showing up over and over:

```
2021-06-07 21:56:57,347 - synapse.http.server - 97 - ERROR - POST-65212 - Failed handle request via 'ReplicationFederationSendEventsRestServlet': <SynapseRequest at 0x7f0be3e0bf60 method='POST' uri='/_synapse/replication/fed_send_events/hqjxRdnKAk' clientproto='HTTP/1.1' site=21111>
Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
    result = current_context.run(result.throwExceptionIntoGenerator, g)
  File "/opt/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/synapse_git/synapse/replication/http/federation.py", line 131, in _handle_request
    room_id, event_and_contexts, backfilled
  File "/opt/synapse/synapse_git/synapse/handlers/federation.py", line 3073, in persist_events_and_notify
    event_and_contexts, backfilled=backfilled
  File "/opt/synapse/synapse_git/synapse/storage/persist_events.py", line 261, in persist_events
    defer.gatherResults(deferreds, consumeErrors=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "redactions_event_id_key"
DETAIL:  Key (event_id)=($bBypHsNXi_WhY7W5teJqbnRgbru7f2nZUWQngekOWuY) already exists.

/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py:662:_runCallbacks
/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py:1514:gotResult
/opt/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py:1443:_inlineCallbacks
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py:500:throwExceptionIntoGenerator
--- <exception caught here> ---
/opt/synapse/synapse_git/synapse/storage/persist_events.py:170:handle_queue_loop
/opt/synapse/synapse_git/synapse/storage/persist_events.py:323:persisting_queue
/opt/synapse/synapse_git/synapse/storage/persist_events.py:535:_persist_events
/opt/synapse/synapse_git/synapse/storage/databases/main/events.py:182:_persist_events_and_state_updates
/opt/synapse/synapse_git/synapse/storage/database.py:664:runInteraction
/opt/synapse/synapse_git/synapse/storage/database.py:742:runWithConnection
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py:238:inContext
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py:255:<lambda>
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/context.py:118:callWithContext
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/context.py:83:callWithContext
/opt/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:293:_runWithConnection
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/deprecate.py:298:deprecatedFunction
/opt/synapse/env/lib/python3.7/site-packages/twisted/python/compat.py:403:reraise
/opt/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:284:_runWithConnection
/opt/synapse/synapse_git/synapse/storage/database.py:736:inner_func
/opt/synapse/synapse_git/synapse/storage/database.py:528:new_transaction
/opt/synapse/synapse_git/synapse/logging/utils.py:69:wrapped
/opt/synapse/synapse_git/synapse/storage/databases/main/events.py:402:_persist_events_txn
/opt/synapse/synapse_git/synapse/storage/databases/main/events.py:1500:_update_metadata_tables_txn
/opt/synapse/synapse_git/synapse/storage/databases/main/events.py:1589:_store_redaction
/opt/synapse/synapse_git/synapse/storage/database.py:844:simple_insert_txn
/opt/synapse/synapse_git/synapse/storage/database.py:290:execute
/opt/synapse/synapse_git/synapse/storage/database.py:316:_do_execute
]]
```

### Version information

- **Homeserver**: https://matrix.nordgedanken.dev

- **Version**: {"server_version":"1.35.1 (b=HEAD,t=v1.35.1,566677334)","python_version":"3.7.3"}

- **Install method**: git clone and pip

- **Platform**: Debian 10

**Comment by erikjohnston** [comment] 2021-06-11 09:49
Have you purge history in that room, or used history retention? There have been bugs like this before due to that.

**Comment by MTRNord** [comment] 2021-06-11 11:01
> 
> 
> Have you purge history in that room, or used history retention? There have been bugs like this before due to that.

while I cant confirm 100% I can confirm that this is most likely as my bot after joining a room will run the history purge API as it will try to crawl the complete room history and I dont want that to be on my server longer than required.

**Comment by erikjohnston** [comment] 2021-06-17 10:33
I think this is a duplicate of https://github.com/matrix-org/synapse/issues/8707

**Closed by erikjohnston** 2021-06-17 10:33 UTC
Labels: X-Needs-Info
