### ISSUE TITLE
Server error on viewing sick community (cannot get room list)

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#7078] opened 2020-03-15 09:55 UTC
### Description

Tried to add a room ( #ubuntu-hour:grin.hu ) to the community, and the server responded that it cannot be added. It wasnt't saved in riot.

Next time I try to come to the community page synapse 500'd it.

```
2020-03-15 10:44:12,652 - synapse.http.server - 110 - ERROR - GET-1036905- Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f64a47982b0 method='GET' uri='/_matrix/client/r0/groups/%2Bmagyarok%3Agrin.hu/rooms' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/usr/lib/python3/dist-packages/synapse/rest/client/v2_alpha/groups.py", line 329, in on_GET
    group_id, requester_user_id
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3/dist-packages/synapse/handlers/room_list.py", line 294, in generate_room_entry
    result["m.federate"] = create_event.content.get("m.federate", True)
AttributeError: 'NoneType' object has no attribute 'content'
```

And later even better
```
2020-03-15 10:48:43,815 - synapse.http.server - 110 - ERROR - GET-1037840- Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f64a6b26320 method='GET' uri='/_matrix/client/r0/groups/%2Bmagyarok%3Agrin.hu/rooms' clientpro
to='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM': {'event_id': '$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM', 'internal_metadata': '{"token_id": 76, "stream_ordering": 1260084}', 'json': '{"auth_events": ["$V9-0PyAxNxHT7BWlILkb7
NZM2HihatEuBD4Oavggfd8", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$dBZOGgyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg"], "type": "m.room.history_visibility", "room_id": "!gAwUAK
JoCAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"history_visibility": "world_readable"}, "depth": 12, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_ts": 1572699110969, "hashes": {"sha256": "4UYq8CM6f6Lbmf
FPMDTMkTvSwYcqGgEsxAbc7ua0K70"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "XLnEPfStDbH6uxaSX+Wb2WMjSOrOWEdip5YIOK/9gBDpuMVQqWt6tLsmbovEt7o74J1YV91wBU8/M+B+minfCw"}}, "unsigned": {"age_ts": 1572699110969, "replaces_state": "$sxCukWrxfmfKOXH
Sszo8LvXWPDxRb_VER1YseqtCV8U"}}', 'format_version': 3, 'rejected_reason': None, 'redactions': []}, '$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI': {'event_id': '$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI', 'internal_metadata': '{"token_id": 
76, "stream_ordering": 1260077}', 'json': '{"auth_events": ["$V9-0PyAxNxHT7BWlILkb7NZM2HihatEuBD4Oavggfd8", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$9kovxH0Ti3NTfX9eJ-6I
80Je1EvVRjJv1D6WUVm-Ssc"], "type": "m.room.join_rules", "room_id": "!gAwUAKJoCAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"join_rule": "public"}, "depth": 5, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server
_ts": 1572699069227, "hashes": {"sha256": "v7Sf2Mi6i48nhIrhazL7J84o3y4SfcZTlPaj0jJUF34"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "IWmTDnK4/xCjiegX/OMnY+svueztxgGII4TH+Lxluh3Y/11FKk7KX5sTLjGYtOks2hooegyagmpHeBxxuKi+DA"}}, "unsigned": {"ag
e_ts": 1572699069227}}', 'format_version': 3, 'rejected_reason': None, 'redactions': []}, '$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-Ssc': {'event_id': '$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-Ssc', 'internal_metadata': '{"token_id": 76, "stre
am_ordering": 1260076}', 'json': '{"auth_events": ["$V9-0PyAxNxHT7BWlILkb7NZM2HihatEuBD4Oavggfd8", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$V9-0PyAxNxHT7BWlILkb7NZM2Hiha
tEuBD4Oavggfd8"], "type": "m.room.canonical_alias", "room_id": "!gAwUAKJoCAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"alias": "#osm:grin.hu"}, "depth": 4, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_t
s": 1572699069078, "hashes": {"sha256": "lxhZkAHii2gRqO8Ajw3mWzOdFFkr+m1kBOqgX2NkSxc"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "LC0t2bNo250w5UQ9tSdlfk1kzTkih6a8kjelWldvbYN8UWW8Tz9th20sFyInFK9TizPgNtj4hzFF4nB3VbkpBQ"}}, "unsigned": {"age_
ts": 1572699069078}}', 'format_version': 3, 'rejected_reason': None, 'redactions': []}, '$GvoF44EmloKhUIL2gqO8-bDTisFDn2kHx0YVCbdDThc': {'event_id': '$GvoF44EmloKhUIL2gqO8-bDTisFDn2kHx0YVCbdDThc', 'internal_metadata': '{"token_id": 76, "stream
_ordering": 1268907}', 'json': '{"auth_events": ["$24-plRKTekEWsMc9mXVdx6zCtG8i4vVGoRKsRcCxYxA", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$DeW9rlBZpTEsx5FhnSjNrrY9lsTLqtd
Ckpq44kAOX2c"], "type": "m.room.topic", "room_id": "!gAwUAKJoCAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"topic": "Az OSM magyarorsz\\u00e1gi k\\u00f6z\\u00f6ss\\u00e9ge.\\nhttps://openstreetmap.hu/\\nMarkdown help: https://com
monmark.org/help/\\n"}, "depth": 31, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_ts": 1572865114935, "hashes": {"sha256": "AOAqZAeTvTvFENPFByTdtoPTwoTW6N9Ve4veijcLYLE"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "
8E01XMLIu7BGwdnGSmefBbSZkFGqgzXoOoDBm32xElxSb3OyKRh5OCUflpGWoKQiqYfzxx0CxVpVMgNM4Z4ZAQ"}}, "unsigned": {"age_ts": 1572865114935, "replaces_state": "$j1Mx52VrcarbzExzZPvJUSGdYa8qqEmA-V3eDYmil2g"}}', 'format_version': 3, 'rejected_reason': None,
 'redactions': []}, '$dBZOGgyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg': {'event_id': '$dBZOGgyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg', 'internal_metadata': '{"token_id": 76, "stream_ordering": 1260083}', 'json': '{"auth_events": ["$V9-0PyAxNxHT7BWlI
Lkb7NZM2HihatEuBD4Oavggfd8", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$zRMX8vfzbKQIQkxsBdPOx0llnopyAxMLkw_G-xkvlr0"], "type": "m.room.guest_access", "room_id": "!gAwUAKJo
CAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"guest_access": "can_join"}, "depth": 11, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_ts": 1572699108433, "hashes": {"sha256": "ixr9fT81xXcrqLI3qZAvqoyLyYRM
qf50pngjx5unyHY"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "Td/K9cLai2NZk6Ob8EZQ04uWFnZxlajKcqDfpGcaFlD6XNx1LSFzvvvqaVBdIzdpM1X5uTb2fB2Gj+6CDzZEBg"}}, "unsigned": {"age_ts": 1572699108433}}', 'format_version': 3, 'rejected_reason': None, 
'redactions': []}, '$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4': {'event_id': '$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4', 'internal_metadata': '{"token_id": 76, "stream_ordering": 1260079}', 'json': '{"auth_events": ["$V9-0PyAxNxHT7BWlIL
kb7NZM2HihatEuBD4Oavggfd8", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$sxCukWrxfmfKOXHSszo8LvXWPDxRb_VER1YseqtCV8U"], "type": "m.room.name", "room_id": "!gAwUAKJoCAuYnIoNe
V:grin.hu", "sender": "@grin:grin.hu", "content": {"name": "OpenStreetMap Hungary"}, "depth": 7, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_ts": 1572699069486, "hashes": {"sha256": "1Mewd3Rk6CHlN4+/CqOT1uNnh71Eq6nTH
zfBUe6aUFg"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "4bNoAePrbRst7ZbyZPbaGl0906q+pw690JvaXfJH4/WhGO6w7ssNDivL4uC/oqVoZderZIXQHr8zaHdVdFnGDw"}}, "unsigned": {"age_ts": 1572699069486}}', 'format_version': 3, 'rejected_reason': None, 'reda
ctions': []}, '$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc': {'event_id': '$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc', 'internal_metadata': '{"token_id": 76, "stream_ordering": 1260087}', 'json': '{"auth_events": ["$vTkp1Bpq52xKbafLApUOXzL
IaDs6JqOcwvGLknzTQ8I", "$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs", "$kVa9uhXUlOH5f23uJIxciUnU_8ZqrhwhRElDt9W1HjA"], "prev_events": ["$vTkp1Bpq52xKbafLApUOXzLIaDs6JqOcwvGLknzTQ8I"], "type": "m.room.avatar", "room_id": "!gAwUAKJoCAuYnIoNeV:g
rin.hu", "sender": "@grin:grin.hu", "content": {"url": "mxc://grin.hu/rQnVLEOuEVKlJktCwosaxAlO"}, "depth": 15, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_server_ts": 1572699276452, "hashes": {"sha256": "dzhG6cM80DlN07A9cbC
U/M1RFUOpTzyPBRpCXD6nu4o"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "3HciawgLNV9XwKUAMk5W3s824IMBaE5Zq9COzO/bKTCzbJP8/ag0CgTAPYB6WGPIHndRcbc4trwFb0ibOvkjAA"}}, "unsigned": {"age_ts": 1572699276452}}', 'format_version': 3, 'rejected_reason
': None, 'redactions': []}, '$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs': {'event_id': '$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs', 'internal_metadata': '{"token_id": 76, "stream_ordering": 1260073}', 'json': '{"auth_events": [], "prev_ev
ents": [], "type": "m.room.create", "room_id": "!gAwUAKJoCAuYnIoNeV:grin.hu", "sender": "@grin:grin.hu", "content": {"room_version": "4", "creator": "@grin:grin.hu"}, "depth": 1, "prev_state": [], "state_key": "", "origin": "grin.hu", "origin_
server_ts": 1572699068282, "hashes": {"sha256": "R5NXXJdBFiv5x9BorOsBPQCCNmN++N7N26TjcULqCiQ"}, "signatures": {"grin.hu": {"ed25519:a_PkUB": "JYJKoJqkY9tGH1zvxmW+ahGzY9aqkf/G3jldWndNl4UFOGynZQ2n4Yggi9ZGBIkauscRuAkA4K5eh6e8HLixBQ"}}, "unsigned"
: {"age_ts": 1572699068282}}', 'format_version': 3, 'rejected_reason': None, 'redactions': []}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc': _EventCacheEntry(event=<FrozenEventV3 event_id='$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc', type='m.room.avatar', state_key=''>, redacted_event=None), '$GvoF44EmloKhUIL2gqO8-bD
TisFDn2kHx0YVCbdDThc': _EventCacheEntry(event=<FrozenEventV3 event_id='$GvoF44EmloKhUIL2gqO8-bDTisFDn2kHx0YVCbdDThc', type='m.room.topic', state_key=''>, redacted_event=None), '$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM': _EventCacheEntry(ev
ent=<FrozenEventV3 event_id='$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM', type='m.room.history_visibility', state_key=''>, redacted_event=None), '$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs': _EventCacheEntry(event=<FrozenEventV3 event_id='
$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs', type='m.room.create', state_key=''>, redacted_event=None), '$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-Ssc': _EventCacheEntry(event=<FrozenEventV3 event_id='$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-
Ssc', type='m.room.canonical_alias', state_key=''>, redacted_event=None), '$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4': _EventCacheEntry(event=<FrozenEventV3 event_id='$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4', type='m.room.name', state_
key=''>, redacted_event=None), '$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI': _EventCacheEntry(event=<FrozenEventV3 event_id='$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI', type='m.room.join_rules', state_key=''>, redacted_event=None), '$dBZO
Ggyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg': _EventCacheEntry(event=<FrozenEventV3 event_id='$dBZOGgyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg', type='m.room.guest_access', state_key=''>, redacted_event=None)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc': _EventCacheEntry(event=<FrozenEventV3 event_id='$k8NsgWNkqATFjHTv5wHMUZ8AxkjmjbYjiTTVtmwnrtc', type='m.room.avatar', state_key=''>, redacted_event=None), '$GvoF44EmloKhUIL2gqO8-bD
TisFDn2kHx0YVCbdDThc': _EventCacheEntry(event=<FrozenEventV3 event_id='$GvoF44EmloKhUIL2gqO8-bDTisFDn2kHx0YVCbdDThc', type='m.room.topic', state_key=''>, redacted_event=None), '$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM': _EventCacheEntry(ev
ent=<FrozenEventV3 event_id='$0xIQjO88lKN0G3ISYi6DZGQZBAcKI0lf2bIP0F5ANdM', type='m.room.history_visibility', state_key=''>, redacted_event=None), '$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs': _EventCacheEntry(event=<FrozenEventV3 event_id='
$yaWi93ApF2JzGFv1s9PNXPIbXq7WO-xKk276_snRWDs', type='m.room.create', state_key=''>, redacted_event=None), '$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-Ssc': _EventCacheEntry(event=<FrozenEventV3 event_id='$9kovxH0Ti3NTfX9eJ-6I80Je1EvVRjJv1D6WUVm-
Ssc', type='m.room.canonical_alias', state_key=''>, redacted_event=None), '$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4': _EventCacheEntry(event=<FrozenEventV3 event_id='$f3nF3vgpFW5zezEbwUg-_eYNJeC3sSh3ljauGYT0HP4', type='m.room.name', state_
key=''>, redacted_event=None), '$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI': _EventCacheEntry(event=<FrozenEventV3 event_id='$2AilMN5BPoHA674Z0NfiUDJT2KKfcgL1aBKfZ8xUgUI', type='m.room.join_rules', state_key=''>, redacted_event=None), '$dBZO
Ggyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg': _EventCacheEntry(event=<FrozenEventV3 event_id='$dBZOGgyow89xtRsfgg_0-gpKOc-knWTTqHNGcj7jFjg', type='m.room.guest_access', state_key=''>, redacted_event=None)}
```
...and so on...

### Steps to reproduce

- try to add room to +magyarok:grin.hu, get error, do not save
- try to view community rooms again

### Version information

- **Homeserver**: 
If not matrix.org: grin.hu

- **Version**:
1.11.1-1 (Debian)

- **Install method**:
Debian (not NV)

**Comment by aaronraimist** [comment] 2020-03-15 18:03
Probably a duplicate of https://github.com/matrix-org/synapse/issues/4891

**Comment by richvdh** [comment] 2020-03-17 17:10
closing as a dup of #4891

**Closed** 2020-03-17 17:12 UTC
