### ISSUE TITLE
Synapse_port_db does not handle column shadow_banned

### ISSUE THREAD

**Issue by DylanVanAssche** [matrix-org/synapse#8431] opened 2020-09-30 18:55 UTC
When moving a SQLite3 DB to PostgreSQL, I encountered a crash of `synapse_port_db`.

```
root@2dc5b8149758:/# synapse_port_db --sqlite-database /data/homeserver.db.snapshot --postgres-config /data/homeserver-sqlite.yaml --curses
Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 622, in run
    consumeErrors=True,
twisted.internet.defer.FirstError: FirstError[#42, [Failure instance: Traceback: <class 'psycopg2.errors.DatatypeMismatch'>: column "shadow_banned" is of type boolean but expression is of type integer
LINE 1: ...BvqC', 1600941970, 1, NULL, 0, NULL, NULL, NULL, NULL, 0, 0)

```
The column datatype doesn't match.

- Synapse V1.20.0
- Docker

**Comment by clokep** [comment] 2020-09-30 19:03
This is a duplicate of #8384, which is fixed in v1.20.1, please upgrade!

**Closed by clokep** 2020-09-30 19:03 UTC
