### ISSUE TITLE
URL preview of animated GIF/JPEG/video should be configurable to show the animation

### ISSUE THREAD

**Issue by williamkray** [matrix-org/synapse#7915] opened 2020-07-20 18:50 UTC
related to https://github.com/vector-im/riot-web/issues/14567

Animated GIF sharing is often done via a URL to the image (via services like giphy or imgur). URL preview should optionally generate an animated thumbnail to use, or be configured in some cases to simply show the full-size image for those use cases.

Suggestion of this feature in Element web/desktop codebase (posted above, not my suggestion) looks like it was directed toward the synapse configuration, and so here's this feature request.

Additional functionality would be that it respects the client's settings for autoplay, but i believe that part of it would be how the client handles the information from the server, and so it is unrelated until this feature actually exists.

**Comment by anoadragon453** [comment] 2020-07-20 19:17
Related: https://github.com/matrix-org/synapse/issues/1278 https://github.com/matrix-org/synapse/issues/4347

Synapse's implementation of the media repo (which is the component that handles media requests and URL previews) does not currently support animated gif thumbnails.

Offhand: you may be interested in [matrix-media-repo](https://github.com/turt2live/matrix-media-repo/), which does support animated thumbnails.

**Comment by anoadragon453** [comment] 2020-07-20 19:21
I'm going to close this issue as a duplicate of https://github.com/matrix-org/synapse/issues/1278 as the thumbnails generated for both usecases run through the same code path.

**Closed by anoadragon453** 2020-07-20 19:21 UTC
