### ISSUE TITLE
[feature request] support mariadb

### ISSUE THREAD

**Issue by nillebor** [matrix-org/synapse#12306] opened 2022-03-26 17:16 UTC
Hi

i would like synapse to support mariadb as a database. i use mariadb for several other docker images. it would be more resource-saving if you don't have to use different databases.

is there anything against using mariadb? sqlite would also be supported by my other dockers, but is not as performant with synapse.

would it be implementable?

**Comment by dklimpel** [comment] 2022-03-26 21:10
IMO it is a duplicate to #2112

**Comment by babolivier** [comment] 2022-03-28 09:23
Indeed, I'm closing this as a duplicate of #2112. We have made our position clear about adding support for another database engine (nothing specifically against MySQL/MariaDB) [here](https://github.com/matrix-org/synapse/issues/2112#issuecomment-779181958).

**Closed by babolivier** 2022-03-28 09:23 UTC
