### ISSUE TITLE
Joining by invite to empty room

### ISSUE THREAD

**Issue by slipeer** [matrix-org/synapse#3602] opened 2018-07-25 07:27 UTC
### Problem reproduction
If user A has invited user B to a new room, but he did not wait when B accenpt invite and leave room.
User B see invite, but when trying to accept it, the error "no known servers"

I believe that synapse must more correct handle this situation:
 - for example return error like "everyone left the room".
- or accept user join into room in which there is already no one (maybe there are messages for user).

Second variant of behavior seems more logical to me.

Probably requires changes in `_is_host_in_room` method in `synapse/handlers/room_member.py` - this method return false if all local users leave room. 

This method is called from `_update_membership` (same handler) and if it return `False` then used method `_remote_join`. I think that call to `_remote_join` is not entirely correct whent local user try to join local room  in which there is already no one.

**Comment by richvdh** [comment] 2018-07-25 09:42
this is basically a duplicate of #1533 and https://github.com/matrix-org/matrix-doc/issues/534.

**Closed by richvdh** 2018-07-25 09:42 UTC

**Comment by ara4n** [comment] 2020-09-12 12:17
Another solution would be to for the invite to be cancelled when the inviter leaves, as per https://github.com/matrix-org/matrix-doc/issues/1966
