### ISSUE TITLE
Error while fetching room history

### ISSUE THREAD

**Issue by PeerD** [matrix-org/synapse#9457] opened 2021-02-22 12:59 UTC
### Description

Error while fetching Room History

### Steps to reproduce

Both Synapse and Element are deployed using the latest docker image (as of today, 22.2.2021) for a small private and not federated homeserver.

While trying to fetch the room history (scrolling up) in Element Web a 500 is returned and the following is logged:
```
synapse_1  | 2021-02-22 12:40:01,306 - synapse.http.server - 79 - ERROR - GET-1542562 - Failed handle request via 'RoomMessageListRestServlet': <XForwardedForRequest at 0x7f900e9d1d60 method='GET' uri='/_matrix/client/r0/rooms/!NDEvKJSYxQhgsWVMEM%3Amatrix.example.org/messages?from=t1940-41506_3341610_9388_134371_131180_243_17247_3935_101&limit=20&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site='8008'>
synapse_1  | Traceback (most recent call last):
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 224, in _async_render_wrapper
synapse_1  |     callback_return = await self._async_render(request)
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 402, in _async_render
synapse_1  |     callback_return = await raw_callback_return
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v1/room.py", line 543, in on_GET
synapse_1  |     msgs = await self.pagination_handler.get_messages(
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/pagination.py", line 446, in get_messages
synapse_1  |     await self._event_serializer.serialize_events(
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
synapse_1  |     result = g.send(result)
synapse_1  |   File "/usr/local/lib/python3.8/site-packages/synapse/events/utils.py", line 408, in serialize_event
synapse_1  |     serialized_event["content"].pop("m.relates_to", None)
synapse_1  | AttributeError: 'frozendict' object has no attribute 'pop'
```
This results in the inability to see older messages.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: private (non federated) homeserver

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.26.0","python_version":"3.8.7"}

- **Install method**: docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian 10 on x64
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by PeerD** [comment] 2021-02-22 13:08
Ok, I just noticed that docker latest was 1.26. After manually updating to 1.27 the crashes are gone. So this problem ist probably gone?

**Comment by clokep** [comment] 2021-02-22 15:01
Glad that upgrading worked! I can't immediately find a reason why this would have broken (and subsequently been fixed), but since the problem is gone I'm going to close this. Please comment if you see it again and we'll try to get to the bottom of it!

**Closed by clokep** 2021-02-22 15:01 UTC

**Comment by jordane** [comment] 2021-09-23 06:08
Hi @clokep,

I ran into the same issue recently while running 1.29.0 via the official docker container with a very similar stack trace. I restarted the container without upgrading and the issue went away. I can't seem to reproduce it but I will give it some time and see if I can do so. We're planning on updating soon. I did confirm that the error consistently appeared for the history of a room for any given user that tried to fetch it (I tried 3 different users).

Here is the log I got:
```
2021-09-20 16:54:14,927 - synapse.http.server - 94 - ERROR - GET-3402776 - Failed handle request via 'RoomMessageListRestServlet': <XForwardedForRequest at 0x7f74b02055e0 method='GET' uri='/_matrix/client/r0/rooms/<removed room id>/messages?from=t246-42319_0_0_0_0_0_0_0_0&limit=20&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site='8080'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 259, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 447, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v1/room.py", line 547, in on_GET
    msgs = await self.pagination_handler.get_messages(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/pagination.py", line 454, in get_messages
    await self._event_serializer.serialize_events(
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/usr/local/lib/python3.8/site-packages/synapse/events/utils.py", line 408, in serialize_event
    serialized_event["content"].pop("m.relates_to", None)
--
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 259, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 447, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v1/room.py", line 547, in on_GET
    msgs = await self.pagination_handler.get_messages(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/pagination.py", line 454, in get_messages
    await self._event_serializer.serialize_events(
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/usr/local/lib/python3.8/site-packages/synapse/events/utils.py", line 408, in serialize_event
    serialized_event["content"].pop("m.relates_to", None)
AttributeError: 'frozendict' object has no attribute 'pop'
```
