### ISSUE TITLE
Remote aliases aren't moved to new room on room upgrade.

### ISSUE THREAD

**Issue by mvgorcum** [matrix-org/synapse#6784] opened 2020-01-26 20:43 UTC
**Description:**

**Comment by richvdh** [comment] 2020-01-30 11:04
Could someone explain like I'm five what exactly the problem is here?

**Comment by mvgorcum** [comment] 2020-01-30 11:26
I haven't tested all permutations, but this is what I found:

`@exampleuser:server1.com` creates room, adds alias `#alias:server1.com`. `@exampleuser2:server2.com` joins and adds `#alias2:server2.com`.

`@exampleuser:server1.com` upgrades the room to another room version. `#alias:server1.com` gets moved to the new room, but `#alias2:server2.com` does not get moved.

**Comment by anoadragon453** [comment] 2020-01-30 11:36
@mvgorcum Does the second alias get moved when a user from server2.com joins the upgraded room?

**Comment by anoadragon453** [comment] 2020-01-30 11:41
Just tested and indeed remote aliases don't ever get moved. We should move them when the server processes the create event for the first time, just like other room attributes.

**Comment by mvgorcum** [comment] 2020-01-30 11:51
Yeah, if `@exampleuser2:server2.com` joins that doesn't trigger an alias move.

**Comment by richvdh** [comment] 2020-02-05 10:33
related: #6842

**Comment by anoadragon453** [comment] 2020-03-30 16:53
Fixed by https://github.com/matrix-org/synapse/pull/6946

**Closed by anoadragon453** 2020-03-30 16:53 UTC
Labels: p2, type:roomupgrades
