### ISSUE TITLE
SyTest test "Device deletion propagates over federation" is flaky

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6942] opened 2020-02-18 16:06 UTC
Just saw this test flake on https://buildkite.com/matrix-dot-org/sytest/builds/584#e4539cf6-b7d2-4506-83f1-b4a6b042155a. Re-running `Synapse - :python: 3.5 / :postgres: 9.6 / Workers` fixed the build.

**Comment by richvdh** [comment] 2020-02-20 21:21
I bet this has a similar cause to https://github.com/matrix-org/sytest/pull/816.

**Comment by DMRobertson** [comment] 2022-08-25 11:55
Duplicate of https://github.com/matrix-org/sytest/issues/1156.

**Closed by DMRobertson** 2022-08-25 11:55 UTC
Labels: z-p2, S-Tolerable, T-Task, A-Testing
