### ISSUE TITLE
Listening on Unix Socket

### ISSUE THREAD

**Issue by bahur142** [matrix-org/synapse#14754] opened 2022-12-30 16:17 UTC
**Description:**

Ability Synapse to listen on Unix domain socket.
This will help eliminate TCP between reverse proxy (for example Nginx) and Synapse if both resides on the same machine.

**Comment by dklimpel** [comment] 2022-12-30 16:37
IMO it is a duplicate to #4975

**Comment by clokep** [comment] 2022-12-30 16:40
Thanks, I agree this is a duplicate of #4975

**Closed by clokep** 2022-12-30 16:40 UTC
