### ISSUE TITLE
Message retention problem

### ISSUE THREAD

**Issue by Yarik2308** [matrix-org/synapse#10071] opened 2021-05-26 16:01 UTC
Hello. I asked this question on [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org), but noone answered me. So I try my luck here. 

We are runing Synapse server and have some problem with message retention. 

When we are trying to set `m.room.retention` event with empty content it still deletes messages like it is using previous `m.room.retention` event.

So. To be clear.

1.  Send `m.room.retention`  event with max_lifetime = 60000
Messeges do not show after 1 min
2.  Send `m.room.retention`  event with max_lifetime = 86400000
As `purge_jobs` did not work, we see messages that wasnt seen in step 1.
3.  Repeat step 1 - messages deleted
4.  try to send `m.room.retention`  event with empty content
`expectation:` I can see messages what wasn deleted by purge_jobs yet
`reality:` Can not see messages. They are still removed 1 min after.
5.  Repeat step 2 - see that messages still there.

So what am i doing wrong? maybe there are some options in configurations need to be set?

And then we are sending `m.room.retention`  event with empty content it is not saved in `room_retention` table in db. But It is saved in `event_json` table.

**Comment by richvdh** [comment] 2021-05-27 09:41
note that message retention is an experimental feature - if it works at all, you're lucky, and it's not something we can really support.

At a guess though: you're sending the `m.room.retention` event as a regular event rather than a state event.

**Comment by babolivier** [comment] 2021-05-27 10:04
Hi @Yarik2308. It looks to me like everything is working fine, but I get how it can look confusing. Let me explain what's happening.

Purge jobs are expensive to run for Synapse, so we can't run them every time an event expires. This is why, when configuring purge jobs, you set an interval, which is the amount of time between two runs of the job. This means the deletion of the messages might be delayed by up to the amount of time set as the interval. To prevent messages from still being visible, Synapse will however hide them from clients once they reach their expiration date. Note that this doesn't mean you want to run purge jobs every minute; as I mentioned it's an expensive task to run and running it too often can have a negative impact on your homeserver's performance.

This explains why, if you change the message retention setting to allow for older messages, you still see previous messages that haven't been purged yet. This could arguably be considered a bug, though a minor one since it's only showing up in edge cases (and as @richvdh mentioned this is an experimental feature).

> And then we are sending `m.room.retention` event with empty content it is not saved in `room_retention` table in db. But It is saved in `event_json` table.

This is also expected. The way retention policies are queried is by joining against the `current_state_events` table, which represents the current state of a room. So if the `m.room.retention` event has an empty content, we don't store anything in `room_retention`, knowing that it will be considered as having no policy regardless.

On your 4th point, it does sound like unexpected behaviour, though like @richvdh I also suspect the `m.room.retention` event you're trying to send is a regular event rather than a state event.

**Comment by babolivier** [comment] 2021-05-27 10:06
If you want to know more about how this feature is working under the hood and why it's being done like this, I'd recommend having a look at https://brendan.abolivier.bzh/matrix-retention-policies/ (sorry for the shameless plug :stuck_out_tongue:) which goes in depth into it.

**Comment by Yarik2308** [comment] 2021-05-27 18:23
@richvdh @babolivier Thanks for yours answers, but I can see in `state_events` table, that my events with empty content are there. So that means that im sending state event.

> At a guess though: you're sending the `m.room.retention` event as a regular event rather than a state event.


Alow there one thing that i tried is to send `m.room.retention` event with content like 

```
{
    "max_lifeteime": 60000,
    "min_lifetime": null
}
```

And it is not saved in `room_retention` table.  I can see that `current_state_event` of `m.room.retention` changed. But there is no such `retention `with such` event_id` in `room_retention` table. 


So. to be clear. I are saying, that my 4th point, does sound like as unexpected behaviour? Should messages still be deleted, even if content of new `room_retention` event is empty?

**Comment by clokep** [comment] 2021-05-27 18:28
It looks like it only gets stored if it has a non-empty body and int values:

https://github.com/matrix-org/synapse/blob/224f2f949b1661094a64d1105efb64159ddf4aa0/synapse/storage/databases/main/events.py#L1795-L1821

I think you're trying to reset the room retention data to the default? In this case it looks like it *doesn't* get saved into the `room_retention` table and then the checks for this should cause it to return the default:

https://github.com/matrix-org/synapse/blob/8fb9af570f942d2057e8acb4a047d61ed7048f58/synapse/storage/databases/main/room.py#L621-L644

**Comment by richvdh** [comment] 2022-01-04 15:48
closing this due to lack of info.

**Closed by richvdh** 2022-01-04 15:48 UTC
Labels: X-Needs-Info
