### ISSUE TITLE
Upload capacity

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#10231] opened 2021-06-23 01:12 UTC
there should be a feature to limit every user to a capacity of uploading files like 1GB per user if he exceeded the limit can't upload more

hint: i know about limit upload size but it won't work if spammer is uploading files every second to flood the server

**Comment by dklimpel** [comment] 2021-06-23 05:16
It is a duplicate of #3339 and your's #9784

**Closed** 2021-06-23 10:10 UTC
