### ISSUE TITLE
Shutdown room API should avoid generating notifications

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#12622] opened 2022-05-03 21:22 UTC
The shutdown room API can cause useless notifications since the homeserver is going to be mass kicking all users anyway.

----

Moved from https://github.com/vector-im/element-web/issues/6996

**Comment by anoadragon453** [comment] 2022-05-05 17:58
Sorry, what does the "mute the room" actually mean?

I'm not sure what this issue is asking for.

**Comment by t3chguy** [comment] 2022-05-05 18:04
Pinging @ara4n for more info

**Comment by H-Shay** [comment] 2022-06-01 19:48
This is 30 days old with no updates and seems to come from a 2-year-old issue in element-web, so unless anyone strongly disagrees I am going to close this issue.

**Comment by t3chguy** [comment] 2022-06-01 21:16
Presumably mute in this context is to set the permissions required to speak out of bounds

**Comment by H-Shay** [comment] 2022-06-01 22:08
I'll reopen no problem.

**Comment by clokep** [comment] 2022-08-24 15:19
I've attempted to clarify this issue a bit -- as is mentioned in the Element Web issue I'm not sure what could be done over federation here, but it seems like something useful could be done for local users.

**Comment by richvdh** [comment] 2022-08-25 12:01
Hum; I'm still not sure we're clear what this issue is actually asking for.

> Presumably mute in this context is to set the permissions required to speak out of bounds of local users

This doesn't sound like notifications - rather it's about setting the power levels in the room so that users can't send messages in the first place. I think the problem is that kicking can take a long time, so people can still send messages while it's going on, which isn't terribly helpful.

**Comment by clokep** [comment] 2022-08-25 12:26
> > Presumably mute in this context is to set the permissions required to speak out of bounds of local users
> 
> This doesn't sound like notifications - rather it's about setting the power levels in the room so that users can't send messages in the first place. I think the problem is that kicking can take a long time, so people can still send messages while it's going on, which isn't terribly helpful.

That's a possible interpretation of the original request too. This sounds like #11842, which is fixed.

**Comment by DMRobertson** [comment] 2022-08-25 12:52
Closing as a duplicate of #11842. If @ara4n had something specific in mind that wasn't covered by this, a new issue is very welcome.

**Closed by DMRobertson** 2022-08-25 12:52 UTC
Labels: A-Admin-API, S-Minor, T-Enhancement, O-Uncommon
