### ISSUE TITLE
Synapse does not recover correctly after a database server outage

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11167] opened 2021-10-23 21:10 UTC
Earlier today our database server restarted. The database recovered itself; Synapse did not. In particular we saw "in flight requests" stacking up:

![image](https://user-images.githubusercontent.com/1389908/138571705-ba1c0748-cfe7-4e4f-8d86-87d32eb3dc51.png)

... and the reverse-proxy returned 429s for many requests.

**Comment by squahtx** [comment] 2021-11-03 15:46
Event fetches explain most of the stuck requests.  

There's one class of stuck request that I can't explain yet: `GET FederationUserDevicesQueryServlet` requests were piling up on `federation_reader-1` and don't read any events as far as I can tell. Perhaps it's something to do with the `@cachedList` on `_get_bare_e2e_cross_signing_keys_bulk`? The code for `@cachedList` is tricky to understand but looks sound...

**Comment by squahtx** [comment] 2021-11-03 18:32
In testing, `@cachedList` handled exceptions just fine. I can't reproduce the pile up of `FederationUserDevicesQueryServlet` requests.

**Comment by richvdh** [comment] 2021-11-03 23:45
yeah, very odd. I'm also at a loss to explain it.

**Comment by squahtx** [comment] 2021-11-04 10:39
Fixed by #11240, except for the `FederationUserDevicesQueryServlet` requests which I can't reproduce.

**Comment by richvdh** [comment] 2021-11-04 12:30
Let's close this for now, then.

**Comment by richvdh** [comment] 2021-11-17 08:30
Sadly I think we still have wedging event fetch queries. https://prometheus.matrix.org/graph?g0.expr=min_over_time(synapse_event_fetch_ongoing%5B10m%5D)%3E%200&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=17m2s852ms&g0.end_input=2021-11-17%2008%3A28%3A10&g0.moment_input=2021-11-17%2008%3A28%3A10:


![image](https://user-images.githubusercontent.com/1389908/142163748-28292df6-1457-4960-861c-8561e55511d6.png)

**Comment by richvdh** [comment] 2021-11-17 12:37
I think the problem here is that we increment `_event_fetch_ongoing` [in the main thread](https://github.com/matrix-org/synapse/blob/v1.47.0rc3/synapse/storage/databases/main/events_worker.py#L990), but decrement it [in the event fetch thread](https://github.com/matrix-org/synapse/blob/v1.47.0rc3/synapse/storage/databases/main/events_worker.py#L766).

Apart from the fact that integer increment/decrement operations aren't atomic in Python (so decrementing it without holding the lock is racy), we also have the problem that if we're unable to get a connection to the database (eg, because it is shutting down...), `runWithConnection` will fail without calling `_do_fetch` - hence the counter is incremented but not decremented.

**Closed** 2021-11-26 13:47 UTC
Labels: P1, S-Major, T-Defect
