### ISSUE TITLE
Badges for rooms without notifications

### ISSUE THREAD

**Issue by zzottel** [matrix-org/synapse#2270] opened 2017-06-09 21:36 UTC
I have two rooms that are set to notify only when I'm mentioned. This works, i.e. I only get desktop/mobile notifications when I'm mentioned.

However, whenever there are new messages in these rooms, the window title in Riot Web gets an unread rooms badge ("Riot [1]"), and Riot Android gets a badge shown on the home screen.

As far as I can tell, this happens since a few weeks to all rooms that ever had the setting to notify on every new message, which includes newly joined rooms, as that's the default. When that setting is later (since Synapse v0.21.0?) set to notify for mentions only, the badge count is still stepped up for new messages without a mention.

This does not happen for rooms that were "downgraded" to mentions only notifications earlier, possibly before Synapse v0.21.0.

Switching notifications off and on again doesn't help.

Seen on:
Synapse v0.21.0 (not sure if on earlier versions, too)
Riot Web v0.10.0-0.10.2 (and earlier versions?)
Riot Android 0.6.9 & 0.6.10

**Comment by zzottel** [comment] 2017-06-09 21:41
To clarify: I've seen this on a room that I recently joined, and on a room that I joined long ago and that was always set to mention for every message, but that I set to mentions only recently.

**Comment by turt2live** [comment] 2017-06-09 22:46
I've had this too. It seems to be fixed after synapse restarts.

Related (if not the same?): https://github.com/vector-im/riot-web/issues/3060

**Comment by zzottel** [comment] 2017-06-09 22:55
Can confirm it's fixed after a Synapse restart.

**Comment by zzottel** [comment] 2017-06-29 09:00
It seems this also leads to high bettery usage on Riot Android as the badge update triggers a sync every time it is received.

**Comment by Mikaela** [comment] 2017-06-29 09:02
> It seems this also leads to high bettery usage on Riot Android as the badge update triggers a sync every time it is received.

https://github.com/vector-im/riot-android/issues/1391

**Comment by richvdh** [comment] 2017-07-04 23:37
I'm also seeing this happening the other way around (ie, start with a room which is set to 'mentions only', switch it to 'all messages', and still only getting notifications for mentions). Again, a synapse restart fixes it.

It seems to be semi-reproducible by:
* set room to mentions only
* stop synapse
* some events arrive
* start synapse
* more events arrive (no notifications yet, because still 'mentions only')
* switch room to notify on 'all events'
* yet more events arrive - still no notifications.

If that doesn't repro it, repeating the process a couple of times may do so

**Comment by richvdh** [comment] 2017-07-05 16:27
I've not been able to reproduce my version of this since landing #2332, so perhaps that has fixed it.

@turt2live: It *doesn't* sound the same as https://github.com/vector-im/riot-web/issues/3060, which reports a notification being shown in the favicon and titlebar but not the room list. AIUI @zzottel was seeing badges in the roomlist (when they weren't expected).

Anyway, I'm tentatively declaring this one fixed as of synapse develop.

**Closed by richvdh** 2017-07-05 16:27 UTC
