### ISSUE TITLE
Broken rooms are created

### ISSUE THREAD

**Issue by RomanOlegovich** [matrix-org/synapse#13407] opened 2022-07-28 02:42 UTC
### Description

On our server, chats are administered automatically (backend):
- users are created through the admin API
- further all actions are performed on behalf of users using the token obtained from 
/_synapse/admin/v1/users/{user_id}/login

### Steps to reproduce
Randomly reproduced.
#### Create room
- Log in as user A and create direct room and receive room id (invite user B).
"/_matrix/client/v3/createRoom"
- Log in as user B, join the room by room id
```
You do not have permission to join the room. A meaningful `errcode`
and description error text will be returned. Example reasons for rejection are:
- The room is invite-only and the user was not invited.
- The user has been banned from the room.
- The room is restricted and the user failed to satisfy any of the conditions.
```

#### Try get room details
- Convert alias (known) to roomId 
"/_matrix/client/v3/directory/room/{roomAlias}"
Get a room by roomId (Will be joined_members = 0, canonical_alias = null)
"/_synapse/admin/v1/rooms/{room_id}"
```
{
  "room_id": "!FlLYKuBJcyYAuwDeIN:autostatus",
  "name": null,
  "canonical_alias": null,
  "joined_members": 0,
  "joined_local_members": 0,
  "version": "9",
  "creator": "@4nt7betogyadycbogtx7be6oweadycbogyade:autostatus",
  "encryption": null,
  "federatable": false,
  "public": "false",
  "join_rules": null,
  "guest_access": null,
  "history_visibility": null,
  "state_events": 1,
  "HasError": false,
  "ErrorCode": null,
  "Error": null
}
```

- When searching for an alias, it does not find
"/_synapse/admin/v1/rooms?search_term={alias}"
```
{"rooms":[],"offset":0,"total_rooms":0,"HasError":false,"ErrorCode":null,"Error":null}
```

- When trying to create a room with such an alias, the error "Room alias already taken"
```
{"HasError":true,"Errcode":"M_ROOM_IN_USE","Error":"Room alias already taken","Retry_after_ms":null}
```

### Homeserver

homeserver

### Synapse Version

{"server_version":"1.63.1","python_version":"3.9.13"}

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

container in swarm

### Relevant log output

```shell
-
```

**Comment by erikjohnston** [comment] 2022-07-29 10:07
Hi, can you share the relevant logs showing these steps please? It sounds like it ought to work fine.

Do you have any plugin modules that might be affecting who is allowed to join a room?

**Comment by RomanOlegovich** [comment] 2022-08-01 02:08
May be connected
https://github.com/matrix-org/synapse/issues/13427

**Comment by RomanOlegovich** [comment] 2022-08-08 01:23
I think reason of this issue [described here](https://github.com/matrix-org/synapse/issues/13427)

**Comment by RomanOlegovich** [comment] 2022-08-08 01:24
I think reason of this issue [described here](https://github.com/matrix-org/synapse/issues/13427) and [here](https://github.com/matrix-org/synapse/issues/8895)

**Comment by H-Shay** [comment] 2022-08-09 22:14
It's pretty impossible to say what is going on without the relevant logs, if you can provide logs that cover the steps to reproduce, we can get a better sense of what is happening and diagnose the issue, including whether it is a duplicate of the issues you mentioned.

**Comment by H-Shay** [comment] 2022-09-20 21:09
I am closing this now as we are unable to investigate this due to a lack of information. If more information becomes available in the future we can re-open it.

**Closed by H-Shay** 2022-09-20 21:09 UTC
Labels: X-Needs-Info

**Comment by RomanOlegovich** [comment] 2022-10-04 05:37
@H-Shay hi, can't share logs but I known this is issue is connected to https://github.com/matrix-org/synapse/issues/13427

**Comment by squahtx** [comment] 2022-10-04 15:09
duplicate of #8895
