### ISSUE TITLE
The user list API search name does not support Chinese search. Enter Chinese and report 400 code

### ISSUE THREAD

**Issue by web-chenke** [matrix-org/synapse#16386] opened 2023-09-26 09:38 UTC
The user list API does not support Chinese search and reports a 400 error after Chinese search. Although the client transcodes the parameters and does not report a 400 error, the name field cannot be searched. English characters can search for data

API address: 
  https://matrix.gptchat.fan/_synapse/admin/v2/users?order_by=creation_ts&dir=b&name=%25E5%25B0%258F%25E8%259C%259C%25E8%259C%2582&isShow=true&deactivated=false&limit=10
  
All three encoding processing methods are invalid：
  encodeURIComponent(chineseText); 
  encodeURI(chineseText);
  escape(chineseText);

**Comment by DMRobertson** [comment] 2023-09-26 10:15
Is this a duplicate of https://github.com/matrix-org/synapse/issues/16370?

**Comment by clokep** [comment] 2023-09-26 11:44
Seems like it.

**Closed by clokep** 2023-09-26 11:44 UTC
