### ISSUE TITLE
Provide notification_count value even when the Notifications Rule has been set to Not Send Notifications

### ISSUE THREAD

**Issue by javierquevedo** [matrix-org/synapse#2597] opened 2017-10-27 11:22 UTC
Riot as well as other clients uses the  `@property (nonatomic, readonly) NSUInteger notificationCount;` to determine how many messages/events have occurred since the last time that the user opened a given room.

To mute a room one would normally remove all push notifications on that particular room. This works ok, but after a room has been muted, by removing push notifications in that room, the notification counter will always mark a 0.

A normal use case is that of a user wanting to mute a room, but still be able to see how many messages he/she hasn't read, however, the current mechanism do not make it possible.

Could we keep on sending the correct notification count on the room sync response, even when the Push Notifications have been disabled?

**Comment by clokep** [comment] 2022-08-05 17:21
This sounds like a duplicate of #2632.

**Closed by clokep** 2022-08-05 17:21 UTC
