### ISSUE TITLE
Deleting a device on one HS apparently doesn't propagate to other HSes

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2680] opened 2017-11-16 09:41 UTC
`<kaiyou> Matthew: when someone deletes devices on one homeserver,
the devices still appear on other hs`

**Comment by richvdh** [comment] 2017-11-16 09:45
https://github.com/vector-im/riot-web/issues/4527 is caused by this

**Comment by kaiyou** [comment] 2017-11-27 21:47
I did spend a couple hours in the past week trying to work on this, sorry I have nothing to report yet. I did not find anything unusual going on when parsing and handling the EDUs, maybe I missed something though.

**Comment by kaiyou** [comment] 2017-11-27 21:47
What I can confirm though: I can reproduce this with two local synapse servers speaking to each other.

**Comment by richvdh** [comment] 2019-07-09 10:51
I think this was fixed by #3520

**Closed by richvdh** 2019-07-09 10:51 UTC
