### ISSUE TITLE
Inexplicable search failures

### ISSUE THREAD

**Issue by grahamperrin** [matrix-org/synapse#6630] opened 2020-01-04 06:43 UTC
Seeking `GetTogether` in https://riot.im/app/#/room/#freenode_#lobsters:matrix.org does not find recently posted https://matrix.to/#/!XMCeiYjoZpFFyvICGb:matrix.org/$15781093891822058UPZrT:matrix.org?via=matrix.org

> i’d heard about https://github.com/GetTogetherComm/GetTogether

> [ GitHub - GetTogetherComm/GetTogether: Event manager for local community events ] - github.com

I see https://github.com/vector-im/riot-web/issues/4486 and #3024 relating to URL strings so I tried an alternative search, for a string that is both in and **not** in the context of the URL: 

`GetTogetherComm/GetTogether`

– again, *No results*.

Third attempt: 

`GetTogetherComm/GetTogether:`

– again, *No results*.

**Comment by richvdh** [comment] 2020-01-09 10:59
The body of this event is:

```
i’d heard about https://github.com/GetTogetherComm/GetTogether
```

(note that the URL preview you're seeing is dynamic; it is not part of the searchable content)

This has been tokenised by the search indexer as:

```
'/gettogethercomm/gettogether':6 'github.com':5 'github.com/gettogethercomm/gettogether':4 'heard':2 'i’d':1
```

Searching for `/GetTogetherComm/GetTogether` will find the event, I think.

I think this is basically a duplicate of #3024.

**Closed** 2020-01-09 11:00 UTC

**Comment by grahamperrin** [comment] 2020-01-09 21:37
Thanks, 

> Searching for `/GetTogetherComm/GetTogether` will find the event, I think.

Nope. 

> (note that the URL preview you're seeing is dynamic; it is not part of the searchable content)

Nope, URL previews were and are disabled: 

![image](https://user-images.githubusercontent.com/192271/72106940-4191bd00-3328-11ea-8b4e-880ebf339fcf.png)

**Comment by richvdh** [comment] 2020-01-09 22:20
oh right, those are two separate events. Do you have the event id for the second one?

**Comment by grahamperrin** [comment] 2020-01-13 21:37
Thanks, does this include the ID? 

https://matrix.to/#/!XMCeiYjoZpFFyvICGb:matrix.org/$15781093891822059tDfem:matrix.org?via=matrix.org&via=cryptonomic.tech

**Comment by richvdh** [comment] 2020-01-15 14:53
```
matrix=> select vector from event_search where event_id='$15781093891822059tDfem:matrix.org';
                                                 vector                                                  
---------------------------------------------------------------------------------------------------------
 'communiti':7 'event':3,8 'gettogethercomm/gettogether':2 'github':1 'github.com':9 'local':6 'manag':4
```
