### ISSUE TITLE
Image thumbnailing doesn't preserve orientation

### ISSUE THREAD

**Issue by ahihi** [matrix-org/synapse#2384] opened 2017-07-25 18:33 UTC
Hi,

When I upload image [1], which has the Exif orientation value of 3 (rotate 180°), the thumbnailed image [2] appears upside down :)

[1] https://omino.foldplop.com/~ahihi/IMG_1190.JPG
[2] https://omino.foldplop.com/~ahihi/MeJGeqvdznHgjTSVIQZYPkbf.jpeg

**Comment by turt2live** [comment] 2017-07-25 18:58
Duplicate of #1261, https://github.com/vector-im/riot-web/issues/1999, and https://github.com/vector-im/riot-web/issues/2059

**Comment by richvdh** [comment] 2019-05-16 18:05
fixed by #5039

**Closed by richvdh** 2019-05-16 18:05 UTC
