### ISSUE TITLE
Make the 'and also log out all my devices' behaviour of password reset optional.

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#6976] opened 2020-02-24 10:21 UTC
Password reset signs out all of your sessions.

The 'password reset' and 'log out all devices' actions do not need to be inseparable. If you suspect your account has been compromised then logging out your other devices is important. In (I think) all other cases it is overkill.

Can we make a backwards-compatible change to the password reset API by adding an optional "and log out all my devices" parameter which defaults to 'true'?

**Comment by richvdh** [comment] 2020-02-24 13:59
Related to #6963, though that seems to be about regular password changes rather than password resets.

**Comment by clokep** [comment] 2020-03-04 21:25
As far as I can tell this is a duplicate of #6963 since the code paths converge into the same password reset flow (i.e you eventually end up at [`/_matrix/client/r0/account/password`](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-account-password)).

Regardless I'll look into this.

**Comment by richvdh** [comment] 2020-03-05 14:41
@neilisfragile to discuss the UX implications of this with @lampholder

**Comment by neilisfragile** [comment] 2020-03-09 16:19
After irl, we want the option to specify via the API but default to the current behaviour. So exactly as @lampholder describes above. 

The idea being that the client can support ' I've been hacked, delete all devices!!!' flow along side a 'oh I just want to update my password' flow.

**Comment by richvdh** [comment] 2020-03-16 22:40
> After irl, we want the option to specify via the API but default to the current behaviour.

the spec changes needed for this are at https://github.com/matrix-org/matrix-doc/pull/2457.

**Comment by clokep** [comment] 2020-03-18 11:51
Done in #7085.

**Closed by clokep** 2020-03-18 11:51 UTC
