### ISSUE TITLE
Initial sync included rooms with no information that I'm apparently not in (legacy/unsupported room versions)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#7209] opened 2020-04-02 18:24 UTC
Trying to get members of the room results in `name: "M_FORBIDDEN", message: "User @travis:t2l.io not in room !oeCrnyfPhvZiruUJLn:sw1v.org, and room previews are disabled"`. This is a test room which I should be in.

The room has no name, and I cannot backfill it. 3 of my rooms appear to be impacted by this. 

`!oeCrnyfPhvZiruUJLn:sw1v.org` has the version `eventid-noslash-test`.
`!VXChyxVNCBsWeSGcaN:sw1v.org` is `state-v2-test` (old internal room).
`!bNAPsppHlSHCDvMRhh:abolivier.bzh` is another test room with a version of `org.matrix.msc2260`

The theme appears to be that Synapse doesn't recognize the room versions anymore, not that the rooms have reset or been left. Synapse should probably exclude these rooms, or somehow support them enough to refuse new messages?

**Comment by clokep** [comment] 2020-04-02 18:42
This sounds like a duplicate of #7083, but with a slightly different failure mode.

**Closed by clokep** 2020-04-02 18:42 UTC
