### ISSUE TITLE
Doesn't back off on backfill if remote server returns 404

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#10689] opened 2021-08-25 09:24 UTC
Synapse 1.40.0 does not seem to back off on backfill failures. My log contains a error every 3 seconds, and it's been doing that for at least 30 minutes.

It's trying to talk to Conduit which currently doesn't implement it yet and returns a 404.

**Comment by callahad** [comment] 2021-09-02 14:46
Also worth linking to Conduit's issue tracker for implementing backfill:

- https://gitlab.com/famedly/conduit/-/issues/44
- https://gitlab.com/famedly/conduit/-/issues/45

@kroeckx Is there any harm here beyond logspam on the Synapse side?

It seems like this would best be tackled as part of https://github.com/matrix-org/synapse/issues/8917, but that's realistically, that's unlikely to get scheduled or completed in the next several months.

**Comment by richvdh** [comment] 2021-12-23 10:59
I think this is essentially a duplicate of #5442

**Closed by richvdh** 2021-12-23 10:59 UTC
Labels: z-federation, T-Enhancement
