### ISSUE TITLE
Complement test `TestPartialStateJoin/State_rejected_incorrectly` is flaky

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13565] opened 2022-08-19 11:08 UTC
https://github.com/matrix-org/synapse/runs/7914130880?check_suite_focus=true

**Comment by richvdh** [comment] 2022-08-26 10:48
Duplicate of https://github.com/matrix-org/synapse/issues/13564

**Closed by richvdh** 2022-08-26 10:48 UTC
Labels: A-Federated-Join, S-Minor, T-Task, Z-Flake, O-Occasional, A-Testing

**Comment by DMRobertson** [comment] 2022-11-10 19:44
Has this resurfaced? https://github.com/matrix-org/synapse/actions/runs/3439617166/jobs/5737176807

(may well be the same failure mode that #13564 describes, I've not dug)
