### ISSUE TITLE
`leave` event (when uninviting users) does not get federated 

### ISSUE THREAD

**Issue by 2chen** [matrix-org/synapse#13633] opened 2022-08-25 18:53 UTC
### Summary 
When a local user invites a remote user to a local private channel and revokes the invite before the remote user has a chance to join, the initial `invite` event gets federated but the subsequent `leave` event does not get federated. This leads to a situation where the remote user sees the channel in their list of channels, but isn't able to join the channel.

### Affected version
1.65 (but also all prior versions)

### Steps to repro
- As user A, create a private channel
- As user A, invite a user from another homeserver to the channel
- As other user, confirm that the channel appears on the second user's list of channels, but do not join the channel
- As user A, uninvite the other user from the channel
- As the other user, there is now a persistent channel that you cannot join (although you can reject the invite)

**Comment by clokep** [comment] 2022-08-25 19:05
Maybe similar to #1563? 🤷

**Comment by richvdh** [comment] 2022-08-26 07:37
Duplicate of #4808

**Closed by richvdh** 2022-08-26 07:37 UTC
Labels: A-Federation, S-Minor, T-Defect, O-Uncommon
