### ISSUE TITLE
There's some regression with the room directory member count

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#7041] opened 2020-03-05 17:53 UTC
Riot keeps getting reports of the room directory being wrong for the member count. Theory is that it's not counting left members, or double counting joins (possibly profile changes?). Most extreme example is a room that has ~2k joined members and the room directory says it is 20k on matrix.org

**Comment by richvdh** [comment] 2020-03-06 10:31
I've noticed it being wildly inaccurate for a long time. I think this is a duplicate of #1294.

**Closed by richvdh** 2020-03-06 10:31 UTC
