### ISSUE TITLE
Can't see old messages in rooms on my private server

### ISSUE THREAD

**Issue by mrlogick** [matrix-org/synapse#12222] opened 2022-03-14 19:10 UTC
(If I use matrix.org, I can create rooms, writing something into them, and new people can join and view old messages.)

I just created my own homesever (with _matrix-docker-ansible-deploy_)
I created a first user and created a group room.
I immediatly checked that this option is selected (with element):
```
Who can read history?
[*] Members only (since the point in time of selecting this option)
```

Then I typed:
_"first message"
"second message"
"third message"_

Then I created a second user. I invited the second user, and joined inside the room.

The problem is that the second user can't see the first three messages. I can only see messages **after** I join.
Do I need to do something with synapse?

**Comment by H-Shay** [comment] 2022-03-14 20:33
Interesting. Can you provide a little bit more info? Specifically, it would be helpful to know the version of synapse that your homeserver is running, and the type of element client (and version) you are using, i.e. element web or desktop, etc.

**Comment by mrlogick** [comment] 2022-03-15 07:33
I'm new to the Matrix ecosystem. The first time that I tried synapse was few months ago on a different hardware; I think it was 1.48 version and I had the same problem. Right now, I found out this project: _matrix-docker-ansible-deploy_ and I wanted to try again. I have the latest version 1.54. I'm on a vps with debian 11. In both times I tried with different clients (element desktop, element web, element for Android, fluffychat desktop, fluffychat for Android). But I never managed to get a room and be able to view old messages. (with the exception of matrix.org). Usually Element tells me: `"You can't see earlier messages"`. With Fluffychat it seems more like I need a key to decrypt the messages, but If I request the keys nothing happens.

**Comment by H-Shay** [comment] 2022-03-15 18:10
It seems that you are using an encrypted room-how clients handle the visibility of message history in an encrypted room prior to joining can be a little opaque. Essentially, you cannot see the messages since you do not have the keys to decrypt them. Were this to be an unencrypted room, the messages would be visible. Sorry that this is a little confusing! Currently there is no way to get the decryption keys for past messages in an encrypted room.

**Comment by mrlogick** [comment] 2022-03-16 00:32
> "there is no way to get the decryption keys for past messages in an encrypted room."


But why I'm able to view past messages with _matrix.org_?
I created an encrypted room with element-web with a first user (registered in matrix.org). Then i join with a second user (registered in matrix.org). As soon as I start writing with the second user I can view past messages (written before the invitation).

**Comment by H-Shay** [comment] 2022-03-16 01:52
Right, I was wrong about not being able to get decryption keys for past events. Out of curiosity, if you switch out of the room in question on the new homeserver into another room and then and switch back, do the messages become visible?

**Comment by mrlogick** [comment] 2022-03-16 03:58
I'm not sure what you mean by switching out and back between rooms. I tried to click everywhere, even logging off with both users. But after few seconds, old messages does always appear. It is enough that use at least one user from matrix.org.
So maybe there is a way to make even my homeserver show past messages?

**Comment by H-Shay** [comment] 2022-03-16 21:20
Sorry I wasn't clear! My question is: on your homeserver, if the first user creates an encrypted room, sets the history visibility to be "members only (from the point in time of selecting this option)" and invites user b, user b joins the room and can't see the messages, if user b then switches to look at another room (you will have to create or join some more rooms to do this) and then switches back to the room in question, are the messages still not visible?

**Comment by mrlogick** [comment] 2022-03-16 23:18
No, using only my own homeserver there's no way: user B cannot see the messages. On Element I always get `"You can't see earlier messages"`. Instead, with fluffychat I can see the "hidden messages": they appear as `"Encrypted"` with a padlock. If I click on one of them, a popup appears: `"Request to read older messages"`. But nothing happens. Even switching out and back between rooms with both users, logging off and re-entering. Past messages never show up.

**Comment by richvdh** [comment] 2022-03-19 17:24
Reading events sent in encrypted rooms before you joined can be finnicky: there are a number of moving parts which have to align.

To be sure you are comparing like with like - are you sure you are using encrypted rooms in both cases? Element web will show a shield in the message composer for an encrypted room:

![image](https://user-images.githubusercontent.com/1389908/159131486-fe138f3a-bdaa-4f89-944d-fb2b9fabed77.png)

If so, logs from your client might help to diagnose the problem. Please could you reproduce the issue as you describe, using Element web, and then click "Submit debug logs" (from Settings -> Help & About), on *both* the client that sent the messages, and the one that is failing to receive them. Refer to this issue when submitting the logs.

**Comment by mrlogick** [comment] 2022-03-21 06:42
I finally understood something. It is not true that between my homeserver and matrix.org there is difference. They behave exactly in the same way.

When I invite user B, while I have an open session (with Element) with the user A, then, as soon as the user B writes, past messages appear, even for user B. (it works if the Element session is still open, if user A don't log out)

Instead, if the user A creates the room, invites user B, and then logout; after that user B does login, accepts the invitation, and writes something, past messages do not appear.

So the problem remains. If I don't keep both sessions open simultaneously (when user B joins and writes), it seems impossible to exchange keys. If user B writes his first message while user A is not connected, it seems impossible to remedy after, even re-logging with user A and B, having both users connected simultaneously.

If you give me another little time, I'll submit some logs.

**Comment by waclaw66** [comment] 2022-03-21 07:27
There had been a discussion with users facing the same problem...
https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$7vrlcgauXtX9DTwc8ytaTm4ags9C-CMb-fRYJdIaSZs?via=matrix.org&via=privacytools.io&via=mozilla.org
I have personally the same problem with room version 6, but 9 is ok. Maybe is depends on length of historyof of the room or the homeserver itself.

**Comment by richvdh** [comment] 2022-03-22 13:15
> if the user A creates the room, invites user B, and then [logs out] and after that user B [logs in], accepts the invitation, and writes something, past messages do not appear.

Right. This sounds like expected behaviour, for encrypted rooms. Since user B has not yet logged in when user A sends the invite, user B has not yet created their cryptographic keys, so there is no way for user A to securely send the decryption keys that user B will need.

**Comment by richvdh** [comment] 2022-03-22 13:19
Possibly the clients could do more to make the situation here clear, so you might consider filing a bug against the clients. If you do so, the authors will appreciate *clear* reproduction steps and screenshots.

I don't think there's anything to be done from the server side, so I'm going to go ahead and close this.

**Closed by richvdh** 2022-03-22 13:19 UTC
Labels: X-Needs-Info

**Comment by mrlogick** [comment] 2022-03-22 17:24
I created _alice_ and _bob_ users.

I logged in with _alice_:
I set up a Secure Backup, generating encryption keys.
I created a room "v9 encrypted room created by alice".
I wrote:
`first message`
`second message`
`third message`
I invited _bob_.
I wrote:
`I just invited bob.`
I made debug logs.
I logged out.

I logged in with _bob_.
I set up Secure Backup, generating encryption keys.
I accepted the invitation.
I wrote:
`first message by bob.`
I made debug logs.
(Now, bob can't see any message from alice.)
I logged out.

Debug log from _alice_
[issue.txt](https://github.com/matrix-org/synapse/files/8326528/issue__alice.txt)
[log-0.log](https://github.com/matrix-org/synapse/files/8326529/log-0__alice.log)

Debug log from _bob_
[issue.txt](https://github.com/matrix-org/synapse/files/8326533/issue__bob.txt)
[log-0.log](https://github.com/matrix-org/synapse/files/8326534/log-0__bob.log)
