### ISSUE TITLE
Spam messages shouldn't be sent to clients

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3649] opened 2018-08-06 00:50 UTC
This is apparently desired behaviour according to the following, however that feels like a mistake. It should probably just not send it to users/appservices.

https://github.com/matrix-org/synapse/blob/f009df23ec711e943d958bb0a0e3185d42d7cc79/synapse/events/spamcheck.py#L34-L36

**Comment by turt2live** [comment] 2018-08-06 15:47
for perspective, this is what is seen in clients (`[e] TravisR` being a remote spammer):

![image](https://user-images.githubusercontent.com/1190097/43726916-b7be3c12-995d-11e8-8390-56e923f26c48.png)

**Comment by neilisfragile** [comment] 2018-08-28 10:41
I've tagged it as a feature even though it is not really (more a change from current expected behaviour) - agreed that blocking all makes most sense UX wise

**Comment by richvdh** [comment] 2022-03-07 11:57
I'm a bit surprised this is still the case. The comment is still present at https://github.com/matrix-org/synapse/blob/0171fa5/synapse/events/spamcheck.py#L248 implying it is, though.

**Comment by H-Shay** [comment] 2022-03-09 18:01
Looking at the code starting here https://github.com/matrix-org/synapse/blob/032688854babeea832cbb4f762fc70fe31e73cc6/synapse/federation/federation_base.py#L101 it appears that we redact and soft-fail spammy events received over federation. My understanding of the spec is that soft-failed events are most likely not passed on to clients (although I think that's an implementation detail?). If this is the case I can change the misleading comment.

**Comment by turt2live** [comment] 2022-03-09 18:09
it is an implementation detail, somewhat surprisingly. Spec has this to say:

> However, servers may choose not to send such events on to their clients, so that end users won’t actually see the events.

**Comment by H-Shay** [comment] 2022-03-10 16:46
Well it looks like up until about 8 months ago Synapse just redacted the events and sent them on. The code to soft-fail the spammy events was added 8 months ago (by Rich, I might add :slightly_smiling_face: ). Either way the comment is definitely wrong and I can fix it, and I think that means we can close this issue as well?

**Comment by richvdh** [comment] 2022-03-10 17:14
yes it is, thank you!

**Closed** 2022-03-10 17:40 UTC
Labels: z-feature
