### ISSUE TITLE
Synapse's performance appears to be limited by how fast it can log

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2703] opened 2017-11-22 16:33 UTC
### Description

This is somewhat empirical evidence based upon observations of how synapse behaves on busy systems. 
In a relatively large-scale test, I ensured the disk was busy while running synapse and noticed transactions and requests timing out. Once the disk wasn't being slaughtered by another process synapse bounced to normal behaviour right away. Slaughtering the disk again did cause synapse to fail again.

Reducing logging and repeating the same test did result in less failures, although some were still present while synapse tried to log a large amount of data. Disabling logging completely allowed synapse to perform almost as though the disk wasn't being used (there was still some impact, but nothing unreasonable). 

I haven't done any testing on this front, but I suspect making the logging async to the server operation would allow for some gains when the disk is under high load or is just slow (like a raspberry pi). To avoid out of order log entries, this would probably end up looking like an in-memory buffer (yay! more memory!) which streams to the disk independently of incoming requests. There's possibly even a way to do this in the python libraries already being used, although I'm not too familiar with them and haven't looked into it much.

### Version information

- **Homeserver**: t2bot.io
- **Version**:        0.25.0 with patches (https://github.com/turt2live/synapse/tree/travis/t2bot.io)
- **Install method**: pip
- **Platform**:       Debian container on an Ubuntu host.

**Comment by richvdh** [comment] 2017-11-27 12:14
This is basically a duplicate of #1727.

**Closed by richvdh** 2017-11-27 12:14 UTC
