### ISSUE TITLE
Postgres error on startup: ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time

### ISSUE THREAD

**Issue by t-aus-m** [matrix-org/synapse#7039] opened 2020-03-04 20:46 UTC
### Description

After upgrading my homeserver to the current versions using docker, postgres is throwing an error that prevents my homeserver from starting.

### Steps to reproduce

- upgrade to current versions
- rebuild container
- show logs

```
db_1       | 2020-03-04 20:19:04.586 UTC [38] ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
db_1       | 2020-03-04 20:19:04.586 UTC [38] HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
db_1       | 2020-03-04 20:19:04.586 UTC [38] STATEMENT:  INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, 50, 64353, 1583366400000, 86400000 FROM room_stats_current WHERE room_id = '!someroom:homeserver.tld' ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes
```
I would expect the server to start properly without any errors.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: llit.eu

<!--
 What version of Synapse is running?
1.10.1, also tested with 1.11.1

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.10.1, also tested with 1.11.1

- **Install method**: docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: docker based an debian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by t-aus-m** [comment] 2020-03-04 22:02
After dumping and restoring the database (without any errors apart from duplicate entries), I now get the following error:
```
db_1       | ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
db_1       | STATEMENT:  INSERT INTO room_stats_current (room_id, completed_delta_stream_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room) VALUES ('!anotherRoom:another.tld', 174991, 0, 0, 0, 0, 0, 0) ON CONFLICT (room_id) DO UPDATE SET completed_delta_stream_id = EXCLUDED.completed_delta_stream_id, current_state_events = EXCLUDED.current_state_events + room_stats_current.current_state_events, joined_members = EXCLUDED.joined_members + room_stats_current.joined_members, invited_members = EXCLUDED.invited_members + room_stats_current.invited_members, left_members = EXCLUDED.left_members + room_stats_current.left_members, banned_members = EXCLUDED.banned_members + room_stats_current.banned_members, local_users_in_room = EXCLUDED.local_users_in_room + room_stats_current.local_users_in_room
```

**Comment by richvdh** [comment] 2020-03-06 10:36
are you sure you correctly recreated the database? looks like your `room_stats_current` table is incorrectly defined.

**Comment by t-aus-m** [comment] 2020-03-06 10:43
All I did was dumping the database using `pg_dumpall`and restoring it by piping it back into the container. So theoretically nothing should be changed there.

How could I check, whether the table is correctly defined?

**Comment by richvdh** [comment] 2020-03-06 10:52
`\d room_stats_current`. `room_id` should be the PRIMARY KEY.

**Comment by t-aus-m** [comment] 2020-03-06 11:11
```
       Table "public.room_stats_current"
          Column           |  Type   | Modifiers 
---------------------------+---------+-----------
 room_id                   | text    | not null
 current_state_events      | integer | not null
 joined_members            | integer | not null
 invited_members           | integer | not null
 left_members              | integer | not null
 banned_members            | integer | not null
 local_users_in_room       | integer | not null
 completed_delta_stream_id | bigint  | not null
```
So `room_id` isn't the primary key.
I tried altering the table to make `room_id` the primary key, but the operation fails:
```
synapse=# alter table room_stats_current add primary key (room_id);
ERROR:  could not create unique index "room_stats_current_pkey"
DETAIL:  Key (room_id)=(!someroom:homeserver.tld) is duplicated.
```
after removing all duplicates I restarted the database. Still throwing an error which now is:
```
db_1       | ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
db_1       | STATEMENT:  INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, 4, 6750, 1583539200000, 86400000 FROM room_stats_current WHERE room_id = '!anotherRoom:anotherhomeserver.tld' ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes
```

**Comment by richvdh** [comment] 2020-03-06 11:18
honestly if you're using an incorrect schema, then something has gone badly wrong and I wouldn't recommend trying to patch it incrementally to make errors go away: you need to fix the underlying problem.

Do you still have the original database? Does it show the same problem? Are you sure your dump/restore process correctly preserved the database schema?

When you upgraded synapse, what were you upgrading from? did you keep a backup from before the upgrade?

**Comment by t-aus-m** [comment] 2020-03-08 10:37
I do still have the original database, from before I did the dumb & restore thing. 
It has the same issues mentioned in my last comment, so that is
```
db_1       | 2020-03-08 10:33:09.304 UTC [35] ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
db_1       | 2020-03-08 10:33:09.304 UTC [35] HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
db_1       | 2020-03-08 10:33:09.304 UTC [35] STATEMENT:  INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, 5, 4515, 1583712000000, 86400000 FROM room_stats_current WHERE room_id = '!CwvRWWOBJwdnMBDIcg:farafin.de' ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes
```
I upgraded synapse from the official images from docker hub, but unfortunately I did not keep any backups.

**Comment by mtippmann** [comment] 2020-03-12 00:42
> All I did was dumping the database using pg_dumpall and restoring it by piping it back into the container. So theoretically nothing should be changed there.

if you did not use `--clean` on `pg_dumpall` and you restored it back into the existing database you'll probably have ton's of duplicated rows - got errors very similiar to yours due making that mistake.

**Comment by t-aus-m** [comment] 2020-03-13 09:12
Thanks for that advise, I did a recheck, what exactly I did and I did use `--clean`

**Comment by richvdh** [comment] 2020-03-17 12:17
can you confirm the schema on the *original* database with `\d room_stats_current`.

**Comment by t-aus-m** [comment] 2020-03-17 13:57
```
synapse=# \d room_stats_current
                  Table "public.room_stats_current"
          Column           |  Type   | Collation | Nullable | Default 
---------------------------+---------+-----------+----------+---------
 room_id                   | text    |           | not null | 
 current_state_events      | integer |           | not null | 
 joined_members            | integer |           | not null | 
 invited_members           | integer |           | not null | 
 left_members              | integer |           | not null | 
 banned_members            | integer |           | not null | 
 local_users_in_room       | integer |           | not null | 
 completed_delta_stream_id | bigint  |           | not null | 
Indexes:
    "room_stats_current_pkey" PRIMARY KEY, btree (room_id)
```
Looks fine to me...

**Comment by richvdh** [comment] 2020-03-17 18:11
ok so there are two problems here:

1) your original database has the `ON CONFLICT DO UPDATE command cannot affect row a second time` error. I don't know what's causing this. Can you share the homeserver logs for the affected period? Can you also check the collation shown by `\l synapse` ?

2) whatever you did to dump and restore the database dropped the indexes, thus causing a whole bunch of new problems and probably didn't fix the original problem. So don't do that.

**Comment by t-aus-m** [comment] 2020-03-17 18:37
So I've set the logs to debug and they are showing this. Everything right before this output does not seem to have anything to do with the error since the room ids were different:
```
synapse_1  | 2020-03-17 19:30:56,472 - synapse.storage.SQL - 193 - DEBUG - stats.notify_new_event-0 - [SQL values] {stats_incremental_total_events_and_bytes-9a} (159886, 175817, -175817, -159886)
synapse_1  | 2020-03-17 19:30:56,800 - synapse.storage.SQL - 207 - DEBUG - stats.notify_new_event-0 - [SQL time] {stats_incremental_total_events_and_bytes-9a} 0.327493 sec
synapse_1  | 2020-03-17 19:30:56,801 - synapse.storage.SQL - 188 - DEBUG - stats.notify_new_event-0 - [SQL] {stats_incremental_total_events_and_bytes-9a} SELECT events.sender, COUNT(*) AS new_events, SUM(OCTET_LENGTH(json)) AS new_bytes FROM events INNER JOIN event_json USING (event_id) WHERE (? < stream_ordering AND stream_ordering <= ?) OR (? <= stream_ordering AND stream_ordering <= ?) GROUP BY events.sender
synapse_1  | 2020-03-17 19:30:56,802 - synapse.storage.SQL - 193 - DEBUG - stats.notify_new_event-0 - [SQL values] {stats_incremental_total_events_and_bytes-9a} (159886, 175817, -175817, -159886)
synapse_1  | 2020-03-17 19:30:57,041 - synapse.storage.SQL - 207 - DEBUG - stats.notify_new_event-0 - [SQL time] {stats_incremental_total_events_and_bytes-9a} 0.238677 sec
synapse_1  | 2020-03-17 19:30:57,050 - synapse.storage.SQL - 188 - DEBUG - stats.notify_new_event-0 - [SQL] {bulk_update_stats_delta-9b} INSERT INTO room_stats_current (room_id, completed_delta_stream_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (room_id) DO UPDATE SET completed_delta_stream_id = EXCLUDED.completed_delta_stream_id, current_state_events = EXCLUDED.current_state_events + room_stats_current.current_state_events, joined_members = EXCLUDED.joined_members + room_stats_current.joined_members, invited_members = EXCLUDED.invited_members + room_stats_current.invited_members, left_members = EXCLUDED.left_members + room_stats_current.left_members, banned_members = EXCLUDED.banned_members + room_stats_current.banned_members, local_users_in_room = EXCLUDED.local_users_in_room + room_stats_current.local_users_in_room
synapse_1  | 2020-03-17 19:30:57,050 - synapse.storage.SQL - 193 - DEBUG - stats.notify_new_event-0 - [SQL values] {bulk_update_stats_delta-9b} ['!room:homeserver.tld', 175817, 4, 10, -1, 2, 0, 0]
synapse_1  | 2020-03-17 19:30:57,054 - synapse.storage.SQL - 207 - DEBUG - stats.notify_new_event-0 - [SQL time] {bulk_update_stats_delta-9b} 0.003757 sec
synapse_1  | 2020-03-17 19:30:57,055 - synapse.storage.SQL - 188 - DEBUG - stats.notify_new_event-0 - [SQL] {bulk_update_stats_delta-9b} INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, ?, ?, ?, ? FROM room_stats_current WHERE room_id = ? ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes
synapse_1  | 2020-03-17 19:30:57,055 - synapse.storage.SQL - 193 - DEBUG - stats.notify_new_event-0 - [SQL values] {bulk_update_stats_delta-9b} [400, 504301, 1584489600000, 86400000, '!room:homeserver.tld']
db_1       | 2020-03-17 18:30:57.061 UTC [35] ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
synapse_1  | 2020-03-17 19:30:57,062 - synapse.storage.SQL - 207 - DEBUG - stats.notify_new_event-0 - [SQL time] {bulk_update_stats_delta-9b} 0.006203 sec
db_1       | 2020-03-17 18:30:57.061 UTC [35] HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
db_1       | 2020-03-17 18:30:57.061 UTC [35] STATEMENT:  INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, 400, 504301, 1584489600000, 86400000 FROM room_stats_current WHERE room_id = '!room:homeserver.tld' ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes
```
Also this:
```
synapse=# \l synapse
                             List of databases
  Name   |  Owner  | Encoding |  Collate   |   Ctype    | Access privileges 
---------+---------+----------+------------+------------+-------------------
 synapse | synapse | UTF8     | en_US.utf8 | en_US.utf8 | 
(1 row)
```

**Comment by richvdh** [comment] 2020-03-17 19:33
right, so I think that the collation is the problem: it looks like you have duplicate entries for `!room:homeserver.tld` in `room_stats_current` which are likely caused by changes to the sorting order in the `en_US` locale. See https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#fixing-incorrect-collate-or-ctype and https://wiki.postgresql.org/wiki/Locale_data_changes.

the solution is indeed to dump and restore the database, but you need to do it in a way that doesn't drop the indexes. Possibly the process you followed before failed due to the duplicate rows, so maybe try removing the duplicates before dumping, or editing the dump file.

I think this is now out of scope for a synapse bug, and is now a general postgres support issue, so I'm going to go ahead and close this.

**Closed by richvdh** 2020-03-17 19:33 UTC
Labels: info-needed

**Comment by t-aus-m** [comment] 2020-03-17 19:36
Gonna test that, thank you very very much!
