### ISSUE TITLE
Federation stops working on specific room after a few days

### ISSUE THREAD

**Issue by symphorien** [matrix-org/synapse#9920] opened 2021-05-02 14:10 UTC
When joining #freenode_#nixos:matrix.org I can receive events for a few days and then I stop receiving events at all.
Around the time of the last message I have this error in the log:
```
        -624| 2021-04-28T16:05:16.773 1356393937161 matrix-synapse.service homeserver[17350] INFO {GET-O-53105} [sumnerevans.com] Request failed: GET matrix://sumnerevans.com/_matrix/federation/v1/state_ids/%21AinLFXQRxTuqNpXyXk%3Amatrix.org?event_id=%241593518478323lehIL%3Ajaccu.se: HttpResponseException('404: Not Found')
         624| 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO Error attempting to resolve state at missing prev_events
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO Traceback (most recent call last):
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 375, in on_receive_pdu
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     await self._get_state_after_missing_prev_event(
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 688, in _get_state_after_missing_prev_event
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     ) = await self.federation_client.get_room_state_ids(
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 346, in get_room_state_ids
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     result = await self.transport_layer.get_room_state_ids(
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 866, in get_json
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     response = await self._send_request_with_optional_trailing_slash(
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 297, in _send_request_with_optional_trailing_slash
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     response = await self._send_request(request, **send_request_args)
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 543, in _send_request
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO     raise exc
            | 2021-04-28T16:05:17.397 1356394561617 matrix-synapse.service homeserver[17350] INFO synapse.api.errors.HttpResponseException: 404: Not Found
         187| 2021-04-28T16:05:17.584 1356394748556 matrix-synapse.service homeserver[17350] INFO Received prev_event $16064195660vschV:arcn.mx failed history check.
         679| 2021-04-28T16:05:18.263 1356395427692 matrix-synapse.service homeserver[17350] INFO {GET-O-53106} [sumnerevans.com] Request failed: GET matrix://sumnerevans.com/_matrix/federation/v1/state_ids/%21AinLFXQRxTuqNpXyXk%3Amatrix.org?event_id=%24161006251170083NfBtY%3Amatrix.org: HttpResponseException('404: Not Found')
         001| 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO Error attempting to resolve state at missing prev_events
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO Traceback (most recent call last):
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 375, in on_receive_pdu
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     await self._get_state_after_missing_prev_event(
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 688, in _get_state_after_missing_prev_event
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     ) = await self.federation_client.get_room_state_ids(
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 346, in get_room_state_ids
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     result = await self.transport_layer.get_room_state_ids(
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 866, in get_json
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     response = await self._send_request_with_optional_trailing_slash(
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 297, in _send_request_with_optional_trailing_slash
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     response = await self._send_request(request, **send_request_args)
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 543, in _send_request
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO     raise exc
            | 2021-04-28T16:05:18.264 1356395428706 matrix-synapse.service homeserver[17350] INFO synapse.api.errors.HttpResponseException: 404: Not Found
         002| 2021-04-28T16:05:18.266 1356395430419 matrix-synapse.service homeserver[17350] INFO Received prev_event $161006256070305jgSKa:matrix.org failed history check.
    1m21s957| 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO Error attempting to resolve state at missing prev_events
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO Traceback (most recent call last):
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 411, in on_receive_pdu
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO     state = [event_map[e] for e in state_map.values()]
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO   File "/nix/store/c337yb18lr52hwhm1ab0jyr672bsn4fx-matrix-synapse-1.32.2/lib/python3.8/site-packages/synapse/handlers/federation.py", line 411, in <listcomp>
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO     state = [event_map[e] for e in state_map.values()]
            | 2021-04-28T16:06:40.223 1356477387651 matrix-synapse.service homeserver[17350] INFO KeyError: '$DB8a8zlc0hvUZz8EZOOWDfhz1KVkqBVlsW6R9RxSOKg:cs.xa0.uk'
         003| 2021-04-28T16:06:40.226 1356477390624 matrix-synapse.service homeserver[17350] INFO Received prev_event $16174673781oKQvZ:arcn.mx failed history check.
         242| 2021-04-28T16:06:40.468 1356477632706 matrix-synapse.service homeserver[17350] INFO Rejecting: failed to fetch 1 prev events: ['$16174673781oKQvZ:arcn.mx']
         002| 2021-04-28T16:06:40.470 1356477634262 matrix-synapse.service homeserver[17350] INFO Error handling PDU $161961850330jzxMH:sumnerevans.com: ERROR 403: Your server isn't divulging details about prev_events referenced in this event.

```
When trying to leave the room, I get the error message "not a known room".

Context: Linux x86_64, NixOS 20.09, synapse 1.32.2
Other rooms (which are way smaller) are unaffected.

**Comment by erikjohnston** [comment] 2021-05-13 10:39
So, those logs are showing that when you receive an event from `sumnerevans.com`  with a missing prev event, its refusing to answer give you the prev events (which it should do). However, I don't think that should stop you from getting messages from other servers.

I wonder whether the room is getting state reset back to before you were joined? It looks to be an old v1 room, where that is a known issue. That would explain why a) servers aren't sending you messages, b) why `sumnerevans.com`  is rejecting your request and c) why your server refuses to let you leave the room (as it thinks you're not in it).

What happens if you try and join the room?

**Comment by symphorien** [comment] 2021-05-13 16:26
> What happens if you try and join the room?

A new error :) (I tried twice)
```
2021-05-13T18:22:57.133 1274900691998 matrix-synapse.service homeserver[28729] INFO {PUT-O-6306} [matrix.org] JSON response exceeded max size 104857600 - PUT matrix://matrix.org/_matrix/federation/v2/send_join/%21AinLFXQRxTuqNpXyXk%3Amatrix.org/%24162092293411DFmcY%3Axlumurb.eu
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Failed to send_join via matrix.org
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Traceback (most recent call last):
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 183, in _handle_json_response
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     body = await make_deferred_yieldable(d)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO synapse.http.client.BodyExceededMaxSize
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO The above exception was the direct cause of the following exception:
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Traceback (most recent call last):
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 517, in _try_destination_list
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     return await callback(destination)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 668, in send_request
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     content = await self._do_send_join(destination, pdu)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 759, in _do_send_join
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     return await self.transport_layer.send_join_v2(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 256, in send_join_v2
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     response = await self.client.put_json(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 759, in put_json
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     body = await _handle_json_response(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 194, in _handle_json_response
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     raise RequestSendFailed(e, can_retry=False) from e
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO synapse.api.errors.RequestSendFailed: Failed to send request: BodyExceededMaxSize:
```


Actually my initial report describes a phenomenon which happened twice. After the first time, I left and joined again, and I only received messages for a few days.

**Comment by NULLx76** [comment] 2021-05-13 21:26
I seem to be getting the exact the same error when also trying to rejoin the `#freenode_#nixos:matrix.org` room:
```
May 13 14:21:41 synapse synapse[8822]: synapse.http.matrixfederationclient: [POST-5986] {PUT-O-6537} [matrix.org] JSON response exceeded max size 104857600 - PUT matrix://matrix.org/_matrix/federation/v2/send>
May 13 14:21:41 synapse synapse[8822]: synapse.federation.federation_client: [POST-5986] Failed to send_join via matrix.org
                                       Traceback (most recent call last):
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 183, in _handle_json_>
                                           body = await make_deferred_yieldable(d)
                                       synapse.http.client.BodyExceededMaxSize

                                       The above exception was the direct cause of the following exception:

                                       Traceback (most recent call last):
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 517, in _try_destina>
                                           return await callback(destination)
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 668, in send_request
                                           content = await self._do_send_join(destination, pdu)
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 759, in _do_send_join
                                           return await self.transport_layer.send_join_v2(
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 256, in send_join_v2
                                           response = await self.client.put_json(
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 759, in put_json
                                           body = await _handle_json_response(
                                         File "/nix/store/3d7ccz31h75p0d3x346l2jd3j1m0hc87-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 194, in _handle_json_>
                                           raise RequestSendFailed(e, can_retry=False) from e
                                       synapse.api.errors.RequestSendFailed: Failed to send request: BodyExceededMaxSize:
```

**Comment by richvdh** [comment] 2021-05-14 09:44
the `BodyExceededMaxSize` error looks like it specific to joining, so a different problem to the original error. Please could one of you open a new issue, with the complete stack trace (it looks like the traces above are truncated).

**Comment by symphorien** [comment] 2021-05-14 11:32
The backtrace is complete to the best of my knowledge, issue opened at https://github.com/matrix-org/synapse/issues/9992

**Comment by richvdh** [comment] 2021-07-22 12:06
it sounds like the original problem got fixed, and the BodyExceededMaxSize error was a duplicate of another issue.

**Closed by richvdh** 2021-07-22 12:06 UTC
Labels: X-Needs-Info
