### ISSUE TITLE
memory leak since 1.53.0

### ISSUE THREAD

**Issue by lchanouha** [matrix-org/synapse#12160] opened 2022-03-04 14:20 UTC
### Description

Since upgrade tomatrix-synapse-py3==1.53.0+focal1 from 1.49.2+bionic1 i observe memory leak on my instance.
The upgrade is concomitant to OS upgrade from Ubuntu bionic => focal / Python 3.6 to 3.8

We didn't change homeserver.yaml during upgrade

Our machine had 3 GB memory for 2 years and now 10G isn't enough.

### Steps to reproduce

root@srv-matrix1:~# systemctl status matrix-synapse.service
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-03-04 10:21:05 CET; 4h 45min ago
    Process: 171067 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homese>
   Main PID: 171075 (python)
      Tasks: 30 (limit: 11811)
     Memory: 6.1G
     CGroup: /system.slice/matrix-synapse.service
             └─171075 /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml ->

![image](https://user-images.githubusercontent.com/16241429/156779898-2fb30028-0c27-4452-8728-01ed6ab9d4cd.png)

I tried to change this config without success
expiry_time: 30m

syslogs says oom killer killed synapse:
Mar  4 10:20:54 XXXX kernel: [174841.111273] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/matrix-synapse.service,task=python,pid=143210,uid=114
Mar  4 10:20:54 srv-matrix1 kernel: [174841.111339] Out of memory: Killed process 143210 (python) total-vm:12564520kB, anon-rss:9073668kB, file-rss:0kB, shmem-rss:0kB, UID:114 pgtables:21244kB oom_score_adj:0

no further usefull information in homeserver.log
### Version information

$ curl http://localhost:8008/_synapse/admin/v1/server_version
{"server_version":"1.53.0","python_version":"3.8.10"}

- **Version**: 1.53.0

- **Install method**:
Ubuntu apt repo

- **Platform**:
VMWare

I could be happy to help getting python stacktrack to debug this, if I have any lead how to do so.

(sorry for my english)

**Comment by reivilibre** [comment] 2022-03-07 14:25
Hi, thanks for your report!

Out of interest, where is this graph from? The units are in K but I assume that's meant to be G.
In any case, `anon-rss:9073668kB` is clear that we're looking at 9+ GB.

Do you happen to have [metrics](https://matrix-org.github.io/synapse/latest/metrics-howto.html) set up? The graphs there would give us some indication as to where the memory is being used.

You could try reducing the cache factor, but if you've only needed 3 GB so far then I'm not sure this would help as it sounds like there's something wrong.

Are you able to downgrade to try a few versions and see which one introduces the problem?
If I understand correctly, you're using the packages.matrix.org repository, so you should be able to downgrade by specifying `apt install matrix-synapse-py3==1.50.0` (for example).
It would be really useful to know which version introduces the problem if possible!

**Comment by lchanouha** [comment] 2022-03-07 23:43
No I can't do via apt because older version are not proposed:
```
# apt-cache policy matrix-synapse-py3
matrix-synapse-py3:
  Installé : 1.53.0+focal1
  Candidat : 1.53.0+focal1
 Table de version :
 *** 1.53.0+focal1 500
        500 https://packages.matrix.org/debian focal/main amd64 Packages
        100 /var/lib/dpkg/status
```
I just downgraded to 1.50.2, let's see if there is still mem leaks.
```
 wget https://packages.matrix.org/debian/pool/main/m/matrix-synapse-py3/matrix-synapse-py3_1.50.2%2Bfocal1_amd64.deb
dpkg -i matrix-synapse-py3_1.50.2+focal1_amd64.deb
```
I will update this issue in few hours.

**Comment by lchanouha** [comment] 2022-03-08 08:11
V1.50.2
I can do one update per day, will continue
![image](https://user-images.githubusercontent.com/16241429/157193992-a674800f-5d5f-48c9-9708-46a550f13409.png)

**Comment by lchanouha** [comment] 2022-03-08 21:32
updated:
![image](https://user-images.githubusercontent.com/16241429/157328371-4a62a2d3-da16-4a94-b937-0c8db77e00ed.png)

1.53.0 service is consuming more than 600M after 22 minutes

**Comment by H-Shay** [comment] 2022-03-08 23:18
I'm not entirely sure if this is related, but the `expiry_time` config flag is now deprecated and should be removed from your config. From the 1.53.0 release notes: "Enable cache time-based expiry by default. The `expiry_time` config flag has been superseded by `expire_caches` and `cache_entry_ttl`." 
If the memory leak is the result of the caches never expiring, removing the deprecated flag from the config and restarting should fix it. Synapse should then expire caches after 30 mins by default, or you can use the new flags to set a different time-to-live for the caches.

**Comment by lchanouha** [comment] 2022-03-09 22:55
![image](https://user-images.githubusercontent.com/16241429/157552620-43f8ae47-1cc2-47e0-afd4-ada266d392f4.png)

tried 1.54.0 with
```
expire_caches: 2m
cache_entry_ttl: 2m
```
i still need rolling back to 1.52

**Comment by H-Shay** [comment] 2022-03-10 00:52
Hi there thanks for getting back to us. One thing: `expire_caches` is a boolean flag, so the only valid values are `true` or `false`. Thus, if you wanted to the ttl on the caches to be 2m, the configuration would be 
```
expire_caches: true
cache_entry_ttl: 2m
```
And just to be crystal clear, the `expiry_time` option needs to be deleted from the config. It seems like something else is probably going on here, but it's good to eliminate what we can.

**Comment by lchanouha** [comment] 2022-03-12 18:03
retried with 1.54.0
```
expire_caches: true
cache_entry_ttl: 2m
````
same problem.
Looks related to (lot of / second) queries done by pantalaimon + maubot client. I stopped them and the memory stopped increasing, but memory weren't freed so I still think there is a memory leak somewhere. Synapse memory usage is back to normal despite memory footprint increases but very slowly now. Our bots were very old (version > 1y),  it could be an old API.

We don't really use our bots so I can stay like that, but this could be problematic one some installations (ore nasty clients) and could be use to do a DOS. 

I can see an error on logs, but i don't think this is related since this error happened on 1.52.0
```
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: 2022-03-12 18:48:25,014 - synapse.http.server - 100 - ERROR - GET-396 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f12201fe340>
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: Traceback (most recent call last):
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     result = current_context.run(gen.send, result)
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: StopIteration: SyncResult(next_batch=StreamToken(room_key=RoomStreamToken(topological=None, stream=445658, instance_map=frozendict.frozendict({})), presence>
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: During handling of the above exception, another exception occurred:
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: Traceback (most recent call last):
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 269, in _async_render_wrapper
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     callback_return = await self._async_render(request)
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 471, in _async_render
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     callback_return = await raw_callback_return
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 219, in on_GET
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     response_content = await self.encode_response(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 794, in _trace_inner
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     return await func(*args, **kwargs)
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 242, in encode_response
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     joined = await self.encode_joined(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 794, in _trace_inner
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     return await func(*args, **kwargs)
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 363, in encode_joined
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     joined[room.room_id] = await self.encode_room(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 558, in encode_room
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     serialized_timeline = serialize(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 532, in serialize
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     return self._event_serializer.serialize_events(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/events/utils.py", line 530, in serialize_events
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     return [
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/events/utils.py", line 531, in <listcomp>
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     self.serialize_event(event, time_now=time_now, **kwargs) for event in events
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/events/utils.py", line 419, in serialize_event
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     self._inject_bundled_aggregations(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/events/utils.py", line 513, in _inject_bundled_aggregations
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]:     serialized_event["unsigned"].setdefault("m.relations", {}).update(
mars 12 18:48:25 srv-matrix1 matrix-synapse[2117]: KeyError: 'unsigned'
````


Louis

**Comment by anoadragon453** [comment] 2022-03-25 14:34
> Looks related to (lot of / second) queries done by pantalaimon + maubot client.

Are these `/sync` queries, or something else? Knowing which endpoint is involved can help us greatly narrow down what might have changed in v1.53.0 to cause this.

**Comment by lchanouha** [comment] 2022-03-31 11:52
yes, maubot is doing a lot of sync queries.
Memleaks looks like proportional with number of queries.

**Comment by lchanouha** [comment] 2022-03-31 12:03
![image](https://user-images.githubusercontent.com/16241429/161050344-5bff6d3d-3077-4f9d-96e3-98e16f402a7c.png)
since 12/03, synapse has grow up to 3,8G of memory

**Comment by squahtx** [comment] 2022-04-07 16:13
@lchanouha I'm guessing the spiky part of the graph from 2022-03-02 to 2022-03-08 is Synapse 1.53/1.54?
Which version of Synapse were you running from 2022-03-13 onwards?

**Comment by squahtx** [comment] 2022-04-07 16:23
It's interesting to see that matrix.org's memory usage also shows a linear rise in memory over time, until restarted:
![image](https://user-images.githubusercontent.com/8349537/162250350-96748bdb-407e-449b-b68c-c6371504263c.png)
We no longer have pre-1.53 data unfortunately.

**Comment by squahtx** [comment] 2022-04-07 17:10
> Are all of matrix.org's cache's configured with time-based expiry?

I think so?

**Comment by squahtx** [comment] 2022-04-07 17:11
There appear to be three caches that are not subject to time-based expiry in Synapse:
* `get_users_in_room`, with a base size of 100,000.
* `get_rooms_for_user_with_stream_ordering`, with a base size of 500,000.
* `get_users_who_share_room_with_user`, with a base size of 500,000.

In the case of matrix.org, `get_rooms_for_user_with_stream_ordering` tends to increase linearly but never hits capacity before a restart.

The only change to these caches that I can see in 1.53 is that we reduced the frequency at which `get_users_in_room` gets cleared (#11878).

@lchanouha Would you be willing to try setting the `per_cache_factors` for these three caches to something small like `0.01` for a couple of day, to see if the memory usage hits a ceiling?

**Comment by lchanouha** [comment] 2022-04-07 22:51
@squahtx that's done, lets see the behaviour next days.
```
per_cache_factors:
  get_users_in_room: 0.01
  get_rooms_for_user_with_stream_ordering: 0.01
  get_users_who_share_room_with_user: 0.01

```
Here is the updated graph, (service was running since Sat 2022-03-12 18:43:33 CET; 3 weeks 5 days ago, v1.54.0) and used 4,1G
![image](https://user-images.githubusercontent.com/16241429/162330915-1f33cc59-b5bb-47ad-99e9-ec1c3ca0fd92.png)

We have 560 users (probably less than 100 active) & 2,8G in /var/lib/postgresql

**Comment by erikjohnston** [comment] 2022-04-13 12:29
We have an experimental option to track the memory usage of caches, though it does add load to the server so I'm not sure its feasible for you to leave it running? If you want to try it then add the following to your config:

```yaml
caches:
    track_memory_usage: true

    # .. rest of the caches config 
```

You'll need to install the `pympler` python library in your virtual env. 

This will add the following Prometheus metric `synapse_util_caches_cache_size_bytes`, which will give the estimated total size of the cache in bytes.

**Comment by H-Shay** [comment] 2022-06-01 19:57
Is this still an issue/has this been resolved?

**Comment by byanes** [comment] 2022-06-01 21:02
We are still seeing this. We upgraded to `1.54.0` a few months ago and we've been having to bounce synapse daily since then.

**Comment by aaronraimist** [comment] 2022-06-02 14:48
@tomsisk I'm not the developer so I don't know if specific changes fixed it but saying "We are still seeing this" while behind 6 versions behind (technically 11 counting patch releases) doesn't seem like a very helpful comment. I would recommend you at least see if the current version improves it and if not then enable https://github.com/matrix-org/synapse/issues/12160#issuecomment-1097993084 and provide more information so they can fix it. (I'm assuming you operating the same server as @byanes?)

Just glancing at the changelog there are several changes that specifically call out reducing memory usage.
https://github.com/matrix-org/synapse/pull/12544
https://github.com/matrix-org/synapse/pull/12656
https://github.com/matrix-org/synapse/pull/12554
https://github.com/matrix-org/synapse/pull/10533

**Comment by tomsisk** [comment] 2022-06-02 15:36
Our last upgrade unleashed a pretty large memory leak so we're not exactly excited to live on the bleeding edge when there isn't a lot of time to commit to this at the moment. You have a point that we haven't done anything, but I think @byanes comment was just so this didn't get blindly closed out as fixed when the actual issue was never diagnosed in the first place. We'll try upgrading and see where that gets us.

**Comment by tomsisk** [comment] 2022-06-06 16:52
Looks like this is still an issue in 0.60.0. I'll try to turn on `track_memory_usage` to see if there's anything helpful there.

**Comment by tomsisk** [comment] 2022-06-10 16:02
Our issue doesn't look related to cache, the cache usage is consistently very low.

![image](https://user-images.githubusercontent.com/3673791/173102890-b821d794-780b-4adb-b793-1735c35df8d4.png)
![image](https://user-images.githubusercontent.com/3673791/173103174-c2e08848-87e1-4e1f-93c0-b7f73e5101eb.png)

**Comment by squahtx** [comment] 2022-07-14 13:22
\> Our issue doesn't look related to cache, the cache usage is consistently very low.

`synapse_util_caches_cache_size_bytes` has a label for each individual cache. Does that chart show the sum over all caches? Those numbers look impossibly low.

**Comment by felixdoerre** [comment] 2022-07-14 21:48
I don't want to hijack this issue, but it looks like we have a very similar memleak pattern (also a few hundred MB per month):
![Screenshot-2022-07-14-23-42-54](https://user-images.githubusercontent.com/10275116/179091513-2b2156ca-282c-4f50-af1f-cdaa6dc19d73.png)
Apart from the used memory (first chart), I've also discovered that the continuous increase seems to be correlated with `synapse_pushers` in our case (second chart). I've also added the requested `synapse_util_caches_cache:size` graphs for all individual caches, those all seem not to be correlated.

**Comment by squahtx** [comment] 2022-07-14 22:18
@felixdoerre Would you be willing to turn on `track_memory_usage` (see https://github.com/matrix-org/synapse/issues/12160#issuecomment-1097993084 for instructions) and get a chart of `synapse_util_caches_cache_size_bytes` instead?

It'd be very useful to see the largest caches by memory usage instead of number of entries.

**Comment by felixdoerre** [comment] 2022-07-14 22:30
Sure, I've enabled that option and now we need to wait a few weeks for a noticeable leak to build up again.

**Comment by tomsisk** [comment] 2022-07-14 23:02
@squahtx We really don't have many users. Here's grouped by label:

![image](https://user-images.githubusercontent.com/3673791/179106249-d0114eab-43be-42c7-9f8e-b21b7cd28e6a.png)

We're bouncing our Synapse container daily again, but it still doesn't look related. The weekends especially have no one using the service and it still burns through memory. If there's any other metrics you'd like to see that you think might be helpful, let me know.

**Comment by squahtx** [comment] 2022-07-14 23:05
> felixdoerre:
> the continuous increase seems to be correlated with `synapse_pushers`

That's an interesting lead. It looks like we start pushers and never stop them unless explicitly deleted by clients. We don't, however, create duplicate pushers for client devices, so the number of pushers ought to be capped by the number of user devices.

Using `pympler`, I went and measured the memory usage of an example iOS pusher and it came out to 4,696 B.
Taking the number of pushers at the peak of the chart, we get 1,000 pushers * ~5,000 B, which comes out to about 5 MB. Which doesn't explain the 100 MB+ in memory usage you're seeing unfortunately.

**Comment by squahtx** [comment] 2022-07-14 23:23
> @squahtx We really don't have many users. Here's grouped by label:
> 
> ![image](https://user-images.githubusercontent.com/3673791/179106249-d0114eab-43be-42c7-9f8e-b21b7cd28e6a.png)
> 
> We're bouncing our Synapse container daily again, but it still doesn't look related. The weekends especially have no one using the service and it still burns through memory. If there's any other metrics you'd like to see that you think might be helpful, let me know.

Thanks, that really does suggest it's not the caches leaking memory. Could you plot the `sum()` over all the labels instead of the `max()`, so we know how much is _not_ accounted for by caches? There are over 100 caches, and if each one grew by 1 MiB, that can add up to 100s of megabytes while not standing out on the chart.

**Comment by tomsisk** [comment] 2022-07-14 23:29
Here you go:

![image](https://user-images.githubusercontent.com/3673791/179117851-fef72312-4d11-4e56-8409-c8c37325f721.png)
![image](https://user-images.githubusercontent.com/3673791/179117822-31e4c74d-f3c0-431c-b797-617ed7685e26.png)

**Comment by squahtx** [comment] 2022-07-14 23:38
Thanks. I don't understand why those values are in the gigabyte range and exceed the previous chart of total memory usage for synapse. What are the raw grafana queries producing each chart?

**Comment by tomsisk** [comment] 2022-07-15 00:31
Good point, wasn't even paying attention. The time grouping was off:

![image](https://user-images.githubusercontent.com/3673791/179123033-be73d90c-f1b9-455a-bcc1-9e8c713315ba.png)
![image](https://user-images.githubusercontent.com/3673791/179123119-31a67fb7-ce8a-478d-af27-8862021a0f0c.png)

**Comment by felixdoerre** [comment] 2022-07-15 06:40
@squahtx 
> That's an interesting lead. It looks like we start pushers and never stop them unless explicitly deleted by clients. We don't, however, create duplicate pushers for client devices, so the number of pushers ought to be capped by the number of user devices.

I am pretty sure we don't have 1000 client devices. We have 5 MAUs with maybe 5 clients each (very likely over-estimated), and thats a factor of 40 more.

**Comment by squahtx** [comment] 2022-07-15 12:28
> @squahtx
> I am pretty sure we don't have 1000 client devices. We have 5 MAUs with maybe 5 clients each (very likely over-estimated), and thats a factor of 40 more.

That's strange then. Could you run the following SQL query to get the exact upper bound on pushers?
```sql
SELECT COUNT(*) FROM pushers;
```

**Comment by squahtx** [comment] 2022-07-15 12:47
@tomsisk Thanks for all the charts. The memory usage building up even during weekends when clients weren't actively using the service proved incredibly insightful.

We've identified two memory leaks in an upstream dependency that would cause memory usage to grow over time as clients `/sync` in the background. Once those are fixed, it'd be great if to get more charts to see if they improve things.

**Comment by felixdoerre** [comment] 2022-07-15 15:40
As I've applied the `track_memory_usage`, the pushers are down now again, and the memory hasn't increased enough in our instance to be able to attribute that again to the pushers, right now we are at 31/11:
![Screenshot-2022-07-15-17-36-05](https://user-images.githubusercontent.com/10275116/179257477-3ed63a18-60ba-4bc2-b51c-8ef2098253d4.png)
And the count shows only 8:
```
# SELECT COUNT(*) FROM pushers;
 count 
-------
     8
(1 row)
```
If the metric and the rows in the table show line up exactly, then they have already diverged now.

**Comment by squahtx** [comment] 2022-07-15 16:28
> As I've applied the `track_memory_usage`, the pushers are down now again, and the memory hasn't increased enough in our instance to be able to attribute that again to the pushers, right now we are at 31/11:
> And the count shows only 8:
> 
> ```
> # SELECT COUNT(*) FROM pushers;
>  count 
> -------
>      8
> (1 row)
> ```
> 
> If the metric and the rows in the table show line up exactly, then they have already diverged now.

After digging deeper, it turns out there's a bug in how Synapse counts pushers for the metric. Whenever the Element mobile apps are launched, they update their pushers on the server using `/pushers/set`. Synapse then goes and replaces the existing pusher and unconditionally increments the metric, even though the net number of pushers has not changed. So that chart is actually tracking the number of times the app has been opened, plus 8.

Thanks for bringing the bug to the attention of the Synapse team. It's being tracked as #13295.

**Comment by squahtx** [comment] 2022-07-21 17:43
> We've identified two memory leaks in an upstream dependency that would cause memory usage to grow over time as clients `/sync` in the background. Once those are fixed, it'd be great to get more charts to see if they improve things.

The fixes for #13282 and #13286 will land in the 1.64.0 Docker image (rc0 on 2022-07-26 and release on 2022-08-02).
For non-Docker deployments, frozendict can be manually upgraded to 2.3.3 to pick up the fixes.

**Comment by squahtx** [comment] 2022-08-02 12:50
The 1.64.0 Docker image has now been released, which includes fixes for the two `/sync` memory leaks.

@tomsisk @felixdoerre Could you upgrade if possible and report back in a few days on whether things have improved?

**Comment by tomsisk** [comment] 2022-08-02 13:16
> @tomsisk @felixdoerre Could you upgrade if possible and report back in a few days on whether things have improved?

We will upgrade later today and let you know.

**Comment by felixdoerre** [comment] 2022-08-02 16:10
![Screenshot-2022-08-02-18-05-03](https://user-images.githubusercontent.com/10275116/182421530-aee69613-4f19-479e-bcdf-333da832b049.png)
We had a very slow memory leak so it might be to early to tell, but it seems to have fixed our memory leak. At the dashed line, we manually upgraded frozendict to 2.3.3. The graph before is included to have something for comparison.

**Comment by tomsisk** [comment] 2022-08-03 15:06
It's too early to tell for us whether this is fixed, mainly because 1.64.0 introduced something new: when presence is enabled, we are seeing mass memory consumption in a very short period. FWIW, we upgraded from 1.60.0.

![image](https://user-images.githubusercontent.com/3673791/182641191-4d3ec1bd-d695-4c7b-a083-98c5bfebb621.png)

The first increase this morning was when users started to come online. The highlighted area is when we disabled presence. I re-enabled just to ensure this was the issue and it consumed over 5G in 10 minutes.

I want to note also that we're using a pretty old version of the JavaScript Client SDK. I don't know if that could be contributing to the extremes we're seeing, but it definitely feels like there was a regression in a recent version.

**Comment by jnthn-b** [comment] 2022-08-30 21:51
Hey, i just want to jump on this issue, i have pretty much the same issue.
Memory (& Swap) getting to nearly 100% then the service getting restarted.
This is the Used Memory Graph from my Monitoring of that VM:
![image](https://user-images.githubusercontent.com/15343360/187549255-d46c4b11-e62a-4783-95f7-5bdaec0c4263.png)
You can see the spikes to full 100% usage pretty clearly, shortly after it gets restarted and the same is happening.


I have played around a bit with the diffrent versions (including the Pre Release that should have fixxed the issue) with no luck. I still have the same issue. For me it only takes about a minute for the Processes to get killed. I have upgraded the VM to 8GB bc i first though 4GB wasnt enough. Currently I am not able to get the Service to run stable.

VM is running Ubuntu 20.04 LTS (Cloud Init - Custom Image), 4 Cores, 8GB RAM - Proxmox Hypervisor (even tho it dont think this really matters)

This is from my homeserver.log:
```2022-08-30 23:46:22,216 - synapse.federation.federation_server - 1365 - INFO - main - Registering federation EDU handler for 'm.device_list_update'
2022-08-30 23:46:22,216 - synapse.federation.federation_server - 1385 - INFO - main - Registering federation query handler for 'profile'
2022-08-30 23:46:22,217 - synapse.federation.federation_server - 1365 - INFO - main - Registering federation EDU handler for 'm.presence'
2022-08-30 23:47:56,033 - root - 343 - WARNING - main - ***** STARTING SERVER *****
2022-08-30 23:47:56,034 - root - 344 - WARNING - main - Server /opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.64.0rc1
2022-08-30 23:47:56,034 - root - 349 - INFO - main - Server hostname: paradisematrix.de
2022-08-30 23:47:56,034 - root - 350 - INFO - main - Instance name: master
2022-08-30 23:47:56,034 - synapse.app.homeserver - 376 - INFO - main - Setting up server```

**Comment by jnthn-b** [comment] 2022-08-30 22:08
I just did an Backup Restore (because the instance isnt in _real_ production). And Version 1.63.1 seems to work for me:
```
Name: matrix-synapse
Version: 1.63.1
```
Memory stays on about 1GB and the instance is running just fine. The Mentiont Package (frozendict) is on Version 2.3.0
```
Name: frozendict
Version: 2.3.0
```
If there is anything i can help to solve this issue, please let me know!

**Comment by erikjohnston** [comment] 2022-08-31 08:40
@jnthn-b Ugh. Do you have presence enabled? If so can you see if you can reproduce it with presence disabled?

**Comment by squahtx** [comment] 2022-08-31 09:41
> ```
> Name: frozendict
> Version: 2.3.0
> ```
> 
> If there is anything i can help to solve this issue, please let me know!

Do note that #13286 and #13282 were fixed by frozendict 2.3.3 and it's best to upgrade it to rule out those known leaks.

**Comment by jnthn-b** [comment] 2022-08-31 09:55
@erikjohnston I will check that later today (hopefully) :)
@squahtx I have upgraded to the rc Version which was supposed to fix this issue, with no luck - I didn't even notice any change in the behavior, the memory leak still accord as hard as before

**Comment by jnthn-b** [comment] 2022-09-03 14:38
@erikjohnston Presence is enabled, i just upgraded the instance to 1.66.0. The Bug seems to be solved for me. I see no more Memory Leaks.
Maybe the Issue was unrelated. But the 2.3.3 Version of frozendict is now installed and its working.

```
Name: frozendict
Version: 2.3.3
```

```
Name: matrix-synapse
Version: 1.66.0
```

**Comment by anoadragon453** [comment] 2022-09-20 10:20
It appears that the affected cases here have been resolved. If people notice similar issues with the latest version of Synapse (presence enabled or no), please file a new issue. Thanks!

**Closed by anoadragon453** 2022-09-20 10:20 UTC
Labels: A-Presence, S-Minor, T-Defect, O-Occasional, A-Memory-Usage

**Comment by DMRobertson** [comment] 2022-09-29 19:09
> It appears that the affected cases here have been resolved. If people notice similar issues with the latest version of Synapse (presence enabled or no), please file a new issue. Thanks!

From the scrollback it doesn't seem like things were resolved for @tomsisk's deployment(s) and we are seeing presence-related memory problems e.g. in #13901.

I notice that there is a new release of frozendict available [which claims to fix more memory leaks](https://github.com/Marco-Sulla/python-frozendict/releases/tag/v2.3.4). @tomsisk: would you be willing to build and test a docker image which includes that release if I make the changes on a branch?

**Comment by tomsisk** [comment] 2022-09-29 19:14
@DMRobertson Sure

**Comment by DMRobertson** [comment] 2022-09-29 21:06
Thanks, let's take this to #13955.
