### ISSUE TITLE
1st User Invited to Room when Online Is Considered as Direct Chat instead of Room 

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#2741] opened 2017-12-20 03:51 UTC
HS: Matrix.org

Using Client : iOS and Android Vanilla Riot

Create Room -> Invite a User who is ONLINE. (Not Minimized or Closed). The first user will get this Room Chat in his/her People Tab instead of Room Tab. The second user onwards will get it in Room Tab. 

This happens both in Android and iOS so I think, this is an API issue in Synapse.

**Comment by turt2live** [comment] 2017-12-20 04:11
Related or possible duplicate of https://github.com/vector-im/riot-web/issues/5402

**Comment by richvdh** [comment] 2018-02-05 13:33
assuming a dup as above

**Closed by richvdh** 2018-02-05 13:33 UTC
