### ISSUE TITLE
'Re-starting finished log context federation_transaction_transmission_loop' frequently appears in logs

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#11434] opened 2021-11-26 11:16 UTC
These log lines appear frequently in my homeserver's logs and seemingly in community members' too.

It's fairly noisy, sounds strange to people who don't know what log contexts are and probably means we're not following log context rules properly.

Otherwise harmless.

```
2021-11-26 11:09:57,205 - synapse.http.matrixfederationclient - 684 - WARNING - federation_transaction_transmission_loop-525651 - {PUT-O-927977} [***.xyz] Request failed: PUT matrix://***.xyz/_matrix/federation/v1/send/1637674882346: HttpResponseExcepti>
2021-11-26 11:09:57,206 - synapse.federation.sender.per_destination_queue - 345 - WARNING - federation_transaction_transmission_loop-525651 - TX [***.xyz] Received 301 response to transaction: 301: Moved Permanently
2021-11-26 11:09:57,211 - synapse.logging.context - 70 - WARNING - federation_transaction_transmission_loop-525651 - Re-starting finished log context federation_transaction_transmission_loop-525651
2021-11-26 11:09:57,212 - synapse.logging.context - 70 - WARNING - federation_transaction_transmission_loop-525651 - Re-starting finished log context federation_transaction_transmission_loop-525651
2021-11-26 11:09:57,212 - synapse.logging.context - 70 - WARNING - federation_transaction_transmission_loop-525651 - Re-starting finished log context federation_transaction_transmission_loop-525651
2021-11-26 11:09:57,212 - synapse.logging.context - 70 - WARNING - federation_transaction_transmission_loop-525651 - Re-starting finished log context federation_transaction_transmission_loop-525651
```

(I'd be surprised if there wasn't an issue already about this, but I didn't dig anything up by searching for the main string...)

**Comment by squahtx** [comment] 2021-11-26 13:14
Duplicate of #10855, the other half of #5604?
When a federation request times out, we don't actually cancel the request which leads to the messages you're seeing.

**Closed by squahtx** 2021-11-26 13:14 UTC
