### ISSUE TITLE
Allow sso logging in with a existed user

### ISSUE THREAD

**Issue by OmmyZhang** [matrix-org/synapse#8155] opened 2020-08-24 15:21 UTC
I enabled sso login after there're already some users, who registered by interacting with a bot to act like sso. (In fact, I have just learned the special trick to using OAuth as OpenID from [here](https://github.com/matrix-org/synapse/blob/5c5516f80ef08dc07c1a7c297614f455c1bc75d4/docs/openid.md) )
So it would be great if there's an option in config to allow sso logging in with a existed user. Now it will show `Error: mapping_error mxid {} is already taken` .

**Comment by clokep** [comment] 2020-08-24 16:01
I thin this is a duplicate of #7633.

**Closed by clokep** 2020-08-24 16:01 UTC
