### ISSUE TITLE
If the only user on a server leaves and rejoins a room, the intervening history is not visible

### ISSUE THREAD

**Issue by sbug-1bit** [matrix-org/synapse#8936] opened 2020-12-14 15:26 UTC
### Description

Missing history for rooms I'm rejoining

### Steps to reproduce

- Join an active room with a user on your homeserver. (As the only user from your homeserver in that room!).
- Stay in the room for a few days to gather some history.
- Leave the room.
- After a few days/a week, rejoin the room.
- Notice how your server feeds you the last events it had in the room before you left it.
It also feeds you new events since you rejoined the room.
However, all events during the time you were not in the room will not be fetched and fed to you by your homeserver.
You will see something like the following:

...
some message
some other message
more messages
you leaving the room
*everything that happend here is missing*
you joining the room (a week later)
new messages since you rejoined
...

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 1bit.se

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
{
    "python_version": "3.7.3",
    "server_version": "1.23.0"
}

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
package from matrix.org for debian
- **Platform**: debian buster
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by violoncelloCH** [comment] 2021-03-19 17:58
the strange thing is that on the initial join, the homeserver correctly fetches history of the room, but it doesn't fetch the intermediate events from in between the user leaving and rejoining

**Comment by richvdh** [comment] 2021-04-30 11:19
unless the room history is set to be publicly-visible, it's deliberate that you cannot see the events in a room while you were not part of that room,

**Comment by violoncelloCH** [comment] 2021-04-30 11:30
@richvdh room history is public (set to "anyone") in the concerned rooms (at least in my case) (happened e.g. in #whatsapp:maunium.net for me)

**Comment by erikjohnston** [comment] 2021-05-20 11:41
Hmm, this is surprising, the server should correctly try and backfill when the user paginates back. It'd be useful to see the servers logs for when the user paginates back to where they should see history.

**Comment by richvdh** [comment] 2021-07-22 12:07
closing this pending the requested info.

**Closed by richvdh** 2021-07-22 12:07 UTC
Labels: S-Minor, T-Defect, X-Needs-Info

**Comment by rom4nik** [comment] 2022-08-13 12:56
I've experienced this today in [#element-community-testing:matrix.org](https://matrix.to/#/#element-community-testing:matrix.org), and reproduced it (with slightly odd results) in a separate room. I can share Synapse debug logs in private ([@przemek:rom4nik.pl](https://matrix.to/#/@przemek:rom4nik.pl)) due to large size, or in public if you give me a hint which parts are most important.

### #element-community-testing
I was in this room in December 2021, then left. Today I joined the room using Nheko, and my history looked like this:

![image](https://user-images.githubusercontent.com/46846000/184494347-23db8537-ef87-4516-83d9-6a2ee8a004c6.png)

At this point I configured Synapse to do debug logging (hopefully not too late!) and restarted it. I launched Element Desktop, and once it became aware of the new room the history looked the same. Scrolling up only loaded older messages from December, clearing cache didn't help.

When I launched Element on Android, once it became aware of new room the history was immediately correctly backfilled with messages from this month. Clearing ED's cache at that point made it get the missing messages from server, while in Nheko I'm still stuck with missing messages.

### separate room

With my Synapse instance set to capture debug logs, I created a new room with user on matrix.org homeserver and invited my user on my server. Remote user sent 3 messages and removed them. I sent a message (1). Remote user sent a few messages (1,2,3), then I left the room. Remote user sent a few more messages (4,5,6,7), then invited me again. Remote user sent a few more messages (8,9).

Here's how clients display it after the rejoin:
#### Nheko
![image](https://user-images.githubusercontent.com/46846000/184494619-07332a31-6781-41ad-954e-30307da7b578.png)

#### Element Desktop
![image](https://user-images.githubusercontent.com/46846000/184494654-3fe1f344-ff04-4697-ab4a-d0925cbd74d8.png)

#### Element Android
![Screenshot_20220813-142953_Element](https://user-images.githubusercontent.com/46846000/184494751-ae68053a-7ca4-42de-a040-3dbd3c57858c.png)

#### Element Web (remote user)
![image](https://user-images.githubusercontent.com/46846000/184494720-406cb182-e9f3-41cc-b901-d10539b58b1d.png)

Interesting things imo:
- EA was closed during this experiment, but this time didn't get messages in correct order
- in this separate room, after rejoin the messages sent while I was gone were placed above all other messages for some reason, I haven't observed this in #element-community-testing

**Comment by DMRobertson** [comment] 2022-08-15 12:30
> I can share Synapse debug logs in private ([@przemek:rom4nik.pl](https://matrix.to/#/@przemek:rom4nik.pl)) due to large size, or in public if you give me a hint which parts are most important.

We'd be looking for the logs pertaining to `/messages` requests from your client.

**Comment by rom4nik** [comment] 2022-09-06 20:42
I've repeated those steps in demo federation of Synapse v1.66.0, here's a HAR file with requests to `/messages` sent by Element Web v1.11.4 after rejoining the room by user2: 
[messages app.element.io_Archive [22-09-06 22-32-46].har.tar.gz](https://github.com/matrix-org/synapse/files/9500545/messages.app.element.io_Archive.22-09-06.22-32-46.har.tar.gz)

Here's message order as seen by user2 after rejoin:
![image](https://user-images.githubusercontent.com/46846000/188733559-48d368c5-7665-49a3-8784-2b8fa40879ba.png)

**Comment by t3chguy** [comment] 2023-09-13 10:30
I seem to have been hit by this

<img width="670" alt="image" src="https://github.com/matrix-org/synapse/assets/2403652/eabacd1e-1978-4c05-9049-fbafad667dba">
<img width="987" alt="image" src="https://github.com/matrix-org/synapse/assets/2403652/fc11893c-ab48-47b9-968e-4df88fef76a1">
