### ISSUE TITLE
Upload limit should not apply over federation

### ISSUE THREAD

**Issue by timokoesters** [matrix-org/synapse#15792] opened 2023-06-17 06:39 UTC
### Description

There's a lot of confusion when a user on server B can't view media from server A. Often it's caused by the upload limit of server B being too low. But why does the upload limit even apply? The server could just stream the media from server A or cache it for a short duration. It's even worse that clients don't show any indication of this error, they are just stuck showing a loading indicator.

### Steps to reproduce

- Upload video on server A
- Try to watch video on server B with lower upload limit

### Homeserver

fachschaften.org

### Synapse Version

1.85.2

**Comment by richvdh** [comment] 2023-06-20 10:10
related/nearly a duplicate of https://github.com/matrix-org/synapse/issues/3918

**Comment by timokoesters** [comment] 2023-06-20 10:14
Ah you're right, I couldn't find that. Unfortunately there hasn't been any update since 2018

**Comment by clokep** [comment] 2023-06-20 11:37
Sounds like there's agreement this is a duplicate.

**Closed by clokep** 2023-06-20 11:37 UTC
Labels: A-Media-Repository, S-Minor, T-Enhancement, O-Occasional

**Comment by MadLittleMods** [comment] 2023-06-28 05:51
Related to https://github.com/matrix-org/synapse/issues/15489
