### ISSUE TITLE
How to disable encryption e2e permanently 

### ISSUE THREAD

**Issue by anilk9096** [matrix-org/synapse#7431] opened 2020-05-06 04:57 UTC
Hi,
Thanks for synapse it was nice. My requirement was internal usage for communication on multiple devices same time . E2E creating lot of problems . Can you please guide me to disable E22 permanently for DIRECT MESSAGES, ROOMS from home server .

Note : I dont need federation

**Comment by babolivier** [comment] 2020-05-06 08:36
Duplicate of https://github.com/matrix-org/synapse/issues/4401

**Closed by babolivier** 2020-05-06 08:36 UTC

**Comment by jamesorose** [comment] 2020-12-15 15:27
+1 for this. I'd love to deploy matrix to my clients, but the regulatory issues with not having chat logs, and the key management issues is a show stopper.

Is the holdup on this feature funding? Is there a bounty/kickstarter or something for this, or does this request conflict so severely with the design goals of the project that it will never be implemented? If the latter, please let us know so we can look for other possible solutions.

Otherwise this is excellent! Thanks!

**Comment by clokep** [comment] 2020-12-15 15:29
This issue is closed, please see #4401.
