### ISSUE TITLE
deleting an alias which points to an empty room doesn't remove it from the room directory

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6735] opened 2020-01-17 21:45 UTC

**Comment by ara4n** [comment] 2020-01-17 21:58
To be precise:
 * Create a room; add an alias; put it in the directory.
 * Leave the room
 * Try to delete the alias - fails
 * Look in room directory; zombie room with 1 user (who isn't even there) is shown; no way to remove it.

**Comment by urielarg** [comment] 2020-01-18 01:09
I can give it a try to this one, writing the test now.

**Comment by richvdh** [comment] 2020-01-20 10:22
> Try to delete the alias - fails

How are you doing this, exactly, given that you're not in the room any more?

**Comment by richvdh** [comment] 2020-01-20 10:23
possibly related to #6346?

**Comment by kewisch** [comment] 2020-01-20 10:32
What I did was to leave the room, I think I even kicked myself. The alias was still on the room and it was in the directory. The room showed up in a "historical" section, going to room settings I couldn't change any of the values or remove it from the directory.

**Comment by urielarg** [comment] 2020-01-22 05:35
I made a unittest calling:
```
PUT directory/room/{new_alias}
POST rooms/{room_id}/leave
DELETE directory/room/{new_alias}
```
and could not reproduce, I'm not sure if it's worth testing in some different env from what `python -m twisted.trial tests` is using, or just wait for more clarification on what the client did to get the error or some logging.

**Comment by richvdh** [comment] 2020-01-23 16:11
yeahh I'm going to close this for lack of info. @ara4n if you can clarify I'll reopen.

**Comment by kewisch** [comment] 2020-02-14 10:39
@ara4n filed this issue on my behalf from feedback on the Mozilla instance. I can't say how it would work on a unit test, but here are the STR:

1) Create public room, give it an alias, put it in the global room directory
2) Potentially have some folks join
3) Kick everyone in the room, including yourself

Results:
* The room cannot be joined again
* The room still has its main alias
* The room still shows up in the room directory, supposedly with one person in it.

Expected:
* The room does not show in the room directory
* (maybe a different issue?) The room alias is automatically freed since the room is empty

Said room #webextensions:mozilla.org is still in the room directory. While writing this I had a hunch, maybe that one person in it is the "moderator" bot that somehow rejoined despite me kicking them. @ara4n can you check if that is the case and possibly remove that room in some way?

**Comment by richvdh** [comment] 2020-02-14 11:30
Right, this caused a brief bit of confusion because `#webextensions:mozilla.org` now points at a different room which has 80ish members and is *not* listed in the room directory. I think I've found the room you are talking about (room id `!xnwCHNqemRUqzMDblH:mozilla.org`, for the record).

The room directory is lying about the one person in the room; the fact that it gets out of sync is tracked at https://github.com/matrix-org/synapse/issues/1294.

I think @urielarg 's assessment of the steps taken here are basically correct:
 * create the room and add it to the directory
 * wait for the room directory to catch up, if need be
 * everybody leaves the room
 * attempt to delete the alias via `DELETE directory/room/{alias}`
 * observe that the room is still listed in the directory with its current name.

That said, I'm still mystified by how @ara4n carried out that `DELETE` operation, given as far as I know the only ways you can do it in riot require you to either be a member of the room (via the room settings), or by shift-clicking in the directory, which removes the room from the directory anyway.

Still, it's an edge case in the room directory which should probably be fixed.

I've now removed `!xnwCHNqemRUqzMDblH:mozilla.org` from the directory (by shift-clicking on it as an admin user.)

**Comment by richvdh** [comment] 2020-02-14 11:36
(the problem here is that once everyone's left the room, we can no longer update the room state, which is used to populate the room directory - from the server's point of view, the "current state" is still as it was when everyone left, with a `canonical_alias` event listing `#webextensions:mozilla.org`. So maybe this is just a special-case of #6346.

Or it could be considered a consequence of #1294: if the room directory correctly tracked that there were zero users in the room, it could hide it.

**Comment by richvdh** [comment] 2020-02-14 12:20
> I've now removed !xnwCHNqemRUqzMDblH:mozilla.org from the directory (by shift-clicking on it as an admin user.)

... and got bitten by https://github.com/vector-im/riot-web/issues/12373, for my troubles.

**Comment by richvdh** [comment] 2022-05-17 10:14
I no longer understand how this is different from #6346, so I'm going to close it as a dup.

**Closed by richvdh** 2022-05-17 10:14 UTC
Labels: z-bug, z-p2
