### ISSUE TITLE
API: v1/join/<room_id_or_alias> fails for room alias

### ISSUE THREAD

**Issue by rht** [matrix-org/synapse#9527] opened 2021-03-02 14:10 UTC
### Description

I discovered this bug while implementing a room join feature for this Matrix admin CLI: https://github.com/JOJ0/synadm/pull/32.
While room id works for joining a user into a room, room alias fails. Probably because `#` is a special character.

### Steps to reproduce

- curl -d '{"user_id": "@user:domain"}'  -H 'Content-Type: application/json' -X POST 'https://matrix.domain/_synapse/admin/v1/join/#testing:domain?access_token=token'
- Got `{"errcode":"M_MISSING_TOKEN","error":"Missing access token"}`

### Version information

- **Homeserver**: own homeserver

If not matrix.org:

- **Version**: {"server_version":"1.27.0","python_version":"3.8.5"}

- **Install method**: apt-get

- **Platform**: Ubuntu

**Comment by rht** [comment] 2021-03-02 14:15
I tried `!testing:domain`, got `{"errcode":"M_UNKNOWN","error":"!testing:domain\\ was not legal room ID or room alias"}`, which was the same type of error I got in https://github.com/JOJ0/synadm/pull/32.

**Comment by dklimpel** [comment] 2021-03-02 14:37
Did you tried to escape the `#` with `%23`.
You can show details of your request with `-v`.
There you can see the request like:
`POST /_synapse/admin/v1/join/%23testing:domain?access_token=token HTTP/2`

**Comment by clokep** [comment] 2021-03-02 14:39
This is a duplicate of #9505. It will be fixed in the next Synapse release.

**Closed by clokep** 2021-03-02 14:39 UTC

**Comment by rht** [comment] 2021-03-03 07:54
I got an internal server error when I tried `%23`. The error in the server log:
```
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 319, in _do_execute
    return func(sql, *args)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/psycopg2/extensions.py", line 121, in getquoted
    pobjs = [adapt(o) for o in self._seq]
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/types.py", line 220, in __iter__
    raise ValueError("Attempted to iterate a %s" % (type(self).__name__,))
ValueError: Attempted to iterate a RoomID
```

**Comment by dharmendrakariya** [comment] 2021-07-27 17:27
any lead here guys? facing same issue ```Could not join room undefined - M_UNKNOWN: undefined was not legal room ID or room alias```
