### ISSUE TITLE
Internal server error when uploading encrypted image with correct mimetype

### ISSUE THREAD

**Issue by ChristianPauly** [matrix-org/synapse#7126] opened 2020-03-23 08:55 UTC
### Description
If the client tries to upload an **encrypted** image with the Content-Type for example "image/jpeg", the server response with "Internal server error". For encrypted images I need to change the Content-Type to "application/octet-stream".

### Steps to reproduce

- Build a fancy Matrix client with file encryption
- Encrypt an image file
- Upload the image with the Content-Type of the unencrypted image mimetype

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
Expected:
The server recognized that the file is encrypted and handles it like a blob and does not respond with an internal server error.

Actual:
Can't upload the image without an internal server error.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: https://famedly.de

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: Can tell you this later today

- **Install method**: Docker, more information will come later today
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian, more information will come later today
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2020-04-02 17:09
@ChristianPauly Is this a client that you're developing?

Taking a look at the [spec for encrypted attachments](https://matrix.org/docs/spec/client_server/r0.6.0#sending-encrypted-attachments) it doesn't seem to specify what the mime type should be in that case.

My guess is that this is breaking when attempting to generate the thumbnail for unknown data, that seems like not great of Synapse. It would be interesting to see the stack trace in the Synapse logs when this happens.

**Comment by clokep** [comment] 2020-04-02 17:27
A bit more thoughts:

* Including the actual content type of encrypted is a metadata leak.
* There isn't a recommendation for what should be used for the content type, but a octet stream is reasonable, `application/x-riot-encrypted` is another idea that came up. It is also possible to not provide a content type.
* The 500 error seems to be a duplicate of #3763 

I'm going to close this as a duplicate, but please shout if this seems different.

**Closed by clokep** 2020-04-02 17:27 UTC
Labels: media-repository
