### ISSUE TITLE
groups rooms GET results in 500

### ISSUE THREAD

**Issue by stoically** [matrix-org/synapse#6974] opened 2020-02-24 06:51 UTC
### Description

Created the community `+containers:mozilla.org` with the account `@stoic:mozilla.org` and now I'm unable to configure it with Riot Web - viewing or trying to edit the community results in an endless spinner. 

The network inspector shows that the request to `https://mozilla.modular.im/_matrix/client/r0/groups/%2Bcontainers%3Amozilla.org/rooms` fails with `500 Internal Server Error` and the response is

```
{"errcode":"M_UNKNOWN","error":"Internal server error"}
```

### Steps to reproduce

- Join `+containers:mozilla.org` with Riot Web

### Version information

- **Homeserver**: mozilla.modular.im
- **Version**: 1.11.0

**Comment by aaronraimist** [comment] 2020-02-24 07:17
Probably a duplicate of https://github.com/matrix-org/synapse/issues/4891

**Closed** 2020-02-24 07:25 UTC
