### ISSUE TITLE
Cannot override rc_joins per user (to create thousands of rooms intentionally)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#9077] opened 2021-01-12 02:15 UTC
Use case: I have a conference bot that wants to create literally thousands of rooms as fast as possible. Currently the `rc_message` limit can be overridden, which is great, but the lack of rate limit is not given to the function which creates the membership event, thus rate limiting `/createRoom`.

It would be great to have an option in the rate limit override table to exclude users from *all* rate limits, including `rc_message` and `rc_joins` in particular.

**Comment by callahad** [comment] 2021-01-13 14:50
@turt2live Can you clarify how urgent this is for supporting FOSDEM?

**Comment by callahad** [comment] 2021-01-13 14:50
(We can rush it if so, but if you have a workaround you're happy enough with, we'd rather defer.)

**Comment by turt2live** [comment] 2021-01-13 15:25
@callahad I'd argue this is critical. The workaround means that it'll take 15-20 hours to create the conference when it should only take 1-2 hours.

**Comment by turt2live** [comment] 2021-01-14 05:11
Through further discussion elsewhere, we can avoid this ratelimit in other ways - we'll do that instead.

This can probably fall into the general backlog rather than be on the task board.

**Comment by richvdh** [comment] 2021-02-08 12:29
I think this is a duplicate of #6286

**Comment by fooness** [comment] 2021-02-19 08:16
> Through further discussion elsewhere, we can avoid this ratelimit in other ways - we'll do that instead.
> 
> This can probably fall into the general backlog rather than be on the task board.

@turt2live Mind sharing how _we can avoid this ratelimit in other ways_?

Thank you!

**Comment by aliceEddie** [comment] 2021-02-20 11:00
> Through further discussion elsewhere, we can avoid this ratelimit in other ways - we'll do that instead.
> 
> This can probably fall into the general backlog rather than be on the task board.

also really interested in how you avoided the ratelimit. Having the same problem.

**Comment by richvdh** [comment] 2021-04-09 17:12
closing as a dup of #6286

**Closed by richvdh** 2021-04-09 17:12 UTC
Labels: z-info-needed
