### ISSUE TITLE
Add option for disable all E2E encription stuff on server side

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#7433] opened 2020-05-06 09:41 UTC
Some organizations needs, that all messages will be available on server side unencrypted, without E2EE. So we need the way to disable all E2EE stuff globally on server side.

Can you provide some option in Synapse config to disable all E2EE features on current server?

**Comment by babolivier** [comment] 2020-05-06 11:07
Duplicate of https://github.com/matrix-org/synapse/issues/4401

**Closed by babolivier** 2020-05-06 11:07 UTC
