### ISSUE TITLE
Support Matrix v1.6 (tracking issue)

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#15451] opened 2023-04-17 14:44 UTC
We seem to have missed the v1.6 release of the Matrix spec.

https://spec.matrix.org/v1.6/

We need to support it fully and then advertise support for it in the client versions.

Work to be done:
- to be researched

Blocks:
- #15449 (because we don't advertise support for v1.6 and we removed the unstable prefixed version of `timestamp_to_event`, this API is currently 'unusable')

**Comment by clokep** [comment] 2023-04-20 12:39
Duplicate of #15089.

**Closed by clokep** 2023-04-20 12:39 UTC
Labels: T-Task
