### ISSUE TITLE
Load custom module with a Docker image

### ISSUE THREAD

**Issue by gauss-lvs-dev** [matrix-org/synapse#14036] opened 2022-10-04 06:12 UTC
Is it possible to load a custom module from an absolute location?

Initially I installed Synapse with the apt repository and placed my custom python module in /opt/venvs/matrix-synapse/lib/python3.8/site-packages. I was able to load the module with:

```
modules:
  - module: custom_event_rules.MyRules
```

Recently I used the Docker image to install Synapse on a different server. Unfortunatly I was not able to manage to load a custom module with the Docker image. I placed the file in the Docker volume folder and modifed the homeserver.yaml like this:

```
modules:
  - module: /data/custom_event_rules.MyRules
```

The documentation states:

> Each module is defined by a path to a Python class as well as a configuration. This information for a given module should be available in the module's own documentation.

[https://matrix-org.github.io/synapse/latest/modules/index.html](https://matrix-org.github.io/synapse/latest/modules/index.html)

Maybe I am missunderstanding the documentation.

Kind regards!

**Comment by clokep** [comment] 2022-10-04 11:11
I think this is pretty much a duplicate of #9944.

**Comment by clokep** [comment] 2022-10-04 11:11
(That being said -- if you have ideas of how to solve this, please let us know in #9944!)

**Closed by clokep** 2022-10-04 11:11 UTC
