### ISSUE TITLE
remove_devices_from_device_inbox using a ton of IO, huge spike in load

### ISSUE THREAD

**Issue by finned-palmer** [matrix-org/synapse#11929] opened 2022-02-07 19:43 UTC
### Description

Synapse seems to be using a ton of IO for the past few days. I assume it's caused by this background process failing:

```
2022-02-07 19:38:33,769 - synapse.storage.txn - 616 - WARNING - background_updates-0 - [TXN OPERROR] {_remove_devices_from_device_inbox_txn-1186} could not read block 113271 in file "base/18090/18236": Input/output error
 5/5
2022-02-07 19:38:33,771 - synapse.storage.background_updates - 269 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 267, in run_background_updates
    result = await self.do_next_background_update(sleep)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 391, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 434, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/deviceinbox.py", line 717, in _remove_dead_devices_from_device_inbox
    finished = await self.db_pool.runInteraction(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 741, in runInteraction
    result = await self.runWithConnection(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 846, in runWithConnection
    return await make_deferred_yieldable(
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
    raise exception.with_traceback(traceback)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 841, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 609, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/deviceinbox.py", line 704, in _remove_dead_devices_from_device_inbox_txn
    txn.execute(sql, (start, stop))
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 310, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 343, in _do_execute
    return func(sql, *args)
psycopg2.errors.IoError: could not read block 113271 in file "base/18090/18236": Input/output error
```

### Version information

- **Homeserver**

If not matrix.org:

- **Version**: 1.51

- **Install method**:
Docker hub image.

- **Platform**:

Arch linux.

**Comment by richvdh** [comment] 2022-02-07 19:46
> psycopg2.errors.IoError: could not read block 113271 in file "base/18090/18236": Input/output error

sounds like postgres can't read from your disk. I hope you've got a backup.

**Comment by babolivier** [comment] 2022-02-08 13:42
As @richvdh points out, it looks like the root cause of your issue is PostgreSQL not being able to read from your disk. Since it looks like this is an issue with your host and not Synapse, I'm closing this issue.

**Closed by babolivier** 2022-02-08 13:42 UTC
