### ISSUE TITLE
Upgrade to synapse-1.27.0 fails

### ISSUE THREAD

**Issue by michaelschefczyk** [matrix-org/synapse#9455] opened 2021-02-20 16:17 UTC
Running docker container locally on Debian Buster on Pcengines APU2 hardware did work well until synapse-1.26.0. Upgrading to synapse-1.27.0 led to the following error for which I did not find documentation or upgrade hints:

2021-02-20 09:10:02,153 - synapse.metrics.background_process_metrics - 210 - ERROR - user_directory.notify_new_event-8- Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 110, in process
    await self._unsafe_process()
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 158, in _unsafe_process
    max_pos, deltas = await self.store.get_current_state_deltas(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/state_deltas.py", line 51, in get_current_state_deltas
    prev_stream_id = int(prev_stream_id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Can someone who knows how to resolve this please be so kind to share some insight?

Regards,

Michael Schefczyk

**Comment by dklimpel** [comment] 2021-02-20 21:48
See also: #9420
It is a duplicate.

**Comment by clokep** [comment] 2021-02-22 12:40
Yes, this is a duplicate of #9420, there seems to be a workaround at https://github.com/matrix-org/synapse/issues/9420#issuecomment-780571049, but this will be fixed in v1.28.0.

**Closed by clokep** 2021-02-22 12:40 UTC
