### ISSUE TITLE
Room upgrades can carry over weird state from previous version

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6438] opened 2019-11-29 00:06 UTC
I had been accidentally banned from the original `#matrix:matrix.org` (`!QtykxKocfZaZOUrTwp:matrix.org`) several months ago. I had tried to get back in after being unbanned which never really worked. I would maybe get in for a day or two and then get state reset back out of it.

After the room was upgraded (`!OGEhHVWSdvArJzumhm:matrix.org`) I was able to join initially and I thought it was working but after a few days I just stopped getting messages in the room. I checked on another account (`@aaron:kde.org`) and the room was getting new messages. I left and rejoined `#matrix:matrix.org` which seemed to work again for a few days but then I again stopped getting new messages. From `@aaron:kde.org`'s perspective I was banned from the new room.

Currently I am in the room but I can't see any messages and messages I send don't seem to be received by kde.org or matrix.org.

![Screen Shot 2019-11-28 at 5 59 56 PM](https://user-images.githubusercontent.com/5855073/69835660-e50b9000-1208-11ea-847a-583d3eac71ea.png)

**Comment by aaronraimist** [comment] 2019-11-29 00:07
Ok I just left again and used the purge room admin API and I seem to be back in the room. Let's see if it happens again.

**Comment by aaronraimist** [comment] 2019-12-03 00:00
Yep it happened again. Is this a state reset?

From `@aaron:kde.org` it looks like I am banned and the most recent message I received in the room is from Nov 30th.

![Screen Shot 2019-12-02 at 5 58 32 PM](https://user-images.githubusercontent.com/5855073/70004850-5c089780-152d-11ea-94fa-53b718233ab4.png)

**Comment by richvdh** [comment] 2019-12-03 11:31
the ban was copied over from the old room. the upgrade process just copies the state of the room at the point of the upgrade: it so happened that state resets had led to your ban being active at that point.

I've now unbanned your account.

The mystery here is why it appeared that you were able to join the upgraded room despite the ban being in place.

**Comment by aaronraimist** [comment] 2019-12-10 23:16
I appear to be banned again?

![Screen Shot 2019-12-10 at 5 15 17 PM](https://user-images.githubusercontent.com/5855073/70577334-b11d5c80-1b70-11ea-8189-093aa0302e08.png)
![Screen Shot 2019-12-10 at 4 41 49 PM](https://user-images.githubusercontent.com/5855073/70576171-d65c9b80-1b6d-11ea-8301-4017444e8d5a.png)

**Comment by richvdh** [comment] 2019-12-11 11:49
well, that is a sad situation. I've opened #6520 to track it.

**Comment by richvdh** [comment] 2019-12-11 11:49
meanwhile, I think that the room upgrade process is working as intended, so I'm going to close this.

**Closed by richvdh** 2019-12-11 11:49 UTC
Labels: bug, p2, room-upgrade-2019
