### ISSUE TITLE
Stuck invite - Tell Matthew to fix Matrix

### ISSUE THREAD

**Issue by SWW13** [matrix-org/synapse#7355] opened 2020-04-27 13:55 UTC
### Description

After receiving a broken invite and rejecting it, the invite persists in the riot webclient.
Only whiping the cache solves the issue, which isn't a great workflow for rejecting an invite.

### Steps to reproduce

- Wait for broken invite
- Understand the hate someone else has with matrix after having the same problem
- Open issue here

I'm expecting a chat software that works, or at least have a decent why to fix itself.
Something like "clear cache" would be nice if the software itself is broken on a regular basis.

Here is btw the debug console log:
```
Switching to room id !HfiOiEJJbHoCPJEnCP:bau-ha.us at event undefined
RVS update: !HfiOiEJJbHoCPJEnCP:bau-ha.us undefined loading? false joining? false initial? true shouldPeek? true
Returning cached capabilities
Starting watcher for hideReadReceipts@<null room> as ID 1587994746578_20_hideReadReceipts_null
Ending watcher ID 1587994743544_17_hideReadReceipts_null
Ending watcher ID 1587994743605_19_showTypingNotifications_null
Ending watcher ID 1587994743566_18_MessageComposerInput.autoReplaceEmoji_null
newscreen room/!HfiOiEJJbHoCPJEnCP:bau-ha.us
Room undefined does not have an m.room.create event
[!HfiOiEJJbHoCPJEnCP:bau-ha.us] Current version: 1
[!HfiOiEJJbHoCPJEnCP:bau-ha.us] Version capability:  
Object { default: "5", available: {…} }
!! Room !HfiOiEJJbHoCPJEnCP:bau-ha.us nearly lost: Ran off the end of im.vector.fake.invite
!! Inserting at position 0 with category idle
Switching to room id !OTXoQxlEOLgpfSENoS:bau-ha.us at event undefined
RVS update: !OTXoQxlEOLgpfSENoS:bau-ha.us undefined loading? false joining? false initial? true shouldPeek? true
Returning cached capabilities
Starting watcher for hideReadReceipts@<null room> as ID 1587994749500_21_hideReadReceipts_null
Ending watcher ID 1587994746578_20_hideReadReceipts_null
newscreen room/!OTXoQxlEOLgpfSENoS:bau-ha.us
Room undefined does not have an m.room.create event
[!OTXoQxlEOLgpfSENoS:bau-ha.us] Current version: 1
[!OTXoQxlEOLgpfSENoS:bau-ha.us] Version capability:  
Object { default: "5", available: {…} }
```

### Version information

- **Homeserver**:
matrix.brn.li

- **Version**:
```
{
    "python_version": "3.8.2",
    "server_version": "1.11.0"
}
```

- **Install method**:
Arch Linux community repo.

- **Platform**:
Arch Linux

**Comment by neilisfragile** [comment] 2020-04-27 14:20
Dupe of #2181

**Closed by neilisfragile** 2020-04-27 14:20 UTC

**Comment by SWW13** [comment] 2020-04-27 14:27
For my future self and other, current workaround: https://github.com/matrix-org/synapse/issues/2181#issuecomment-597258045
