### ISSUE TITLE
Email matching for invitations is case-sensitive

### ISSUE THREAD

**Issue by abliss** [matrix-org/synapse#8522] opened 2020-10-12 12:51 UTC
### Description
When inviting someone to a channel by email, the email is matched case-sensitively. It should be case insensitive.

### Steps to reproduce

- Create a private channel
- Invite with email a new user who has never used matrix. Use a capital letter in the email address, like `User@example.com`
- The new user receives the email and tries to log in, but uses an all-lowerecase email, like `user@example.com`

Expected: User should be able to log in.
Actual : User is denied with a message like: "This invite to this room was sent to User@example.com which is not associated with your account"
### Version information

- **Homeserver**: matrix.org (using the riot.im frontend)

**Comment by dklimpel** [comment] 2020-10-12 13:27
It is related to #7021 and #7016

**Comment by Vetchu** [comment] 2022-06-15 12:17
@MadLittleMods care to take a look and close this issue if this is no longer a problem? I'd submit a fix, but I cannot reproduce it on matrix.org

**Comment by DMRobertson** [comment] 2022-06-15 13:58
> I invited my other email starting with capital letter, during process of registration I used all lowercase and it worked like a charm.

To clarify:
- were you able to register a new account using the all-lowercase address?
- when logged in to that new account, did the client show the invite you made before?

**Comment by Vetchu** [comment] 2022-06-15 15:21
Yes, I followed this procedure:
* from exisiting account I invited User@domain.com
* I got an email on user@domain.com
* I created account user@domain.com
* on first login, I was shown the prompt to join room and joined the room without problem

I think this reproduces the thinking presented in OP, and it does not produce an error anymore. I can reproduce with screenshots if needed.

**Closed** 2022-06-15 15:23 UTC
Labels: z-bug, Z-Help-Wanted, z-p3, T-Defect, A-Invite
