### ISSUE TITLE
user can't log in anymore

### ISSUE THREAD

**Issue by mr-teaser** [matrix-org/synapse#8134] opened 2020-08-19 19:53 UTC
It happened out of the blue and i cannot log in anymore with my regular user on my homeserver.
It does not matter if I use the app or the browser after signing in an endless loop is starting for the sync process. When I reload the browsers I get a message "Cannot connect to homeserver. Retrying..."

In the logfile I can see errors like:

synapse.http.server - 84 - ERROR - GET-5265 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f4f3df6eba8 method='GET' uri='/_matrix/client/r0/sync?filter=5&timeout=0' clientproto=

It just happens with this one particular (frequently used) user.

I tried to change the password on the commandline, but apparently it is still accepting the old one.

The user account seems broken.
Any idea what's going on here and how to fix it?

I am using postgre by the way and did an update today. I was hoping to solve it that way.

Thanks in advance.

**Comment by clokep** [comment] 2020-08-19 19:58
@mr-teaser Are there any useful logs around that line? If you don't have INFO logging on please enable it. Hopefully somewhere it says what the actual error is. (Also the log line above seems cut-off at the end.)

**Comment by mr-teaser** [comment] 2020-08-19 20:10
Well, yes there are plenty of more lines in the log:

2020-08-19 20:06:48,497 - synapse.access.http.8008 - 311 - INFO - GET-7618 - 190.237.61.122 - 8008 - {None} Processed request: 0.000sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 142B 200 "GET /_matrix/client/versions HTTP/1.0" "Mozilla/5.0 (Windows NT 6.1; rv:79.0) Gecko/20100101 Firefox/79.0" [0 dbevts]
2020-08-19 20:06:49,091 - root - 110 - WARNING - GET-7620 - Tried to decode ''\\x7b22617574685f6576656e7473223a5b5b222431353238373330313038373738333769614565533a6d61747269782e6f7267222c7b22736861323536223a2246616461494345625055313143466543384e6c76414e4851646b76694c715237523364674c513774456c45227d5d2c5b222431353631323437353537333383438386c6775687a3a6d61747269782e6f7267222c7b22736861323536223a22386c69794472487270525356536134575534636d713546735333732b49575830426467324d425a4a575751227d5d2c5b22243135353631333739373232335541624f6b3a737731762e6f7267222c7b22736861323536223a2235373168707261364f6f38657a5649363768386457726e4172516962485a61456d686d72385678692f3351227d5d5d2c22636f6e74656e74223a7b7d2c226465707468223a3134363933392c226576656e745f6964223a2224313336303234313536333934737167495a3a6d61747269782e6f7267222c22686173686573223a7b22736861323536223a227152435a4c6555354749555669457a5537686a342b522f442f7857546d526649727a484133507462554e73227d2c226f726967696e223a226d61747269782e6f7267222c226f726967696e5f7365727665725f7473223a313536313433363032343139302c22707265765f6576656e7473223a5b5b2224313536313433353532323336393231394f515479713a6d61747269782e6f7267222c7b22736861323536223a225861767a6665782f4e58427736354a4e59702f456c5a77384646476a31646164426d746558494f3539796b227d5d5d2c22707265765f7374617465223a5b5d2c22726f6f6d5f6964223a22215174796b784b6f63665a615a4f55725477703a6d61747269782e6f7267222c2273656e646572223a2240646973706f7361626c653a6d61747269782e6f7267222c227369676e61746573223a7b226d61747269782e6f7267223a7b22656432353531393a6175746f223a224e6139327a7970737a3951496a6a46367969663364656c7133495a48386c54762f6b322f3946436930597865696c784c7633633062555759616b445832763161556852427371634e665a434a2b4e7a53627334464141227d7d2c2273746174655f6b6579223a2276466972484e637768576362597459786f414b636161504562466641456643736658546669736e6b4d6b4e6e42614b674b68724d454c7a55477266446463575444575548796d6d757a534e4e4276644d626a6a5774647474414a57524b767276577774636765586b5a664a44636961777776537372454c614e6c41765a497a65222c2274797065223a226d2e726f6f6d2e74686972645f70617274795f696e76697465222c22756e7369676e6564223a7b7d7d'' as JSON and failed
2020-08-19 20:06:49,093 - synapse.http.server - 84 - ERROR - GET-7620 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7fe4495e8780 method='GET' uri='/_matrix/client/r0/sync?filter=6&timeout=0&_cacheBuster=1597867608601' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$15614391673301Pwaun:matrix.org': {'event_id': '$15614391673301Pwaun:matrix.org', 'internal_metadata': '{"outlier": false, "stream_ordering": 136640}', 'json': '{"depth": 146945, "event_id": "$15614391673301Pwaun:matrix.org", "room_id": "!QtykxKocfZaZOUrTwp:matrix.org", "prev_state": [], "prev_events": [["$1561439160164379PFzrc:matrix.org", {"sha256": "nrjiK15K6YaUw40i8ku0rMRMeON/8EeqriEAI4DhYqs"}]], "content": {}, "sender": "@disposable:matrix.org", "hashes": {"sha256": "1GW1uGlzvV5SIIWlYR4pGuY1nNQAmqoK5fTGXegsm4Q"}, "origin": "matrix.org", "type": "m.room.redaction", "redacts": "$1561436024156394sqgIZ:matrix.org", "origin_server_ts": 1561439167632, "auth_events": [["$152873010877837iaEeS:matrix.org", {"sha256": "FadaICEbPU11CFeC8NlvANHQdkviLqR7R3dgLQ7tElE"}], ["$155613797223UAbOk:sw1v.org", {"sha256": "571hpra6Oo8ezVI67h8dWrnArQibHZaEmhmr8Vxi/3Q"}], ["$1561247557398488lguhz:matrix.org", {"sha256": "8liyDrHrpRSVSa4WU4cmq5FsS3s+IWX0Bdg2MBZJWWQ"}]], "signatures": {"matrix.org": {"ed25519:auto": "kKWkeeYFKcuLyaFjDNKQIm47QgaX4PVFHmDc1n8CINiwKlDzxR7kD2VHpST7lhjURHbNGgwpf5VI54OenfXUDQ"}}, "unsigned": {"age": 313927}}', 'format_version': 1, 'room_version_id': '1', 'rejected_reason': None, 'redactions': []}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 311, in _wait_for_sync_for_user
    sync_config, since_token, full_state=full_state
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 342, in current_sync_for_user
    return await self.generate_sync_result(sync_config, since_token, full_state)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 999, in generate_sync_result
    sync_result_builder, account_data_by_room
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 1430, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/async_helpers.py", line 157, in _concurrently_execute_inner
    await maybe_awaitable(func(next(it)))
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 1425, in handle_room_entries
    always_include=sync_result_builder.full_state,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 1861, in _generate_room_entry
    room_id, batch, sync_config, since_token, now_token, full_state=full_state
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/sync.py", line 921, in compute_state_delta
    state = await self.store.get_events(list(state_ids.values()))
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/databases/main/events_worker.py", line 265, in get_events
    allow_rejected=allow_rejected,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/databases/main/events_worker.py", line 310, in get_events_as_list
    set(event_ids), allow_rejected=allow_rejected
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/databases/main/events_worker.py", line 457, in _get_events_from_cache_or_db
    missing_events_ids, allow_rejected=allow_rejected
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/databases/main/events_worker.py", line 613, in _get_events_from_db
    d = db_to_json(row["json"])
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 108, in db_to_json
    return json.loads(db_content)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by babolivier** [comment] 2020-08-26 15:56
It looks like this was caused by an event being badly stored by a previous version of Synapse. This should be fixed now (i.e. it might happen for old enough instances but it shouldn't be such an issue that it's going to pop up twice a day). If this comes up in the future we should be able to help out on a case by case basis.
I'm going to close this since your specific issue is fixed, sorry for taking a few days to get back to you!

**Closed by babolivier** 2020-08-26 15:56 UTC
Labels: info-needed
