### ISSUE TITLE
user_may_invite in spam checker leads to 404 / M_UNKNOWN when rejecting invite

### ISSUE THREAD

**Issue by WebFreak001** [matrix-org/synapse#6762] opened 2020-01-22 11:18 UTC
### Description

I have an anti spam plugin which simply returns `False` in `user_may_invite` when the inviter_user_id or room_id ends with a given room string or is equal to a user string.

Now I still have an active invite which I want to reject, however when I try to reject it and the /leave endpoint is called on the room, it results in

```json
{"errcode":"M_UNKNOWN","error":"Not a known room"}
```

### Steps to reproduce

- invite a user to a room
- block the room in an anti spam plugin so that the invite wouldn't be valid anymore (return `False` in `user_may_invite`)
- see that the invite is still there and rejecting it gives the M_UNKNOWN error so it stays in the list

Screenshots in riot:

![invite list with bad server in riot](https://wfr.moe/f6G9f2.png)

resulting in

![error dialog saying not a valid room](https://wfr.moe/f6GTA7.png)

It seems that it results in an internal server error on the remote, causing it to fail:

```
(local log)

2020-01-22 11:50:03,939 - synapse.access.https.8448 - 233 - INFO - OPTIONS-31 - ::ffff:addr - 8448 - Received request: OPTIONS /_matrix/client/r0/rooms/!room_id%3Aremote/leave
2020-01-22 11:50:03,942 - synapse.access.https.8448 - 302 - INFO - OPTIONS-31 - ::ffff:addr - 8448 - {None} Processed request: 0.001sec/0.001sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "OPTIONS /_matrix/client/r0/rooms/!room_id%3Aremote/leave HTTP/1.1" "UserAgent" [0 dbevts]
2020-01-22 11:50:04,009 - synapse.access.https.8448 - 233 - INFO - POST-32 - ::ffff:addr - 8448 - Received request: POST /_matrix/client/r0/rooms/!room_id%3Aremote/leave
2020-01-22 11:50:04,096 - synapse.http.matrixfederationclient - 408 - INFO - POST-32 - {GET-O-3} [remote] Sending request: GET matrix://remote/_matrix/federation/v1/make_leave/%21room_id%3Aremote/%40user%3Alocal; timeout 20.000000s
2020-01-22 11:50:04,097 - synapse.http.federation.well_known_resolver - 234 - INFO - POST-32 - Fetching https://remote/.well-known/matrix/server
2020-01-22 11:50:04,463 - synapse.http.federation.well_known_resolver - 178 - INFO - POST-32 - Response from .well-known: {'m.server': 'matrix.remote:443'}
2020-01-22 11:50:04,464 - synapse.http.federation.matrix_federation_agent - 242 - INFO - POST-32 - Connecting to matrix.remote:443
2020-01-22 11:50:04,842 - synapse.http.matrixfederationclient - 440 - INFO - POST-32 - {GET-O-3} [remote] Got response headers: 500 Internal Server Error
2020-01-22 11:50:04,842 - synapse.http.matrixfederationclient - 522 - WARNING - POST-32 - {GET-O-3} [remote] Request failed: GET matrix://remote/_matrix/federation/v1/make_leave/%21room_id%3Aremote/%40user%3Alocal: HttpResponseException("500: b'Internal Server Error'")
2020-01-22 11:50:04,843 - synapse.federation.federation_client - 397 - WARNING - POST-32 - Failed to make_leave via remote: 500 500: b'Internal Server Error'
2020-01-22 11:50:04,843 - synapse.handlers.room_member - 996 - WARNING - POST-32 - Failed to reject invite: 502: Failed to make_leave via any server
2020-01-22 11:50:04,877 - synapse.access.https.8448 - 302 - INFO - POST-32 - ::ffff:addr - 8448 - {@user:local} Processed request: 0.868sec/0.000sec (0.010sec, 0.002sec) (0.004sec/0.104sec/5) 22B 200 "POST /_matrix/client/r0/rooms/!room_id%3Aremote/leave HTTP/1.1" "UserAgent" [0 dbevts]
```

I don't have access to this remote machine or another matrix instance to test this with, but I hope this is enough information to reproduce it.

### Version information

- **Version**: 1.8.0

- **Install method**: pip (python 3.7.4)

- **Platform**: Linux 5.3.7 x86_64 (ArchLinux)

**Comment by richvdh** [comment] 2020-01-23 11:55
> 2020-01-22 11:50:04,842 - synapse.http.matrixfederationclient - 522 - WARNING - POST-32 - {GET-O-3} [remote] Request failed: GET matrix://remote/_matrix/federation/v1/make_leave/%21room_id%3Aremote/%40user%3Alocal: HttpResponseException("500: b'Internal Server Error'")

looks like the 500 is coming from `remote`. You'll need to check the logs there.

In the meantime you can probably get rid of the stuck invite by flushing the cache on the client. see #2181.

**Comment by richvdh** [comment] 2020-01-23 11:56
I'm assuming you don't control the remote server, so this is just a duplicate of #2181 really.

**Closed** 2020-01-23 11:56 UTC
Labels: stuck-invite
