### ISSUE TITLE
Stop sending v1 format events to appservices

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#6457] opened 2019-12-03 17:30 UTC
See also #6452 

As per the above issue, we currently send a special format to appservices which contains the old v1 format keys as well as the v2 keys. The spec states that we should send the same format as we do to clients (v2 only). We've been using this approach for a long time to avoid breakages, but now is probably a good time to move on and be compliant with the spec.

Because this will break appservices still relying on the v1 format event, we need to announce that this will break things.

**Comment by Half-Shot** [comment] 2019-12-03 17:36
We also need to stop using the `unstable` prefix, and instead use `v1` https://github.com/matrix-org/synapse/blob/fdec84aa427e2e3b806eb15f462d652f8554cc8d/synapse/appservice/api.py#L51

**Comment by turt2live** [comment] 2019-12-03 17:39
That's https://github.com/matrix-org/synapse/issues/3780 which is slightly more difficult.

**Comment by Half-Shot** [comment] 2019-12-03 17:40
Rather than trying to do two deprecations, I will probably bundle these together.

**Comment by richvdh** [comment] 2020-10-20 15:35
isn't this a duplicate of #6452?

**Closed by richvdh** 2020-10-20 15:35 UTC
