### ISSUE TITLE
The path of user_consent_template_dir should be under synapse/synapse/res/templates/privacy, but under synapse/synapse/app/res/templates/privacy

### ISSUE THREAD

**Issue by 7-cat** [matrix-org/synapse#8219] opened 2020-09-01 06:51 UTC
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by babolivier** [comment] 2020-09-01 14:27
Hi, given the little info on this issue I'm not sure what the problem is. I assume you mean that the default template directory for user consent templates should be in `synapse/app/res/templates/privacy`, instead of `synapse/res/templates/privacy`. I don't think it makes sense, as all other templates Synapse uses are in the latter, and `synapse/app` is intended to host code files for Synapse's main process and its workers. On top of this, the template directory can be changed in the configuration, so if that location doesn't fit your needs you can change it.
I'm going to close this issue, but feel free to answer here if I misunderstood your concern. For more general Synapse support, please use `#synapse:matrix.org`.

**Closed by babolivier** 2020-09-01 14:27 UTC
