### ISSUE TITLE
Allow docker to take multiple configuration files (e.g. for worker mode)

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/synapse#8065] opened 2020-08-12 11:47 UTC
If I understood docs correctly - this feature is already working outside of docker and worker docs are written like it were available in every supported scenario - also in docker.
I managed to run workers in docker (after few days of fight with docs not being docker-ready - #8053).
Now I'm concatenating configs outside of docker, which is far from ideal solution, I need to remember to refresh configs after change in `homeserver.yaml` and in worker config itself.

**Comment by clokep** [comment] 2020-08-12 13:38
I suspect what would be nice is if you can give the docker container multiple configuration files, which is what the worker docs assume is possible?

**Comment by JuniorJPDJ** [comment] 2020-08-13 02:05
It's better approach of what I was thinking about, thank you for specification :)

**Comment by ptman** [comment] 2020-08-13 11:41
Would that help help with https://github.com/matrix-org/synapse/issues/6662 as well?

**Comment by JuniorJPDJ** [comment] 2020-08-13 13:18
@ptman It could ;D

**Comment by richvdh** [comment] 2020-08-13 15:32
It sounds like this might just be a duplicate of #6662?

**Comment by clokep** [comment] 2020-08-13 15:44
Sounds like a duplicate, yep!

**Closed by clokep** 2020-08-13 15:44 UTC
Labels: docker, help wanted, p3
