### ISSUE TITLE
Missing dependency to lxml for URL previewing

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#2425] opened 2017-08-21 12:47 UTC
URL previewing in Synapse requires the lxml library (`python[2]-lxml`) to work (source: tried to run Synapse without the lxml package installed and with URL previewing enabled and it crashed), but this optional dependency is missing from `synapse/python_dependencies.py`.

Should be an easy one to fix but I'm unsure about the lowest working version of lxml for this feature.

**Comment by gpierron** [comment] 2017-09-17 17:43
Got the same problem here. (debian stable package from repository (0.22.1-1)

**Comment by ara4n** [comment] 2017-09-17 17:47
we deliberately didn't include lxml in the deps for synapse as it's a beast and only needed for optional url previews. so the readme asks users to install manually when needed. this was @erikjohnston's idea; i forget why we don't put it in the optional deps (other than possibly optional deps get installed anyway?)

**Comment by kyrias** [comment] 2017-09-18 19:26
I mean, if it's not listed as a conditional dependency for URL previewing, that makes that section of the dependencies script entirely useless and misleading, so removing it entirely and listing it in e.g. the README or related document would be much better.

**Comment by turt2live** [comment] 2017-09-18 19:30
fwiw, synapse does complain about the missing dependency in a sensible manner.

**Comment by richvdh** [comment] 2018-05-29 15:51
it is listed in the readme. I think this is working as intended.

**Comment by richvdh** [comment] 2018-05-29 16:45
oh, yes it is. sorry, I hadn't realised that we have a separate section of CONDITIONAL_REQUIREMENTS for preview_url. Could somebody just make a PR for this?

**Comment by erikjohnston** [comment] 2018-05-29 17:05
`CONDITIONAL_REQUIREMENTS ` is a bit weird in that I think that all the packages list will be installed when using e.g. `pip`, but on the other hand won't stop synapse from starting. If we added `lxml` then `pip` would try and install it and likely fail due to lack of `libxml2-dev` library, which wouldn't be ideal.

Whether we necessarily want to install `CONDITIONAL_REQUIREMENTS` by default with pip is a possible question.

**Comment by richvdh** [comment] 2018-05-29 17:07
@erikjohnston: so why do we bother listing `netaddr` there?

**Comment by hawkowl** [comment] 2018-12-21 14:56
Fixed in #4298 .

**Closed by hawkowl** 2018-12-21 14:56 UTC
Labels: packaging

**Comment by rubo77** [comment] 2023-09-28 13:09
what is the workaround? I tried

    apt install python3-lxml 

but no luck

**Comment by rubo77** [comment] 2023-09-28 16:07
### Workaround:

    pip install lxml
