### ISSUE TITLE
Sentry spam caused by `ijson` errors

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14062] opened 2022-10-05 13:33 UTC
From matrix.org logs:

```
2022-10-05 03:34:19,746 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- - Traceback (most recent call last):
2022-10-05 03:34:19,750 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -   File "/home/synapse/env-pyston-poetry/lib/python3.8-pyston2.3/site-packages/ijson/backends/python.py", line 46, in utf8_encoder
2022-10-05 03:34:19,754 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -     target.close()
2022-10-05 03:34:19,758 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -   File "/home/synapse/env-pyston-poetry/lib/python3.8-pyston2.3/site-packages/ijson/backends/python.py", line 116, in Lexer
2022-10-05 03:34:19,764 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -     target.send(EOF)
2022-10-05 03:34:19,769 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -   File "/home/synapse/env-pyston-poetry/lib/python3.8-pyston2.3/site-packages/ijson/backends/python.py", line 161, in parse_value
2022-10-05 03:34:19,773 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- -     raise common.IncompleteJSONError('Incomplete JSON content')
2022-10-05 03:34:19,777 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- - ijson.common.IncompleteJSONError: Incomplete JSON content
2022-10-05 03:34:19,781 - twisted - 274 - ERROR - _maybe_retry_device_resync-67-- - Exception ignored in: <generator object utf8_encoder at 0x7f3047891ba0>

```

I _think_ these are printed directly to stderr, and hence become separate events in Sentry---thanks to this bit of monkey patching.

https://github.com/matrix-org/synapse/blob/285d72556bb3c36f075b336b2bdd6acb08391ad5/synapse/app/_base.py#L211-L223

**Comment by clokep** [comment] 2022-10-05 13:41
Duplicate of #13293.

**Closed by clokep** 2022-10-05 13:41 UTC
Labels: S-Tolerable, T-Defect, Z-Dev-Wishlist, O-Uncommon, Z-Sentry

**Comment by DMRobertson** [comment] 2022-10-05 16:50
(thanks for the pointer---saved me a lot of time by not having to diagnose the issue!)
