### ISSUE TITLE
 builtins.ValueError: list.remove(): <twisted.internet.task.CooperativeTask object at 0x00007f8015a05da8> is not in list

### ISSUE THREAD

**Issue by mtippmann** [matrix-org/synapse#6131] opened 2019-09-27 21:00 UTC
### Description

Seeing this error in the logfile. pypy3 7.1.1 / Synapse 1.4.0rc1 (updated from 1.3.1 that ran fine with pypy3): 

```
Sep 27 20:41:19 matrix python[32369]: 2019-09-27 20:41:19,291 - twisted - 171 - CRITICAL - -
Sep 27 20:41:19 matrix python[32369]: Traceback (most recent call last):
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/web/_newclient.py", line 565, in connectionLost
Sep 27 20:41:19 matrix python[32369]:     self.response._bodyDataFinished()
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/web/_newclient.py", line 973, in dispatcher
Sep 27 20:41:19 matrix python[32369]:     return func(*args, **kwargs)
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/web/_newclient.py", line 1229, in _bodyDataFinished_CONNECTED
Sep 27 20:41:19 matrix python[32369]:     self._bodyProtocol.connectionLost(reason)
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/web/client.py", line 2238, in connectionLost
Sep 27 20:41:19 matrix python[32369]:     self.deferred.callback(b''.join(self.dataBuffer))
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/defer.py", line 460, in callback
Sep 27 20:41:19 matrix python[32369]:     self._startRunCallbacks(result)
Sep 27 20:41:19 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/defer.py", line 561, in _startRunCallbacks
Sep 27 20:41:19 matrix python[32369]:     raise AlreadyCalledError
Sep 27 20:41:19 matrix python[32369]: twisted.internet.defer.AlreadyCalledError
Sep 27 20:41:21 matrix python[32369]: 2019-09-27 20:41:21,657 - twisted - 171 - CRITICAL - - Unhandled Error
Sep 27 20:41:21 matrix python[32369]: Traceback (most recent call last):
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/synapse/app/_base.py", line 114, in run
Sep 27 20:41:21 matrix python[32369]:     run_command()
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/base.py", line 1272, in run
Sep 27 20:41:21 matrix python[32369]:     self.mainLoop()
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/base.py", line 1281, in mainLoop
Sep 27 20:41:21 matrix python[32369]:     self.runUntilCurrent()
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/synapse/metrics/__init__.py", line 434, in f
Sep 27 20:41:21 matrix python[32369]:     ret = func(*args, **kwargs)
Sep 27 20:41:21 matrix python[32369]: --- <exception caught here> ---
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
Sep 27 20:41:21 matrix python[32369]:     call.func(*call.args, **call.kw)
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/task.py", line 671, in _tick
Sep 27 20:41:21 matrix python[32369]:     taskObj._oneWorkUnit()
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/task.py", line 521, in _oneWorkUnit
Sep 27 20:41:21 matrix python[32369]:     self._completeWith(TaskFailed(), Failure())
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/task.py", line 477, in _completeWith
Sep 27 20:41:21 matrix python[32369]:     self._cooperator._removeTask(self)
Sep 27 20:41:21 matrix python[32369]:   File "/opt/venvs/matrix-synapse-pypy3/site-packages/twisted/internet/task.py", line 644, in _removeTask
Sep 27 20:41:21 matrix python[32369]:     self._tasks.remove(task)
Sep 27 20:41:21 matrix python[32369]: builtins.ValueError: list.remove(): <twisted.internet.task.CooperativeTask object at 0x00007f801478f248> is not in list
```

### Steps to reproduce

- Use Synapse with pypy3 7.1.1 
- Update to Synapse 1.4.0rc1 
- ??? 

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.bau-ha.us 

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.4.0rc1

- **Install method**: pip install -U matrix-synapse==1.4.0rc1
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian 10 / Kernel 5.0 / amd64
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
- Hardware: LXD-Container on Bare-Metal

**Comment by richvdh** [comment] 2019-10-09 20:13
I think this is a duplicate of #4418.

**Closed by richvdh** 2019-10-09 20:13 UTC
