### ISSUE TITLE
Synapse >=1.66 does not send default: false in pushrules anymore

### ISSUE THREAD

**Issue by nico-famedly** [matrix-org/synapse#13884] opened 2022-09-23 09:18 UTC
### Description

It seems like https://github.com/matrix-org/synapse/pull/13522 regressed sending the "default" field if it is set to false. This causes issues with our SDK, since that relies on those definitions in the spec to be correct and now fails to parse the rules because of schema violations.

If this field is not sent anymore, the spec should be adapted so that our openapi generator doesn't need another special case.

Spec link: https://github.com/matrix-org/matrix-spec/blob/7ab3aecf29fc0fd1daba7842db1cf95461edde5e/data/api/client-server/definitions/push_rule.yaml#L54

### Steps to reproduce

- add a custom push rule
- check if Synapse sends the default field

### Homeserver

other homeservers

### Synapse Version

1.67

### Installation Method

Other (please mention below)

### Platform

custom built docker image

### Relevant log output

```shell
Expected bool, got Null
```

**Comment by richvdh** [comment] 2022-09-23 09:27
Duplicate of https://github.com/matrix-org/synapse/issues/13837

**Closed by richvdh** 2022-09-23 09:27 UTC
