### ISSUE TITLE
Messages are not transmitted via federation, typing notifications are

### ISSUE THREAD

**Issue by problame** [matrix-org/synapse#3750] opened 2018-08-23 20:06 UTC
### Description

Other users on other homeservers can send messages to my account.
My account however cannot send messages to those users.
However, those users see typing notifications from my account, just not the actual message.

The log does not show any warning or error messages apart from the following messages which I suppose are unrelated to this problem:

```
2018-08-23 20:02:52,600 - synapse.storage._base - 317 - WARNING - - Starting db txn 'update_presence' from sentinel context
2018-08-23 20:02:52,600 - synapse.storage._base - 353 - WARNING - - Starting db connection from sentinel context: metrics will be lost
```

The info log _suggests_ (not sure if I read it correctly) that the remote homeservers accept the message event.

### Steps to reproduce

The problem just occurred on synapse 0.27.X after months of not touching it (just worked).
I thought maybe some backwards-incompatible change happend with the federation protocol, so I updated to 0.33.2.
However, this did not help.
Again: the upgrade did not correlate with the bug I describe above.

**Comment by richvdh** [comment] 2018-08-23 21:16
We'll need more logs to investigate.

**Comment by problame** [comment] 2018-08-24 06:53
So here we go: I did a screen recording of the problem:
The upper right is my account on matrix.org, the lower right is the account on my homeserver.
The left shows the home server, with a tmux pane with the system's current time to correlate UI actions with the logs.

* Screencast and homeserver debug log at: https://nextcloud.cschwarz.com/s/QoQEwPq5tqyzeoM
* For the record / convenience, the debug log is also attached to this message (Github doesn't allow uploading the screen recording)
[homeserver_cschwarz_org.txt](https://github.com/matrix-org/synapse/files/2317371/homeserver_cschwarz_org.txt)

**Comment by problame** [comment] 2018-08-28 12:43
Is there anything else I can do?
Sorry to nag, but I can't communicate right now :(

If there is an option to copy the data of my account into a freshly installed synapse database, that would be fine, too.

**Comment by richvdh** [comment] 2018-08-28 16:26
Sorry, I'm not going to have time to look at this this week. I suggest you try asking in #synapse-community:matrix.org (possibly from a matrix.org account) to see if anyone there can help.

**Comment by andreaspeters** [comment] 2018-08-30 18:42
Have the same problem but not the warnings @problame habe. It was starting with version 0.33.2! If I changed back to version 0.33.1 the federation chat was working again. The update to 0.33.3 didnt solve the problem but I can not change back to 0.33.1 because of changes in the database with the new version.  Even the debug logs dont show any kind of error messages.  Maybe the other side of a federated room (as example matrix.org) will find error messages in the log?

**Comment by andreaspeters** [comment] 2018-08-30 18:56
Ok, I change the log level from debug to warning and got this one.

```
08-30 18:49:44,177 - synapse.federation.federation_server - 197 - WARNING - PUT-501- Error handling PDU $15356549812145840FGIfB:matrix.org: ERROR 403: Your server isn't divulging details about prev_events referenced in this event.
2018-08-30 18:50:01,305 - synapse.storage._base - 317 - WARNING - - Starting db txn 'update_presence' from sentinel context
2018-08-30 18:50:01,306 - synapse.storage._base - 353 - WARNING - - Starting db connection from sentinel context: metrics will be lost
2018-08-30 18:50:20,853 - synapse.http.site - 185 - WARNING - GET-517- Error processing request <SynapseRequest at 0x7fa0f0634098 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099145_10422820_0_903679_50632_102_1645_62577_24&timeout=30000' clientproto='HTTP/1.1' site=8008>: <class 'twisted.internet.error.ConnectionLost'> Connection to the other side was lost in a non-clean fashion.
2018-08-30 18:50:21,130 - synapse.http.server - 394 - WARNING - GET-517- Not sending response to request <SynapseRequest at 0x7fa0f0634098 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099145_10422820_0_903679_50632_102_1645_62577_24&timeout=30000' clientproto='HTTP/1.1' site=8008>, already disconnected.
2018-08-30 18:50:24,755 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-14- TX [matrix.org] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 18:50:24,887 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-15- TX [tchncs.de] Failed to send transaction: (u'@ahe:matrix.aventer.biz', u'FLXXHDQTMR')
2018-08-30 18:50:27,212 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-17- TX [tchncs.de] Failed to send transaction: (u'@ahe:matrix.aventer.biz', u'FLXXHDQTMR')
2018-08-30 18:50:27,216 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-16- TX [matrix.org] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 18:50:27,993 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-19- TX [tchncs.de] Failed to send transaction: (u'@ahe:matrix.aventer.biz', u'FLXXHDQTMR')
2018-08-30 18:50:27,997 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-18- TX [matrix.org] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
```

**Comment by andreaspeters** [comment] 2018-08-30 19:40
Well, I done a test with the instance of a friend. Here are the log of his instance:

```
2018-08-30 19:24:45,417 - synapse.http.outbound - 246 - INFO - federation_transaction_transmission_loop-862569- {PUT-O-446650} [matrix.aventer.biz] Result: 200 OK
2018-08-30 19:24:45,418 - synapse.federation.transaction_queue - 669 - INFO - federation_transaction_transmission_loop-862569- TX [matrix.aventer.biz] {1535579338111} got 200 response
2018-08-30 19:24:45,419 - synapse.federation.transaction_queue - 625 - INFO - federation_transaction_transmission_loop-862569- TX [matrix.aventer.biz] {1535579338112} Sending transaction [1535579338112], (PDUs: 1, EDUs: 1)
2018-08-30 19:24:45,419 - synapse.http.outbound - 164 - INFO - federation_transaction_transmission_loop-862569- {PUT-O-446651} [matrix.aventer.biz] Sending request: PUT matrix://matrix.aventer.biz/_matrix/federation/v1/send/1535579338112/
2018-08-30 19:24:45,491 - synapse.access.https.8448 - 215 - INFO - PUT-218672- 50.31.112.231 - 8448 - Received request: PUT /_matrix/federation/v1/send/1535394475689/
```

And same time on my one:

```
2018-08-30 19:24:18,149 - synapse.http.site - 185 - WARNING - GET-1690- Error processing request <SynapseRequest at 0x7f89083341b8 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099186_10426671_20_903784_50649_102_1645_62585_24&timeout=30000' clientproto='HTTP/1.1' site=8008>: <class 'twisted.internet.error.ConnectionLost'> Connection to the other side was lost in a non-clean fashion.
2018-08-30 19:24:18,318 - synapse.http.server - 394 - WARNING - GET-1690- Not sending response to request <SynapseRequest at 0x7f89083341b8 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099186_10426671_20_903784_50649_102_1645_62585_24&timeout=30000' clientproto='HTTP/1.1' site=8008>, already disconnected.
2018-08-30 19:24:18,777 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-81- TX [matrix.vgorcum.com] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 19:24:23,398 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-82- TX [matrix.vgorcum.com] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 19:24:26,786 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-83- TX [matrix.vgorcum.com] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 19:24:28,373 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-84- TX [matrix.vgorcum.com] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
2018-08-30 19:24:58,138 - synapse.http.site - 185 - WARNING - GET-1763- Error processing request <SynapseRequest at 0x7f88c6713710 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099186_10426671_20_903784_50649_102_1645_62585_24&timeout=30000' clientproto='HTTP/1.1' site=8008>: <class 'twisted.internet.error.ConnectionLost'> Connection to the other side was lost in a non-clean fashion.
2018-08-30 19:24:58,471 - synapse.http.server - 394 - WARNING - GET-1763- Not sending response to request <SynapseRequest at 0x7f88c6713710 method='GET' uri='/_matrix/client/r0/sync?access_token=<redacted>&filter=1&since=s6099186_10426671_20_903784_50649_102_1645_62585_24&timeout=30000' clientproto='HTTP/1.1' site=8008>, already disconnected.
2018-08-30 19:24:58,639 - synapse.federation.transaction_queue - 539 - WARNING - federation_transaction_transmission_loop-85- TX [matrix.vgorcum.com] Failed to send transaction: (u'@andreas:matrix.aventer.biz', u'LVYCUTJIWH')
```

I hope it will help a little to find out whats wrong.

**Comment by andreaspeters** [comment] 2018-08-31 18:53
I restored the database with a backup from before the problem. I just want see if its a issue of a corrupt database item. Well, nothing changed! Failure is still there.

**Comment by problame** [comment] 2018-09-01 14:42
Some progress: I connected directly to the synapse web interface instead of using riot-web, and voila, after creating a new chat with my matrix.org-account, federation with matrix.org works again.
Still gotta test other servers...

**Comment by andreaspeters** [comment] 2018-09-01 17:35
some more information! if I invite a federated user, he get it and can accept my invitation. but after that, he still dont receiver what I'm writing.

**Comment by andreaspeters** [comment] 2018-09-07 06:17
Ok... one day later, its not working again... :-(

**Comment by andreaspeters** [comment] 2018-09-07 06:38
move back to 0.33.1 fix it for me again. well, I think u have a big problem, and its not these bug, its that u dont care.

**Comment by hawkowl** [comment] 2018-09-07 11:03
@andreaspeters Hi, sorry about the issues you're having. We've identified some of the possible causes of federation issues, and we're working on fixing them as soon as we can.

**Comment by hawkowl** [comment] 2018-09-07 11:04
Related items:
https://github.com/matrix-org/synapse/issues/3798 (matrix.org not resetting timeouts when in a worker configuration)
https://github.com/matrix-org/synapse/issues/3797 (typing going through even when we're timed out)
https://github.com/matrix-org/synapse/issues/3807 (requests hanging and getting queued)

**Comment by andreaspeters** [comment] 2018-09-11 10:47
ok, thanks for your reply. I will wait.

**Comment by ara4n** [comment] 2018-09-16 15:12
i’m unconvinced that #3798 or #3807 are related, as the first is for workers and second is for develop only as far as know. meanwhile #3797 is the symptom rather than the cause. so i think something else is up here...

**Comment by andreaspeters** [comment] 2018-09-24 14:52
I can also not find any relation to my issue. :-(  the point is, if I move back to v0.33.1 with the procedure I already described here, the federation is working quite well. So, what happend between v0.33.1 and v0.33.2 that it breaks the federation? I also dont believe I'm the only one. Actually, I receive messages from the federation, it means, if I would not build the docker-matrix image and talk a lot over the federation (before this problem), then I would just think that nobody like to talk with me. :-D

**Comment by TheForcer** [comment] 2018-09-25 22:00
I am currently facing the same issue using @andreaspeters Dockerfile for hosting synapse. My server can receive messages from the federated network, but cannot send any ("currently typing" is being displayed though). This is on version 0.33.4.

Unfortunately I can't fix this by downgrading to 0.33.1 or 0.33.0 with the beforementioned database actions. The behaviour does not change as it seems.

Taking a peek at the logfiles, the following part appears very often. Maybe this is somehow related? Currently at my wit's end on how to fix this

`2018-09-25 21:57:27,291 - synapse.storage.background_updates - 103 - ERROR -  - Error doing update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/background_updates.py", line 100, in start_doing_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/background_updates.py", line 175, in do_next_background_update
    res = yield self._do_background_update(update_name, desired_duration_ms)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/background_updates.py", line 209, in _do_background_update
    items_updated = yield update_handler(progress, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/state.py", line 1010, in _background_index_state
    yield self.runWithConnection(reindex_txn)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 368, in runWithConnection
    inner_func, *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 364, in inner_func
    return func(conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/state.py", line 992, in reindex_txn
    "CREATE INDEX CONCURRENTLY state_groups_state_type_idx"
ProgrammingError: relation "state_groups_state_type_idx" already exists
`

**Comment by richvdh** [comment] 2018-10-02 11:27
First of all, thank you to @problame for an excellent initial bug report here, complete with video demonstrating the problem and clear logs from the homeserver. I can only apologise that it has taken a month and a half for me to have time to look at it. The logs certainly show some odd behaviour which I don't really understand. I would ask you to enable some debug logs, but it sounds like the problem has maybe gone away?

@andreaspeters your log snippets suggest that something completely different is going on for you. Unfortunately quite a bit changed between 0.33.1 and 0.33.2, so it's going to be hard to figure out the problem from that. Please could you send me your complete homeserver.log (with at least INFO logs) for a period of about 30 minutes including you sending a message which isn't received. I'll probably also need logs from the other end so please either send your message to a room where there are matrix.org users, or get me the logs from the other homeserver too. You can reach me at `@richvdh:sw1v.org` if you would prefer not to post the logs publicly.

@TheForcer it sounds like you have yet a third problem, though I think yours might be easily solved. Please try the following:
* stop synapse
* from a `psql` console, run `DROP INDEX state_groups_state_type_idx;`
* start synapse
* leave it running until you see "No more background updates to do" in the log. Note that stopping synapse in this period can occasionally leave the database in an inconsistent state, which I think is what has happened here.

If you're still having problems after all that, please send me logs as per the above.

**Comment by richvdh** [comment] 2018-10-03 17:08
For the record: @TheForcer sent me his logs and we identified that his database had gotten into an odd state, possibly as a result of a database backup/restore he'd done previously. To confirm if you're affected by the same thing, run the following on your database:
```sql
SELECT COUNT(*) FROM federation_stream_position;
```
- if that returns anything other than `2`, then you have the same problem as @TheForcer. Let me know if this happens and I can find some sql to fix it for you.

However, I don't really expect it to be a common problem. The fact that @problame's server recovered of its own accord suggests that he was having a different problem. I think @andreaspeters's problem is also different.

**Comment by andreaspeters** [comment] 2018-10-04 08:40
```
matrix=> SELECT COUNT(*) FROM federation_stream_position;
 count 
-------
     2
(1 row)
```

We are on travel at the moment. If we have a more stable sat connection I will send you a 30minutes log from my instance and from a friends one. Thanks for your help guys.

**Comment by richvdh** [comment] 2018-10-09 09:17
ok, I'm going to close this issue, because I'm tired of everybody thinking that the same symptoms mean the same problem. Sounds like the OP's problem got solved. Anyone else coming here, please open a new issue *and share at least 10 minutes' worth of complete logs*.

**Closed by richvdh** 2018-10-09 09:17 UTC
Labels: p1
