### ISSUE TITLE
E2E verif requests can take a surprisingly long time to come through - blocked until next /sync?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5148] opened 2019-05-07 12:00 UTC
This looks to be the same bug i saw back at FOSDEM - that an E2E verif request can take up to 30s to actually arrive, at least some of the time, particularly when verifying your own devices. It looks like we might be missing a wakup prod somewhere?

**Comment by uhoreg** [comment] 2022-01-11 17:25
This could be caused by https://github.com/matrix-org/synapse/issues/9564 and/or https://github.com/matrix-org/synapse/issues/11457

**Comment by DMRobertson** [comment] 2022-08-30 17:09
I propose we close this, unless there is something reproducible or actionable (especially given the two mentioned issues areclosed). Please reopen if it you see it again.

**Closed by DMRobertson** 2022-08-30 17:09 UTC
Labels: P2, T-Defect
