### ISSUE TITLE
Can't upgrade from 1.31

### ISSUE THREAD

**Issue by marekjedrzejewski** [matrix-org/synapse#10052] opened 2021-05-24 15:03 UTC
Hello,
I know this is not support forum, and I should write in #synapse:matrix.org, problem is I wrote there twice and got no response.

I'm trying to upgrade from prebuilt package on ubuntu 20.04, tried upgrading to .32, .33 and .34 and also tried building from source to see if that would give me anything else to grab to, but all I got was:
```
# synctl start
Starting ...
error starting (exit code: 1); see above for logs
```
Can anyone tell me where to look to get anything more than that and finally be able to start the server after upgrade?

**Comment by anoadragon453** [comment] 2021-05-25 12:14
Hi @marekjedrzejewski.

Sorry to hear you didn't get an answer in #synapse:matrix.org. Note that sometimes it may take a while for people to respond depending on timezones/volunteer appetite.

This isn't really the place for support, but to help answer your question: you may find more logs for the Debian/Ubuntu package by looking in the journal with `journalctl -eu matrix-synapse`, or by checking `/var/log/matrix-synapse/homeserver.log`. You may also be able to see further stderr output using `systemctl status matrix-synapse`.

If those all come up short, then ensure that you haven't modified `/etc/matrix-synapse/log.yaml` to point to a different logfile location.

**Comment by richvdh** [comment] 2021-05-25 12:29
(`journalctl` and `systemctl` won't help you if you're starting synapse with `synctl` rather than `systemd`. But yes, check `homeserver.log`, whereever it is configured to be.)

You might also try running synctl with `--no-daemonize`, which can sometimes help show errors that are otherwise getting swallowed.

**Comment by richvdh** [comment] 2021-05-25 12:31
I'm going to go ahead and close this, since likely it's not a bug in synapse.

**Closed by richvdh** 2021-05-25 12:31 UTC
Labels: T-Other

**Comment by babolivier** [comment] 2021-05-26 08:42
`psql --version` returns the version of `psql`, not necessarily the version of PostgreSQL, so this output doesn't mean your PostgreSQL instance is on a recent enough version. See https://github.com/matrix-org/synapse/issues/10031 for more details.
