### ISSUE TITLE
m.login.sso and m.login.token not working with register_password_auth_provider_callbacks > auth_checkers

### ISSUE THREAD

**Issue by msitruk** [matrix-org/synapse#14169] opened 2022-10-13 14:14 UTC
Hello,

I m using synapse v1.68.0 on debian bullseye with keycloak as oidc provider and access it with last version of Element.
I would like to do extra specific things in a custom module when people log to my homeserver so I created a module and try to use the register_password_auth_provider_callbacks with auth_checkers : 

```python
import json
from typing import Union, Awaitable, Callable, Optional, Tuple, Literal
import synapse
import logging
from synapse.module_api import ModuleApi

logger = logging.getLogger(__name__)

class Guard:
    def __init__(self, config: dict, api: ModuleApi):
        self.api = api

        api.register_password_auth_provider_callbacks(
            auth_checkers={
                ("m.login.sso", ()): self.check_auth, # DO NOTHING
                ("m.login.password", ()): self.check_auth, # WORK
                ("m.login.token", ()): self.check_auth, # DO NOTHING
            },
        )

    async def check_auth(
        self,
        user: str,
        login_type: str,
        login_dict: "synapse.module_api.JsonDict",
    ) -> Optional[
        Tuple[
            str,
            Optional[Callable[["synapse.module_api.LoginResponse"], Awaitable[None]]],
        ]
    ]:
        logger.warning("GUARD - I CAN DO THINGS HERE !!!!")
        return None
```

When I login with my admin account with classic login / password the type (m.login.password) it's working great I got my log warning.
**When  I login with the oidc I got nothing...why am I missing something ??**

What I found for the moment ... :  

When I look the network tab of the browser I found this result for login calls : 

BEFORE ANY LOGIN  on the login page : 

![image](https://user-images.githubusercontent.com/15679329/195619141-14c58782-f3fe-4ff7-b17b-5c3286c14fc9.png)

I dont understand why I got multiple "type": "m.login.sso" here maybe it's related to my issue ?

AFTER OIDC LOGIN and "Continue to your account" page 
payload
![image](https://user-images.githubusercontent.com/15679329/195620065-3fe25c8a-6494-4136-b3f3-0d431ae0dcf6.png)
response
![image](https://user-images.githubusercontent.com/15679329/195620493-4398c2e5-9c59-4ed5-b90e-8101aea5627f.png)

**Comment by msitruk** [comment] 2022-10-13 18:48
Thank @DMRobertson for your answer.

The final goal of this module is : 
1) When any user login using sso / oidc I will make an api request on an external service to get more info about him with his email as input.
2) According to datas from API, module will verify and adjust if necessary the list of space-room / and rights for this user.

Do you think I should use [SSO mapping provider](https://matrix-org.github.io/synapse/latest/sso_mapping_providers.html) ?

In any case, it does not change the fact that the auth_checkers seems to have an issue with login type "m.login.sso" and / or "m.login.token".

**Comment by H-Shay** [comment] 2022-10-17 19:35
I have a suspicion that the answer to why your module's `auth_checkers` callback is not firing can be found in the docs that DMR mentioned, quoting:

> If multiple modules register an auth checker for the same login type with the same fields, then the callbacks will be executed in order, until one returns a Matrix User ID (and optionally a callback). In that case, the return value of that callback will be accepted and subsequent callbacks will not be fired. If every callback returns None, then the authentication fails.

That is, both the OIDC module and your custom module have registered an auth checker for the same login types. The OIDC module executes first, and subsequent callbacks are not executed. 

As for how to achieve your end goals, I am not sure how to advise. I would suggest asking in #synapse-dev, someone there might have suggestions?

**Comment by msitruk** [comment] 2022-10-18 08:15
Hello @H-Shay ,

Thank for your return, I tried of course to register only one login type in auth checker but this never change anything.

Well I follow @DMRobertson advice and I tryed the SSO mapper module and it works great at this point.

**Comment by H-Shay** [comment] 2022-10-19 19:55
Right well it seems that this is not a bug, so I will close this issue. Feel free to ask in #synapse-dev for more advice on developing your custom module.

**Closed by H-Shay** 2022-10-19 19:55 UTC
Labels: A-SSO, T-Other, A-Modules, O-Uncommon

**Comment by msitruk** [comment] 2022-10-21 13:58
Maybe not a bug
Imo, auth_checkers is not working well or at least miss some docs about no compatibility with SSO.
