### ISSUE TITLE
401 Unauthorized only when trying to federate with matrix.org

### ISSUE THREAD

**Issue by Pablossi** [matrix-org/synapse#7764] opened 2020-06-30 18:38 UTC
I cannot federate with matrix.org. When I try to see the list of public rooms in Riot I get the following error in Synapse:

2020-06-30 13:32:01,021 - synapse.http.matrixfederationclient - 537 - WARNING - POST-743 - {GET-O-23} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=20: HttpResponseException("401: b'Unauthorized'",)
2020-06-30 13:32:01,021 - synapse.http.server - 84 - INFO - POST-743 - <XForwardedForRequest at 0x7fa624e77320 method='POST' uri='/_matrix/client/r0/publicRooms?server=matrix.org' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - No key for mydomain.com with ids in ['ed25519:a_MWcv'] (min_validity 1593534720408)

**Comment by dannycolin** [comment] 2020-07-01 01:32
Looks like a duplicate of #7762

**Comment by richvdh** [comment] 2020-07-01 10:05
without knowing what your domain is, we can't do much with this. In general this suggests that you have a configuration error that you might be able to get help with in `#synapse:matrix.org`

**Closed by richvdh** 2020-07-01 10:05 UTC

**Comment by richvdh** [comment] 2020-07-03 19:26
for the record, turns out @Pablossi was using duckdns.org, which returns A responses when you send them a query for SRV records, which is of course invalid. Dup #5882.

**Comment by dannycolin** [comment] 2020-07-03 19:45
@richvdh I have the same error message but I don't use duckdns.org so this issue isn't solved for me.

**Comment by richvdh** [comment] 2020-07-06 10:57
@dannycolin:

> without knowing what your domain is, we can't do much with this.

I suggest asking (again) for help in #synapse:matrix.org.
