### ISSUE TITLE
SynapseError 400 Additional properties are not allowed ('unread_thread_notifications' was unexpected)

### ISSUE THREAD

**Issue by coolmast** [matrix-org/synapse#14399] opened 2022-11-09 11:15 UTC
When trying to sign in with a new device on an existing account on a self-hosted synapse server, I get the following SynapseError preventing the client to sync rooms.

Any idea on what is wrong here:

```
Nov 09 12:05:31 vps813791.ovh.net synapse[205558]: synapse.http.server: [GET-1928] <XForwardedForRequest at 0x7fc8f86c6c50 method='GET' uri='/_matrix/client/r0/sync?filter=%7B%22room%22%3A%7B%22state%22%3A%7B%22lazy_load_members%22%3Atrue%7D%2C%22timeline%22%3A%7B%22unread_thread_notifications%22%3Atrue%7D%7D%7D&set_presence=offline&timeout=0' clientproto='HTTP/1.0' site='8008'> SynapseError: 400 - Additional properties are not allowed ('unread_thread_notifications' was unexpected)
                                                   
                                                   Failed validating 'additionalProperties' in schema['properties']['room']['properties']['timeline']:
                                                       {'additionalProperties': False,
                                                        'properties': {'contains_url': {'type': 'boolean'},
                                                                       'include_redundant_members': {'type': 'boolean'},
                                                                       'lazy_load_members': {'type': 'boolean'},
                                                                       'limit': {'type': 'number'},
                                                                       'not_rooms': {'$ref': '#/definitions/room_id_array'},
                                                                       'not_senders': {'$ref': '#/definitions/user_id_array'},
                                                                       'not_types': {'items': {'type': 'string'},
                                                                                     'type': 'array'},
                                                                       'org.matrix.labels': {'items': {'type': 'string'},
                                                                                             'type': 'array'},
                                                                       'org.matrix.not_labels': {'items': {'type': 'string'},
                                                                                                 'type': 'array'},
                                                                       'related_by_rel_types': {'items': {'type': 'string'},
                                                                                                'type': 'array'},
                                                                       'related_by_senders': {'items': {'type': 'string'},
                                                                                              'type': 'array'},
                                                                       'rooms': {'$ref': '#/definitions/room_id_array'},
                                                                       'senders': {'$ref': '#/definitions/user_id_array'},
                                                                       'types': {'items': {'type': 'string'},
                                                                                 'type': 'array'}},
                                                        'type': 'object'}
                                                   
                                                   On instance['room']['timeline']:
                                                       {'unread_thread_notifications': True}
```

**Comment by DMRobertson** [comment] 2022-11-09 11:47
Duplicate of https://github.com/matrix-org/synapse/issues/14365, I think?

**Closed by DMRobertson** 2022-11-09 11:47 UTC

**Comment by DMRobertson** [comment] 2022-11-09 11:49
(Should be fixed in the next Synapse release; until that's available, I suggest using an older version of your client which doesn't know about `unread_thread_notifications`.

**Comment by squahtx** [comment] 2022-11-09 12:18
Note that the current release of Synapse accepts the `unread_thread_notifications` setting, so upgrading Synapse ought to fix the error for you.
