### ISSUE TITLE
json data migrated incorrectly with synapse_port_db

### ISSUE THREAD

**Issue by hatifnatt** [matrix-org/synapse#5312] opened 2019-06-02 06:22 UTC
### Description

I'm trying to migrate small homeserver installation (about 10 users) from default sqlite to postgresql. But after migration I have found errors in log complaining about data in `pushers` table.
```
2019-06-02 09:08:16,769 - synapse.storage.pusher - 50 - WARNING - start_pushers-0- Invalid JSON in data for pusher 320: \x7b2275726c223a22687474703a2f2f3132372e302e302e313a353030302f5f6d61747269782f707573682f76312f6e6f74696679227d, Expecting value: line 1 column 1 (char 0)
2019-06-02 09:08:16,769 - synapse.storage.pusher - 50 - WARNING - start_pushers-0- Invalid JSON in data for pusher 321: \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a22687474703a2f2f3132372e302e302e313a353030302f5f6d61747269782f707573682f76312f6e6f74696679227d, Expecting value: line 1 column 1 (char 0)
2019-06-02 09:08:16,769 - synapse.storage.pusher - 50 - WARNING - start_pushers-0- Invalid JSON in data for pusher 5966: \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a2268747470733a2f2f6d61747269782e6f72672f5f6d61747269782f707573682f76312f6e6f74696679227d, Expecting value: line 1 column 1 (char 0)
2019-06-02 09:08:16,769 - synapse.storage.pusher - 50 - WARNING - start_pushers-0- Invalid JSON in data for pusher 3776: \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a2268747470733a2f2f6d61747269782e6f72672f5f6d61747269782f707573682f76312f6e6f74696679227d, Expecting value: line 1 column 1 (char 0)
```
Simple comparison of data in sqlite and postgresql shows that instead of JSON string in postgresql I've got hex encoded string.
sqlite:
```
sqlite> select id,data from pushers order by id limit 5;
108|{"format":"event_id_only","url":"https://matrix.org/_matrix/push/v1/notify"}
320|{"url":"http://127.0.0.1:5000/_matrix/push/v1/notify"}
321|{"format":"event_id_only","url":"http://127.0.0.1:5000/_matrix/push/v1/notify"}
3589|{"format":"event_id_only","url":"https://matrix.org/_matrix/push/v1/notify"}
3776|{"format":"event_id_only","url":"https://matrix.org/_matrix/push/v1/notify"}
```
postgresql:
```
synapse=# select id,data from pushers order by id limit 5;                                                                                                                                                                                   
  id  |                                                                               data
------+------------------------------------------------------------------------------------------------------------------------------------------------------------------
  108 | {"format":"event_id_only","url":"https://matrix.org/_matrix/push/v1/notify"}
  320 | \x7b2275726c223a22687474703a2f2f3132372e302e302e313a353030302f5f6d61747269782f707573682f76312f6e6f74696679227d
  321 | \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a22687474703a2f2f3132372e302e302e313a353030302f5f6d61747269782f707573682f76312f6e6f74696679227d
 3589 | \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a2268747470733a2f2f6d61747269782e6f72672f5f6d61747269782f707573682f76312f6e6f74696679227d
 3776 | \x7b22666f726d6174223a226576656e745f69645f6f6e6c79222c2275726c223a2268747470733a2f2f6d61747269782e6f72672f5f6d61747269782f707573682f76312f6e6f74696679227d
```
I found that the data in the `pushers` table is corrected after the user has logged in, user with `id` 108 has logged in and it data is fine now, but I'm not sure if there are any other JSON data corrupted during migration.

### Steps to reproduce

- simply follow [documentation](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst) about DB migration:
  - prepare PostgreSQL database
  - migrate data with help of `synapse_port_db` script
  - compare data in sqlite DB and in PostgreSQL DB

### Version information

- **Version**:
  - matrix-synapse: 0.99.2-5~bpo9+1
  - postgresql-11: 11.3-1.pgdg90+1
- **Install method**: apt, from Debian backports repository
- **Platform**:  Debian 9 Stretch running in VM

**Comment by msirringhaus** [comment] 2019-11-20 11:51
I'm affected as well, while upgrading from 1.4 to 1.5.1 (with the supposedly fixed `synapse_port_db`-script).

**Comment by richvdh** [comment] 2019-11-20 14:38
1.5.1 does not claim to fix this bug, ftr.

**Comment by richvdh** [comment] 2019-11-21 14:07
event_json is similarly affected (see https://github.com/matrix-org/synapse/issues/6207#issuecomment-552226655).

frankly much of the root cause here is https://github.com/matrix-org/synapse/issues/4475, but that's a longer-term problem.

**Comment by richvdh** [comment] 2020-01-24 12:09
So, I believe this was fixed by #6513.

The problem was that before that change, synapse_port_db made its own connection pool (https://github.com/matrix-org/synapse/pull/6513/files#diff-e2723e06c17d57db056383ea4f1479f5L479), which didn't set the `on_new_connection` property, and therefore did not set `bytea_output` on its connections.

but then... how did this work at all?

**Comment by richvdh** [comment] 2020-01-24 14:00
ok so it it worked at all because, most of the time, when we select from a `TEXT` column in sqlite, we get a `str` in python so it doesn't matter what `bytea_output` is set to.

*However*, the type of data that we get back from sqlite (and hence the type that python maps the result onto) depends on the way it was *stored*, rather than being anything to do with the column type. As per https://www.sqlite.org/datatype3.html:

> A column with TEXT affinity stores all data using storage classes NULL, TEXT or BLOB.

And the really fun thing is that both BLOBs and TEXTs look the same from the sqlite console:

```
sqlite> create temporary table test (testcol text);
sqlite> insert into test values ('abc');
sqlite> insert into test values (cast('abc' as blob));

sqlite> select *, typeof(testcol) from test;
testcol     typeof(testcol)
----------  ---------------
abc         text           
abc         blob    
```

The data will be a BLOB in the sqlite database if we wrote a python `bytes` into it rather than a `str`. This will have happened to event_json thanks to #6185 (or rather, the bug fixed by it); it happens in `pushers` because we always write `bytes` there (#4475).

Soooo... if the sqlite database contains BLOBs due to one of the above bugs, *and* you did the port to postgres with a version of synapse earlier than 1.8, you will have ended up with this `\x`-encoded data in your postgres.

**Comment by richvdh** [comment] 2020-01-24 14:03
It should be possible to fix the corrupt data with something like this on your postgres database:

```sql
set bytea_output='escape';
update pushers set data = decode(substr(data,3), 'hex') where data like '\\x%';
update event_json set json = decode(substr(json,3), 'hex') where json like '\\x%';
```

**Closed** 2020-01-24 14:10 UTC
Labels: bug, p2
