### ISSUE TITLE
Searching for Users in Element Client

### ISSUE THREAD

**Issue by jstampfer** [matrix-org/synapse#9156] opened 2021-01-19 10:57 UTC
I have installed a Homeserver with spantaleevs ansible playbook. It works really fine.
But one problem I have, is when I try to search for contacts (f.e. when try to start a chat) - 
in Element-Web / Windows Client and in Element-IOs and Android App too.

Some Users I can find without any problems, others just seems to be case sensitive
an I can just find it if i write the correct uppercases. Some users I just can find
if I enter a "@" in the searchfield, and then I have to find it in the list.
Does anybody have the same problem?

Thx in advance :-)

**Comment by jstampfer** [comment] 2021-01-19 16:29
Will have a look. thx

But just for my interest: Could it be different if a user is created by the /synapse-admin package or the /matrix-registration package. For me it looks like, users I created with the /synapse-admin are used to be casesensitive. users created your useraccount by itself with /matrix-registrations can be found without any problems.

Because of this: user_directory.search_all_users set to true?
I can find and see all users so it should be true. isn´t it? I sometime have to write the right uppercases and lowercases (especially with users created with /synapse-admin).

**Comment by callahad** [comment] 2021-01-21 22:50
The synapse-admin theory is interesting! You mean this, yes? https://github.com/Awesome-Technologies/synapse-admin

**Comment by jstampfer** [comment] 2021-01-22 06:35
Yes

**Comment by richvdh** [comment] 2021-04-09 15:22
I'm going to close this as a duplicate of #7588/#3631

**Closed by richvdh** 2021-04-09 15:22 UTC
Labels: z-info-needed
