### ISSUE TITLE
Fails to join room because response body is too large

### ISSUE THREAD

**Issue by symphorien** [matrix-org/synapse#9992] opened 2021-05-14 11:31 UTC
When joining `#freenode_#nixos:matrix.org`, joining fails and I get the following backtrace
```
2021-05-13T18:22:57.133 1274900691998 matrix-synapse.service homeserver[28729] INFO {PUT-O-6306} [matrix.org] JSON response exceeded max size 104857600 - PUT matrix://matrix.org/_matrix/federation/v2/send_join/%21AinLFXQRxTuqNpXyXk%3Amatrix.org/%24162092293411DFmcY%3Axlumurb.eu
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Failed to send_join via matrix.org
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Traceback (most recent call last):
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 183, in _handle_json_response
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     body = await make_deferred_yieldable(d)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO synapse.http.client.BodyExceededMaxSize
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO The above exception was the direct cause of the following exception:
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO Traceback (most recent call last):
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 517, in _try_destination_list
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     return await callback(destination)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 668, in send_request
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     content = await self._do_send_join(destination, pdu)
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 759, in _do_send_join
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     return await self.transport_layer.send_join_v2(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 256, in send_join_v2
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     response = await self.client.put_json(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 759, in put_json
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     body = await _handle_json_response(
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO   File "/nix/store/0k6lr4z1vxgv2vhclfkpsgppwi15p7ri-matrix-synapse-1.33.2/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 194, in _handle_json_response
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO     raise RequestSendFailed(e, can_retry=False) from e
2021-05-13T18:22:57.348 1274900906651 matrix-synapse.service homeserver[28729] INFO synapse.api.errors.RequestSendFailed: Failed to send request: BodyExceededMaxSize:
```

_Originally posted by @symphorien in https://github.com/matrix-org/synapse/issues/9920#issuecomment-840675048_

Synapse 1.33.2, Nixos 20.09 on x86_64-linux.
The backtrace is there in full, it is not truncated.

**Comment by erikjohnston** [comment] 2021-05-20 11:11
This actually looks to be a duplicate of https://github.com/matrix-org/synapse/issues/9956, so I'm going to close this in favour of that one. Thanks for providing the logs though! :slightly_smiling_face:

**Closed by erikjohnston** 2021-05-20 11:11 UTC
Labels: S-Major, T-Defect
