### ISSUE TITLE
Room and space upgrades leave members behind

### ISSUE THREAD

**Issue by nrktkt** [matrix-org/synapse#13559] opened 2022-08-18 20:00 UTC
### Description

Hi, I believe there is a bug in upgrading spaces. 
I recently upgraded [#scala-space:matrix.org](https://matrix.to/#/#scala-space:matrix.org) and when I did the space address was reassigned to the new space and all the rooms were added as well. However none of the room members were moved over.

So now all the members of the space are stuck in the old one unless they manually move.
And several rooms require you to be a member of the space to access them, so should someone be in the wrong room they're cut off from access to those rooms.

### Steps to reproduce

- have a space on version 6
- accept the prompt in element to upgrade

### Homeserver

matrix.org

### Synapse Version

1.65.0

### Platform

hosted

### Relevant log output

```shell
hosted
```

**Comment by clokep** [comment] 2022-08-18 20:18
> However none of the room members were moved over.

This is expected -- room members are not automatically migrated when rooms are upgraded. This seems to be mostly covered by matrix-org/matrix-spec#455. (I think there's been a couple of proposals to fix this.)

>  And several rooms require you to be a member of the space to access them, so should someone be in the wrong room they're cut off from access to those rooms.

I think this might be matrix-org/matrix-spec#1072. The homeserver doesn't touch other rooms during the upgrade process (I think some clients might do some magic here when you upgrade a space, but I'm not 100% sure).

The behavior for this isn't even 100% clear if you upgrade Space `!a:foo` to `!b:foo`, and you have a room `!c:foo` restricted to room `!a:foo` -- is the proper thing to allow joins from members of `!a:foo` or `!b:foo`? Or maybe only members of `!b:foo` (and users would need to manually follow the upgrade first)?

So yes, this isn't great behavior, but I suspect it needs some spec changes before Synapse can improve here.

**Comment by Mikaela** [comment] 2022-08-22 16:04
I think this is (also) a client issue that is tracked at least at:

* https://github.com/vector-im/element-web/issues/19208
  * https://github.com/vector-im/element-web/issues/19841 but closed as duplicate of the above
* [gitlab.com/famedly/fluffychat: Feature request: add a button to follow tombstone / room upgrade into room/space settings](https://gitlab.com/famedly/fluffychat/-/issues/694)

**Comment by nrktkt** [comment] 2022-08-22 18:16
I at the least I think (lmk if I'm wrong) the spec allows clients to know that a space/room has a new version. Element should give some prompt to users to join the new space. Permissions sound more complicated, but at a minimum the UI should allow ad admin to discern which version of the space they're currently depending on.

In summary the impression I have is that to fix the issue spec changes are needed, but in the meantime client changes are needed to prevent this use case from becoming catastrophic (as it has been for me).

**Comment by DMRobertson** [comment] 2022-08-22 20:52
> I at the least I think (lmk if I'm wrong) the spec allows clients to know that a space/room has a new version. E

In general yes: this is the [`replacement_room`](https://spec.matrix.org/v1.3/client-server-api/#mroomtombstone) field on the m.room.tombstone event. But I'm not sure if there are any specific caveats regarding spaces here.

In fact, I'm not sure there's much to do here in Synapse for the time being. Suggest we close this in lieu of https://github.com/matrix-org/matrix-spec/issues/455 and https://github.com/matrix-org/matrix-spec/issues/1072 or similar spec issues(?)

**Closed** 2022-11-15 15:20 UTC
Labels: A-Room-Upgrades, S-Major, T-Defect, O-Occasional
