### ISSUE TITLE
Gif preview for externally linked gifs not animated even when "Autoplay GIFs and videos" enabled in Element, stuck on first frame

### ISSUE THREAD

**Issue by ell1e** [matrix-org/synapse#7922] opened 2020-07-21 18:31 UTC
### Description

Gif preview for externally linked gifs is broken and stuck on the first frame even when "Autoplay GIFs and videos" enabled in Element. It was suggested to me here https://github.com/vector-im/riot-web/issues/14567 that this is potentially a server-side problem, hence I am filing a ticket here. It would be nice if this worked, so maybe you could join forces with the Element developers to figure out what is needed to fix this.

### Steps to reproduce

1. Launch Element client
2. Go into Element's preferences an enable "Autoplay GIFs and videos", "Show previews/thumbnails for images", and "Enable inline URL previews by default"
3. Pick a room to talk in
4. If the room is encrypted, go into room settings and enable "Enable URL previews for this room (only affects you)" 
5. Send this message:
    > https://i.imgur.com/26k9Td7.gif

You should see that, somewhat disappointingly, while the gif will have a graphical preview that preview won't animate but rather end up stuck on its first frame.

### Version information

- **Homeserver**: matrix.org

**Comment by clokep** [comment] 2020-07-21 18:34
This got filed as #7922 yesterday, but it is a duplicate of #1278.

**Closed by clokep** 2020-07-21 18:34 UTC
