### ISSUE TITLE
Special Characters in the E-Mail "notif_from" field causes mail to fallback to a mix of hostname.

### ISSUE THREAD

**Issue by JustinBack** [matrix-org/synapse#10249] opened 2021-06-25 04:38 UTC
### Description

As the title implies having the ";" character (in quotes as well) in the notif_from key causes the email to fallback to the machine hostname, thus preventing emails with a strict sender check

```
  notif_from: "ToS;DR %(app)s <matrix@tosdr.org>"
```
![image](https://user-images.githubusercontent.com/40178814/123369829-cf924f80-d57e-11eb-92f7-324aa67cc0d1.png)

Removing the semicolon fixes the issue.
![image](https://user-images.githubusercontent.com/40178814/123369871-e8026a00-d57e-11eb-9cf7-63cf540dc673.png)

### Steps to reproduce

- Use a semicolon in the notif_from key
- Send a test email

It should include the Semicolon as well.

### Version information

- **Homeserver**: matrix.tosdr.org

If not matrix.org:

- **Version**: 1.31.1

- **Install method**: Package Manager

- **Platform**: Debian Buster (10) Not containerd, running on a dedicated server.

CPU: AMD EPYC 7702 | 64 Cores with the average load being below 0.2 in general
Memory: 64 GB DDR4 ECC RAM 

Identity server is vector.im by default

**Comment by babolivier** [comment] 2021-06-25 13:59
Related: https://github.com/matrix-org/synapse/issues/10173

**Comment by babolivier** [comment] 2021-06-28 11:33
Actually this is a duplicate of https://github.com/matrix-org/synapse/issues/10173

**Closed by babolivier** 2021-06-28 11:33 UTC
