### ISSUE TITLE
Rejected pushes delete the pusher, then try to update it

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3718] opened 2018-08-19 06:20 UTC
This causes a row not found error, as observed here: https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1534653938464946EbFoK:matrix.org (#matrix-dev)

**Comment by lcosmin** [comment] 2018-08-19 06:44
The exception occurs when the other user in the room has written a message and I'm supposed to get a notification on Riot.im (on my mobile). It seems that my user is not in the `pushers` table and that's the reason for the exception.

Here's a more complete log: https://pastebin.com/Mf5vJ4iZ

**Comment by lcosmin** [comment] 2018-08-20 05:51
The exception occurs when the other user in the room has written a message and I'm supposed to get a notification on Riot.im (on my mobile). It seems that my user is not in the pushers table and that's the reason for the exception.

Here's a more complete log: https://pastebin.com/raw/DGsbAuF3

Edit: Also, if of any relevance: I was logged in with the same account from two different computers (user-1 in the log above)

**Comment by richvdh** [comment] 2020-10-31 11:14
anyone got stacktraces here? is this a duplicate of https://github.com/matrix-org/synapse/issues/5101 ?

**Comment by richvdh** [comment] 2020-12-14 09:44
closing for lack of response.

**Closed by richvdh** 2020-12-14 09:44 UTC
Labels: info-needed, minor, p2, push
