### ISSUE TITLE
state_groups_state contains an event which is in a different room

### ISSUE THREAD

**Issue by worldowner** [matrix-org/synapse#7012] opened 2020-02-28 11:36 UTC
### Description

Today morning Riot couldn't lazy load messages from one room and was not showing me as a member of a room on a list. According to client/r0/joined_rooms (via curl) I was joined to it. The room was created 3 days ago while I was running synapse 1.11.0. Room version was 5.

```
select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
```
Above query shown me that I got one wrong entry in state_group_edges for affected room. Deleting bad entry fixed the room for me.

It seems that the same issue hit another person (#6779) where the same workaround fixed problem. The conclusion was that the bug that caused it was fixed long ago which may not be the case.

I don't know if the fact that I was hit by it today while running the latest synapse means that this bug is still present or it is a leftover after what older synapse versions did (I've been running and constantly upgrading synapse since 0.26 or 0.27).

### Steps to reproduce

- I don't know if any particular step triggers this issue

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: my private homeserver

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.11.0

- **Install method**: avhost/docker-matrix
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Docker on Debian Linux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment] 2020-02-28 11:47
@worldowner are you using postgres or sqlite?

if this is affecting a room created only three days ago, it can't be related to old bugs in synapse.

It would be useful to know when the state_groups in question were created: can you join against the `events` table via `events_to_state_group`, and inspect the `origin_server_ts` for those events?

**Comment by worldowner** [comment] 2020-02-28 13:02
I'm on sqlite.

```
SELECT datetime(e.origin_server_ts/1000, 'unixepoch', 'localtime') FROM state_groups stg JOIN event_to_state_groups etsg ON (stg.id = etsg.state_group) JOIN events e ON (etsg.event_id = e.event_id) WHERE stg.room_id='AFFECTED_ROOM:remote_server';
2020-02-27 14:04:56
2020-02-27 14:05:00
2020-02-27 14:06:21
2020-02-27 17:32:44
2020-02-27 17:42:38
2020-02-27 17:43:12
2020-02-27 17:43:15
2020-02-27 17:43:35
2020-02-27 17:48:49
2020-02-27 17:49:10
2020-02-27 17:49:10
2020-02-27 17:49:24
2020-02-27 17:49:29
2020-02-27 17:49:40
2020-02-27 18:04:38
2020-02-27 18:04:38
2020-02-27 18:04:52
2020-02-27 18:04:52
2020-02-27 18:05:01
2020-02-27 18:05:05
2020-02-27 18:05:52
2020-02-27 18:05:52
2020-02-27 18:05:54
2020-02-27 18:05:55
2020-02-27 18:07:04
2020-02-27 18:26:39
2020-02-27 18:26:42
2020-02-27 18:26:45
2020-02-27 18:26:50
2020-02-27 18:26:53
2020-02-27 18:28:30
2020-02-27 18:28:31
2020-02-27 18:28:51
2020-02-27 18:40:36
2020-02-27 18:40:44
2020-02-27 18:40:46
2020-02-27 18:40:47
2020-02-27 18:40:48
2020-02-27 18:40:51
2020-02-27 18:40:52
2020-02-27 18:41:01
2020-02-27 18:41:12
2020-02-27 18:41:12
2020-02-27 18:41:19
2020-02-27 18:41:21
2020-02-27 18:41:34
2020-02-27 18:42:06
2020-02-27 18:42:19
2020-02-27 18:42:33
2020-02-27 18:51:45
2020-02-27 18:55:37
2020-02-27 19:43:39
2020-02-27 19:44:24
```
That would mean yesterday.
I hope my query is ok.

I made a mistake, the room was created 7 days ago (not 3 like I wrote before) but that doesn't change the fact that both homeservers had already been running 1.11.0 at that time.

**Comment by richvdh** [comment] 2020-02-28 13:25
> I'm on sqlite.

right. Just to let you know: using sqlite for anything other than a test instance is a bad idea for performance reasons. Nevertheless this sounds like a bug which needs fixing.

I'm specifically interested in the state_groups which have an entry in `state_group_edges` which point to a state_group for a different room, ie the one that was in the row you deleted.

**Comment by worldowner** [comment] 2020-02-28 13:46
I know about performance, but my homeserver is so small that PostgreSQL is an overkill for now and following months. I will migrate one day :)

Either I don't know how to extract such an information or I don't have rows like that (because I've already deleted row).

**Comment by richvdh** [comment] 2020-02-28 14:20
you said:

>  Deleting bad entry fixed the room for me.

do you have a record of what exactly you deleted (or a backup from before you deleted it)?

**Comment by worldowner** [comment] 2020-02-28 15:03
Unfortunately I don't. I deleted backup after I saw that deleting the row fixed my problem. I guess it's too late to investigate :/

**Comment by richvdh** [comment] 2020-02-28 16:04
let's close this then and reopen if we see it again.

**Comment by worldowner** [comment] 2020-02-28 20:05
Now I have something different:

```
sqlite> SELECT sgs.state_group, e.type, datetime(e.origin_server_ts/1000, 'unixepoch', 'localtime') FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
1134|m.room.member|2020-02-27 17:32:44
```
```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
sqlite>
```
Second query returns nothing this time. I'm quite sure that I didn't have this entry returned by first query earlier today.
I ran VACUUM on sqlite database (I have retention configured). Isn't VACUUM supported on sqlite?

Should I delete something now? So far I don't see any issues in Riot.

**Comment by richvdh** [comment] 2020-02-29 23:39
I'd like to see your homeserver logs around 2020-02-27 17:32. Can you upload them somewhere and contact me via matrix (`@richvdh:sw1v.org`) to let me know where to see them?

**Comment by worldowner** [comment] 2020-03-01 18:45
I'm not allowed to federate with servers outside of a short list but my servers are so small that logs are short enough to post here I think:

```
2020-02-27 17:32:44,633 - synapse.federation.transport.server - 406 - INFO - PUT-4869- Received txn 1582809632600 from remote-server. (PDUs: 1, EDUs: 0)
2020-02-27 17:32:44,637 - synapse.crypto.keyring - 311 - INFO - PUT-4869-event_id- Waiting for existing lookups for ['remote-server'] to complete [loop 1]
2020-02-27 17:32:44,639 - synapse.handlers.federation - 190 - INFO - PUT-4869-event_id- handling received PDU: <FrozenEventV3 event_id='event_id', type='m.room.member', state_key='@remote_user1:remote-server'>
2020-02-27 17:32:44,695 - synapse.metrics - 462 - INFO - - Collecting gc 1
2020-02-27 17:32:44,710 - synapse.access.https.8448 - 302 - INFO - PUT-4869- 10.255.0.2 - 8448 - {remote-server} Processed request: 0.079sec/0.001sec (0.020sec, 0.000sec) (0.018sec/0.014sec/10) 62B 200 "PUT /_matrix/federation/v1/send/1582809632600 HTTP/1.1" "Synapse/1.11.0" [1 dbevts]
```
State_key from the log matches the one returned by query I posted on Friday.

Since Friday evening situation seems to get worse:
```
sqlite> SELECT sgs.state_group, e.type, datetime(e.origin_server_ts/1000, 'unixepoch', 'localtime') FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
1134|m.room.member|2020-02-27 17:32:44
1137|m.room.member|2020-02-23 20:40:34
1137|name: m.room.retention|2020-02-23 20:41:00
```
I know that type in last row is wrong. I think that someone sent wrong custom event via Riot.
I don't have logs for 2020-02-23.
I have access to remote_server so I'm able to run some queries there if needed.

**Comment by richvdh** [comment] 2020-06-05 10:37
sorry, we seem to have forgotten about this. what's the current status of it?

**Comment by worldowner** [comment] 2020-06-06 16:30
Thanks for asking. Situation didn't change. The queries currently return the same results as in my previous post.
```
sqlite> SELECT sgs.state_group, e.type, datetime(e.origin_server_ts/1000, 'unixepoch', 'localtime') FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
1134|m.room.member|2020-02-27 17:32:44
1137|m.room.member|2020-02-23 20:40:34
1137|nazwa: m.room.retention|2020-02-23 20:41:00
```

```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
sqlite>
```

The good thing is that nothing new is affected but I still don't know what to do with those leftovers. Those 2 affected rooms were created by users on remote server that my homeserver is federated with. Both rooms are actively used and there seems to be no issues with them from client perspective. Both SQL queries return nothing on second server.

In the meantime I upgraded Synapse. Currently I run 1.14.0.

**Comment by richvdh** [comment] 2020-06-29 14:00
I must admit I'm not really sure how to proceed here. 

I've re-checked the database on matrix.org, and have confirmed we haven't seen any instances of `state_groups_state` referencing events in the wrong room since 2018-08-25 (except for old versions of #matrix:matrix.org and #riot:matrix.org, whose brokenness started long earlier).

since this seems to be a one-off, I'm inclined to ignore it and move on. Figuring out what happened is likely to take a lot of time-consuming digging into the database.

In terms of how to clean up: well, you could just ignore the problem. Alternatively, if you feel confident with sql, you could delete the  offending rows from `state_groups_state`. Be sure that you delete only the three affected rows if so.

**Comment by schnuffle** [comment] 2020-08-25 19:30
I'm on synapse 1.9.0  with Postgres 
and when I run richvdh query, I get:

```
synapse=# select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
   id   |             room_id              |                   event_id                   | state_group | prev_state_group |   id   |            room_id             |                   event_id                   
--------+----------------------------------+----------------------------------------------+-------------+------------------+--------+--------------------------------+----------------------------------------------
 526588 | !pJuUbnUuHXkdtZkuqv:matrix.org   | $15109483053HCPgf:schnuffle.de               |      526588 |           526587 | 526587 | !zNvOEhgMmMbHoqgwfD:matrix.org | $15109482971ypZxe:schnuffle.de
 526589 | !ZBjIxlFhJPUkrJGgCg:schnuffle.de | $15109483114cjUlM:schnuffle.de               |      526589 |           526588 | 526588 | !pJuUbnUuHXkdtZkuqv:matrix.org | $15109483053HCPgf:schnuffle.de
 742706 | !mjbDjyNsRXndKLkHIe:matrix.org   | $7eGUUGnG-f-AkUuiEM2CIW_C9_vO5dbxtoo48lFzeWg |      742706 |           742705 | 742705 | !OGEhHVWSdvArJzumhm:matrix.org | $rudfE1NeOC05BNGMoEdFBmCnOxrELXVTV4n7I7iMx6E
 742708 | !OGEhHVWSdvArJzumhm:matrix.org   | $vHX87BC0dhsB5ybdz_jyyANQUwAx2ya9JfRVnUq2sQE |      742708 |           742707 | 742707 | !mjbDjyNsRXndKLkHIe:matrix.org | $H2H9TlDQfJdhMakjvwArYwQ-3FNJCl272Z9k0_m1tNA
 742712 | !mjbDjyNsRXndKLkHIe:matrix.org   | $E568sGBnF3CUGKZQVfykEsN8Cq4RcyBZmdz3DyGaZ-M |      742712 |           742711 | 742711 | !OGEhHVWSdvArJzumhm:matrix.org | $gHSz1KPgIllYE8ryyBpwsZQ57y9ftdMU1zfYuHG68K4
 742713 | !OGEhHVWSdvArJzumhm:matrix.org   | $ar1rB_xWKQdHeAAVTdBbTymWHFJxbLJeTDBzPhOLBuw |      742713 |           742712 | 742712 | !mjbDjyNsRXndKLkHIe:matrix.org | $E568sGBnF3CUGKZQVfykEsN8Cq4RcyBZmdz3DyGaZ-M
 742716 | !mjbDjyNsRXndKLkHIe:matrix.org   | $SH7v2PXNX417twT_3WjqmqBEfzSqYXOGrJEyabKW1MY |      742716 |           742715 | 742715 | !OGEhHVWSdvArJzumhm:matrix.org | $xwiDOzd5NBQ3_EttWPDVHFr77HBf99tcE5PREpEkiZY
 742717 | !OGEhHVWSdvArJzumhm:matrix.org   | $SOeUehZoBftRV4QduWhHeCcq89uQrYCBTOpzxyAdDQ8 |      742717 |           742716 | 742716 | !mjbDjyNsRXndKLkHIe:matrix.org | $SH7v2PXNX417twT_3WjqmqBEfzSqYXOGrJEyabKW1MY
 742724 | !mjbDjyNsRXndKLkHIe:matrix.org   | $gGg4Ge1nuFDorrOylRvobbTZKYwXqw38W8pz0lYi0Ik |      742724 |           742723 | 742723 | !OGEhHVWSdvArJzumhm:matrix.org | $7VzU6Diy1z6scSXb7JRomKEtGTjT3VWNFI1Yz6VZwUc
 742725 | !OGEhHVWSdvArJzumhm:matrix.org   | $iLehzVciY311KlnaPgIztkQGyIOCG22SemJcvyBpxj8 |      742725 |           742724 | 742724 | !mjbDjyNsRXndKLkHIe:matrix.org | $gGg4Ge1nuFDorrOylRvobbTZKYwXqw38W8pz0lYi0Ik
 742731 | !mjbDjyNsRXndKLkHIe:matrix.org   | $K2apsC6NQN93KRUUE4NI2qsgePZVtkmVYiF--m8z8y8 |      742731 |           742730 | 742730 | !OGEhHVWSdvArJzumhm:matrix.org | $ondpxRRgEX5bvW2M1pQ3k6hYrZk9-i1Mr5JJbITPDrM
 742733 | !OGEhHVWSdvArJzumhm:matrix.org   | $e4S-hSsTbLquwE1u17kzfX3gmF2X4C3KS8a9TArRqjs |      742733 |           742732 | 742732 | !mjbDjyNsRXndKLkHIe:matrix.org | $gEFPHRuo3vbhy5-BjjLy18jyVFLsKY6u22ajB4TnAs0
 742734 | !mjbDjyNsRXndKLkHIe:matrix.org   | $eaoXxMJ7LOCfQO75fVnYMZYhDie7c_lLNM3JLYjO13o |      742734 |           742733 | 742733 | !OGEhHVWSdvArJzumhm:matrix.org | $e4S-hSsTbLquwE1u17kzfX3gmF2X4C3KS8a9TArRqjs
 742735 | !OGEhHVWSdvArJzumhm:matrix.org   | $JRTnjD9PQInaWgKVpK_zIh2asc3IxWBolKoLZmVjw2w |      742735 |           742734 | 742734 | !mjbDjyNsRXndKLkHIe:matrix.org | $eaoXxMJ7LOCfQO75fVnYMZYhDie7c_lLNM3JLYjO13o
 742736 | !mjbDjyNsRXndKLkHIe:matrix.org   | $17VBb5c8yENt7nz3JnTHR6zs7rWR_XwhDJSNviDL9Uo |      742736 |           742735 | 742735 | !OGEhHVWSdvArJzumhm:matrix.org | $JRTnjD9PQInaWgKVpK_zIh2asc3IxWBolKoLZmVjw2w
 742738 | !OGEhHVWSdvArJzumhm:matrix.org   | $T2ukM-22b2PJdFSfeBabPizM3pQCCGlzJacFiiup1Mk |      742738 |           742737 | 742737 | !mjbDjyNsRXndKLkHIe:matrix.org | $iAE3TVHronrPsfKGRkxcUJIZmzjE9HyD__xM3acJ0-w
 742750 | !xYvNcQPhnkrdUmYczI:matrix.org   | $5LguKnKqEsOclr8F6Tarez65N-XRyny9dmi_dnYtfvE |      742750 |           742749 | 742749 | !OGEhHVWSdvArJzumhm:matrix.org | $pDSWrSRLr2lOrWWXIhWDkuxDWXxwltJ8AXXt9wwNNU0
 742751 | !mjbDjyNsRXndKLkHIe:matrix.org   | $_em7gCNp1yGTYcD47VN8alHi5qtDCSOTLDFsOf2AZYc |      742751 |           742750 | 742750 | !xYvNcQPhnkrdUmYczI:matrix.org | $5LguKnKqEsOclr8F6Tarez65N-XRyny9dmi_dnYtfvE
 742754 | !OGEhHVWSdvArJzumhm:matrix.org   | $k8lVDvYNfXzJeXGQEHS1skQkbZsDcYIx2xc2S67crsQ |      742754 |           742753 | 742753 | !mjbDjyNsRXndKLkHIe:matrix.org | $8rnhE3tswyoWucqL1RwagJ8POXhDJ7v3hRoEMLXH2q4
 742757 | !xYvNcQPhnkrdUmYczI:matrix.org   | $16_cvJxO3AZHZXNSVHW9EqN7O7Fx-2XMcLrBY3kxBmE |      742757 |           742756 | 742756 | !OGEhHVWSdvArJzumhm:matrix.org | $XM7y-9ZCJ3WVw4NhpvEvL7XzG41SW2jWZBjqQk3IjtE
 742758 | !mjbDjyNsRXndKLkHIe:matrix.org   | $FhgRdM62K9IsRhpweAXk75CvnTeEJT-4bPAYes4zLEg |      742758 |           742757 | 742757 | !xYvNcQPhnkrdUmYczI:matrix.org | $16_cvJxO3AZHZXNSVHW9EqN7O7Fx-2XMcLrBY3kxBmE
 742760 | !OGEhHVWSdvArJzumhm:matrix.org   | $E3hcdWrHNZtWajNaTd6aPnAAowtJAWk6MXLfCmEuEiU |      742760 |           742758 | 742758 | !mjbDjyNsRXndKLkHIe:matrix.org | $FhgRdM62K9IsRhpweAXk75CvnTeEJT-4bPAYes4zLEg
 742761 | !mjbDjyNsRXndKLkHIe:matrix.org   | $SGUYCjl91khVh49VBAEObBADu47J6q27G6jA84nDyBQ |      742761 |           742760 | 742760 | !OGEhHVWSdvArJzumhm:matrix.org | $E3hcdWrHNZtWajNaTd6aPnAAowtJAWk6MXLfCmEuEiU
 742763 | !OGEhHVWSdvArJzumhm:matrix.org   | $4dsH4SJufBC12Eprmsm1IczFcb4PdAZlq0nO4L96iHw |      742763 |           742762 | 742762 | !mjbDjyNsRXndKLkHIe:matrix.org | $XuiHwUTfee5t6w6DGBXwe8u-UQtBy3VG1iKMmhmUUSQ
 742774 | !mjbDjyNsRXndKLkHIe:matrix.org   | $Zr6HuXzqg0VtNIdG_Dr9vjIvn-xl1BXmD2wXtcrnP6k |      742774 |           742773 | 742773 | !OGEhHVWSdvArJzumhm:matrix.org | $zZ3eG9Qxps5ioUMQkShDBgsThwbaff5FnDeEVu7EZ4U
 742785 | !OGEhHVWSdvArJzumhm:matrix.org   | $gqkoqOwZa4m-2l-C4vUp81JbbNHt0RhvAw3zNDecLsc |      742785 |           742784 | 742784 | !mjbDjyNsRXndKLkHIe:matrix.org | $A1RI6YnHjkaYmkrNz8YbrzOauPw9aFhf7VkBpiFBmSE
 742790 | !OGEhHVWSdvArJzumhm:matrix.org   | $BAct0BFtPzULc9xC9ZpkPExmhdieqBT3J93PREmYUBo |      742790 |           742789 | 742789 | !xYvNcQPhnkrdUmYczI:matrix.org | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8
 742812 | !OGEhHVWSdvArJzumhm:matrix.org   | $JC8J8qnIjwsGyc4IEBvg2QAD1nyAOIwaiC9WLmNbx4Q |      742812 |           742811 | 742811 | !xYvNcQPhnkrdUmYczI:matrix.org | $r9P750FnWIMqZWgg_6bmx_flLW-ZasMbky1kyu3MOOQ
 742815 | !xYvNcQPhnkrdUmYczI:matrix.org   | $3RJl-7Sap-9YVt0eLfWsyvPD82isArpGhM2Fa3xyUMg |      742815 |           742814 | 742814 | !OGEhHVWSdvArJzumhm:matrix.org | $qhtRTKoUrKD3XBytNGyACC-7Ppeexf99p63iY7biin8
 742786 | !mjbDjyNsRXndKLkHIe:matrix.org   | $yesnbQFa-PmWzBV7BaEGUCLldFXPWnsyp6Hj2b2LZ4Q |      742786 |           742785 | 742785 | !OGEhHVWSdvArJzumhm:matrix.org | $gqkoqOwZa4m-2l-C4vUp81JbbNHt0RhvAw3zNDecLsc
 742817 | !xYvNcQPhnkrdUmYczI:matrix.org   | $WK847qQk9V7eWn_oq0byr6M4brIiRErXDRfbgCKmRjk |      742817 |           742816 | 742816 | !OGEhHVWSdvArJzumhm:matrix.org | $XZ0JSzsaa0IMwMOAsT7BEnEthCtrspl3uKY8gp4UImk
 743101 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743101 |           743100 | 743100 | !xYvNcQPhnkrdUmYczI:matrix.org | $yHomHoiz2R8IuB3Z6ovHO3uzDGo60pUgj_VEruWUJfM
 742788 | !OGEhHVWSdvArJzumhm:matrix.org   | $j0zXBsbk0bCaZ_IjmN_4Op11ckrq7oyh7BBxEe2yVsE |      742788 |           742787 | 742787 | !mjbDjyNsRXndKLkHIe:matrix.org | $N6GgBcwQf-7JOhww4DtwfmgzuoudBhFKGOF2cr2EuGU
 742816 | !OGEhHVWSdvArJzumhm:matrix.org   | $XZ0JSzsaa0IMwMOAsT7BEnEthCtrspl3uKY8gp4UImk |      742816 |           742815 | 742815 | !xYvNcQPhnkrdUmYczI:matrix.org | $3RJl-7Sap-9YVt0eLfWsyvPD82isArpGhM2Fa3xyUMg
 742789 | !xYvNcQPhnkrdUmYczI:matrix.org   | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8 |      742789 |           742788 | 742788 | !OGEhHVWSdvArJzumhm:matrix.org | $j0zXBsbk0bCaZ_IjmN_4Op11ckrq7oyh7BBxEe2yVsE
 742792 | !xYvNcQPhnkrdUmYczI:matrix.org   | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8 |      742792 |           742791 | 742791 | !OGEhHVWSdvArJzumhm:matrix.org | $Ltx-RHwgptTTowd6SCqdjbo10EOeewUBqk8HNjOr17k
 743113 | !xYvNcQPhnkrdUmYczI:matrix.org   | $_fgwyVRq43OZrgc8YWUweJaRTzQf9haRUGt4QY49kqI |      743113 |           743112 | 743112 | !mjbDjyNsRXndKLkHIe:matrix.org | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU
 743102 | !xYvNcQPhnkrdUmYczI:matrix.org   | $cMOCtwagISN7vZOsByam_3Utq2PdPcKSYabA1o4zAW8 |      743102 |           743101 | 743101 | !mjbDjyNsRXndKLkHIe:matrix.org | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU
 743111 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743111 |           743110 | 743110 | !xYvNcQPhnkrdUmYczI:matrix.org | $EbBMH7ssxwx27J89VeYHn6WIRqu9cW5TlBmv-WQXmE4
 743116 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743116 |           743110 | 743110 | !xYvNcQPhnkrdUmYczI:matrix.org | $EbBMH7ssxwx27J89VeYHn6WIRqu9cW5TlBmv-WQXmE4
```

Now the question is, how do I get this corrected?

 It has the effect that after having logged out my principal user, after logging in again, the initial sync is stuck forever, which can be seen as another error on Element Web/Android

And of course it has an impact in my logs:

```
2020-08-25 18:50:40,842 - synapse.http.server - 80 - ERROR - GET-12 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f1fc27a9100 method='GET' uri='/_matrix/client/r0/sync?filter=21&timeout=0' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$7tPxEanEvRk8ADzN9TxNOxr4__jTh9-PnToak-_kbDY':  ..................... a Massive json construct which I cut off

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 310, in _wait_for_sync_for_user
    result = await self.current_sync_for_user(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 342, in current_sync_for_user
    return await self.generate_sync_result(sync_config, since_token, full_state)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 998, in generate_sync_result
    res = await self._generate_sync_entry_for_rooms(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1430, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 157, in _concurrently_execute_inner
    await maybe_awaitable(func(next(it)))
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1418, in handle_room_entries
    res = await self._generate_room_entry(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1808, in _generate_room_entry
    batch = await self._load_filtered_recents(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 504, in _load_filtered_recents
    current_state_ids_map = await self.state.get_current_state_ids(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 167, in get_current_state_ids
    ret = await self.resolve_state_groups_for_events(room_id, latest_event_ids)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/util/metrics.py", line 88, in measured_func
    r = await func(self, *args, **kwargs)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 388, in resolve_state_groups_for_events
    result = await self._state_resolution_handler.resolve_state_groups(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 510, in resolve_state_groups
    new_state = await resolve_events_with_store(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/v2.py", line 104, in resolve_events_with_store
    raise Exception(
Exception: Attempting to state-resolve for room !xYvNcQPhnkrdUmYczI:matrix.org with event $3fZr80mRY-86Nq0ry4kl-TlF9vIIjFC2_adusEZOQVA which is in !OGEhHVWSdvArJzumhm:matrix.org

```

I needed to delete the logs as they had been growing to 40GB filling up my disk.


Regards

Schnuffle

**Comment by schnuffle** [comment] 2020-08-25 19:56
After deleting the wrong rows, I can login again:
Statement: DELETE FROM state_group_edges WHERE (state_group=X AND prev_state_group=Y) ;

**Comment by richvdh** [comment] 2020-08-26 10:40
@schnuffle I suspect your issue was unrelated, since you're using an older version of synapse. I suggest you upgrade.

since the original reporter is no longer reporting issues, I'm going to close this issue.

**Comment by worldowner** [comment] 2020-08-27 12:03
Yes, sorry for lack of response, I missed notification.
Anyway, for now I decided to ignore the issue because it has no influence on me or users of affected homeserver. I'm confident with SQL so I may just delete those 3 rows in the future.

**Comment by worldowner** [comment] 2022-06-12 20:06
Unfortunately I think that this issue should be reopened. From time to time I re-check those queries to see if problem returned and it did. This happened recently:
```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
1468|!EEE:REMOTE_SERVER|$7jT805cbjr6JbvAo7AFm_S1E8YQs6bDbgRtHmhcUF2c|1468|1467|1467|!FFF:REMOTE_SERVER|$jJ_iNC8kIlfXZqN0piMc9oRpe9rgoWn_HfzFT6Sjf_4```
```

It happened when I was running synapse 1.58.1. During upgrade to 1.60.0 I run DELETE query mentioned in upgrade notes because I had 4 duplicate entries in state_group_edges but it didn't affect the result above.

If I remember correctly last time the issue was that room had 2 candidates for a previous state group. However it doesn't seem to be the case this time:

```
sqlite> select * from state_group_edges where state_group=1468;
1468|1467
sqlite> select * from state_group_edges where state_group=1467;
sqlite>
```
Affected room version is 6.

**Comment by richvdh** [comment] 2022-06-13 10:00
do you happen to have logs covering the time when those events (`$jJ_iNC8kIlfXZqN0piMc9oRpe9rgoWn_HfzFT6Sjf_4`, `$7jT805cbjr6JbvAo7AFm_S1E8YQs6bDbgRtHmhcUF2c`) were received?

**Comment by worldowner** [comment] 2022-06-15 16:15
Also I see that my `events` table contains entries from 2018, 2019, 2022, 2021 and current year. My retention configuration is
```
redaction_retention_period: 1d

retention:
    enabled: true
    default_policy:
        min_lifetime: 1d
        max_lifetime: 7d
    allowed_lifetime_min: 1d
    allowed_lifetime_max: 1y
    purge_jobs:
        - interval: 30m
```
Is it normal or should I open another issue?

**Comment by richvdh** [comment] 2022-06-15 17:23
> Should I do anything to fix database in the meantime?

You had better purge room `!EEE:REMOTE_SERVER`. If it has events from other rooms in its state, then it's pretty badly broken.

> Also I see that my events table contains entries from 2018, 2019, 2022, 2021 and current year.

iirc event retention does not purge state events. Be advised also that event retention is experimental and not recommended for use in production.

**Comment by worldowner** [comment] 2022-06-15 20:35
Maybe the problem is that there is missing candidate for a previous state group for `state_group=1467`?
```
sqlite> select * from state_group_edges where state_group=1468;
1468|1467
sqlite> select * from state_group_edges where state_group=1467;
sqlite>
```

What do you mean by purge?
This room has 2 members, me (on my own homeserver) and another person (on his homeserver). Should I ask this person to leave the room and then use Purge room API (or Delete room API with `force_purge` option because most likely I will be unable to leave the room) API on this room?
Or maybe there is easier way like delete offending event?
There is no issue on the other homeserver. Only my is affected.

**Comment by richvdh** [comment] 2022-06-16 09:51
> Maybe the problem is that there is missing candidate for a previous state group for state_group=1467?

that is not unexpected.

> What do you mean by purge?

Yes, use the Delete room API, with `"purge": true`. The trouble with deleting a single event is that this room is clearly messed up: if we see more problems, we won't know if they are due to lingering problems from before, or if we are really introducing new problems.

**Comment by squahtx** [comment] 2022-07-18 15:50
AIUI there's not much that can be investigated unless the issue happens again, after the room has been purged.

**Comment by babolivier** [comment] 2022-08-24 15:29
As @squahtx says there doesn't seem to be anything we can do about this issue unless it happens again. At this point, given it's been over 2 months since the last report of this issue, I think it's best to close it and reopen it (or open a new issue) if it happens again.

**Closed by babolivier** 2022-08-24 15:29 UTC
Labels: S-Major, T-Defect, X-Needs-Info, A-DAG, O-Uncommon
