### ISSUE TITLE
Matrix-Synapse does not start after synapes_port_db porting

### ISSUE THREAD

**Issue by maicardi** [matrix-org/synapse#9557] opened 2021-03-06 23:44 UTC
### Description

synapes_port_db successfully convert my sqlite3 DB to postgres, but then matrix-synapse fails to start due to errors in the ported DB.

### Steps to reproduce

```
# su - postgres
$ psql
postgres=# DROP DATABASE synapse;
DROP DATABASE
postgres=# CREATE DATABASE synapse
 ENCODING 'UTF8'
 LC_COLLATE='C'
 LC_CTYPE='C'
 template=template0
 OWNER synapse_user;
CREATE DATABASE
[exit psql & back to root user]
service matrix-synapse stop
synapse_port_db --curses --sqlite-database homeserver.db --postgres-config /etc/matrix-synapse/homeserver-postgres.yaml
cp /etc/matrix-synapse/homeserver-postgres.yaml /etc/matrix-synapse/homeserver.yaml
service matrix-synapse start
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details
# cat /var/log/matrix-synapse/homeserver.log
2021-03-06 22:19:55,358 - twisted - 257 - INFO - None - Redirected stdout/stderr to logs
2021-03-06 22:19:55,358 - root - 322 - WARNING - None - ***** STARTING SERVER *****
2021-03-06 22:19:55,358 - root - 323 - WARNING - None - Server /opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.28.0
2021-03-06 22:19:55,358 - root - 324 - INFO - None - Server hostname: asd.yt
2021-03-06 22:19:55,358 - root - 325 - INFO - None - Instance name: master
2021-03-06 22:19:55,358 - synapse.app.homeserver - 357 - INFO - None - Setting up server
2021-03-06 22:19:55,358 - synapse.server - 274 - INFO - None - Setting up.
2021-03-06 22:19:55,456 - synapse.storage.databases - 50 - INFO - None - [database config 'master']: Checking database server
2021-03-06 22:19:55,457 - synapse.storage.databases - 53 - INFO - None - [database config 'master']: Preparing for databases ['main', 'state']
2021-03-06 22:19:55,457 - synapse.storage.prepare_database - 100 - INFO - None - ['main', 'state']: Checking existing schema version
2021-03-06 22:19:55,459 - synapse.storage.prepare_database - 105 - INFO - None - ['main', 'state']: Existing schema is 59 (+11 deltas)
2021-03-06 22:19:55,460 - synapse.storage.databases.main - 379 - INFO - None - Checking database for consistency with configuration...
2021-03-06 22:19:55,461 - synapse.storage.prepare_database - 376 - INFO - None - Applying schema deltas for v59
2021-03-06 22:19:55,462 - synapse.storage.prepare_database - 501 - INFO - None - Schema now up to date
2021-03-06 22:19:55,466 - synapse.storage.databases - 68 - INFO - None - [database config 'master']: Starting 'main' database
2021-03-06 22:19:55,466 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for presence_stream(stream_id)
2021-03-06 22:19:55,467 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for public_room_list_stream(stream_id)
2021-03-06 22:19:55,467 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for device_lists_stream(stream_id)
2021-03-06 22:19:55,468 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for user_signature_stream(stream_id)
2021-03-06 22:19:55,468 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for device_lists_outbound_pokes(stream_id)
2021-03-06 22:19:55,469 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for e2e_cross_signing_keys(stream_id)
2021-03-06 22:19:55,469 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for event_reports(id)
2021-03-06 22:19:55,469 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for push_rules(id)
2021-03-06 22:19:55,470 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for push_rules_enable(id)
2021-03-06 22:19:55,471 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for local_group_updates(stream_id)
2021-03-06 22:19:55,522 - synapse.storage.databases.main.event_push_actions - 538 - INFO - None - Searching for stream ordering 1 month ago
2021-03-06 22:19:55,527 - synapse.storage.databases.main.event_push_actions - 542 - INFO - None - Found stream ordering 1 month ago: it's 29578
2021-03-06 22:19:55,527 - synapse.storage.databases.main.event_push_actions - 545 - INFO - None - Searching for stream ordering 1 day ago
2021-03-06 22:19:55,531 - synapse.storage.databases.main.event_push_actions - 549 - INFO - None - Found stream ordering 1 day ago: it's 35654
2021-03-06 22:19:55,541 - synapse.storage.util.sequence - 174 - WARNING - None - Postgres sequence device_inbox_sequence is behind table device_inbox: 1 < 25734
2021-03-06 22:19:55,541 - twisted - 257 - ERROR - None - ***************************************************************************
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  Postgres sequence 'device_inbox_sequence' is inconsistent with associated
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  table 'device_inbox'. This can happen if Synapse has been downgraded and
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  then upgraded again, or due to a bad migration.
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  To fix this error, shut down Synapse (including any and all workers)
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  and run the following SQL:
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -      SELECT setval('device_inbox_sequence', (
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -          SELECT GREATEST(MAX(stream_id), 0) FROM device_inbox
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -      ));
2021-03-06 22:19:55,542 - twisted - 257 - ERROR - None -  
2021-03-06 22:19:55,543 - twisted - 257 - ERROR - None -  See docs/postgres.md for more information.
2021-03-06 22:19:55,543 - twisted - 257 - ERROR - None -  
2021-03-06 22:19:55,543 - twisted - 257 - ERROR - None - ***************************************************************************
# su - postgres
$ psql synapse
psql (12.6 (Ubuntu 12.6-0ubuntu0.20.04.1))
Type "help" for help.

synapse=# SELECT setval('receipts_sequence', (SELECT GREATEST(MAX(stream_id), 0) FROM receipts_linearized));
 setval 
--------
  33713
(1 row)
[exit psql & back to root user]
# service matrix-synapse start
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.
# tail /var/log/matrix-synapse/homeserver.log 
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  To fix this error, shut down Synapse (including any and all workers)
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  and run the following SQL:
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -      SELECT setval('account_data_sequence', (
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -          SELECT GREATEST(MAX(stream_id), 0) FROM room_account_data
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -      ));
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  See docs/postgres.md for more information.
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None -  
2021-03-06 23:33:34,835 - twisted - 257 - ERROR - None - *******************************************************************************
```

The server then does not quit/crash but stays hanged doing nothing, and it doesn't aswer on TCP port.

Can't get out of this situation.

### Version information

- **Homeserver**:
asd.yt

- **Version**:
{"server_version":"1.28.0","python_version":"3.8.5"}

- **Install method**:
https://packages.matrix.org/debian/

- **Platform**:
Ubuntu Server 20.04 running on a dedicated x64 server

**Comment by maicardi** [comment] 2021-03-07 08:06
This morning I have tried DB porting on a VM server hosting a Matrix-Synapse server for another domain.

Exactly the same happened.

While the asd.yt server has many messages and a few rooms, with a sqlite3 DB of 300MB, this server has just 2 users and some  test messages.

```
2021-03-07 08:03:47,759 - synapse.app.homeserver - 357 - INFO - None - Setting up server
2021-03-07 08:03:47,759 - synapse.server - 274 - INFO - None - Setting up.
2021-03-07 08:03:47,781 - synapse.storage.databases - 50 - INFO - None - [database config 'master']: Checking database server
2021-03-07 08:03:47,782 - synapse.storage.databases - 53 - INFO - None - [database config 'master']: Preparing for databases ['main', 'state']
2021-03-07 08:03:47,782 - synapse.storage.prepare_database - 100 - INFO - None - ['main', 'state']: Checking existing schema version
2021-03-07 08:03:47,784 - synapse.storage.prepare_database - 105 - INFO - None - ['main', 'state']: Existing schema is 59 (+11 deltas)
2021-03-07 08:03:47,785 - synapse.storage.databases.main - 379 - INFO - None - Checking database for consistency with configuration...
2021-03-07 08:03:47,785 - synapse.storage.prepare_database - 376 - INFO - None - Applying schema deltas for v59
2021-03-07 08:03:47,786 - synapse.storage.prepare_database - 501 - INFO - None - Schema now up to date
2021-03-07 08:03:47,790 - synapse.storage.databases - 68 - INFO - None - [database config 'master']: Starting 'main' database
2021-03-07 08:03:47,791 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for presence_stream(stream_id)
2021-03-07 08:03:47,791 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for public_room_list_stream(stream_id)
2021-03-07 08:03:47,792 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for device_lists_stream(stream_id)
2021-03-07 08:03:47,792 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for user_signature_stream(stream_id)
2021-03-07 08:03:47,793 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for device_lists_outbound_pokes(stream_id)
2021-03-07 08:03:47,793 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for e2e_cross_signing_keys(stream_id)
2021-03-07 08:03:47,793 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for event_reports(id)
2021-03-07 08:03:47,856 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for push_rules(id)
2021-03-07 08:03:47,857 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for push_rules_enable(id)
2021-03-07 08:03:47,857 - synapse.storage.util.id_generators - 56 - INFO - None - initialising stream generator for local_group_updates(stream_id)
2021-03-07 08:03:47,860 - synapse.storage.util.sequence - 174 - WARNING - None - Postgres sequence receipts_sequence is behind table receipts_linearized: 1 < 23
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None - *********************************************************************************
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  Postgres sequence 'receipts_sequence' is inconsistent with associated
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  table 'receipts_linearized'. This can happen if Synapse has been downgraded and
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  then upgraded again, or due to a bad migration.
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  To fix this error, shut down Synapse (including any and all workers)
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  and run the following SQL:
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -  
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -      SELECT setval('receipts_sequence', (
2021-03-07 08:03:47,861 - twisted - 257 - ERROR - None -          SELECT GREATEST(MAX(stream_id), 0) FROM receipts_linearized
2021-03-07 08:03:47,862 - twisted - 257 - ERROR - None -      ));
2021-03-07 08:03:47,862 - twisted - 257 - ERROR - None -  
2021-03-07 08:03:47,862 - twisted - 257 - ERROR - None -  See docs/postgres.md for more information.
2021-03-07 08:03:47,862 - twisted - 257 - ERROR - None -  
2021-03-07 08:03:47,862 - twisted - 257 - ERROR - None - *********************************************************************************
```

**Comment by alex9099** [comment] 2021-03-07 23:05
Running these 4 queries (as suggested by the log) seems to fix it for me, not sure if that is just a workaround for something...

```
 SELECT setval('receipts_sequence', (
    SELECT GREATEST(MAX(stream_id), 0) FROM receipts_linearized
  ));

  
  SELECT setval('account_data_sequence', (
 SELECT GREATEST(MAX(stream_id), 0) FROM room_account_data
));

SELECT setval('account_data_sequence', (
   SELECT GREATEST(MAX(stream_id), 0) FROM account_data
  ));
  
  SELECT setval('device_inbox_sequence', (
 SELECT GREATEST(MAX(stream_id), 0) FROM device_inbox
));


```

**Comment by anoadragon453** [comment] 2021-03-08 12:55
I just tried converting a very small database to postgres and had no issues, but I suspect that this may only happen on larger databases. Interestingly `synapse_port_db` [does attempt to set these sequences itself](https://github.com/matrix-org/synapse/blob/16108c579deb17964f3603c7253454b711e9ccd0/scripts/synapse_port_db#L634-L640), so I'm curious as to why they may still be out of date.

**Comment by clokep** [comment] 2021-03-08 13:27
I think this is a duplicate of #9344, which should be fixed in v1.29.0rc1.

**Closed by clokep** 2021-03-08 13:27 UTC
Labels: S-Major, T-Defect

**Comment by maicardi** [comment] 2021-03-08 21:10
Thanks  alex9099 for your advice.

I have succeed in porting the DB with your 4 SQL command plus the one suggested in the log, therefore:

```
SELECT setval('receipts_sequence', (
    SELECT GREATEST(MAX(stream_id), 0) FROM receipts_linearized
  ));

 SELECT setval('receipts_sequence', (
    SELECT GREATEST(MAX(stream_id), 0) FROM receipts_linearized
  ));

  SELECT setval('account_data_sequence', (
 SELECT GREATEST(MAX(stream_id), 0) FROM room_account_data
));

SELECT setval('account_data_sequence', (
   SELECT GREATEST(MAX(stream_id), 0) FROM account_data
  ));

  SELECT setval('device_inbox_sequence', (
 SELECT GREATEST(MAX(stream_id), 0) FROM device_inbox
));

```

**Comment by MasterJubei** [comment] 2021-03-26 11:21
Can a warning be added to the postgresql setup page about this? I ran into this issue.

**Comment by anoadragon453** [comment] 2021-03-26 15:53
@MasterJubei were you using a version of `synapse_port_db` from Synapse v1.26.0 to v1.28.0? This issue is only fixed in v1.29.0+.

**Comment by MasterJubei** [comment] 2021-03-26 23:52
Oh, my bad I must be facing a different issue then.
@anoadragon453 
checking
/_matrix/federation/v1/version
Gives me 1.30, and if that is true it should be fixed for this issue.
https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md
I had followed this guide and every step worked till I tried to restart the matrix server after switching databases. It would error and told me to check journalctl -xe where it did not reveal anything.
So I just went back to sqlite where it is fine there.

**Comment by MasterJubei** [comment] 2021-03-28 12:23
I am on 1.30, I do not think the issue is fixed. I followed the migration tutorial.
In /var/log/matrix-synapse/homeserver.log

```
2021-03-28 12:13:17,825 - twisted - 260 - ERROR - None -  Postgres sequence 'event_auth_chain_id' is inconsistent with associated
2021-03-28 12:13:17,825 - twisted - 260 - ERROR - None -  table 'event_auth_chains'. This can happen if Synapse has been downgraded and
2021-03-28 12:13:17,825 - twisted - 260 - ERROR - None -  then upgraded again, or due to a bad migration.
2021-03-28 12:13:17,825 - twisted - 260 - ERROR - None -  
2021-03-28 12:13:17,825 - twisted - 260 - ERROR - None -  To fix this error, shut down Synapse (including any and all workers)
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -  and run the following SQL:
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -  
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -      SELECT setval('event_auth_chain_id', (
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -          SELECT GREATEST(MAX(chain_id), 0) FROM event_auth_chains
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -      ));
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -  
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -  See docs/postgres.md for more information.
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None -  
2021-03-28 12:13:17,826 - twisted - 260 - ERROR - None - *******************************************************************************
```
Running that command did however fix the issue.

Was the tutorial I followed the first time, although the second time I did this I followed the official postgres migration guide. Same issue. There are slight differences at the end with the tutorial with copying homeserver.db

https://jonathanbossenger.com/setting-up-a-matrix-server-on-ubuntu-20-04-part-2/

For anyone else who followed that tutorial, and who isn't familiar with SQL at all like myself.
I ran:
```
su - postgres
psql --host=localhost --dbname=synapse --username=synapse_user
SELECT setval('event_auth_chain_id', (
SELECT GREATEST(MAX(chain_id), 0) FROM event_auth_chains
));

```
