### ISSUE TITLE
On my custom server, preview invitations contains matrixid instead of displayname

### ISSUE THREAD

**Issue by jeangb** [matrix-org/synapse#2124] opened 2017-04-12 09:56 UTC
I use a home server recently created and _**not federated**_.
On this hs, I have user 1 and user 2, both have display names.
These both users share the same room (non public) with plenty of other users. So they should know each other display names.

To reproduce:

1. With user1, start a new chat with user2 (on whatever client)

On user2, I'm expecting a preview invitation with the **display name** of user 1.
Instead the preview invitation is named with the **matrix id** of user1.
I won't have this problem if I use **matrix.org**.

**Comment by jeangb** [comment] 2017-04-12 14:49
Actually it doesn't concern only the "new chat" (Direct Message) rooms but also the normal rooms.
If a room is created, his name set up, and a user invited, this one won't see the room name but only the matrix id of the inviter.

**Comment by manuroe** [comment] 2017-04-18 12:50
is it an issue with the room_invite_state_types parameter in hs config?

**Comment by richvdh** [comment] 2017-04-26 13:33
@erikjohnston has promised to look at this! \o/

**Comment by manuroe** [comment] 2017-04-26 13:40
The issue is that, in these conditions, we do not understand why matrix.org sends several room states whereas Jean's local HS sends only one, the invite.
We tried to reuse some bits of the config file of matrix.org with no success.

**Comment by erikjohnston** [comment] 2017-04-26 14:48
@manuroe I'm not sure I follow. What differences are you seeing in the /sync responses?

**Comment by erikjohnston** [comment] 2017-04-26 14:50
Oh, I've reproduced where sync only returns the invite event:

```json
{
  "rooms": {
    "leave": {},
    "join": {},
    "invite": {
      "!htCVufIoLwrPeOhvDL:localhost:8480": {
        "invite_state": {
          "events": [
            {
              "origin_server_ts": 1493217947194,
              "sender": "@test2:localhost:8480",
              "event_id": "$149321794732yVvhM:localhost:8480",
              "unsigned": {
                "age": 114541
              },
              "state_key": "@test:localhost:8480",
              "content": {
                "membership": "invite",
                "avatar_url": "mxc://localhost:8480/eRLOMMwLePpxziytumrHyLEB",
                "displayname": "Bob"
              },
              "membership": "invite",
              "type": "m.room.member"
            }
          ]
        }
      }
    }
  }
}
```

**Comment by erikjohnston** [comment] 2017-04-26 15:19
https://github.com/matrix-org/synapse/pull/2163

**Comment by erikjohnston** [comment] 2017-04-28 09:29
Should be fixed on develop now

**Closed by erikjohnston** 2017-04-28 09:29 UTC

**Comment by jeangb** [comment] 2017-04-28 11:52
Thanks @erikjohnston ! I'm going to test it
