### ISSUE TITLE
Cannot accept/reject a third invite to a room

### ISSUE THREAD

**Issue by madduck** [matrix-org/synapse#1987] opened 2017-03-12 22:40 UTC
![ss png](https://cloud.githubusercontent.com/assets/195073/23836730/d855f820-07e1-11e7-81e3-12c6f01fee10.png)

Here's the bit of relevant log I could find:

    a5b:76ff:fe64:d850 - 8008 - Received request: GET /_matrix/client/r0/rooms/!JSzyEZsDkgCkBiJeDY%3Amatrix.org/initialSync?limit=20&access_token=<redacted>
    2017-03-12 23:40:57,407 - synapse.util.async - 201 - INFO - GET-1559416- Acquired linearizer lock 'state_resolve_lock' for key frozenset([119841L, 131490L])
    2017-03-12 23:40:57,408 - synapse.state - 320 - INFO - GET-1559416- Resolving state for !JSzyEZsDkgCkBiJeDY:matrix.org with 2 groups
    2017-03-12 23:40:57,408 - synapse.state - 335 - INFO - GET-1559416- Resolving conflicted state for '!JSzyEZsDkgCkBiJeDY:matrix.org'
    2017-03-12 23:40:57,409 - synapse.state - 497 - INFO - GET-1559416- Asking for 2 conflicted events
    2017-03-12 23:40:57,410 - synapse.state - 508 - INFO - GET-1559416- Asking for 0 auth events
    2017-03-12 23:40:57,411 - synapse.state - 553 - ERROR - GET-1559416- Failed to resolve state
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/synapse/state.py", line 550, in _resolve_with_state
        conflicted_state, auth_events
      File "/usr/lib/python2.7/dist-packages/synapse/state.py", line 597, in _resolve_state_events
        auth_events
      File "/usr/lib/python2.7/dist-packages/synapse/state.py", line 634, in _resolve_auth_events
        event_auth.check(event, auth_events, do_sig_check=False, do_size_check=False)
      File "/usr/lib/python2.7/dist-packages/synapse/event_auth.py", line 91, in check
        "Room %r does not exist" % (event.room_id,)
    SynapseError: 403: Room '!JSzyEZsDkgCkBiJeDY:matrix.org' does not exist
    2017-03-12 23:40:57,417 - synapse.util.async - 208 - INFO - GET-1559416- Releasing linearizer lock 'state_resolve_lock' for key frozenset([119841L, 131490L])
    2017-03-12 23:40:57,418 - synapse.http.server - 123 - INFO - GET-1559416- <XForwardedForRequest at 0x7f2f5651af80 method=GET uri=/_matrix/client/r0/rooms/!JSzyEZsDkgCkBiJeDY%3Amatrix.org/initialSync?limit=20&access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 403 - Room '!JSzyEZsDkgCkBiJeDY:matrix.org' does not exist
    2017-03-12 23:40:57,420 - synapse.access.http.8008 - 91 - INFO - GET-1559416- 2404:130:0:1000:ca5b:76ff:fe64:d850 - 8008 - {@madduck:madduck.net} Processed request: 16ms (8ms, 0ms) (0ms/0) 102B 403 "GET /_matrix/client/r0/rooms/!JSzyEZsDkgCkBiJeDY%3Amatrix.org/initialSync?limit=20&access_token=<redacted> HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36"

**Comment by madduck** [comment] 2017-03-15 22:48
Any idea what I can do to get rid of the invitation? It's stealing screen estate!

**Comment by Half-Shot** [comment] 2017-03-21 19:45
Recommendation would be to remove the invite from the db if the room can't be found? You're risking upsetting the room on the remote server, but it's that or having stuck notifs for everyone else.

Additonally, some kind of check to ensure an incoming invite makes sense before it makes it's way into storage?

**Comment by madduck** [comment] 2017-03-21 20:13
@Half-Shot I tried removing the line from the database on my homeserver, but since the room is on `matrix.org`, it would need to happen there, right?

**Comment by richvdh** [comment] 2017-04-06 13:21
Rooms aren't on any single server - no it doesn't need removing on matrix.org - this state is coming from your own server.

Nevertheless poking in the db is a dangerous option unless you know exactly what you are doing. @Half-Shot: please don't give that advice without explicit sql.

@madduck: It sounds like you might be suffering from https://github.com/vector-im/riot-web/issues/3462. Try clearing the client cache.

**Comment by madduck** [comment] 2017-04-06 13:40
@richvdh okay. This extends across two clients (Web & Android). How does one clear the client cache?

**Comment by madduck** [comment] 2017-04-06 13:47
I found the option to "clear cache" under the Android settings, but even after selecting it and restarting the app, I still can't reject or accept the invitation on Android. I can't find anything in the web app…

**Comment by richvdh** [comment] 2017-04-06 14:21
@madduck: in riot.im/develop, there's a 'clear cache and reload' button on user settings. On riot.im/app, I think the caching is not yet enabled, so just reload.

**Comment by madduck** [comment] 2017-04-06 14:24
@richvdh yes, found it. Unfortunately, the problem persists.

**Comment by richvdh** [comment] 2017-04-07 09:58
In the specific case of @madduck, we have now worked around this by having him mark the invite as rejected in his local database (and then initiating a new chat with the freenode nickserv).

I have now reproduced this on synapse 0.19.2; and *not* reproduced it on synapse 0.20.0-rc1. I think it has probably been fixed by https://github.com/matrix-org/synapse/pull/2025.

Steps to repeat: (you will need to do this with matrix console or similar due to https://github.com/vector-im/riot-web/issues/3580):
* Receive invite
* reject
* receive second invite to same room
* reject again
* receive *third* invite to same room
* attempt to reject
* observe 'Room '!xXGRyyShrrMnWauHhB:example.com' does not exist (M_UNKNOWN)'

**Comment by richvdh** [comment] 2017-04-07 10:28
Bisecting shows that the fix was actually https://github.com/matrix-org/synapse/pull/1996

**Comment by richvdh** [comment] 2017-04-07 11:16
The difference actually happens during the attempt to save the second rejection. 

Background: Rejections are represented as `m.room.member` events with `membership: leave`. We (seem to) do a state resolution before sending the rejection, and another when saving it to the database - but only if there are two or more forward extremities: if there is only one, we don't bother, because it's a simple modification to the previous state of the room. The problem is that a room you have been invited to, but not accepted, doesn't have a full state - it just has a couple of `m.room.member` events. In particular, it is missing the `m.room.create` event, which means that _state resolution always fails_ on such rooms (with a 'room does not exist' error).

What happened before was that when we tried to send the third rejection, we would see that there were two forward extremities (the two previous leaves), and do a state resolution - resulting in the 'room does not exist' error.

Now that #1996 has landed, the second leave is never persisted to the database, because `_calculate_state_delta` now decides that it conflicts with the previous leave. But that part of the rejection-handling is wrapped in an exception handler, to deal with the case that a rejection is sent to a remote server which rejects the rejection. The upshot is that the server updates `local_invites` to clear the invite state, but the leave event is not persisted to the events table. Then, next time you try to send an accept/reject, there is only one extremity, so no conflict.

I feel like this has been fixed by accident, and could easily be un-fixed again. I'll add a sytest for it in a bit.

**Comment by jwaterwo** [comment] 2017-04-13 15:47
duplicate of #1887 ?

**Comment by richvdh** [comment] 2017-04-20 21:17
Test has now landed; closing this.

**Closed by richvdh** 2017-04-20 21:17 UTC

**Comment by richvdh** [comment] 2017-09-28 17:12
For the record: this was fixed by #1996, which landed in v0.20.0-rc1, which was released on 2017-03-30. 0.20.0 proper was released on 2017-04-01.

**Comment by christiansacks** [comment] 2021-04-02 11:27
> Recommendation would be to remove the invite from the db if the room can't be found? You're risking upsetting the room on the remote server, but it's that or having stuck notifs for everyone else.
> 
> Additionally, some kind of check to ensure an incoming invite makes sense before it makes it's way into storage?

how exactly did you do this? I have a stuck invite for a room on a different server, and if I click it, I just get a borked page and nothing else to do except clear cache and retry, endless loop. Please help.
