### ISSUE TITLE
`/state_ids` federation requests causes large memory spikes

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#13246] opened 2022-07-11 12:58 UTC
Especially if we get some in quick succession, as we will cache the state in memory.

We probably want to add a new (specced) endpoint that allows requesting of *deltas* of state, to reduce the amount of data fetched from the DB.

We could also decide not to cache result of `/state_ids`? But we might get the same request multiple times.

**Comment by MadLittleMods** [comment] 2022-08-24 23:08
Duplicate of https://github.com/matrix-org/synapse/issues/6597

**Closed by MadLittleMods** 2022-08-24 23:08 UTC
Labels: T-Task
