### ISSUE TITLE
"Messages containing my display name" notification rule also scans ID of the replied users

### ISSUE THREAD

**Issue by matejdro** [matrix-org/synapse#7569] opened 2020-05-25 13:40 UTC
# Description

I have "Messages containing my display name" notification rule set to Noisy. This rule should only trigger when actual body of the sent messages contains my display name.

However, there is a small edge case in that behavior: When somebody replies to my message (or vice versa), body of the reply also includes quote of the original message and (most importantly) ID of the reply target.

Generally this is not an issue, except when ID of the user contains my display name. In my particular example, my display name is `matejdro` and my matrix server is `matrix.matejdro.com`. This means that any user ID from my server would end with `@matrix.matejdro.com`. Since that suffix contains my display name, it causes Synapse to **send noisy alert on every single reply, regardless of the sender or the contents**.

### Steps to reproduce

- Set "Messages containing my display name" notification rule to noisy
- Set your display name to the same domain as your matrix server
- Have someone reply to any message that was sent from the user (or puppet) on your homeserver
- you will receive notification of that reply, regardless of the message's content.

### Version information

- **Homeserver**: My own homeserver

- **Version**: `{"server_version": "1.12.4", "python_version": "3.7.7"}`

- **Install method**: Docker

**Comment by matejdro** [comment] 2020-05-25 16:13
Same als oapplies to "Messages containing my username" setting.

**Comment by anoadragon453** [comment] 2020-05-26 12:38
Duplicate of https://github.com/matrix-org/synapse/issues/6202, which is tracked by https://github.com/vector-im/riot-web/issues/7874.

**Closed by anoadragon453** 2020-05-26 12:38 UTC
