### ISSUE TITLE
Synapse doesn't accept m.room.power_level events with string values even though it sends them

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#12538] opened 2022-04-25 10:18 UTC
### Description

Synapse will happily send clients malformed m.room.power_level events with string power levels yet will not accept them, causing stuck PLs in a room where the client shouldn't be expected to have to sanitise the event which it was sent.

### Steps to reproduce

- Have a room with a power level event giving someone PL `"0"` 
- Try to update the power level of someone else

More context https://github.com/vector-im/element-web/issues/19751#issuecomment-1015366213
Related https://github.com/matrix-org/synapse/issues/12537 (same cause)

### Version information

- **Homeserver**: matrix.org

**Comment by richvdh** [comment] 2022-04-26 10:05
I'm not really sure what we should do about this, tbh.

Obviously it's caused by the validation in #10232. On the one hand, it seems obvious that we shouldn't allow clients to send malformed PL events. On the other, if the PL event is malformed to start with, it's maybe not reasonable to require clients to "fix" it.

But attempting to "fix" the event before we pass it on to clients doesn't feel good either.

Maybe we should allow clients to send malformed PL events if the original PL event is malformed?

**Comment by richvdh** [comment] 2022-04-26 10:06
(Maybe we should just fix #12537 and then tell everyone they have to upgrade to a modern room version...)

**Comment by dom96** [comment] 2022-04-26 22:51
While you all resolve this, is there any workaround we can use for our channel? I need to be able to give mod rights to others as it's currently just me and I am not always online to moderate.

**Comment by richvdh** [comment] 2022-04-27 09:50
> While you all resolve this, is there any workaround we can use for our channel?

use the /devtools to replace the strings in the PL event.

**Comment by erciccione** [comment] 2022-04-27 10:17
> use the /devtools to replace the strings in the PL event.

Worked for me. Was unable to give mod powers until i changed all strings into integers.

**Comment by dom96** [comment] 2022-04-27 14:42
>>  use the /devtools to replace the strings in the PL event.
>
> Worked for me. Was unable to give mod powers until i changed all strings into integers.

After figuring out what `/devtools` meant it also worked for me, thanks! (for those that don't know and want to workaround as well: just type in `/devtools` into the Matrix chat box)

**Comment by richvdh** [comment] 2022-04-27 15:25
> Richard gave me "thumbs down" but 2 days ago in #12537 he wanted **to pass them through int()** himself :)

In room upgrades. Not where you suggest.

**Comment by richvdh** [comment] 2022-04-28 16:20
> (Maybe we should just fix https://github.com/matrix-org/synapse/issues/12537 and then tell everyone they have to upgrade to a modern room version...)

We'll wait until #12537 is fixed, but this is our current preferred approach

**Comment by MadLittleMods** [comment] 2023-04-25 22:59
https://github.com/matrix-org/synapse/issues/12537 was closed via https://github.com/matrix-org/synapse/pull/12657

Can we close this if our preferred approach is to force people to upgrade to a modern room version and that works now?

**Comment by DMRobertson** [comment] 2023-04-26 09:51
Let's do so.

**Closed by DMRobertson** 2023-04-26 09:51 UTC
Labels: T-Defect
