### ISSUE TITLE
Exception in user_directory.notify_new_event

### ISSUE THREAD

**Issue by steinex** [matrix-org/synapse#12763] opened 2022-05-17 13:08 UTC
### Description

For 2 days now, Synapse over and over spams the following exception into it's log:
```
2022-05-17 15:04:36,496 - synapse.metrics.background_process_metrics - 245 - ERROR - user_directory.notify_new_event-141 - Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/metrics/background_process_metrics.py", line 243, in run
    return await func(*args, **kwargs)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/handlers/user_directory.py", line 119, in process
    await self._unsafe_process()
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/handlers/user_directory.py", line 182, in _unsafe_process
    await self._handle_deltas(deltas)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/handlers/user_directory.py", line 211, in _handle_deltas
    await self._handle_room_membership_event(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/handlers/user_directory.py", line 348, in _handle_room_membership_event
    await self._handle_possible_remote_profile_change(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/handlers/user_directory.py", line 478, in _handle_possible_remote_profile_change
    await self.store.update_profile_in_user_dir(user_id, new_name, new_avatar)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/databases/main/user_directory.py", line 522, in update_profile_in_user_dir
    await self.db_pool.runInteraction(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 814, in runInteraction
    return await delay_cancellation(_runInteraction())
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 786, in _runInteraction
    result = await self.runWithConnection(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 909, in runWithConnection
    return await make_deferred_yieldable(
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/home/synapse/.local/lib/python3.10/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 902, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 650, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/databases/main/user_directory.py", line 479, in _update_profile_in_user_dir_txn
    self.db_pool.simple_upsert_txn(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 1150, in simple_upsert_txn
    return self.simple_upsert_txn_native_upsert(
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 1276, in simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 337, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/synapse/.local/lib/python3.10/site-packages/synapse/storage/database.py", line 379, in _do_execute
    return func(sql, *args, **kwargs)
ValueError: A string literal cannot contain NUL (0x00) characters.
```

### Steps to reproduce

I can't say what triggered the problem, it suddenly started.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: m.nognu.de

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: started on 1.58.0, meanwhile on 1.59.0 but issue still present

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux x86_64, Python 3.10.4, single synapse (no workers)
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by DMRobertson** [comment] 2022-05-17 13:09
Duplicate of #12755.

**Closed as completed by DMRobertson** 2022-05-17 13:09 UTC
