### ISSUE TITLE
Missing events cause clients to stop syncing on login

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#12820] opened 2022-05-20 15:49 UTC
Assumingly caused by the previously added check for room consistency, client logins fail or load forever due to a missing event response. Depending on how tech savey the affected user is, it is hard to get the actual event id because at least with loglevel ERROR, synapse does not write anything to the logs.

Element-android seems to load forever as people wrote me and Fluffy returns a bit more info.

I know that there is a similar issue, but this query https://github.com/matrix-org/synapse/issues/12549#issuecomment-1119552850 returns `0 rows` for me and i don't find errors in my log... (has the loglevel for this problem changed?) .

**Comment by donicrosby** [comment] 2022-05-24 00:17
I'm also having this same issue, once I clear my cache on my client I can no longer sync with my home server. No errors showing up in logs on INFO level. All of the other database queries, show expected values (0 returned rows). I'm not even sure what the problem is other than Element timing out with no usable errors in the console output.

**Comment by squahtx** [comment] 2022-05-25 10:20
maybe the same as #12837 ? It's hard to tell without INFO-level logs.

**Comment by squahtx** [comment] 2022-05-25 10:31
@verymilan Could you post logs containing the errors you do see?

**Comment by squahtx** [comment] 2022-05-25 10:34
@donicrosby Could you get some logs spanning your sync attempts please?

Also the `Awaiting un-partial-stating of events` stack traces can be safely ignored.

**Comment by richvdh** [comment] 2022-05-25 10:44
> Also the `Awaiting un-partial-stating of events` stack traces can be safely ignored.

er, they suggest that the *extremely* experimental "faster joins" option is enabled, which certainly has the potential to break everything!

**Comment by squahtx** [comment] 2022-05-25 10:55
> > Also the `Awaiting un-partial-stating of events` stack traces can be safely ignored.
> 
> er, they suggest that the _extremely_ experimental "faster joins" option is enabled, which certainly has the potential to break everything!

arg, you're right.
@donicrosby Could you file a new issue please and post some example stack traces? There is a good chance you've run into #12642

**Comment by Kokokokoka** [comment] 2022-05-25 11:37
Have the same issue (I think) no rows from https://github.com/matrix-org/synapse/issues/12549#issuecomment-1119552850 
```
synapse=# select e.room_id, count(*) 
  from events e left join rejections r using (event_id) left join event_to_state_groups esg using (event_id) 
  where not e.outlier and esg.event_id is null and r.event_id is null
  group by e.room_id;
 room_id | count 
---------+-------
(0 rows)
```
`select * from events where event_id = '$aIqnBuJ5eUlApXssddFla-xiRUzzHBcBjWpRV9RccVI';`
```
 topological_ordering |                   event_id                   |       type       |              room_id              | content | unrecognized_keys | processed | outlier | depth | origin_server_ts |  received_ts  |        sender        | contains_url | instance_name | stream_ordering | state_key | rejection_reason 
----------------------+----------------------------------------------+------------------+-----------------------------------+---------+-------------------+-----------+---------+-------+------------------+---------------+----------------------+--------------+---------------+-----------------+-----------+------------------
                   15 | $aIqnBuJ5eUlApXssddFla-xiRUzzHBcBjWpRV9RccVI | m.room.redaction | !EexVSGiDHsNwAPufoF:xxx |         |                   | t         | f       |    15 |    1644079535750 | 1644079535762 | @xxxx | f            | master        |         1851149 |           | 
(1 row)


```

[sync phase](https://files.catbox.moe/kb5uhr.png)

**Comment by donicrosby** [comment] 2022-05-25 17:32
@squahtx I have created #12878 that explains the symptoms that I'm currently having

**Comment by johndball** [comment] 2022-05-26 00:56
I might have a related issue? I thought it was an Element problem, but what you described is what I am experiencing and I do not have faster_joins anywhere in my config. I can see in developer tools that there is a never ending /sync job. This is the issue I opened in Element - https://github.com/vector-im/element-web/issues/22357

There are dozens of these:
sync error M_NOT_FOUND: Could not find event $bEbwpl46iHvYccVAwpkLp6-qzxdeCCmiQTxbo1MObAQ [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
M_NOT_FOUND: Could not find event $bEbwpl46iHvYccVAwpkLp6-qzxdeCCmiQTxbo1MObAQ

GEThttps://[server name redacted].com/_matrix/client/r0/sync?filter=1&timeout=0&_cacheBuster=1653526525072
[HTTP/2 404 Not Found 171ms]

/sync error M_NOT_FOUND: Could not find event $bEbwpl46iHvYccVAwpkLp6-qzxdeCCmiQTxbo1MObAQ [rageshake.ts:63:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
M_NOT_FOUND: Could not find event $bEbwpl46iHvYccVAwpkLp6-qzxdeCCmiQTxbo1MObAQ

Unfortunately I cannot get any logs other than in developer view as I've effectively lost all access to my homeserver, so...

**Comment by johndball** [comment] 2022-05-26 01:33
After trying multiple "things", I ended up rolling back to Matrix Synapse 1.57.0 from 1.59.1 and my clients instantly signed in. The message sync issues disappeared. 
 v 1.58 and it did not work, but downgrade to 1.57.0 did work.

**Comment by verymilan** [comment] 2022-05-26 06:00
> @verymilan Could you post logs containing the errors you do see?

What @johndball just wrote is actually pretty much all i know from other users reporting (and from a Fluffy screenshot, it lets the error message shine through)  – i did not experience it myself yet...

**Comment by richvdh** [comment] 2022-05-26 09:28
I'm going to close this, as it's not currently an actionable bug report, and people are reporting completely unrelated things on the same issue.

Please be aware that we cannot debug any problems without INFO-level synapse logs. If you choose to turn off your logging, we cannot help you.

If you are continuing to experience problems, please open a *new* issue, rather than posting on an issue that looks vaguely related, explaining **clearly** the symptoms you are seeing, and **including INFO-level synapse logs**.

**Closed by richvdh** 2022-05-26 09:28 UTC
Labels: X-Needs-Info

**Comment by verymilan** [comment] 2022-05-26 09:36
Oh well, the very first comment stated that there also is nothing on INFO so i didnt bother...

**Comment by richvdh** [comment] 2022-05-26 09:37
> Oh well, the very first comment stated that there also is nothing on INFO so i didnt bother...

As I said, this issue has had multiple people reporting completely unrelated problems.

**Comment by richvdh** [comment] 2022-05-26 09:45
oh also: please include which **version** of Synapse you are using in any issue reports.
