### ISSUE TITLE
Room admins lost after originating server goes down

### ISSUE THREAD

**Issue by muppeth** [matrix-org/synapse#9139] opened 2021-01-16 22:07 UTC
### Description

All existing admins of a room disappeared after the originating server went down for good including admins on other servers. This creates situation where room is left without an admin
### Steps to reproduce

- Give admin priv to user on another server
- Nuke your own server
- Wait few days
- Check as the new user if you are still admin

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
I have a proof of the user getting the 100 priviledge on the room. There seem to be no other event pointing to the user being removed from admin position later on. 
Room ID: !uDQoIebqsjEEtmWLrO:disroot.org
Event ID: $16067909367001DedIY:disroot.org
      "@redpiller:matrix.org": 100
      "@appservice-irc:matrix.org": 100,

All of those users including others with priv 50 kept their priviledge.  

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2021-01-18 19:50
Hey @muppeth I'm having some trouble following your report here. Could you clarify your steps of what occurred? Do you know if these steps are reproducible or is this just from observation?

**Comment by callahad** [comment] 2021-01-21 22:40
My best reading of the scenario is:

1. A user on a homeserver creates a room
2. A mix of local and federated users join the room, some are given powerlevel 100
3. The homeserver goes offline permanently
4. From the perspective of a federated user, all of the admins (local and federated) in the room disappeared (which I take to mean: lost their admin powerlevel.)

It seems like somehow the event where a federated user was given powerlevel 100 is present and known, but that powerlevel is not reflected in the current state. 

@muppeth could you please clarify?

**Comment by richvdh** [comment] 2021-01-22 10:27
Assuming @callahad's reading is correct, this sounds like it may have been caused by a state reset (see https://github.com/matrix-org/synapse/issues/1953 for some context on what that means, if you're unfamiliar).

These should be less likely in modern room versions, though not unknown (#8629).

So one question here is "what room version was this"? If it was room v1 I'd just write it off as a state reset and move on. If not, it probably bears more investigation.

**Comment by muppeth** [comment] 2021-01-23 10:03
@rickvdh yes it is room ver1. Does that then mean the control over the room is totally lost?

**Comment by muppeth** [comment] 2021-01-31 12:22
Sorry for a bump, but is there anything that can be done at this point?

**Comment by muppeth** [comment] 2021-01-31 12:28
I just checked with another user on PTIO server and he sees the admins on his end. Not sure if it's the state of the room on that server (when creating account here and joining I see the current / broken state of the room) or his client. But yeah kinda annoying loosing access to quite a big room in the network.

**Comment by clokep** [comment] 2021-02-23 13:27
> @callahad From perspective of federated user, I would assume those who had power level 100 would remain having that despite the owner of the room leaving the room. Form federation perspective homeserver going down would not mean anything (at least what I thought) as it is just considered currently offline. Theoretically it could come back at anytime. So why this should matter? The only thing that is different from the federation perspecitve apart form server being down is that the owner of the room left the room. But there were other users from federated third party servers with power level 50 and 100.

Yes this is all correct. It seems that the room suffered a "state reset", which is a bug in the v1 state algorithm used by room version 1. This is fixed in room version 2 (although I'd recommend jumping to the newest room version).

It seems that the thing to do here is to upgrade the room to a newer room version. This can be done by typing `/upgraderoom 6` in Element. You'll need to have a user with the appropriate power levels to do this, so hopefully one of the remaining users is able to perform this upgrade!

**Comment by callahad** [comment] 2021-02-23 14:10
Closing as a known issue with the Matrix specification which has been resolved in later room versions.

**Closed by callahad** 2021-02-23 14:10 UTC
Labels: X-Needs-Info, z-info-needed
