### ISSUE TITLE
missing `room_type` in `/_synapse/admin/v1/rooms/` API endpoint

### ISSUE THREAD

**Issue by airblag** [matrix-org/synapse#12692] opened 2022-05-10 12:32 UTC
I'm writting synapse admin tool to manage my homeserver. I wanted to add a subcommand for managing spaces, but as far as I searched, I cannot find any endpoint giving me a list of local rooms with `room_type == m.space` or any direct endpoint for dealing with spaces.

The endpoint ` /_synapse/admin/v1/rooms/` that I use to retrieve a room list is not returning `room_type` in the json.

It would be really helpfull to get it, to be able to identify spaces on a local home server.
Since spaces are just special rooms, I think it this way would be good enough to allow administrative interaction with spaces.

**Comment by clokep** [comment] 2022-05-10 12:44
I think this is essentially a duplicate of #11904.

**Closed by clokep** 2022-05-10 12:44 UTC
