### ISSUE TITLE
"Internal server error" when sending "\n\u0000" in irc bridged room

### ISSUE THREAD

**Issue by Celmor** [matrix-org/synapse#9785] opened 2021-04-11 07:42 UTC
### Description

When sending a text message containing "\u0000" the message isn't send and an "internal server error" is reported.

### Steps to reproduce

Raw example text which caused this issue:
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "sending this text doesn't work: https://termbin.com/25z6\u0000"
  },
  "event_id": "~!OGEhHVWSdvArJzumhm:matrix.org:m1618126067831.34",
  "user_id": "@Celmor:matrix.org",
  "sender": "@Celmor:matrix.org",
  "room_id": "!OGEhHVWSdvArJzumhm:matrix.org",
  "origin_server_ts": 1618126067831
}
```

on linux:
- run `nc termbin.com 9999 <<< "some text" | xclip -i -sel primary`
- paste and send in a matrix room
- get "internal server error"

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:
matrix.org

- **Version**:

element client:  1.7.23-1

- **Platform**:

OS: Linux
uname -a: `Linux Celmor-PC 5.11.10-1-MANJARO #1 SMP PREEMPT Thu Mar 25 17:14:55 UTC 2021 x86_64 GNU/Linux`

**Comment by clokep** [comment] 2021-04-12 12:02
Thanks for filing. This is a duplicate of #9341.

**Closed by clokep** 2021-04-12 12:02 UTC
