### ISSUE TITLE
python failure at the installation

### ISSUE THREAD

**Issue by fertigfs** [matrix-org/synapse#10023] opened 2021-05-19 16:37 UTC
Hello all,
I've been trying for days to follow these instructions....
https://www.youtube.com/watch?v=H-6kfIqPoI4
...to install a Matrix Server in a Proxmox LXC container.
But whenever I include "docker logs synapse",
I get the following error message...
root@matrixxx:/var/lib/docker# docker logs synapse
This server is configured to use 'matrix.org' as its trusted key server via the parameter
trusted_key_servers configuration option. matrix.org' is a good choice for a key server, as it is a durable
server because it is durable, stable, and trusted. However, some administrators will want to use
want to use a different server for this purpose.

To suppress this warning and continue using 'matrix.org', admins should use the option
suppress_key_server_warning" option in the "homeserver.yaml" file to true.
--------------------------------------------------------------------------------
Traceback (last call):
  File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handler[name])
  file "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  file "/usr/local/lib/python3.8/logging/handlers.py", line 200, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  file "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/homeserver.log'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  file "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 507, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 502, in main
    hs = setup(sys.argv[1:])
  file "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 355, in setup
    synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
  File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 318, in setup_logging
    _setup_stdlib_logging(config, log_config_path, logBeginner=logBeginner)
  File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 204, in _setup_stdlib_logging
    _load_logging_config(log_config_path)
  file "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 282, in _load_logging_config
    logging.config.dictConfig(log_config)
  File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  file "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'.

What can I do to make it work.
It has something to do with python.
I am running version 3.8.5.
Maybe someone can help me.
I am desperate...

Translated with www.DeepL.com/Translator (free version)

**Comment by erikjohnston** [comment] 2021-05-20 11:21
Are you trying to run the as non root by any chance? This sounds like https://github.com/matrix-org/synapse/issues/9970

**Comment by fertigfs** [comment] 2021-05-20 14:43
@erikjohnston i startet it as root and no root:(
i made a vm and tried it there same problem.

**Comment by Houndie** [comment] 2021-05-20 14:55
Just chiming in to say I also hit this error, although I've yet to start debugging.  Running docker container matrixdotorg/synapse:v1.34.0, default generated config.

**Comment by Houndie** [comment] 2021-05-20 15:05
Actually this does sound like a complete duplicate of #9970 and can probably be closed as duplicate.  @fertigfs there's several workarounds in that ticket, such as changing the location of the logfile, or my personal preference, just disabling logging to the file altogether, as docker will capture the stdout logs.

**Comment by itsarchy** [comment] 2021-05-21 08:47
same problem. doesnt work with root or non-root user.

**Comment by fertigfs** [comment] 2021-05-21 11:57
Change the path to homeserver.log to /data/homeserver.log before you start the container.you find it in the logging section

**Comment by erikjohnston** [comment] 2021-05-24 09:18
I'm going to close this as a duplicate of #9970

**Closed by erikjohnston** 2021-05-24 09:18 UTC
Labels: X-Needs-Info
