### ISSUE TITLE
Registration via email fails: emails not delivered; element-web reports "Not Found"

### ISSUE THREAD

**Issue by vanovarderesyan** [matrix-org/synapse#12741] opened 2022-05-16 13:05 UTC
Hi. I want to authenticate the registration process with email in order for users to get confirmation emails. Currently, I added the email field in the registration form, however, when the email is sent, It is not actually delivered. It shows Not Found error. Please, let me know what should I setup in setting in order to solve this issue. Or if there is such an example, please, send me for checking. Thanks in advance.
![image](https://user-images.githubusercontent.com/36670993/168599109-b6fe80b2-3a9c-4f71-970c-f5b188fd6f34.png)

**Comment by DMRobertson** [comment] 2022-05-16 13:21
> when the email is sent, It is not actually delivered.

Are there any errors related to emails in your server's logs? Try looking for where `/register` request is handled in the logs.

In your Chrome screenshot, the `register` request is red, which usually indicates an error. What was its status code?

Have you made any recent/relevant changes to Synapse config? If so, please share.

**Comment by vanovarderesyan** [comment] 2022-05-16 13:56
![image](https://user-images.githubusercontent.com/36670993/168602935-99863a7d-156f-4f1e-aa57-94cfb2f4bf38.png)

![image](https://user-images.githubusercontent.com/36670993/168603000-5941f86c-5db4-4235-ba8e-b9cc68e58a83.png)
Via these screenshots you will see from where the issue comes. Yes, I did changes in configs but I am not sure that I have done what was exactly requested and if it's not hard for you, could you please tell me which lines should I remove from the comment for these all to work correctly.

**Comment by DMRobertson** [comment] 2022-05-16 15:53
@vanovarderesyan you have posted a screenshot of a plaintext password (and a session ID). I hope that's an example password rather than one you actually use. If you do use it, I suggest changing it immediately.

In order to understand where "Not Found" comes from, we'll need logs from Synapse. We won't be able to make progress without those.

For the config: there might be hints in [Synapse's configuration manual](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#registration).

**Comment by vanovarderesyan** [comment] 2022-05-17 06:05
![image](https://user-images.githubusercontent.com/36670993/168739981-f4688dd6-d071-4af6-9f11-144eaae58877.png)
@DMRobertson thank you for the information. After resolving configs, the error has been changed (see screenshot). Can you please tell me now what's the problem?

**Comment by vanovarderesyan** [comment] 2022-05-17 06:05
![image](https://user-images.githubusercontent.com/36670993/168739981-f4688dd6-d071-4af6-9f11-144eaae58877.png)
@DMRobertson thank you for the information. After resolving configs, the error has been changed (see screenshot). Can you please tell me now what's the problem?

**Comment by vanovarderesyan** [comment] 2022-05-17 06:16
![image](https://user-images.githubusercontent.com/36670993/168741630-ef29dafe-3ee9-4d05-aca5-05873bba27ea.png)


![image](https://user-images.githubusercontent.com/36670993/168741658-a1de5a52-1832-4cbd-9668-4777beb5fa11.png)

allowed_local_3pids After changing this key\s value in the configs, I again got the not found error which probably means that the previous problem remains.

**Comment by DMRobertson** [comment] 2022-05-17 12:02
As per https://github.com/matrix-org/synapse/issues/12741#issuecomment-1127845272, I'll need logs from Synapse to understand what the problem is. The [logging config](https://matrix-org.github.io/synapse/latest/usage/configuration/logging_sample_config.html) should tell you where to look for log files.

**Comment by vanovarderesyan** [comment] 2022-05-17 12:26
![image](https://user-images.githubusercontent.com/36670993/168810104-0e645a2e-e23f-4dfa-88ec-44db7973e40b.png)

I think these are the logs that you may need to check. Are there fixed configs for email verification that I can use? If there are by any chance, please, send them to me.

**Comment by babolivier** [comment] 2022-05-17 13:16
@vanovarderesyan It looks to me like the issue is with the double slash in the URL at the line that says `Received response to POST ...`.

It looks to me like you might have something like this in your configuration file:

```yaml
        account_threepid_delegates:
            email: http://matrix-interview.com/
```

Note the trailing slash at the end of the domain. If that's what you have then this is where your issue lies. If you remove it (i.e. set this value to `http://matrix-interview.com`, with no trailing slash) then it should hopefully work.

**Comment by babolivier** [comment] 2022-05-17 13:29
I see. I assume you are running Sydent on that domain (alongside Synapse), but a 404 on that route leads me to believe that your reverse proxy might not be configured to proxy requests to Sydent. I suggest checking your reverse proxy configuration to check whether that is the case.

**Comment by vanovarderesyan** [comment] 2022-05-17 13:34
python3 -m synapse.app.homeserver      --server-name "localhost:8081"         --config-path "8081.config"         --report-stats no

I am runnin everything only with this one, and connecting the domain with the help of a proxy from Nginx
.

**Comment by vanovarderesyan** [comment] 2022-05-17 13:49
Thank you very much. As both of them were activated, that is why it wasn't looking at SMTP configs.

**Comment by babolivier** [comment] 2022-05-17 14:02
Cool, since it sounds like this was the source of the issue I'm going to close it then :slightly_smiling_face: Feel free to shout if it's still not resolved, and for other support questions feel free to use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), which is our preferred medium for support.

**Closed by babolivier** 2022-05-17 14:02 UTC
Labels: X-Needs-Info
