### ISSUE TITLE
allow passing postgres password as environment variable

### ISSUE THREAD

**Issue by woojoo666** [matrix-org/synapse#11646] opened 2021-12-25 23:05 UTC
**Description:**

From looking at the docs and source code, it seems like there is no way to provide the postgres password as an environment variable. You can provide it when generating the config file, but not afterwards. This makes it difficult to version-control the config file.

I found a related issue https://github.com/matrix-org/synapse/issues/11489 that explores being able to dynamically configure any variable. I just wanted to bring this issue up separately because I think it is common enough that it warrants more urgency, so we should provide some solution in the interim in case #11489 requires more time. With the popularity of docker compose and infrastructure-as-code, I'd expect a fair number of users would want to be able to just version control their config file and be able to just add some environment variables and spin up their entire deployment. But having hard-coded passwords in the config file makes this much harder.

**Comment by woojoo666** [comment] 2021-12-26 00:39
Also on closer inspection, it looks like you can only provide the postgres password during config file generation [if you are using the migrate_configs option](https://github.com/matrix-org/synapse/blob/0b99d4c8d219aca3f8a0e4f3542bb67dfc016420/docker/start.py#L103). And this option seems to be for ["legacy support"](https://github.com/matrix-org/synapse/blob/develop/docker/README.md#legacy-dynamic-configuration-file-support), so it sounds like it's not a good thing to rely on. What happens if this option is ever deprecated? Is there going to be another way for providing passwords without hard-coding them?

**Comment by richvdh** [comment] 2022-01-04 14:45
Yes, you should absolutely not rely on the `migrate_config` tool.

I agree it's inconvenient that the postgres password has to be set in `homeserver.yaml`, but it's worth noting that the postgres password is not, in general, the only secret that needs to be set there (see, for example, `recaptcha_private_key`, `registration_shared_secret`, `turn_shared_secret`, et al). On the other hand, they are top-level options, so maybe easier to override in their own config file.

I'm unconvinced a solution that only works for the postgres password is a good one and am inclined to consider this a duplicate of #11489; however I'll keep it open to see what others think.

**Comment by richvdh** [comment] 2022-08-24 12:43
closing this as a duplicate of #11489.

**Closed by richvdh** 2022-08-24 12:43 UTC
Labels: P5, T-Enhancement
