### ISSUE TITLE
Timeout when updating the display name

### ISSUE THREAD

**Issue by bmarty** [matrix-org/synapse#11679] opened 2022-01-04 09:45 UTC
On my main account, using Firefox 95 on MacOS Monterey

Every time I change my display name from the settings, I have a timeout after about 30 seconds.

Note that the display name is actually updated correctly and all my rooms get the membership event.

The request should return a 200 faster and the remaining work (sending all the state events) should continue in background.

See https://github.com/vector-im/element-web/issues/20375

**Comment by DMRobertson** [comment] 2022-01-04 10:35
Double checking: the [spec](https://spec.matrix.org/v1.1/client-server-api/#events-on-change-of-profile-information) suggests that setting the displayname is a separate operation from dispatching the updates.

<blockquote>
Because the profile display name and avatar information are likely to be used in many places of a client’s display, changes to these fields cause an automatic propagation event to occur, informing likely-interested parties of the new values. This change is conveyed using two separate mechanisms:

*    an m.room.member event (with a join membership) is sent to every room the user is a member of, to update the displayname and avatar_url.
*    an m.presence presence status update is sent, again containing the new values of the displayname and avatar_url keys, in addition to the required presence key containing the current presence state of the user.

Both of these should be done automatically by the homeserver when a user successfully changes their display name or avatar URL fields.
</blockquote>

**Comment by DMRobertson** [comment] 2022-01-04 10:44
The relevant bit of source is `set_displayname` in `synapse/handlers/profile.py`.

Its last step, `_update_join_states` is the bit we want to do in the background. It's got a random delay for shadowbanned users, which ought to be not ran in the background.

**Comment by bmarty** [comment] 2022-01-04 22:06
Thanks for looking at this issue @DMRobertson

**Comment by richvdh** [comment] 2022-01-05 14:58
I think this is basically a duplicate of https://github.com/matrix-org/synapse/issues/1297.

**Closed by richvdh** 2022-01-05 14:58 UTC
Labels: Z-Help-Wanted, T-Enhancement, P4
