### ISSUE TITLE
Cannot resolve alias, throws exception synapse.api.errors.RequestSendFailed: Failed to send request: ResponseNeverReceived

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#9122] opened 2021-01-14 20:48 UTC
### Description

Tryin to join an alias (#mirage-client:matrix.org this time but it seems to be unspecific to any server or room) gives repeated M_UNKNOWN to the client, and throws various, probably timeout related traces into the log:

```
2021-01-14 21:18:42,109 - synapse.http.server - 83 - ERROR - POST-6559773- Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7f7eacfec2b0 method='POST' uri='/_matrix/client/r0/join/%23mirage-client:matrix.org?access_token=<redacted>' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/http/matrixfederationclient.py", line 477, in _send_request
    response = await request_deferred
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 224, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 400, in _async_render
    callback_return = await raw_callback_return
  File "/usr/lib/python3/dist-packages/synapse/rest/client/v1/room.py", line 294, in on_POST
    room_id, remote_room_hosts = await handler.lookup_room_alias(room_alias)
  File "/usr/lib/python3/dist-packages/synapse/handlers/room_member.py", line 751, in lookup_room_alias
    mapping = await directory_handler.get_association(room_alias)
  File "/usr/lib/python3/dist-packages/synapse/handlers/directory.py", line 245, in get_association
    ignore_backoff=True,
  File "/usr/lib/python3/dist-packages/synapse/federation/transport/client.py", line 178, in make_query
    ignore_backoff=ignore_backoff,
  File "/usr/lib/python3/dist-packages/synapse/http/matrixfederationclient.py", line 863, in get_json
    timeout=timeout,
  File "/usr/lib/python3/dist-packages/synapse/http/matrixfederationclient.py", line 293, in _send_request_with_optional_trailing_slash
    response = await self._send_request(request, **send_request_args)
  File "/usr/lib/python3/dist-packages/synapse/http/matrixfederationclient.py", line 481, in _send_request
    raise RequestSendFailed(e, can_retry=True) from e
synapse.api.errors.RequestSendFailed: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
```

In a similar fashion The Construct gives plain timeout error trying to do the same.

Creating a *new* alias for the same room (#mirate-test-123:matrix.org this time) makes it joinable through the federation again.

### Version information
- **Homeserver**: grin.hu (and others)
- **Version**: v1.24.0-1

- **Install method**:
Unofficial debian repo.

- **Platform**:
debian stable.

**Comment by joepie91** [comment] 2021-01-14 21:43
On pixie.town we experienced a very similar issue earlier today for #serverlist:nordgedanken.dev, however, the error in the logs was different:

```
Jan 14 18:55:28 terra matrix-synapse[2661812]: 2021-01-14 18:55:28,471 - synapse.http.server - 79 - ERROR - GET-702318 - Failed handle request via 'ClientDirectoryServer': <XForwardedForRequest at 0x7feac86ab91>
Jan 14 18:55:28 terra matrix-synapse[2661812]: Traceback (most recent call last):
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 470, in _send_request
Jan 14 18:55:28 terra matrix-synapse[2661812]:     response = await request_deferred
Jan 14 18:55:28 terra matrix-synapse[2661812]: twisted.internet.error.DNSLookupError: DNS lookup failed: Couldn't find the hostname 'matrix.nordgedanken.dev'.
Jan 14 18:55:28 terra matrix-synapse[2661812]: The above exception was the direct cause of the following exception:
Jan 14 18:55:28 terra matrix-synapse[2661812]: Traceback (most recent call last):
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 224, in _async_render_wrapper
Jan 14 18:55:28 terra matrix-synapse[2661812]:     callback_return = await self._async_render(request)
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 402, in _async_render
Jan 14 18:55:28 terra matrix-synapse[2661812]:     callback_return = await raw_callback_return
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/rest/client/v1/directory.py", line 51, in on_GET
Jan 14 18:55:28 terra matrix-synapse[2661812]:     res = await self.directory_handler.get_association(room_alias)
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/handlers/directory.py", line 242, in get_association
Jan 14 18:55:28 terra matrix-synapse[2661812]:     result = await self.federation.make_query(
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 172, in make_query
Jan 14 18:55:28 terra matrix-synapse[2661812]:     content = await self.client.get_json(
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 850, in get_json
Jan 14 18:55:28 terra matrix-synapse[2661812]:     response = await self._send_request_with_optional_trailing_slash(
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 286, in _send_request_with_optional_trailing_slash
Jan 14 18:55:28 terra matrix-synapse[2661812]:     response = await self._send_request(request, **send_request_args)
Jan 14 18:55:28 terra matrix-synapse[2661812]:   File "/home/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 472, in _send_request
Jan 14 18:55:28 terra matrix-synapse[2661812]:     raise RequestSendFailed(e, can_retry=retry_on_dns_fail) from e
Jan 14 18:55:28 terra matrix-synapse[2661812]: synapse.api.errors.RequestSendFailed: Failed to send request: DNSLookupError: DNS lookup failed: Couldn't find the hostname 'matrix.nordgedanken.dev'.
```

Seems to be a bog standard DNS error, though it was also reported in the client as M_UNKNOWN, and it's odd for these two cases to have happened in the same day. Maybe it's unrelated, though.

**Comment by clokep** [comment] 2021-01-18 17:33
Sounds similar to #2047 / #4665... looks like we're not properly handling a DNS failure somewhere.

**Comment by heftig** [comment] 2021-02-22 22:20
I'm also experiencing this now; trying to join any room on matrix.org fails. There's no mention of a DNS failure and federation of existing rooms with users on matrix.org seems to work (e.g. @appservice-irc:matrix.org still responds in an admin room). A restart of synapse did not help.

```
Feb 22 21:49:46 matrix.archlinux.org synapse[35740]: synapse.http.matrixfederationclient: [GET-5599] {GET-O-2169} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23ruma%3Amatrix.org:>
Feb 22 21:49:46 matrix.archlinux.org synapse[35740]: synapse.http.server: [GET-5599] Failed handle request via 'ClientDirectoryServer': <XForwardedForRequest at 0x7f58ed2df820 method='GET' uri='/_matrix/client/r0/directory/room/%23ruma%3>
                                                     Traceback (most recent call last):
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/matrixfederationclient.py", line 480, in _send_request
                                                         response = await request_deferred
                                                     twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
                                                     
                                                     The above exception was the direct cause of the following exception:
                                                     
                                                     Traceback (most recent call last):
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/server.py", line 252, in _async_render_wrapper
                                                         callback_return = await self._async_render(request)
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/server.py", line 430, in _async_render
                                                         callback_return = await raw_callback_return
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/rest/client/v1/directory.py", line 51, in on_GET
                                                         res = await self.directory_handler.get_association(room_alias)
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/handlers/directory.py", line 242, in get_association
                                                         result = await self.federation.make_query(
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/federation/federation_client.py", line 147, in make_query
                                                         return await self.transport_layer.make_query(
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/federation/transport/client.py", line 172, in make_query
                                                         content = await self.client.get_json(
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/matrixfederationclient.py", line 860, in get_json
                                                         response = await self._send_request_with_optional_trailing_slash(
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/matrixfederationclient.py", line 296, in _send_request_with_optional_trailing_slash
                                                         response = await self._send_request(request, **send_request_args)
                                                       File "/var/lib/synapse/venv/lib/python3.9/site-packages/synapse/http/matrixfederationclient.py", line 484, in _send_request
                                                         raise RequestSendFailed(e, can_retry=True) from e
                                                     synapse.api.errors.RequestSendFailed: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
```

**Comment by richvdh** [comment] 2021-04-08 21:35
I'm unclear what the problem is here. If the destination server is unreachable, "RequestSendFailed: Failed to send request: ResponseNeverReceived" is exactly what I'd expect to see?

**Comment by richvdh** [comment] 2021-05-27 11:33
I'm going to close this, since it sounds like the behaviour is as expected. If anyone can provide clarification, we can reopen.

**Closed by richvdh** 2021-05-27 11:33 UTC
Labels: S-Major, T-Defect, X-Needs-Info
