### ISSUE TITLE
some test failing when  packaging synaps

### ISSUE THREAD

**Issue by alex19EP** [matrix-org/synapse#10848] opened 2021-09-18 20:39 UTC
### Description

hello. I am trying to update synaps to 1.42.0 in Arch Linux
some test are failing on 1.42.0 and 1.41.1 version. 
i think it has something to do with new packages in our repositories.
since some time ago version 1.41.1 passed all tests successfully.

<details>
<summary>synaps dependencies versions</summary>

Repository      : extra
Name            : libwebp
Version         : 1.2.1-2
Description     : WebP library and conversion tools
Architecture    : x86_64
URL             : https://developers.google.com/speed/webp/
Licenses        : BSD
Groups          : None
Provides        : libwebp.so=7-64  libwebpdecoder.so=3-64  libwebpdemux.so=2-64  libwebpmux.so=3-64
Depends On      : libpng  libjpeg  libtiff  giflib
Optional Deps   : freeglut: vwebp viewer
Conflicts With  : None
Replaces        : None
Download Size   : 333.30 KiB
Installed Size  : 1087.96 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Thu Sep 16 00:50:43 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-ijson
Version         : 3.1.4-1
Description     : Iterative JSON parser with Pythonic interface
Architecture    : x86_64
URL             : https://github.com/ICRAR/ijson
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python  yajl
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 50.29 KiB
Installed Size  : 211.57 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Wed Jun 30 17:27:32 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-jsonschema
Version         : 3.2.0-4
Description     : An implementation of JSON Schema validation for Python
Architecture    : any
URL             : https://pypi.python.org/pypi/jsonschema
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-attrs  python-importlib-metadata  python-pyrsistent  python-setuptools
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 100.20 KiB
Installed Size  : 585.64 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Nov 12 16:12:09 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-twisted
Version         : 21.7.0-1
Description     : Asynchronous networking framework written in Python
Architecture    : any
URL             : https://twistedmatrix.com/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-zope-interface  python-constantly  python-incremental  python-automat  python-hyperlink  python-attrs  python-typing_extensions
Optional Deps   : python-pyopenssl: for TLS client hostname verification
                  python-service-identity: for TLS client hostname verification
                  python-idna: for TLS client hostname verification
                  python-cryptography: for using conch
                  python-pyasn1: for using conch
                  python-appdirs: for using conch
                  python-bcrypt: for using conch
                  python-h2: for http2 support
                  python-priority: for http2 support
                  python-pyserial: for serial support
                  tk: for using tkconch
Conflicts With  : python2-twisted<=20.3.0-3
Replaces        : None
Download Size   : 4.75 MiB
Installed Size  : 35.30 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Thu Aug 26 14:15:56 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-pyopenssl
Version         : 20.0.1-1
Description     : Python3 wrapper module around the OpenSSL library
Architecture    : any
URL             : https://github.com/pyca/pyopenssl
Licenses        : Apache
Groups          : None
Provides        : pyopenssl
Depends On      : openssl  python  python-six  python-cryptography
Optional Deps   : None
Conflicts With  : pyopenssl
Replaces        : pyopenssl
Download Size   : 82.93 KiB
Installed Size  : 543.15 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Tue Dec 15 21:27:15 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-yaml
Version         : 5.4.1.1-2
Description     : Python bindings for YAML, using fast libYAML library
Architecture    : x86_64
URL             : https://pyyaml.org/wiki/PyYAML
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  libyaml
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 173.22 KiB
Installed Size  : 763.88 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Sat Apr 24 16:56:40 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-pyasn1
Version         : 0.4.8-4
Description     : ASN.1 library for Python 3
Architecture    : any
URL             : https://github.com/etingof/pyasn1
Licenses        : BSD
Groups          : None
Provides        : pyasn1
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : pyasn1
Download Size   : 114.01 KiB
Installed Size  : 615.35 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Wed Nov 11 14:01:40 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-pynacl
Version         : 1.4.0-3
Description     : Python binding to the Networking and Cryptography (NaCl) library
Architecture    : x86_64
URL             : https://pypi.python.org/pypi/PyNaCl
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : libsodium  python  python-six  python-cffi
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 89.92 KiB
Installed Size  : 675.24 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Thu Nov 12 14:57:46 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-bcrypt
Version         : 3.2.0-3
Description     : Modern password hashing for your software and your servers
Architecture    : x86_64
URL             : https://github.com/pyca/bcrypt
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python-cffi  python-six
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 29.05 KiB
Installed Size  : 62.39 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Nov 12 14:59:58 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-frozendict
Version         : 2.0.6-1
Description     : An immutable dictionary
Architecture    : any
URL             : https://pypi.python.org/pypi/frozendict/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  python-setuptools
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 48.98 KiB
Installed Size  : 181.60 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Sat Aug 14 11:57:49 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-pillow
Version         : 8.3.2-1
Description     : Python Imaging Library (PIL) fork.
Architecture    : x86_64
URL             : https://python-pillow.github.io/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python  freetype2  lcms2  libraqm  libtiff  openjpeg2  libimagequant  libxcb
Optional Deps   : libwebp: for webp images
                  tk: for the ImageTK module
                  python-olefile: OLE2 file support
                  python-pyqt5: for the ImageQt module
Conflicts With  : None
Replaces        : None
Download Size   : 644.67 KiB
Installed Size  : 2968.17 KiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Sat Sep 11 12:01:28 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-pysaml2
Version         : 6.5.1-1
Description     : Python implementation of SAML Version 2
Architecture    : any
URL             : https://pypi.python.org/pypi/pysaml2
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python  python-dateutil  python-defusedxml  python-future  python-importlib_resources  python-pycryptodomex  python-pyopenssl  python-pytz  python-requests  python-six  python-zope-interface  python-xmlschema  xmlsec
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 510.95 KiB
Installed Size  : 4940.93 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Sat Jan 23 02:39:54 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-setuptools
Version         : 1:57.4.0-2
Description     : Easily download, build, install, upgrade, and uninstall Python packages
Architecture    : any
URL             : https://pypi.org/project/setuptools/
Licenses        : PSF
Groups          : None
Provides        : python-distribute
Depends On      : python-appdirs  python-more-itertools  python-ordered-set  python-packaging  python-pyparsing
Optional Deps   : None
Conflicts With  : None
Replaces        : python-distribute
Download Size   : 556.90 KiB
Installed Size  : 3033.09 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Sep  9 16:28:20 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-systemd
Version         : 234-8
Description     : Python bindings for systemd
Architecture    : x86_64
URL             : https://github.com/systemd/python-systemd
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : python3  libsystemd
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 49.96 KiB
Installed Size  : 256.33 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Mon Mar  1 16:27:59 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-unpaddedbase64
Version         : 2.1.0-1
Description     : Unpadded Base64
Architecture    : any
URL             : https://pypi.python.org/pypi/unpaddedbase64/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 9.18 KiB
Installed Size  : 14.53 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Sun Mar 14 15:16:18 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-canonicaljson
Version         : 1.4.0-3
Description     : Canonical JSON
Architecture    : any
URL             : https://pypi.python.org/pypi/canonicaljson/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python  python-simplejson  python-frozendict
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 6.31 KiB
Installed Size  : 11.98 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Wed Nov 11 18:15:10 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-signedjson
Version         : 1.1.1-3
Description     : Sign JSON with Ed25519 signatures
Architecture    : any
URL             : https://pypi.python.org/pypi/signedjson/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python  python-canonicaljson  python-unpaddedbase64  python-pynacl
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 10.37 KiB
Installed Size  : 33.13 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Nov 12 16:21:26 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-pymacaroons
Version         : 0.13.0-8
Description     : Python implementation of Macaroons. They’re better than cookies!
Architecture    : any
URL             : https://github.com/ecordell/pymacaroons
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  python-pynacl  python-six
Optional Deps   : None
Conflicts With  : python-pymacaroons-pynacl
Replaces        : None
Download Size   : 31.98 KiB
Installed Size  : 145.35 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Nov 12 16:19:38 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-service-identity
Version         : 21.1.0-1
Description     : Service identity verification for pyOpenSSL
Architecture    : any
URL             : https://pypi.python.org/pypi/service_identity
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-attrs  python-pyasn1-modules  python-pyasn1  python-cryptography  python-six
Optional Deps   : python-idna: for Internationalized Domain Names support
Conflicts With  : None
Replaces        : None
Download Size   : 19.52 KiB
Installed Size  : 77.69 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Tue May 11 01:46:41 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-msgpack
Version         : 1.0.2-2
Description     : MessagePack serializer implementation for Python
Architecture    : x86_64
URL             : https://github.com/msgpack/msgpack-python
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 74.39 KiB
Installed Size  : 258.77 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Fri Dec 25 05:18:57 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-phonenumbers
Version         : 8.12.31-1
Description     : Python version of Google's common library for parsing, formatting, storing and validating international phone numbers
Architecture    : any
URL             : https://github.com/daviddrysdale/python-phonenumbers
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 2.52 MiB
Installed Size  : 38.36 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Wed Aug 25 17:09:10 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-prometheus_client
Version         : 0.11.0-1
Description     : Prometheus instrumentation library for Python applications
Architecture    : any
URL             : https://github.com/prometheus/client_python
Licenses        : APACHE
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 83.83 KiB
Installed Size  : 397.76 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Sat Jul 31 14:54:00 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-attrs
Version         : 21.2.0-1
Description     : Attributes without boilerplate.
Architecture    : any
URL             : https://attrs.readthedocs.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 77.55 KiB
Installed Size  : 414.13 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Tue May 11 04:54:53 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-netaddr
Version         : 0.8.0-3
Description     : Pure Python network address representation and manipulation library
Architecture    : any
URL             : https://github.com/drkjam/netaddr
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : ipython: netaddr interractive command support
Conflicts With  : None
Replaces        : None
Download Size   : 1414.05 KiB
Installed Size  : 8326.82 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Thu Nov 12 13:06:23 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-sortedcontainers
Version         : 2.4.0-1
Description     : Python Sorted Container Types: SortedList, SortedDict, and SortedSet
Architecture    : any
URL             : http://www.grantjenks.com/docs/sortedcontainers/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 43.33 KiB
Installed Size  : 336.73 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon May 17 18:36:32 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-treq
Version         : 21.5.0-1
Description     : A requests-like API built on top of twisted.web's Agent
Architecture    : any
URL             : https://github.com/twisted/treq
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-incremental  python-requests  python-pyopenssl  python-service-identity  python-idna  python-attrs  python-twisted  python-hyperlink
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 111.46 KiB
Installed Size  : 641.78 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Wed May 26 20:31:02 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-idna
Version         : 3.2-1
Description     : Internationalized Domain Names in Applications (IDNA)
Architecture    : any
URL             : https://github.com/kjd/idna
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 83.46 KiB
Installed Size  : 624.99 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Sun May 30 01:49:39 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-jinja
Version         : 3.0.1-1
Description     : A simple pythonic template language written in Python
Architecture    : any
URL             : https://palletsprojects.com/p/jinja/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python-setuptools  python-markupsafe
Optional Deps   : python-babel: for i18n support
Conflicts With  : None
Replaces        : None
Download Size   : 233.89 KiB
Installed Size  : 1323.24 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Wed May 19 07:51:02 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-bleach
Version         : 4.1.0-1
Description     : An easy whitelist-based HTML-sanitizing tool
Architecture    : any
URL             : https://pypi.org/project/bleach/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python-packaging  python-six  python-webencodings
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 252.70 KiB
Installed Size  : 1470.89 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Tue Aug 31 22:30:17 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-typing_extensions
Version         : 3.10.0.2-1
Description     : Backported and Experimental Type Hints for Python 3.5+
Architecture    : any
URL             : https://github.com/python/typing/tree/master/typing_extensions
Licenses        : custom
Groups          : None
Provides        : python-typing-extensions
Depends On      : python
Optional Deps   : None
Conflicts With  : python-typing-extensions
Replaces        : None
Download Size   : 47.11 KiB
Installed Size  : 284.30 KiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Wed Sep  1 11:31:40 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : core
Name            : systemd
Version         : 249.4-1
Description     : system and service manager
Architecture    : x86_64
URL             : https://www.github.com/systemd/systemd
Licenses        : GPL2  LGPL2.1
Groups          : None
Provides        : nss-myhostname  systemd-tools=249.4  udev=249.4
Depends On      : acl  libacl.so=1-64  bash  cryptsetup  libcryptsetup.so=12-64  dbus  iptables  kbd  kmod  libkmod.so=2-64  hwids  libcap  libcap.so=2-64  libgcrypt  libxcrypt  libcrypt.so=2-64  systemd-libs  libidn2  lz4  pam  libelf  libseccomp  libseccomp.so=2-64  util-linux  libblkid.so=1-64  libmount.so=1-64  xz  pcre2  audit  libaudit.so=1-64  libp11-kit  libp11-kit.so=0-64  openssl
Optional Deps   : libmicrohttpd: remote journald capabilities
                  quota-tools: kernel-level quota management
                  systemd-sysvcompat: symlink package to provide sysvinit binaries
                  polkit: allow administration as unprivileged user
                  curl: machinectl pull-tar and pull-raw
                  libfido2: unlocking LUKS2 volumes with FIDO2 token
                  tpm2-tss: unlocking LUKS2 volumes with TPM2
Conflicts With  : nss-myhostname  systemd-tools  udev
Replaces        : nss-myhostname  systemd-tools  udev
Download Size   : 6.45 MiB
Installed Size  : 25.79 MiB
Packager        : Christian Hesse <arch@eworm.de>
Build Date      : Mon Aug 30 09:45:29 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-authlib
Version         : 0.15.2-3
Description     : The ultimate Python library in building OAuth and OpenID Connect servers
Architecture    : any
URL             : https://github.com/lepture/authlib
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python-cryptography
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 256.59 KiB
Installed Size  : 1717.04 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Thu Nov 12 21:46:55 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-pyjwt
Version         : 1.7.1-6
Description     : JSON Web Token implementation in Python
Architecture    : any
URL             : https://github.com/jpadilla/pyjwt
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-setuptools
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 32.56 KiB
Installed Size  : 129.67 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Wed Nov 11 14:01:38 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : extra
Name            : python-lxml
Version         : 4.6.3-1
Description     : Python3 binding for the libxml2 and libxslt libraries
Architecture    : x86_64
URL             : https://lxml.de/
Licenses        : BSD  custom
Groups          : None
Provides        : None
Depends On      : python  libxslt
Optional Deps   : python-beautifulsoup4: support for beautifulsoup parser to parse not well formed HTML
                  python-cssselect: support for cssselect
                  python-html5lib: support for html5lib parser
                  python-lxml-docs: offline docs
Conflicts With  : None
Replaces        : None
Download Size   : 1165.19 KiB
Installed Size  : 4240.64 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Sun Mar 21 23:09:12 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-parameterized
Version         : 0.8.1-1
Description     : Parameterized testing with any Python test framework
Architecture    : any
URL             : https://github.com/wolever/parameterized
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 32.38 KiB
Installed Size  : 149.28 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Fri Mar 19 23:27:25 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-txredisapi
Version         : 1.4.7-2
Description     : Non-blocking redis client for python
Architecture    : any
URL             : https://pypi.python.org/pypi/txredisapi/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python  python-twisted  python-six
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 47.91 KiB
Installed Size  : 258.69 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Thu Nov 12 22:14:11 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-hiredis
Version         : 2.0.0-1
Description     : Non-blocking redis client for python
Architecture    : x86_64
URL             : https://pypi.org/project/hiredis/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 23.86 KiB
Installed Size  : 55.33 KiB
Packager        : Johannes Löthberg <demize@archlinux.org>
Build Date      : Sat Jul 31 14:49:49 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-psutil
Version         : 5.8.0-1
Description     : A cross-platform process and system utilities module for Python
Architecture    : x86_64
URL             : https://github.com/giampaolo/psutil
Licenses        : custom: BSD
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 360.23 KiB
Installed Size  : 2129.29 KiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Sun Jan  3 19:08:44 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : community
Name            : python-pyjwt
Version         : 1.7.1-6
Description     : JSON Web Token implementation in Python
Architecture    : any
URL             : https://github.com/jpadilla/pyjwt
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-setuptools
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 32.56 KiB
Installed Size  : 129.67 KiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Wed Nov 11 14:01:38 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature

</details>

### Steps to reproduce

- build synaps with check option on arch linux.
- pkgbuild is located at: https://github.com/archlinux/svntogit-community/tree/packages/matrix-synapse/trunk

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

all tests should pass successfully. I will attach build and check logs if someone who knows the code base and understands the testing system can give a hint - I will be very grateful.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.41.1 and 1.42.0

- **Install method**: distribution package
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Arch Linux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

[matrix-synapse-1.42.0-1-x86_64-build.log](https://github.com/matrix-org/synapse/files/7190609/matrix-synapse-1.42.0-1-x86_64-build.log)
[matrix-synapse-1.42.0-1-x86_64-check.log](https://github.com/matrix-org/synapse/files/7190611/matrix-synapse-1.42.0-1-x86_64-check.log)

**Comment by DMRobertson** [comment] 2021-09-20 10:51
Thanks for writing this up!

Searching for `[ERROR]` and `[FAIL]` in the check log file, `tests.rest.client.test_relations` seems to have be failing in its setup:

```
Traceback (most recent call last):
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/unittest.py", line 75, in new
    return code(orig, *args, **kwargs)
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/unittest.py", line 122, in setUp
    return orig()
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/unittest.py", line 300, in setUp
    self.prepare(self.reactor, self.clock, self.hs)
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/rest/client/test_relations.py", line 52, in prepare
    self.room = self.helper.create_room_as(self.user_id, tok=self.user_token)
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/rest/client/utils.py", line 96, in create_room_as
    assert channel.result["code"] == b"%d" % expect_code, channel.result
builtins.AssertionError: {'version': b'1.1', 'code': b'500', 'reason': b'Internal Server Error', 'headers': [(b'Server', b'1'), (b'Date', b'Sat, 18 Sep 2021 20:03:33 GMT'), (b'Content-Type', b'application/json'), (b'Cache-Control', b'no-cache, no-store, must-revalidate'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, HEAD, POST, PUT, DELETE, OPTIONS'), (b'Access-Control-Allow-Headers', b'X-Requested-With, Content-Type, Authorization, Date')], 'body': b'{"errcode":"M_UNKNOWN","error":"Internal server error"}', 'done': True}
```

There's also an internal server error in the two failures too:

```
[FAIL]
Traceback (most recent call last):
  File "/build/matrix-synapse/src/synapse-1.42.0/tests/rest/client/test_third_party_rules.py", line 157, in test_cannot_modify_event
    self.assertEqual(channel.code, 200, channel.result)
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib/python3.9/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.9/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 500 != 200 : {'version': b'1.1', 'code': b'500', 'reason': b'Internal Server Error', 'headers': [(b'Server', b'1'), (b'Date', b'Sat, 18 Sep 2021 20:04:48 GMT'), (b'Content-Type', b'application/json'), (b'Cache-Control', b'no-cache, no-store, must-revalidate'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, HEAD, POST, PUT, DELETE, OPTIONS'), (b'Access-Control-Allow-Headers', b'X-Requested-With, Content-Type, Authorization, Date')], 'body': b'{"errcode":"M_UNKNOWN","error":"Internal server error"}', 'done': True}

tests.rest.client.test_third_party_rules.ThirdPartyRulesTestCase.test_cannot_modify_event
```

**Comment by DMRobertson** [comment] 2021-09-20 10:54
@alex19EP to understand the cause I think we'd need to see synapse's logs as opposed to the test runner's logs. In the directory where the tests were run there should be a `_trial_temp` directory, and within a `test.log` file. Could you attach that file? Hopefully that will help us diagnose the internal server errors.

**Comment by alex19EP** [comment] 2021-09-20 18:53
> @alex19EP to understand the cause I think we'd need to see synapse's logs as opposed to the test runner's logs. In the directory where the tests were run there should be a `_trial_temp` directory, and within a `test.log` file. Could you attach that file? Hopefully that will help us diagnose the internal server errors.

sure heer it is.
[test.log](https://github.com/matrix-org/synapse/files/7198034/test.log)

**Comment by alex19EP** [comment] 2021-09-20 22:31
> Do the tests pass if you require frozendict < 2.0.6?

yes tests pass on python-frozendict 2.0.3-1

**Comment by erikjohnston** [comment] 2021-09-27 14:55
I think this  is fixed by https://github.com/matrix-org/synapse/pull/10902

**Closed** 2021-09-30 14:37 UTC
Labels: z-packaging, z-testing, S-Minor, T-Defect
