### ISSUE TITLE
Element's export room stuck on "M_FORBIDDEN: Host not in room."

### ISSUE THREAD

**Issue by TheFrenchGhosty** [matrix-org/synapse#11579] opened 2021-12-14 19:37 UTC
*Originally sent in the element-web repository, but I was told that it's a synapse bug https://github.com/vector-im/element-web/issues/20190 *

### Steps to reproduce

1. Run an export on an old room (in my case the [Invidious](https://invidious.io/) room [#invidious:matrix.org](https://matrix.to/#/#invidious:matrix.org) )
2. Choose JSON and 4MB
3. Run an export, until it get stuck, looks at the console: 403

#### What did you expect?

Skips the 403, or just don't 403

#### What happened instead?
![this](https://user-images.githubusercontent.com/47571719/146059979-9df3e412-f85c-4a02-94d6-83387cf2911b.png)

Then stops.

If I restart the export again, it give a 403 instantly, however if I clear the cache of the client, it works, until this error happens again.

Note:

It's an old V1 room (from early 2019), we want to export it so that we can upgrade it while keeping a backup of the messages.

We did an HTML export with attachment an hour before without issue.

it's maybe a Synapse issue.

### Operating system

Debian

### Application version

1.9.7

### How did you install the app?

Official Element repository

### Homeserver

My own

### Will you send logs?

No

**Comment by DMRobertson** [comment] 2021-12-16 15:25
Hi @TheFrenchGhosty, cc @t3chguy. I think we'll need logs to work this one out. Could you give the full URL that 403s and an approximate timestamp so I can track this down in matrix.org's logs?

**Comment by richvdh** [comment] 2021-12-16 16:42
looks like this is on a self-hosted server rather than `matrix.org` - we'll need logs from that.

**Comment by TheFrenchGhosty** [comment] 2021-12-16 16:45
Yes, this is on my own homeserver, I can provide an account if you need it.

**Comment by richvdh** [comment] 2021-12-16 16:49
just the `homeserver.log` please.

**Comment by TheFrenchGhosty** [comment] 2021-12-16 17:14
Okay so I was trying to get the errors in logs... and I just did a successful JSON export...

**Comment by TheFrenchGhosty** [comment] 2021-12-16 17:27
And another JSON export without errors (by the way, setting the Size Limit at 4MB doesn't work)

**Comment by TheFrenchGhosty** [comment] 2021-12-16 17:40
Okay, so here's a 5MB log file, of what looks like a different issue: when the client is processing the logs,  synapse seems to loose network access (the server is perfectly fine, but synapse is complaining)

[homeserver.log](https://github.com/matrix-org/synapse/files/7729358/homeserver.log)

**Comment by DMRobertson** [comment] 2021-12-16 17:42
>  synapse seems to loose network access (the server is perfectly fine, but synapse is complaining that it can't reach the network)

This doesn't sound right: Synapse is the homeserver, Do you mean the client (Element?) loses network access?

**Comment by TheFrenchGhosty** [comment] 2021-12-16 17:43
@DMRobertson No I indeed mean Synapse, just look at the log, it's complaining about timeout

**Comment by richvdh** [comment] 2021-12-16 18:11
I'm not seeing any particular problems in that logfile.

It sounds like the original issue here has been resolved, so I'm going to go ahead and close this. If you're able to reproduce it, let us know and we can reopen it.

If you have a different problem, please open a new issue.

**Closed by richvdh** 2021-12-16 18:11 UTC
Labels: X-Needs-Info
