### ISSUE TITLE
Images uploaded using the invalid but occasionally observed "image/jpg" MIME type do not have thumbnails generated

### ISSUE THREAD

**Issue by chr-1x** [matrix-org/synapse#6993] opened 2020-02-26 07:48 UTC
### Description

Some Matrix clients (notably riotX) will upload media attachments to Synapse with the MIME type `image/jpg` (invalid: the registered MIME type for jpeg images is `image/jpeg`: https://www.w3.org/Graphics/JPEG/). When this happens, the image attachment is sent to clients and displayed inline as an image, but no thumbnails are generated (likely because the default thumbnail requirements do not cover `image/jpg`).

(Corresponding issue on riotX: https://github.com/vector-im/riotX-android/issues/1075)

### Steps to reproduce

- Submit an image with the MIME type `image/jpg` to a Synapse server. (One way I have found to reliably do this in the wild is by sharing an image with the `.jpg` extension from a third party application to riotX).
- Observe that no thumbnails are generated for the resulting media attachment.

I would expect Synapse to normalize commonly misused MIME types, at least for this case. While riotX should fix this issue on the client side, Synapse should also be robust to this mistake. 

### Version information

- **Homeserver**: matrix.cybre.space

- **Version**: 1.11.0

- **Install method**: pip

- **Platform**: Ubuntu 18.04

**Comment by chr-1x** [comment] 2020-02-26 07:51
While tracking this issue down, I traced through the relevant code in Synapse, so I think I have an idea of how to make a fix. I will try to submit a PR this weekend!

**Comment by richvdh** [comment] 2020-05-12 20:57
I'm not entirely convinced this is a thing that we should be fixing in the server.

The problem is that once we start doing "helpful" stuff like this, it's easy for client developers to start depending on it - which really means that the same thing has to happen in *all* server implementations (otherwise we end up with some clients only being compatible with some servers), which in turn means it needs to end up in the spec, and ideally we have a test in `sytest` to ensure that all servers implement it.

I also note that the original bug in riotX has now been fixed.

**Comment by anoadragon453** [comment] 2020-05-22 16:12
Closing this for now. Please re-open and let us know if there's a better way to approach this :)

**Closed by anoadragon453** 2020-05-22 16:12 UTC
Labels: bug, media-repository, p2
