### ISSUE TITLE
Jitsi querystring parameters

### ISSUE THREAD

**Issue by masterwotikar** [matrix-org/synapse#8546] opened 2020-10-14 19:53 UTC
After upgrading matrix-synapse to the most recent version, the pop out in Element of jitsi doesnt work anymore, Inside a room it is working but when we click the button to pop out in other screen, it tells that the jitsi app cannot be load. the querystring parameters are not filled i found out. See below

conferenceDomain=$domain&conferenceId=$conferenceId&isAudioOnly=$isAudioOnly&displayName=$matrix_display_name&avatarUrl=$matrix_avatar_url&userId=$matrix_user_id&roomId=$matrix_room_id

**Comment by clokep** [comment] 2020-10-14 19:55
I don't believe that Synapse interacts directly with Jitsi. Could this be due to an update of Element instead?

I'm not sure where those query string parameters are from. Could you give more information?

**Comment by t3chguy** [comment] 2020-10-14 19:56
This was an Element bug and has already been fixed on develop.

**Comment by turt2live** [comment] 2020-10-14 19:57
Duplicate of https://github.com/vector-im/element-web/issues/15443

**Closed by turt2live** 2020-10-14 19:57 UTC
Labels: info-needed
