### ISSUE TITLE
 How to recover from manual event deletion

### ISSUE THREAD

**Issue by capucinepichette** [matrix-org/synapse#2919] opened 2018-02-28 19:11 UTC
### Description

hello, we deleted some rows from the events table, i know it s bad
but there was too much of a sensitive data we needed to rip off.
Now, on that room we get 'Room X does not exist' as soon as we try to push any event (post new messages)
What is the way to recover the state of that room without creating a new one

In the database and on RIOT, the room still exists with valid memberships.
And the creation event (and all of but 2 events of that room) are still there.

### Version information
homeserver: custom
Version de riot-web : 0.13.4
matrix: 0.26.0

- **Install method**: docker (https://github.com/corpusops/docker-matrix)

https://github.com/matrix-org/synapse/blob/master/synapse/event_auth.py#L70

- here the value auth_events is ``{}``, if we change the test is on a boolean value (``if not auth_events``), rather than None, we can post messages, but it seems hacky and not a solution. 
- Indeed, as soon as we remember this "bypass test", we can't post anymore to that failed room.
- Of course, The multiple posts are done with a loggued in user, which is a member of that room

**Comment by Half-Shot** [comment] 2018-02-28 19:27
If other homeservers were joined to the room, you *might* be able to get those events from the other homeserver though that kind of splicing needs to be careful and I don't know if it works.

But you should **never** go in deleting rows for whatever reason, there is a perfectly accessible redact API for that purpose. Really if you start deleting rows, we cannot help you. I suggest in the future you have database backups.

**Comment by capucinepichette** [comment] 2018-02-28 19:28
Redact api does not REMOVE former rows, that was why we did that.

**Comment by capucinepichette** [comment] 2018-02-28 19:40
So, no other servers are participating on this room.
What other solution do i have left ?
Did you saw the updated desc (around the test in auth_events.py)

**Comment by capucinepichette** [comment] 2018-02-28 23:15
By the advice or @ara4n , i tried to remove all the relevant events 

```sql
delete from current_state_delta_stream      where event_id='$EVENTID' or prev_event_id='$EVENTID';
delete from event_destinations              where event_id='$EVENTID';
delete from event_push_actions              where event_id='$EVENTID';
delete from current_state_events            where event_id='$EVENTID';
delete from history_visibility              where event_id='$EVENTID';
delete from receipts_linearized             where event_id='$EVENTID';
delete from room_memberships                where event_id='$EVENTID';
delete from state_events                    where event_id='$EVENTID';
delete from state_groups                    where event_id='$EVENTID';
delete from stream_ordering_to_exterm       where event_id='$EVENTID';
delete from topics                          where event_id='$EVENTID';
delete from events                          where event_id='$EVENTID';
delete from event_json                      where event_id='$EVENTID';
delete from event_content_hashes            where event_id='$EVENTID';
delete from event_reference_hashes          where event_id='$EVENTID';
delete from event_signatures                where event_id='$EVENTID';
delete from event_edge_hashes               where event_id='$EVENTID' or prev_event_id='$EVENTID';
delete from event_to_state_groups           where event_id='$EVENTID';
delete from event_backward_extremities      where event_id='$EVENTID';
delete from event_forward_extremities       where event_id='$EVENTID';
delete from event_edges                     where event_id='$EVENTID' or prev_event_id='$EVENTID';
```

Room access still OK , but posting to room is still BROKEN.

**Comment by neilisfragile** [comment] 2018-03-02 16:15
I'm closing this issue since not a bug or feature.

As I think you've already found the rooms are a good place to get advice - based on the above, personally I can't recommend you another option :( Sorry to not be more helpful.

**Closed by neilisfragile** 2018-03-02 16:15 UTC

**Comment by capucinepichette** [comment] 2018-03-02 18:05
Not to have a way to recover a room in an unstable state is clearly a bug @neilisfragile.
FYI, this room is still broken on our servers, and i have not found yet a solution to make it accessible again.

Arbitrary closing a bug isn't really fair ....

**Comment by turt2live** [comment] 2018-03-02 18:22
> we deleted some rows from the events table, i know it s bad

There's not much the application can do if it is getting data ripped out from under its feet. However, it shouldn't be complaining that the room doesn't exist when posting a new message. I'd bet there's some sort of error in the homeserver logs that could reveal what kind of bug we're dealing with. Knowing what types of events you deleted from the database would also help with triaging.

**Comment by capucinepichette** [comment] 2018-03-02 18:26
@ara4n no problemo to continue to dig in, we can continue to chat on the problem more directly maybe ? (see the riot chat)

**Comment by neilisfragile** [comment] 2018-03-05 10:21
Agreed that rooms should be resilient (as best we can) to unexpected behaviour and if you can provide some details of the current state and logs so it can be reproduced I'd be happy to see /that/ as a issue.
