### ISSUE TITLE
Federation not working with SRV entry and Synapse on a subdomain

### ISSUE THREAD

**Issue by KoltesDigital** [matrix-org/synapse#6710] opened 2020-01-15 10:24 UTC
### Description

Context: I'm using docker to have a Synapse instance (matrixdotorg/synapse:latest), and Traefik to route HTTP traffic to the proper containers. That's why I chose the SRV method for the federation, because accessing .well-known would be more complex. Synapse is running at synapse.example.com, server_name is example.com, and public_baseurl is https://synapse.example.com/

I can't get federation to work. I believe the reason is that the DNS method gets the SRV entry (synapse.example.com:443) but then resolves to the IP (1.2.3.4:443). However, Traefik routes correctly the subdomain name, but if it's queried with the IP it responds 404. Since I serve other sites as well, I wouldn't like to change this behavior.

*Is it by design that the federation sends a request to the IP instead of just taking the SRV entry for granted?*

Another reason would be that the request to the federation is done on the main domain (example.com) whereas it is known that Synapse runs on a subdomain (synapse.example.com)

Here is the report from https://federationtester.matrix.org/api/report?server_name=example.com

```json
{
  "WellKnownResult": {
    "m.server": "",
    "result": "Get https://example.com/.well-known/matrix/server: dial tcp 217.70.184.38:443: i/o timeout"
  },
  "DNSResult": {
    "SRVCName": "_matrix._tcp.example.com.",
    "SRVRecords": [
      {
        "Target": "synapse.example.com.",
        "Port": 443,
        "Priority": 10,
        "Weight": 5
      }
    ],
    "SRVError": null,
    "Hosts": {
      "synapse.example.com.": {
        "CName": "synapse.example.com.",
        "Addrs": [
          "1.2.3.4"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "1.2.3.4:443"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "1.2.3.4:443": {
      "Message": "Non-200 response 404 from remote server"
    }
  },
  "Version": {
    "error": "Get matrix://example.com/_matrix/federation/v1/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
  },
  "FederationOK": false
}
```

\* domain name and IP are anonymized because it's not relevant.

### Steps to reproduce

- docker-compose with postgres and synapse
- DNS entry: _matrix._tcp.example.com. 1800 IN SRV 10 5 443 synapse.example.com.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Custom

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.8.0

- **Install method**: docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: physical server
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment] 2020-01-15 10:43
A few points here:

1. The routing algorithm is very precisely documented at https://matrix.org/docs/spec/server_server/r0.1.2#resolving-server-names.
1. this is a well-tested piece of code: it's almost certain that you are misunderstanding it rather than there being bugs here: I recommend seeking support in #synapse:matrix.org if you have questions.
1. what does 
   > Is it by design that the federation sends a request to the IP instead of just taking the SRV entry for granted?

   mean? It's nonsensical for a TCP connection to be routed directly to a hostname: that hostname has to be resolved to an IP address. Do you mean that the "Host" header doesn't match what you expect? If so, see point 1.
1. > domain name and IP are anonymized because it's not relevant.

   If you think there's a bug here, we're going to need the actual domain in question to be able to debug it.

**Comment by KoltesDigital** [comment] 2020-01-15 12:39
Yes I meant including the Host header, sorry confusion. And the spec you gave states that it should be present. I'll check whether it's indeed the case.

**Closed** 2020-01-15 15:50 UTC

**Comment by KoltesDigital** [comment] 2020-01-17 17:44
For the record: the server pointed by the SRV entry (serving synapse.example.com) still needs to answer to the HTTPS with the original host (example.com), as stated by the above documentation, point 3, 3rd bullet.

So I preferred to use port 8448. SRV entry updated to this port, in Traefik I added a router from example.com:8448 to the same service, and voila at least I can get the room list at matrix.org.

However the federation tester (https://federationtester.matrix.org/api/report?server_name=example.com) cannot get the server version:

```json
  "Version": {
    "error": "Get matrix://example.com/_matrix/federation/v1/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
  },
```

It is expected that a request at https://example.com/_matrix/federation/v1/version doesn't work, whereas https://synapse.example.com/_matrix/federation/v1/version correctly responds `{"server": {"name": "Synapse", "version": "1.8.0"}}`. This request should be sent with the same procedure: as the SRV entry resolved the HS to be at `1.2.3.4:8448` using `Host: example.com`, this must be the case for this request as well.

@richvdh do you want a separate issue?

**Comment by richvdh** [comment] 2020-01-20 10:15
if you are sure the federation tester is doing the wrong thing, please open a bug against https://github.com/matrix-org/matrix-federation-tester, *citing a domain demonstrating the problem*

**Comment by bjeanes** [comment] 2020-10-03 22:24
In the name of posterity and to help others with a similar setup (I also have Synapse behind Traefik on a `synapse.$DOMAIN` using `SRV` records), I was able to keep synapse on port 443 by using the following Traefik rule:

```
Host(`synapse.example.com`) || (Host(`example.com`) && PathPrefix(`/_matrix/`))
```

Traefik correctly procured a LetsEncrypt certificate for both domains and responds to the federation tester, even though "`example.com`"'s `A` record points to a different server. However, this probably only works because I have Traefik configured to use `DNS-01` certificate challenge and so I do not need to be able to resolve that top-level domain to the Traefik host -- I only need to prove that I own the DNS records for the domain.
