### ISSUE TITLE
Purge all the local media content that does not link to any source

### ISSUE THREAD

**Issue by Narakuku** [matrix-org/synapse#9880] opened 2021-04-25 19:04 UTC
**Description:**

I found out that any picture/media that was removed in the chat history (Element) still exists in the "/data/media_store", and the files are no longer needed anymore but consumes a lot of disk space.

So is there any way to clean all the local content that does not link to any chat room or history?

I'm aware of there is a media_admin_api, but that will also remove all the media that is still **used** by chat history, point is I don't want to jeopardize any history but only remove the files that are not needed.

**Comment by dklimpel** [comment] 2021-04-25 20:39
In my opinion is such API not possible. The messages are encrypted and the server does not know which files are used or not.

**Comment by Narakuku** [comment] 2021-04-26 05:56
The question is, why not remove the actual file together when deleting the pic from the chat history?

**Comment by dklimpel** [comment] 2021-04-26 07:15
> The question is, why not remove the actual file together when deleting the pic from the chat history?

This is a duplicate of #1263 and #8638

**Comment by clokep** [comment] 2021-04-27 11:41
Closing in favor of #1263.

**Closed by clokep** 2021-04-27 11:41 UTC
