### ISSUE TITLE
Notify device update on login causing massive amount of federation

### ISSUE THREAD

**Issue by hifi** [matrix-org/synapse#12048] opened 2022-02-20 14:45 UTC
### Description

When signing in on a new device, `notify_device_update` gets called immediately creating a massive burst of outgoing federation. This causes other unrelated issues like extremely slow initial sync or failed login (currently with FluffyChat) because the HS is stuck doing outgoing federation and killing the CPU.

### Steps to reproduce
- Workerless synapse with user that's federating with lots of HSs
- Login from a new device causing `notify_device_update` being called
- Watch Synapse flooding with outgoing federation

Would be nice if this could be deferred or slowed down enough not to cause such a huge issue immediately.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: vi.fi

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.52.0

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux, 2 CPU VM
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment] 2022-02-21 12:29
this is basically the same as https://github.com/matrix-org/synapse/issues/7721 I think?

**Comment by squahtx** [comment] 2022-02-21 12:34
closing as duplicate of #7221

**Closed by squahtx** 2022-02-21 12:34 UTC
Labels: S-Major, T-Defect

**Comment by hifi** [comment] 2022-02-21 13:27
Ah, indeed. I couldn't find that issue by searching for notify device update so didn't find it. Thanks.
