### ISSUE TITLE
Synapse error logged on opening client (room list handler)

### ISSUE THREAD

**Issue by V02460** [matrix-org/synapse#7262] opened 2020-04-11 07:37 UTC
Whenever I open up a client, this error is emitted to Synapse’s logs:

`AttributeError: 'NoneType' object has no attribute 'content'`

The code line at fault is in the room list handler. It seems to assume there is always a create event returned from the database, which in my case appears to fail:

https://github.com/matrix-org/synapse/blob/883ac4b1bb7c520e928e8a42d7700de7f0d56055/synapse/handlers/room_list.py#L284-L285

I am running Synapse v1.12.3.

**Comment by clokep** [comment] 2020-04-13 12:04
I think this is a duplicate of #4891, but it is hard to tell without the full stack trace. It seems to point to the same line of code though so I'm going to close this as a duplicate. Please reopen it if this seems to be a different issue.

**Closed by clokep** 2020-04-13 12:04 UTC
