### ISSUE TITLE
`cache_invalidation_stream_by_instance` grows without bounds and causes slow startup

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8269] opened 2020-09-07 12:55 UTC
cf https://github.com/matrix-org/synapse/issues/7968#issuecomment-688307145

**Comment by richvdh** [comment] 2020-09-07 12:56
it seems like we ought to be able to clear these out, but I don't know how we can tell?

**Comment by erikjohnston** [comment] 2022-05-17 07:52
Yup, we can clean things out. It only ever gets read sequentially by the workers, so once a row has been read by all running processes then it can be deleted. Also note that when starting up a worker will read from the *most recent* row, so it is also safe to delete all the rows if all Synapse processes have stopped. 

The hard part is to figure out which rows all processes have seen. As a bit of a bodge I suggest we just delete all rows with an `invalidation_ts` over a month old, which should definitely be safe. We might also want to add some logic to the read part to ensure that it exits if the rows of the cache its reading is more than a week old, or something.

The `cache_invalidation_stream_by_instance` doesn't have an index on `invalidation_ts`, so I think the best way of deleting the rows is pulling out the 100th row (ordered by `stream_id`), check if its old enough, and then delete all rows before it if so.

**Comment by richvdh** [comment] 2022-08-05 15:36
this is a subset of https://github.com/matrix-org/synapse/issues/5888.

see also https://github.com/matrix-org/synapse/issues/13456 which discusses ways of getting rid of this table altogether.

**Comment by reivilibre** [comment] 2023-07-04 13:23
Dupe of #3665 which will be closed by #15868.

**Closed by reivilibre** 2023-07-04 13:23 UTC
Labels: A-Disk-Space, T-Task
