### ISSUE TITLE
left_members in room_stats can go (very) negative.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5491] opened 2019-06-18 22:53 UTC
Unsure what it means to have negative left members, but there must be a bug in the code which tracks how many of the membership events in a room are for left users...

```
matrix=> select * from matrix.room_stats where left_members < 0 order by left_members asc limit 1;
                room_id                 |     ts     | bucket_size | current_state_events | joined_members | invited_members | left_members | banned_members | state_events 
----------------------------------------+------------+-------------+----------------------+----------------+-----------------+--------------+----------------+--------------
 !XZRkbGFMRqNOBdwevA:irc.snt.utwente.nl | 1560816000 |       86400 |                22909 |         260639 |               0 |      -237739 |              0 |       135253
```

for instance.

**Comment by hawkowl** [comment] 2019-07-08 11:54
closing as a duplicate of https://github.com/matrix-org/synapse/issues/5423

**Closed by hawkowl** 2019-07-08 11:54 UTC
Labels: bug, p2
