### ISSUE TITLE
Incorrect login flow when somebody tries to log in with a capitalized user ID in combination with ldap_auth_provider

### ISSUE THREAD

**Issue by FrankNagel** [matrix-org/synapse#12494] opened 2022-04-19 10:04 UTC
### Description

We use `ldap_auth_provider.LdapAuthProvider` as password provider for synapse. If someone tries to log in to our synapse
instance with a capitalized local part of the user ID the operation seems to succeed but the server returns an invalid user ID
and the provided macaroon token is not recognized later on.

### Steps to reproduce
- Prerequisites
  - Synapse Server with `ldap_auth_provider.LdapAuthProvider` as password provider
  - Matrix Client which makes no consistency checks on a given user ID (i.e. Element Web Version 1.10.7)
- Try to log in with a valid user ID, but capitalize some or all of the letters
   ```JSON
   {
     "type": "m.login.password",
     "password": "XXX",
     "identifier": {
       "type": "m.id.user",
       "user": "TEST"
     },
     "initial_device_display_name": "matrix.uni-marburg.de (Firefox, Linux)"
   }
   ```
   This seems to succeed and the server returns an `access_token`. But note that the `user_id` contains the unaltered 
  local part of the user ID as given by the user.
   ```JSON
   {
     "user_id": "@TEST:matrix.uni-marburg.de",
     "access_token": "syt_TmFnZWxmcg_QJUOneAbKBZtoXHhKKlC_0lvgyI",
     "home_server": "matrix.uni-marburg.de",
     "device_id": "LJPAAHKWEF",
     "well_known": {
       "m.homeserver": {
         "base_url": "https://matrix-homeserver.uni-marburg.de/"
       }
     }
   }
   ```
  Subsequent requests of the client fail with the following error message:
   ```JSON
   {
     "errcode": "M_UNKNOWN_TOKEN",
     "error": "Invalid macaroon passed.",
     "soft_logout": false
   }
   ```

I would expect the synapse server to either implicitly convert the user id to lowercase or fail the login immediately
with a meaningful error message that the user ID is invalid.

### Version information

- **Homeserver**: matrix.uni-marburg.de

If not matrix.org:

- **Version**: 1.56.0+bullseye1

- **Install method**: apt package from `https://packages.matrix.org/debian bullseye/main amd64 Packages`

- **Platform**:
  - Debian Bullseye
  - VM

**Comment by H-Shay** [comment] 2022-04-21 21:20
Just to clarify, there are two possible cases that login could refer to: 
The first is when a user is logging in to synapse for the first time authenticating against the LDAP server. In this case, a matrix id will be generated for them. 
The second case is when a user has successfully logged into synapse in the past authenticating against the LDAP server, and should have a matrix id associated with their LDAP credentials. 
It appears from your question that you are referring to the second case, but I just wanted to make sure.

**Comment by H-Shay** [comment] 2022-04-21 22:38
Also, if possible, can you give an example of one of the subsequent requests?

**Comment by FrankNagel** [comment] 2022-04-22 08:13
In my initial comment above I described the second case with existing matrix id.

The failing HTTP requests (Error 401) of the Element client which occur after the apparently successful login are:
```
GET https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/thirdparty/protocols
GET https://matrix-homeserver.uni-marburg.de/_matrix/client/unstable/room_keys/version
GET https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/capabilities
GET https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/voip/turnServer
POST https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/keys/upload
POST https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/logout
POST https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/keys/query
GET https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/pushrules/
PUT https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/presence/%40mAtrix_test_1%3Amatrix.uni-marburg.de/status
```

Logfile excerpt:
```
2022-04-22 09:44:55,830 - synapse.rest.client.login - 278 - INFO - POST-985027 - Got login request with identifier: {'type': 'm.id.user', 'user': 'mAtrix_test_1'}, medium: None, address: None, user: None
2022-04-22 09:44:55,981 - ldap_auth_provider - 178 - INFO - sentinel - User authenticated against LDAP server: ldap://ldap04.hrz.uni-marburg.de:389 - cleartext - user: uid=matrix_test_1,ou=REDACTED - not lazy - bound - open - <local: 137.248.1.46:32831 - remote: 192.168.1.45:389> - tls started - listening - SyncStrategy - internal decoder
2022-04-22 09:44:55,981 - synapse.storage.database - 748 - WARNING - sentinel - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
2022-04-22 09:44:55,981 - synapse.storage.database - 808 - WARNING - sentinel - Starting db connection from sentinel context: metrics will be lost
2022-04-22 09:44:55,983 - synapse.storage.database - 748 - WARNING - sentinel - Starting db txn 'store_device' from sentinel context
2022-04-22 09:44:55,983 - synapse.storage.database - 808 - WARNING - sentinel - Starting db connection from sentinel context: metrics will be lost
2022-04-22 09:44:55,985 - synapse.util.metrics - 133 - WARNING - sentinel - Starting metrics collection 'notify_device_update' from sentinel context: metrics will be lost
2022-04-22 09:44:55,988 - synapse.handlers.auth - 974 - INFO - sentinel - Logging in user @mAtrix_test_1:matrix.uni-marburg.de on device XJZZDOWZIS
```

**Comment by FrankNagel** [comment] 2022-04-22 08:20
The other case, a first time login, fails with a misleading error message, too.

```
POST https://matrix-homeserver.uni-marburg.de/_matrix/client/r0/login
{
  "type": "m.login.password",
  "password": "XXX",
  "identifier": {
    "type": "m.id.user",
    "user": "mAtrix_test_1"
  },
  "initial_device_display_name": "matrix.uni-marburg.de (Firefox, Linux)"
}

HTTP Error 403
{
  "errcode": "M_FORBIDDEN",
  "error": "Invalid password"
}
```

Logfile excerpt:
```
2022-04-22 09:28:48,081 - synapse.rest.client.login - 278 - INFO - POST-976954 - Got login request with identifier: {'type': 'm.id.user', 'user': 'mAtrix_test_1'}, medium: None, address: None, user: None
2022-04-22 09:28:48,227 - ldap_auth_provider - 178 - INFO - sentinel - User authenticated against LDAP server: ldap://ldap01.hrz.uni-marburg.de:389 - cleartext - user: uid=matrix_test_1,ou=REDACTED - not lazy - bound - open - <local: 137.248.1.46:47123 - remote: 172.25.1.123:389> - tls started - listening - SyncStrategy - internal decoder
2022-04-22 09:28:48,228 - synapse.storage.database - 748 - WARNING - sentinel - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
2022-04-22 09:28:48,228 - synapse.storage.database - 808 - WARNING - sentinel - Starting db connection from sentinel context: metrics will be lost
2022-04-22 09:28:48,229 - synapse.handlers.auth - 1037 - WARNING - sentinel - Attempted to login as @mAtrix_test_1:matrix.uni-marburg.de but they do not exist
```

**Comment by H-Shay** [comment] 2022-04-22 21:18
Thank you for the information, it's very helpful. In the case of a first-time login, the behavior you are describing is reflected in the code, so it is expected but probably not desired. I will check in with the team and see how we want to handle that case. 

The second login case is slightly more confounding. It would be really helpful if you could provide a logfile excerpt from the time around the failing subsequent requests, i.e. what is recorded after a seemingly successful login followed by a failed request -> and the failed request itself if possible. Thanks again for reporting this and the information you have already provided.

**Comment by H-Shay** [comment] 2022-04-25 23:14
It appears this is a duplicate of https://github.com/matrix-org/matrix-synapse-ldap3/issues/72, I am closing this in favor of that issue.

**Closed by H-Shay** 2022-04-25 23:14 UTC
Labels: T-Defect, X-Needs-Discussion
