### ISSUE TITLE
The password based user interactive auth requires a top level user field in the auth field.

### ISSUE THREAD

**Issue by poljar** [matrix-org/synapse#8558] opened 2020-10-15 16:39 UTC
### Description

As the title mentions, the password based user interactive auth seems to require a top level `user` field in the `auth` field.
I haven't checked the other user interactive auth types, but at least the password based one requires this.

### Steps to reproduce

After doing a request that requires user interactive auth the server returns this 
```json
{
    "flows": [
        {
            "stages": [
                "m.login.password"
            ]
        }
    ],
    "params": {},
    "session": "sboloUTeNsVdqMtuoJdBniSV"
}
```
We now create the same request but provide authentication info, for example, for a [delete_devices](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-delete-devices) request:
```json
{
    "auth": {
        "identifier": {
            "type": "m.id.user",
            "user": "example"
        },
        "password": "wordpass",
        "session": "sboloUTeNsVdqMtuoJdBniSV",
        "type": "m.login.password"
    },
    "devices": [
        "ACJOOAHTKD"
    ]
}
```

This fails with a 400 status code, bad request, the body for the response is as follows:
```json
{
    "errcode": "M_MISSING_PARAM",
    "error": ""
}
```

After double checking the spec for a missing parameter in my request I decided to see what Element does:
```json
{
    "devices":["JBUVJRJFBT"],
    "auth":{
        "session":"YTVZEVtoLTVcQYkTcpPLSIgP",
        "type":"m.login.password",
        "user":"@example:localhost",
        "identifier":{
            "type":"m.id.user",
            "user":"@example:localhost"
        },
        "password":"wordpass"
    }
}
```

Notice the additional user field, adding this field indeed makes the previous request succeed. As far as I can tell this isn't required, nor mentioned in the [UIAA section of the spec](https://matrix.org/docs/spec/client_server/latest#password-based).

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

- **Homeserver**:
A local installation was used to test this.
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
1.20.1

- **Install method**:
Package manager.
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
ArchLinux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2020-10-15 16:51
I believe this is a duplicate of #5665.

**Closed by clokep** 2020-10-15 16:51 UTC
