### ISSUE TITLE
Purge Room API fails to remove all rows from state_groups_state

### ISSUE THREAD

**Issue by Ralith** [matrix-org/synapse#6566] opened 2019-12-18 19:36 UTC
### Description

Invoking the `/_synapse/admin/v1/purge_room` endpoint on a room removes many, but not all, rows from `state_groups_state` (other tables not investigated).

### Steps to reproduce

- `select count(*) as num_rows from state_groups_state where room_id = '!PcCidzjUKXHKImhTrB:matrix.org';` => 159049493
- `curl -XPOST "https://example.com/_synapse/admin/v1/purge_room?access_token=$ACCESS_TOKEN" -d "{ \"room_id\": \"!PcCidzjUKXHKImhTrB:matrix.org\" }"` => `{}`
- `select count(*) as num_rows from state_groups_state where room_id = '!PcCidzjUKXHKImhTrB:matrix.org';` => 997223

### Version information

- **Homeserver**: ralith.com

If not matrix.org:

- **Version**: 1.6.1

- **Install method**: NixOS module

- **Platform**: NixOS on dedicated atom server

**Comment by Ralith** [comment] 2019-12-18 19:40
Furthermore, multiple attempts to purge `!QtykxKocfZaZOUrTwp:matrix.org` fail to remove *any* rows, even as each attempt indicates success.

**Comment by richvdh** [comment] 2019-12-24 23:02
I assume it has managed to remove all the rows from `state_groups`?

The problem is that `state_groups_state` lacks an index on `room_id` so we can't just delete the rows from `state_groups_state`; instead we look up the state groups to delete from `state_groups` and then delete the relevant groups.

So that explains why it still doesn't do anything on a second attempt. What it doesn't explain is why it fails on the first attempt. There are two possibilities:
* the relevant state groups lack entries in `state_groups` for some reason, so we don't know that we have to purge the rows from `state_groups_state`
* the purge transaction got as far as deleting the rows from `state_groups`, but then failed to remove the rows from `state_groups_state`.

Logs from the *first* purge attempt would be useful in determining which of these is the problem.

**Comment by richvdh** [comment] 2020-03-17 21:36
closing this pending the information needed to investigate.

**Closed by richvdh** 2020-03-17 21:36 UTC
Labels: info-needed

**Comment by Ralith** [comment] 2020-03-17 22:12
What recourse is available for cleaning up the millions of orphaned rows?

**Comment by richvdh** [comment] 2020-07-09 14:30
@Ralith : are the orphaned rows in question in (a) `state_groups` or (b) `state_groups_state` ? 

For case (a), https://github.com/erikjohnston/synapse-find-unreferenced-state-groups is a thing that helps find unreferenced state groups and clear them out.

For case (b) (the rows have gone from `state_groups` but there are still orphaned rows in `state_groups_state`), you might be able to build a list of such rows with a `SELECT` query and then run a series of `DELETE`s.

**Comment by Ralith** [comment] 2020-07-09 17:19
I have rows for both ostensibly-purged rooms in `state_groups`, but a comparatively trivial number: only 365 for `!PcCidzjUKXHKImhTrB:matrix.org`, and 1531 for `'!QtykxKocfZaZOUrTwp:matrix.org'`. I'll try Erik's tool, thanks! From the warning, I gather it's safe to run deletes for orphaned rooms, or when synapse is shut down, but generally not for live rooms when synapse is running?

**Comment by richvdh** [comment] 2020-07-09 17:25
yes.

**Comment by rettichschnidi** [comment] 2021-06-29 17:44
For all victims of the spam wave in «Matrix HQ»: Using synapse-find-unreferenced-state-groups (still) works!

After closing down Matrix HQ (!OGEhHVWSdvArJzumhm:matrix.org) using Synapse Admin on my homeserver, I was left with 2.5M rows for this room in the state_groups_state stable. Using synapse-find-unreferenced-state-groups deleted all of those. Did not shut down Synapse while doing so, as the room got deleted before already.

**Comment by lnicola** [comment] 2022-05-20 11:31
I'm seeing about 700K rows in `current_state_delta_stream` and more than 40M rows in `state_groups_state` for rooms that should have been purged (ref. #12730). At some point purging failed because of a serialization error.

Unfortunately, `synapse-find-unreferenced-state-groups` doesn't seem to work. I can delete the rows manually, but I don't know exactly what tables I should be looking at.
