### ISSUE TITLE
The default OIDC handler ignores email scope when creating new users

### ISSUE THREAD

**Issue by tucnak** [matrix-org/synapse#12605] opened 2022-05-02 13:02 UTC
### Description

I've set up a SSO interface using OIDC (OpenID Connect) and the default mapping provider that goes with it.

I can see quite clearly from the debug logs that it's actually able to retrieve the email scope successfully, but it won't reflect in the client as such.

homeserver.yaml
```yaml
oidc_providers:
  - idp_id: backend
    idp_name: "Hrest.org"
    issuer: "https://api.myweb.site/oauth2"
    client_id: "synapse"
    client_secret: "synapse-secret"
    scopes: ["openid", "profile", "email"]
    user_profile_method: "userinfo_endpoint"
    allow_existing_users: true
    user_mapping_provider:
      config:
        localpart_template: "{{ user.sub }}"
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}"
```

homeserver.log
```
2022-05-02 01:07:47,603 - synapse.handlers.oidc - 882 - DEBUG - GET-10- Userinfo for OIDC login:
{'sub': 'Brody40', 'name': 'Ilya Kowalewski', 'given_name': 'Ilya', 'family_name': 'K', 'preferred_username': 'Brody40', 'email': 'badt@aletheia.icu', 'email_verified': True, 'locale': 'en'}j
2022-05-02 01:07:47,620 - synapse.handlers.sso - 519 - DEBUG - GET-10- Retrieved user attributes from user mapping provider: 
UserAttributes(localpart='brody40', confirm_localpart=False, display_name='Ilya K', emails=['badt@aletheia.icu']) (attempt 0)
```

Even though that seems to be the case, when opening the user profile in Element web, it doesn't show said email as belonging to said user.

### Steps to reproduce

- Set up a OIDC provider with default mapping
- Make an authorisation using client_secret method
- Confirm with logs that the email has been retrieved
- Check for user's email information, it's not been set.

I would expect the user to indeed have the login email set.

### Version information

Our homeserver is running Synapse [v1.57.1](https://hub.docker.com/layers/synapse/matrixdotorg/synapse/v1.57.1/images/sha256-c30ec59505505392ae13e51f6cadf912a8873b12e7fa3765e5fbbefb86ede6a3?context=explore).

- **Version**:

v1.57.1

- **Install method**:

Docker, docker-compose

- **Platform**:

Debian 10

**Comment by H-Shay** [comment] 2022-05-02 20:56
Thanks for the report! It's unclear to me from this information whether this is a bug in Synapse or a bug in Element web, especially given that the email is being successfully retrieved and stored. Would you mind opening this bug against https://github.com/vector-im/element-web/issues and see what they say about it? In the meantime I will leave this issue open and if it turns out to not be a bug in Element web will investigate further.

**Comment by richvdh** [comment] 2022-05-03 13:23
Perhaps you could explain what exactly you mean by:

> Check for user's email information, it's not been set.

how are you checking this?

**Comment by loelkes** [comment] 2022-05-16 12:06
I can add some detail about this. My issue is *slighty* different but I think not enough to open a new one:

User information from OIDC is only fetch at the initial user creation and never again. If you add the *email_template* to the *user_mapping_provider* later existing users will not be updated. If a users email changes this change is never reflected. If you set the log level of the sso and oidc handler and log in with existing and new accounts it's clearly visible that user information is only fetched and successfully stored with the initial user creation.

**Comment by squahtx** [comment] 2022-07-14 13:52
@tucnak Could you explain how you're checking user emails in Element Web? There isn't a way to do so, as far as I'm aware. A screenshot might help.

**Comment by tucnak** [comment] 2022-07-15 05:45
@squahtx Sure, Settings &rarr; General &rarr; Email addresses (Element)

**Comment by tucnak** [comment] 2022-07-15 05:48
@richvdh Well, yeah, I'm simply using the user's account once logged in, and checking out the recovery email or whatever, which is supposed to be set in the OIDC handler via email_template, and this is 100% what I'm doing, and `user.email` is 100% what I'm passing, you can see this in the homeserver log along the subject, preferred_username, and the locale of all things.

**Comment by tucnak** [comment] 2022-07-15 05:54
@clokep Can we get some fancy labels, and hopefully— the attention for this issue? Honestly, this is not too big of a deal because when jacked on OIDC you wouldn't ever need to reset your password anyway, but now that we're at [The Stone Cross Foundation of Ukraine](https://hrest.org) are finally scaling up, including our Matrix chat server we would want to supply our users with better email notifications, and stuff like that so it's becoming more of an issue.

**Comment by tucnak** [comment] 2022-07-15 13:35
@squahtx I don't think it's the same, as it's not the matter of _updating_ user profile data, in fact I'm talking about 100% new user logins (with localparts never seen before)

**Comment by squahtx** [comment] 2022-07-15 13:39
I see

**Comment by richvdh** [comment] 2022-07-27 10:17
@tucnak I'm afraid I've not been able to reproduce this. Please could you supply more complete Synapse logs showing the creation of a new user?

**Comment by richvdh** [comment] 2022-08-11 19:45
I'm going to close this for now, as we'll need logs to be able to investigate further.

**Closed by richvdh** 2022-08-11 19:45 UTC
Labels: A-SSO, S-Minor, T-Defect, X-Needs-Info
