### ISSUE TITLE
ValueError: The key must be exactly 32 bytes long when trying to join room or invite

### ISSUE THREAD

**Issue by Linuxine** [matrix-org/synapse#6813] opened 2020-01-30 12:39 UTC
Before updating my homeserver to synapse 1.9.0, I had to migrate the database from SQLite to PostgreSQL. The migration script did fail a few time, partially because I am on CentOS7, so every lib is quite old, so I have a virtualenv for python, a custom compiled SQLite, and custom install of PostgreSQL... I did manage to migrate the database, but a few table were missing, that were not present in my SQLite db, but expected in PostgreSQL.

Now I have version 1.9.1, and the instance is quite stable, except that I cannot join a room, or invite an external user to join my room, I get the following error :
```
2020-01-30 13:19:25,286 - synapse.http.server - 110 - ERROR - PUT-98953- Failed handle request via 'FederationSendServlet': <SynapseRequest at 0x7efc3247e3c8 method='PUT' uri='/_matrix/federation/v1/send/1580220122420' clientproto='HTTP/1.1' site=8448>
Traceback (most recent call last):
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/federation/transport/server.py", line 303, in new_func
    origin = await authenticator.authenticate_request(request, content)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/federation/transport/server.py", line 157, in authenticate_request
    origin, json_request, now, "Incoming request"
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/crypto/keyring.py", line 860, in _handle_key_deferred
    _, key_id, verify_key = yield verify_request.key_ready
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/crypto/keyring.py", line 339, in do_iterations
    yield self._attempt_key_fetches_with_fetcher(f, remaining_requests)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/crypto/keyring.py", line 397, in _attempt_key_fetches_with_fetcher
    results = yield fetcher.get_keys(missing_keys)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/crypto/keyring.py", line 459, in get_keys
    res = yield self.store.get_server_verify_keys(keys_to_fetch)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 495, in runInteraction
    **kwargs
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 543, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 540, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 378, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/data_stores/main/keys.py", line 92, in _txn
    _get_keys(txn, batch)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/data_stores/main/keys.py", line 85, in _get_keys
    verify_key=decode_verify_key_bytes(key_id, bytes(key_bytes)),
  File "/home/matrix/synapse/lib/python3.6/site-packages/signedjson/key.py", line 100, in decode_verify_key_bytes
    key = nacl.signing.VerifyKey(key_bytes)
  File "/home/matrix/synapse/lib/python3.6/site-packages/nacl/signing.py", line 71, in __init__
    nacl.bindings.crypto_sign_PUBLICKEYBYTES,
nacl.exceptions.ValueError: The key must be exactly 32 bytes long
2020-01-30 13:24:23,556 - synapse.crypto.keyring - 361 - ERROR - - Unexpected error in _get_server_verify_keys: [Failure instance: Traceback: <class 'nacl.exceptions.ValueError'>: The key must be exactly 32 bytes long
```
It seems there is an issue with a key ? maybe a parameter I have to change when upgrading from 1.8 to 1.9 ?

**Comment by richvdh** [comment] 2020-01-30 13:28
check the `server_signature_keys` table for the server that you are having trouble with.

**Comment by richvdh** [comment] 2020-01-30 13:28
possibly related: https://github.com/matrix-org/synapse/issues/5312

**Comment by Linuxine** [comment] 2020-01-30 13:51
Thanks @richvdh for the anwser ! I was trying to interact with matrix.org. I have 2 lines on this table for this server, with 2 different keys... should I drop one ? or both ? is there an impact when clearing this table, or are the keys re-fetched from the server if empty ?

**Comment by richvdh** [comment] 2020-01-30 14:16
I think they will be re-fetched

can you paste the data you have

**Comment by Linuxine** [comment] 2020-01-30 14:21
Okay, I have :
```matrix=# select * from server_signature_keys where server_name='matrix.org' ;
 server_name |     key_id     | from_server |  ts_added_ms  |                                                                                                                      verify_key                                                 
                                                                     | ts_valid_until_ms 
-------------+----------------+-------------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------+-------------------
 matrix.org  | ed25519:auto   | matrix.org  | 1579762058619 | \x232835342031333620313836203930203136372033203134332036382033382036332031362031343120363620313638203330203230372034203232392034203137302032323320313639203233320a20203838203231
3420323337203133332032303120393920323533203138352031343029           |     1576767829750
 matrix.org  | ed25519:a_RXGa | matrix.org  | 1579762058619 | \x23283135312031393320323233203138332031353420313531203432203132352031313120313234203132322032323420323232203135382036322039312032303020342034352035203130340a202032343020323231
20313139203338203733203131302034392032343920313637203231382031393629 |     1579831050873

```

**Comment by richvdh** [comment] 2020-01-30 15:37
interesting. Are there other rows in `server_signature_keys` which have verify_key values which are `\x`-encoded in this way, or do others look ok?

**Comment by richvdh** [comment] 2020-01-30 15:38
wait, they are supposed to look like that. sorry, hold on.

**Comment by richvdh** [comment] 2020-01-30 16:19
so those rows *are* bogus, though not because of the reason I initially thought. They should look like this:

```
synapse=# select server_name,key_id,verify_key, length(verify_key) from server_signature_keys where server_name='matrix.org';
 server_name |     key_id     |                             verify_key                             | length 
-------------+----------------+--------------------------------------------------------------------+--------
 matrix.org  | ed25519:a_RXGa | \x97c1dfb79a972a7d6f7c7ae0de9e3e5bc8042d0568f0dd7726496e31f9a7dac4 |     32
 matrix.org  | ed25519:auto   | \x3688ba5aa7038f44263f108d42a81ecf04e504aadfa9e858d6ed85c963fdb98c |     32
```

as the error says, `length(verify_key)` should be 32 for each row.

It looks like there's some sort of odd double-encoding going on with your data. I think it's safe to delete, but I'd be interested in investigating how we got into this situation. Do you have the the original sqlite database? If so, could you run the following query on it:

```sql
select key_id,typeof(verify_key),hex(verify_key) from server_signature_keys where server_name='matrix.org';
```

**Comment by Linuxine** [comment] 2020-01-30 16:57
Yes I have the sqlite database, I will run you query tomorrow :)

**Comment by Linuxine** [comment] 2020-01-31 10:10
Hi,

here is the result of the query in my previous sqlite database: 
```
sqlite> select key_id,typeof(verify_key),hex(verify_key) from server_signature_keys where server_name='matrix.org';
ed25519:a_RXGa|blob|97C1DFB79A972A7D6F7C7AE0DE9E3E5BC8042D0568F0DD7726496E31F9A7DAC4
ed25519:auto|blob|3688BA5AA7038F44263F108D42A81ECF04E504AADFA9E858D6ED85C963FDB98C
```
In my sqlite, all the length(verify_key) where indeed of 32; whereas in my posgres db, it was between 117 and 125... I am not sure it is really a bug of the migration script ; as I had some trouble to launch it, with all my custom binaries and path, and maybe it crashed before performing the migration of this table. As I was not able to perform completely the migration, I used pgloader to migrate my db from sqlite to postgres, and I guess it miss some of the specificity of the db. I had a bunch of missing column and indexes too, that I had to add manually, looking into data_stores/main/schema/full_schemas/54/full.sql.postgres. 

So I guess my db is not fully migrated yet...  While we are on the subject, I still have a bunch of indexes named for example "idx_407019_sqlite_autoindex_remote_media_cache_thumbnails_1" (with sqlite in the name). Should I keep them, or not ?

**Comment by richvdh** [comment] 2020-01-31 11:21
hrrrm.... if you're going to write your own scripts to migrate from sqlite to postgres, I think you're on your own: we don't have time to support that.

>  I still have a bunch of indexes named for example "idx_407019_sqlite_autoindex_remote_media_cache_thumbnails_1" (with sqlite in the name). Should I keep them, or not ?

No idea where they came from.

I'm going to close this as it sounds like it's not a bug in our system.

**Closed by richvdh** 2020-01-31 11:21 UTC

**Comment by richvdh** [comment] 2020-01-31 11:23
(if you want help investigating why `synapse_port_db` fails on your system, that's a thing we could look at)

**Comment by Linuxine** [comment] 2020-01-31 12:23
Indeed, I think it was not really a bug, sorry for the confusion ! And thanks for the help ! I think the idx_sqlites indexes might have been added by pgloader when migrating the database from sqlite to postgres. I will manage to fix the database by myself. As for the fail of the script, I don't know if it is worth investigating for you, as I said, I had a lot of custom binaries and pathes to be able to launch synapse, so I might have mixed up some of them and that might have caused the fail...
