### ISSUE TITLE
Account validity: admin account has expired

### ISSUE THREAD

**Issue by ukcb** [matrix-org/synapse#7292] opened 2020-04-16 18:44 UTC
I start a script at irregular intervals for various tasks that require an admin account. I have activated the option for account validity configuration (synapse v1.12.x).

```
account_validity:
  enabled: true
  period: 6w
  renew_at: 1w
```

At some point my system admin was gone.

```
ROOM_ID: !xxxxxxxxxxxxx
{
    "errcode": "ORG_MATRIX_EXPIRED_ACCOUNT",
    "error": "User account has expired"
}
```

An admin's account shouldn't expire?

**Comment by babolivier** [comment] 2020-04-17 09:22
Currently the account validity doesn't differentiate between server admin and normal user. This is intentional, as some server admins wanted that to apply to other admins. What we could do is add an extra config flag to ignore server admins.

**Comment by richvdh** [comment] 2020-04-20 15:10
closing, since it's expected behaviour

**Closed by richvdh** 2020-04-20 15:10 UTC
