### ISSUE TITLE
Can't open attached images in a new tab anymore

### ISSUE THREAD

**Issue by nukeop** [matrix-org/synapse#15959] opened 2023-07-19 12:39 UTC
### Description

I used to be able to open media links of this format in a new tab:
https://server.com/_matrix/media/v3/download/server.com/media-id

Now, the default behavior is to download them, instead of opening them. I am running the latest Synapse.

### Steps to reproduce

Using Element, attach an image. Middle-click the posted image.

### Homeserver

My own homeserver originally, and it affects any server running the latest synapse

### Synapse Version

v1.88.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL, single server

### Workers

Single process

### Platform

N/A

### Relevant log output

```shell
N/A
```

**Comment by reivilibre** [comment] 2023-07-21 16:11
This was more or less an intentional choice (but perhaps one we should change our mind on), the change appeared in #15680.

The idea is that this is for security: not all documents are really safe to present inline to a web browser.

I can see us changing our minds by e.g. having a small list of media types which we allow to be opened inline, e.g. `text/plain`, `image/png`, `image/jpeg`, etc.

cc @Half-Shot who was talking about this earlier on since this change currently provides an impediment to the way that IRC bridges use the media store as a pastebin for long pieces of text.

**Comment by itsrachelfish** [comment] 2023-07-21 23:56
Duplicate of #15885? Either way, please fix this! :pray:

**Comment by reivilibre** [comment] 2023-07-24 10:54
indeed, duplicate of #15885 :)

**Closed by reivilibre** 2023-07-24 10:54 UTC
Labels: A-Media-Repository, S-Tolerable, T-Enhancement, X-Regression, O-Occasional
