### ISSUE TITLE
room stats are not working for rooms created since the initial background_update

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5624] opened 2019-07-05 14:20 UTC

**Comment by hawkowl** [comment] 2019-07-05 14:27
The problem is that https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/storage/stats.py#L423 isn't being run when there's a new room https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/handlers/stats.py#L234 .

The fix should add that, with proper values (so probably all zeroes except for the state events or whatever?) 

Plus, https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/storage/stats.py#L442 , which let this pass by silently, should raise an exception instead, or go and calculate the room stats itself (since raising an exception would explode existing users without rerunning the background update, which sucks for matrix.org).

**Comment by richvdh** [comment] 2019-07-05 14:29
incidentally, there is an `update_stats` at  https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/storage/stats.py#L414 which seems unused but should possibly be used here?

**Comment by reivilibre** [comment] 2019-07-15 14:11
I've been looking into some of the code surrounding this issue.

### Some notes

* I don't think that room creation & upgrade needs any special effort — as long as `update_state_deltas` is fixed.
* If you have room_stats for H but are missing room_stats for M,
then after a background room_stats update, you will have room_stats for M but be missing them for H.
(This happens because the setup code only selects rooms without stats to have stats calculated,
but the actual process of calculating stats discards all existing stats)

### Possible solutions

1. Make room creation & upgrade insert a zero-row into room_stats AND fix the background update process so it doesn't discard existing progress.
    * This relies on us scheduling another background update (but only a partial one) in the migration SQL to fix existing installations.
2. Make update_state_deltas calculate the stats if required instead of ignoring a lack of stats rows.
    * This would mean that current rooms missing stats would have them generated as soon as a new state event is added into them.
    * However, this means that these rooms won't appear in the room directory (after #4043) until a state event occurs.
        * For this reason, it is probably desirable to fix the background update process to not discard existing progress and also schedule one using the migration SQL.
3. For completeness' sake, both options could be combined.

**Comment by reivilibre** [comment] 2019-07-18 10:40
As part of this issue, I also need to schedule a new background update.

It's not clear (to me) whether it should discard previous room_stats or not. In general, they are likely to be wrong due to #5423 and #5690. Any thoughts on this?

I will block this background issue on #5690 #5423 #5710 being resolved.

**Comment by erikjohnston** [comment] 2019-09-05 09:57
Fixed in #5971

**Closed by erikjohnston** 2019-09-05 09:57 UTC
Labels: bug, p1
