### ISSUE TITLE
SSO CAS login issue

### ISSUE THREAD

**Issue by trogeat** [matrix-org/synapse#9862] opened 2021-04-22 10:24 UTC
### Description

SSO CAS configuration don't work as expected.

### Steps to reproduce

First i configured a cas service in homeserver.yaml:

```
server_name: "domain.io"
public_baseurl:"im.domain.io"

cas_config:
  enabled: True
  server_url: "https://im.domain.io/_matrix/cas_server.php"

```
when reaching the server i'm getting redirected in loop to :
https://im.domain.io/_matrix/client/r0/login/sso/redirect?redirectUrl=https%3A%2F%2Felement.domain.io%2F%23%2F

If i reach:
https://im.domain.io/_matrix/cas_server.php/login?service=https%3A%2F%2Fim.domain.io%2F_matrix%2Fclient%2Fr0%2Flogin%2Fcas%2Fticket%3FredirectUrl%3Dhttps%253A%252F%252Felement.domain.io%252F%2523%252F
i'm getting loggued and redirected properly

It seems that synapse doesn't redirect the user to the cas server url and i don't understand why.
The location header in the previous version was good and in 1.31.0 we get stuck in a redirect loop.

I'm running synapse server v1.31.0.
I don't get this problem in v1.28

- **Version**: v1.31.0
- **Install method**: from sources (yunohost)
- **Platform**: VM / Debian buster

**Comment by trogeat** [comment] 2021-04-22 16:56
1.28.0: GET on https://im.domain.io/_matrix/client/r0/login
```
{
  "flows": [
    {
      "type": "m.login.cas"
    },
    {
      "type": "m.login.sso"
    },
    {
      "type": "m.login.token"
    },
    {
      "type": "uk.half-shot.msc2778.login.application_service"
    }
  ]
}
```

1.31.0: GET on https://im.domain.io/_matrix/client/r0/login
```
{
  "flows": [
    {
      "type": "m.login.cas"
    },
    {
      "type": "m.login.sso",
      "identity_providers": [
        {
          "id": "cas",
          "name": "CAS"
        }
      ]
    },
    {
      "type": "m.login.token"
    },
    {
      "type": "uk.half-shot.msc2778.login.application_service"
    }
  ]
}
```

is this the attended result with the same configuration ?

**Comment by Starz0r** [comment] 2021-04-22 19:05
I'm seeing a similar issue running 1.32.2 with OpenID Connect configured. Looks like there might have been a regression past 1.28.0.

**Comment by Starz0r** [comment] 2021-04-23 09:29
Was asked personally to post my OIDC homeserver configuration:
```yaml
oidc_providers:
  - idp_id: keycloak
    idp_name: "My Personal IdP"
    skip_verification: false
    issuer: "https://external.domain.tld/auth/realms/XXXXX"
    client_id: "matrix"
    client_secret: "XXXXX"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
```

**Comment by richvdh** [comment] 2021-04-23 10:07
this sounds similar to https://github.com/matrix-org/synapse/issues/9680. Please see the advice there.

**Comment by trogeat** [comment] 2021-04-23 17:01
@richvdh you where right, in my case header host was missing !

`
        proxy_set_header Host $host;
`

According to documentation : https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md

My setup was working in 1.28.0 but not with latest versions.

Thanks !

**Comment by clokep** [comment] 2021-04-23 17:14
Glad you figured it out. I think Synapse always expected this, but it become required in v1.29.0: https://github.com/matrix-org/synapse/blob/release-v1.31.0/UPGRADE.rst#requirement-for-x-forwarded-proto-header

I'm going to close this.

**Closed by clokep** 2021-04-23 17:14 UTC
Labels: X-Needs-Info
