### ISSUE TITLE
Pushes should be bundled in 1 request to push gateway

### ISSUE THREAD

**Issue by vjoomens** [matrix-org/synapse#6852] opened 2020-02-05 16:34 UTC
My first experience with a large setup is that the push gateway is overloaded with requests coming from synapse. I believe the gateway is called for every pusher available. So if I have a chat group with say 10K users, all with active pushers and no push rules set, the gateway will receive 10K requests. This leads to performance issues on both sides.

A simple solution for this example would be to bundle the push into 1 request, listing the devices with the push keys in the payload.

**Comment by richvdh** [comment] 2020-02-05 17:05
duplicate of https://github.com/matrix-org/synapse/issues/1455 I think

**Closed by richvdh** 2020-02-05 17:05 UTC
