### ISSUE TITLE
Infinte Redirect Loop For SSO Login When Behind A Reverse Proxy

### ISSUE THREAD

**Issue by warricksothr** [matrix-org/synapse#10492] opened 2021-07-28 13:00 UTC
### Description

When SSO is enabled, the public_baseurl is set to an `https` scheme endpoint, and the site is running 
behind a reverse proxy that terminates ssl and forwards all traffic as `http` the SSO login redirect will 
infinitely loop because the request is for an `http` endpoint but the `public_baseurl` is pointed at an
`https` endpoint. The root of the issue is the simple `startswith` bytes check inside the SSO redirect
that is meant to make sure that cookies are set on the right domain (#9436).

The `public_baseurl` mentions that it should be set to the same scheme as what is behind the reverse proxy
however that results in clients like element web being unable to resolve resources behind the reverse proxy
as they aren't always obeying `301` and `302` redirects for resources and exposing the `http` endpoint externally is
undesirable.

#### Workaround

The current work around used on my homeserver (matrix.nulloctet.com) is to point the reverse proxy at the `https`
backend for synapse and leave the `public_baseurl` as `https://matrix.nulloctet.com/`. This results in no loop because
the web request is on the same scheme as the `public_baseurl`. However I am not a fan of terminating an `TLS` connection only to remote proxy another `TLS` connection behind the scene. I also do not want to run synapse 
completely public as that would be a regression in functionality and would be a special snowflake among the other 
services I run.

#### Proposed Solution

The check of the request and the `public_baseurl` should completely ignore the scheme, as only the dns name
is required to match for cookies to be correctly set.

### Steps to reproduce

- Set public_baseurl to use `https` scheme
- Setup; reverse proxy that forwards all https traffic to the http endpoint of synapse
- Enable an SSO provider
- Attempt to login with that provider

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.nulloctet.com

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
Versions Tested:
- **Version**: 1.38.1
- **Version**: 1.37.1
- **Version**: 1.35.0

- **Install method**: Docker-Compose
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu Linux 20.04 HWE with Docker CE
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment] 2021-07-28 14:37
@warricksothr Have you seen [the docs](https://matrix-org.github.io/synapse/latest/reverse_proxy.html) on ensuring that `X-Forwarded-Proto` is configured properly by your reverse proxy? I believe that fixes this issue.

**Comment by warricksothr** [comment] 2021-07-28 14:53
@clokep I have my server defined with the `X-Forwarded-Proto` as defined in the reverse proxy definition

Here is the relevant nginx location block with the workaround I mentioned above. I tested this previously with the proxy_pass pointed to the `http` port with the correct matching scheme.
```
        location ~* ^(\/_matrix|\/_synapse\/client) {
                proxy_pass https://localhost:8448;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;
        }
```

Unfortunately the code that is responsible for this check just looks at just the request to see if it is secure and doesn't check any additional headers.

```python
def get_request_uri(request: IRequest) -> bytes:
    """Return the full URI that was requested by the client"""
    return b"%s://%s%s" % (
        b"https" if request.isSecure() else b"http",
        _get_requested_host(request),
        # despite its name, "request.uri" is only the path and query-string.
        request.uri,
    )
```

and then does an assertion that the request and the `public_baseurl` start with the same bytes

```python
...
        requested_uri = get_request_uri(request)
        baseurl_bytes = self._public_baseurl.encode("utf-8")
        if not requested_uri.startswith(baseurl_bytes):
...
```

This does bring up a potentially cleaner fix than the one I have proposed in #10494 however it might also be a bit more opaque and error prone when that header is missing.

**Comment by clokep** [comment] 2021-07-28 14:56
I believe the `isSecure` check takes into account the multiple headers:

https://github.com/matrix-org/synapse/blob/95e47b2e782b5e7afa5fd2afd1d0ea7745eaac36/synapse/http/site.py#L448-L476

**Comment by warricksothr** [comment] 2021-07-28 15:04
Hmm... I'll have to do a bit more digging then. Thanks for the information!

**Comment by warricksothr** [comment] 2021-07-28 15:10
I agree, this code definitely is supposed to take that into account. My configuration is setup with the appropriate header on the proxied request, but I still received the following log entries.

```
**2021-07-27 21:08:25,279 - synapse.rest.client.v1.login - 555 - INFO - GET-26 - Requested URI http://matrix.nulloctet.com/_matrix/client/r0/login/sso/redirect/oidc-keycloak?redirectUrl=https%3A%2F%2Felement.nulloctet.com%2F is not canonical: redirecting to https://matrix.nulloctet.com/_matrix/client/r0/login/sso/redirect/oidc-keycloak?redirectUrl=https%3A%2F%2Felement.nulloctet.com%2F**
```

🤔

**Comment by jerrykan** [comment] 2021-08-05 04:10
I just upgrade from Synapse v1.28.0 to v.1.39.0 and hit this issue. Using the Apache setting `ProxyPreserveHost  On` seems to have resolved the problem. Ideally it would be good if Synapse looked at the first entry in `X-Forwarded-Host` request header so this extra settings isn't required (we have multiple reverse proxies sitting in front of Synapse, so we had to make the change on each of those).

**Comment by richvdh** [comment] 2021-08-05 09:31
I'm pretty sure this is a configuration error in the reverse-proxy. If there's any doubt, I suggest taking a `tcpdump` of the traffic between the reverse-proxy and Synapse, and inspecting the headers.

In the meantime, I'm going to close this.

**Closed by richvdh** 2021-08-05 09:31 UTC
Labels: X-Needs-Info

**Comment by warricksothr** [comment] 2021-08-05 22:32
Apologies for the delay, I did switch back to the http port to do some debugging, and here's part of a TCP dump of the traffic across the poxy during an OIDC redirect.

```
.GET /_matrix/client/r0/login/sso/redirect/oidc-keycloak?redirectUrl=https%3A%2F%2Felement.nulloctet.com%2F HTTP/1.0
X-Forwarded-For: <redacted ipv4 address>
X-Forwarded-Proto: https
Host: matrix.nulloctet.com
Connection: close
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-language: en-us
accept-encoding: gzip, deflate, br
```

To me this looks correct, both `X-Forwarded-For` and `X-Forwarded-Proto` are set, yet a redirect is being triggered.

**Comment by warricksothr** [comment] 2021-08-05 22:37
@richvdh is there anything else you'd want to see from a TCP dump, I didn't see a whole lot but am not necessarily sure what I'd be looking for. I have a snapshot of 30 seconds of traffic during which the OIDC redirect is triggered that I'd be willing to share. However it is full of ipv4 addresses so I'm not willing to share such a log publicly without redacting all of those addresses.

**Comment by warricksothr** [comment] 2021-08-05 22:51
Here's the full reverse proxy configuration for reference

```
server {
        listen 173.208.198.250:80 ;
        listen [::]:80 ;
        server_name matrix.nulloctet.com;

        location / {
                return 301 https://$host$request_uri;
        }
}

server {
        listen [::]:443 ssl ipv6only=on;
        listen 173.208.198.250:443 ssl;
        ssl_certificate /etc/letsencrypt/live/matrix.nulloctet.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/matrix.nulloctet.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        root /var/www/html;
        server_name matrix.nulloctet.com;

        # This value also needs to be changed in the homeserver.yaml file
        client_max_body_size 500M;

        location ~* ^(\/_matrix|\/_synapse\/client) {
                proxy_pass http://localhost:8447;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;
        }
}
```

**Comment by richvdh** [comment] 2021-08-06 08:18
silly question maybe, but have you set `x_forwarded: true` in the listener configuration in the homeserver config file? cf https://matrix-org.github.io/synapse/latest/reverse_proxy.html#homeserver-configuration

**Comment by warricksothr** [comment] 2021-08-06 13:17
Not a silly question at all. I don't know how I missed this configuration parameter for the http port. With `x_forwarded: true` set, redirecting is working correctly. Thank you @richvdh and @clokep for your help!

This syanpse configuration file is a few years old, I'll need to go through it again to make sure I haven't missed other settings as I've upgraded.

**Comment by richvdh** [comment] 2021-08-06 14:20
great, glad you got it sorted.

I think it's a shame that https://matrix-org.github.io/synapse/latest/reverse_proxy.html#homeserver-configuration is easy to overlook. It might be better to move that section above the "Reverse-proxy configuration examples". If you'd like to make a PR to do so, that would be great!

**Comment by warricksothr** [comment] 2021-08-06 16:41
Sure, I'll open a PR later today for the documentation change to move that section toward the top of the Reverse Proxy documentation.

**Comment by VPaulV** [comment] 2023-07-02 12:58
Hi guys, sorry for not creating a new issue, but my problem seems to be very similar to the one described here. 

I have an nginx -> synapse setup with Authentik-based SSO login. The problem of an infinite redirect loop persists even if I set up `x_forwarded: true` and use proper headers (`X-Forwarded-Proto` etc). To get rid of this loop, I have to set the `public_baseurl` to HTTP instead of HTTPS. Then SSO works as it should, but the problem is that the Element desktop client doesn't redirect requests properly, and I cannot log in with the desktop client (the web client works and FluffyChat also works). Is there any workaround for this problem?

**Comment by VPaulV** [comment] 2023-07-05 17:34
Had the same problem, despite the proper config had infinite loop. Was able to resolve by updating nginx to the last stable version
