### ISSUE TITLE
Default rate limit on joins breaks profile picture and display name updates to propagate to rooms

### ISSUE THREAD

**Issue by csett86** [matrix-org/synapse#8148] opened 2020-08-23 19:44 UTC
### Description

Since #8008 joins are rate-limited. As profile picture updates are send out to all rooms as a burst of "join" events, these are effectively broken and only distributed to a very small number of rooms (~3).

### Steps to reproduce

- Have Synapse 1.19.0
- Change profile picture or display name in user preferences
- Profile picture / display name update is not reflected in rooms, but logs are filled with:
```
2020-08-23 21:11:23,608 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,622 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,642 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,658 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,689 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,703 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,720 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,753 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.de - 429: Too Many Requests
2020-08-23 21:11:23,765 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,786 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,807 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,830 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,846 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,865 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,882 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,899 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,909 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.io - 429: Too Many Requests
2020-08-23 21:11:23,924 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.xyz - 429: Too Many Requests
2020-08-23 21:11:23,938 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:23,964 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.im - 429: Too Many Requests
2020-08-23 21:11:23,979 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
2020-08-23 21:11:24,008 - synapse.handlers.profile - 297 - WARNING - PUT-149100 - Failed to update join event for room !REDACTED:example.org - 429: Too Many Requests
```
- Setting the join rate-limiting burst to something larger than the rooms you are in, the profile updates are again working.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org
- **Homeserver**: settgast.org

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.19.0

- **Install method**: package manager
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by compu42** [comment] 2020-08-24 02:48
can confirm! was causing me a huge headache.

I feel that this should be tagged as a fire. The way to temporarily fix this is to set `rc_joins` to a higher burst, which may have to be a high number and can easily be abused.

**Comment by babolivier** [comment] 2020-08-24 14:38
Thanks for your report! This is indeed a pretty serious regression caused by #8008, which will be fixed in https://github.com/matrix-org/synapse/pull/8153, and released in 1.19.1 later this week.

**Comment by babolivier** [comment] 2020-08-24 17:16
https://github.com/matrix-org/synapse/pull/8153 has been merged into the release branch, so I'm closing this issue.

**Closed by babolivier** 2020-08-24 17:16 UTC

**Comment by babolivier** [comment] 2020-08-27 10:44
FYI the fix to this issue has just been released in Synapse v1.19.1 :slightly_smiling_face:

**Comment by csett86** [comment] 2020-08-27 10:58
Dear @babolivier, thank you for quickly fixing and releasing the patched version!

**Comment by compu42** [comment] 2020-08-27 17:21
Excellent!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
