### ISSUE TITLE
/createRoom returns spurious `alias` property

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/synapse#6879] opened 2020-02-09 20:01 UTC
### Description

According to the spec, `_matrix/client/r0/createRoom` returns only the `room_id`. When setting an alias while creating the room, synapse also returns that, which is not spec compliant. Relevant spec bit: https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-createroom

### Steps to reproduce

- create room with alias
- look at response
- find additional property that the spec does not list

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: jcg.re

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: Synapse version 1.7.3, but that bit hasn't changed since then (am updating to 1.9.1 atm)

- **Install method**: docker container
<!-- examples: package manager/git clone/pip  -->

- **Platform**: n/a
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment] 2020-02-09 22:38
I don't think it's correct to say that returning *additional* properties makes for a non-compliant implementation. As a client, you are free to ignore it (indeed you should, since other server implementations will not return it).

**Comment by jcgruenhage** [comment] 2020-02-10 11:00
What good is it to return unspecced additional properties? Best case they are ignored, worst case clients start to depend on them and make the ecosystem divert from spec and stuff starts to break when  people use other servers.

Aside of that, depending on the way clients verify/parse json, adding additional properties breaks stuff. Room creation in matrix-nio was broken because of this. Does the spec say that additional properties may be returned?

**Comment by Half-Shot** [comment] 2020-02-10 11:17
@jcgruenhage It may be that you can specify a `room_alias_name` which is just the localpart of an alias. While you can obviously construct this yourself, I can imagine this is why the property is returned?

**Comment by jcgruenhage** [comment] 2020-02-10 11:23
@Half-Shot Then it might make sense to add to the spec that this should be returned when an alias is passed for room creation. Clients shouldn't use information returned by a server that is unspecced (for reasons brought forward earlier), so returning it has no use at all

**Comment by richvdh** [comment] 2020-02-10 11:35
> Does the spec say that additional properties may be returned?

if it doesn't, it should. This is one of the key reasons for using json rather than a rigid binary format: it gives the ability to introduce new fields without breaking existing clients. Any client which breaks when additional properties are returned should be considered buggy.

I'm not saying that synapse *should* return this property. I am saying that returning it doesn't make it non-compliant.

IIRC on this particular property we went round the loop a while ago and decided it was redundant and should not be added to the spec.

**Comment by jcgruenhage** [comment] 2020-02-10 12:04
>  it gives the ability to introduce new fields without breaking existing clients

makes sense, yeah

> Any client which breaks when additional properties are returned should be considered buggy.

@poljar I think that means all `"additionalProperties": False` lines should be removed from the schema file in nio then

> I am saying that returning it doesn't make it non-compliant.

It's at least an unspecced deviation, but I sort of agree now.

I still think that returning unspecced properties is harmful. Having additional properties be a non-breaking change is something else than returning additional stuff that is neither specced nor to-be-specced. Can we get this removed from synapse?

**Comment by poljar** [comment] 2020-02-10 12:14
> @poljar I think that means all `"additionalProperties": False` lines should be removed from the schema file in nio then
> 
Sure.

**Comment by DMRobertson** [comment] 2022-08-25 12:44
The name of the property seems to be `room_alias`:

https://github.com/matrix-org/synapse/blob/357561c1a2b2da6d1a7ad1e2340217fee18cc2b1/synapse/handlers/room.py#L1007-L1008

The v1.3 spec still only mandates a `room_id` field in its 200 response, see https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3createroom . The openAPI [definition](https://github.com/matrix-org/matrix-spec/blob/ca466b5a572a867de79ba9077e6445265b841c96/data/api/client-server/create_room.yaml#L231-L241) doesn't have `"additionalProperties": false`, which means that additional properties are allowed, c.f. [here](https://github.com/matrix-org/matrix-spec/pull/1162#discussion_r921378998).

> IIRC on this particular property we went round the loop a while ago and decided it was redundant and should not be added to the spec.

The best reference for this I could find was https://github.com/matrix-org/synapse/issues/10321 which was apparently moved from the spec repo.

I suggest we close this issue in favour of that one.

**Comment by DMRobertson** [comment] 2022-08-25 12:45
Duplicate of #10321.

**Closed by DMRobertson** 2022-08-25 12:44 UTC
Labels: z-p3, z-maintenance, A-Create-Room
