### ISSUE TITLE
Unable to dynamicly generate thumbnail

### ISSUE THREAD

**Issue by tleydxdy** [matrix-org/synapse#3393] opened 2018-06-13 15:05 UTC
### Description

Cannot get server to generate thumbnails for rooms

### Steps to reproduce

I cleared my client's cache and they can't get any avatars from remote server, after clearing remote media cache using the admin api, most avatar and their thumbnail are fixed. However when riot android are requesting the avatars, server creates a lof of the folloing error(independent of the size or the server etc). I'm using dynamic thumbnail. 
```
2018-06-13 10:47:03,167 - synapse.http.server - 102 - ERROR - GET-2634 - Failed handle request via <function _async_render_GET at 0x[address]>: <XForwardedForRequest at 0x[address] method='GET' uri='/_matrix/media/v1/thumbnail/terracrypt.net/dgrTvNjRusPYHJNDqgvscjwZ?width=40&height=40&method=crop' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 79, in wrapped_request_handler
    yield h(self, request)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 77, in _async_render_GET
    width, height, method, m_type
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 220, in _select_or_generate_remote_thumbnail
    desired_height, desired_method, desired_type
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/rest/media/v1/media_repository.py", line 553, in generate_remote_exact_thumbnail
    t_width, t_height, t_type, t_method, t_len
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 429, in _simple_insert
    self._simple_insert_txn, table, values,
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 325, in runInteraction
    result = yield self.runWithConnection(inner_func, *args, **kwargs)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 370, in runWithConnection
    inner_func, *args, **kwargs
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 366, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 321, in inner_func
    func, *args, **kwargs
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 246, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 449, in _simple_insert_txn
    txn.execute(sql, vals)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 87, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/USER_NAME/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 117, in _do_execute
    sql, *args
psycopg2.IntegrityError: duplicate key value violates unique constraint "remote_media_cache_thumbnails_media_origin_media_id_thumbna_key"
DETAIL:  Key (media_origin, media_id, thumbnail_width, thumbnail_height, thumbnail_type)=(terracrypt.net, dgrTvNjRusPYHJNDqgvscjwZ, 40, 40, image/png) already exists.
```

### Version information

- **Homeserver**: Self-hosted homeserver. but relates to remote media only

- **Version**:       0.31.1 
- **Install method**: pip
- **Platform**:       Debian 9

**Comment by turt2live** [comment] 2018-06-13 15:06
Duplicate of https://github.com/matrix-org/synapse/issues/2182

**Closed** 2018-06-13 16:16 UTC
