### ISSUE TITLE
Remote media purge leaves a lot of directories

### ISSUE THREAD

**Issue by namazso** [matrix-org/synapse#16229] opened 2023-09-03 06:58 UTC
### Description

I recently noticed my remote media folder grew to 5 GB again, so I ran a media purge for all files (timestamp in future). However, after finishing the remote media folder still weighed 500 MB. It turns out that was the combined size of the empty folders left behind.

### Steps to reproduce

- run homeserver for a while
- run media purge
- observe leftover empty folders

### Homeserver

namazso.eu

### Synapse Version

1.91.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL 15

### Workers

Single process

### Platform

Linux 6.5.0

### Relevant log output

```shell
-
```

**Comment by DMRobertson** [comment] 2023-09-04 16:18
Relevant source: https://github.com/matrix-org/synapse/blob/3de82bb2af28f56696a79bf41ccffc81385b6e2c/synapse/media/media_repository.py#L934-L970

I suppose when deleting a file on disk we could try to `os.rmdir()` its parent directories, catching and ignoring OSError due to the directory not being empty?

Would probably also want to do something similar in `delete_old_local_media`.

As a one-time cleanup job I guess one could `find -empty -type d -delete`?

**Comment by clokep** [comment] 2023-09-05 13:02
Duplicate of #7690.

**Closed by clokep** 2023-09-05 13:02 UTC
Labels: A-Media-Repository, S-Minor, T-Defect, O-Uncommon
