### ISSUE TITLE
web_client: False doesn't turn off the in built angular web client.

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/synapse#2113] opened 2017-04-09 13:11 UTC
`web_client: False` in homeserver.yaml config file doesn't turn off the built-in angular web client.
Removing webclient from `resources.names: [client, webclient]` turns it off.

Need to confirm that this was the intended purpose of `web_client: False`.
If yes, I'll try to fix this.

**Comment by Darlelet** [comment] 2017-08-02 11:34
I'm also facing this issue

**Comment by Darlelet** [comment] 2017-08-02 11:35
#1883

**Comment by Darlelet** [comment] 2017-08-02 11:35
Check out #1883

**Comment by ewtoombs** [comment] 2017-08-04 19:21
I had the same problem. These are the changes I made to my homeserver.yaml:

--- homeserver.yaml-	2017-08-04 15:20:14.653075263 -0400
+++ homeserver.yaml	2017-08-04 15:18:22.910135500 -0400
@@ -50,7 +50,7 @@
 pid_file: /etc/synapse/homeserver.pid
 
 # Whether to serve a web client from the HTTP/HTTPS root resource.
-web_client: True
+web_client: False
 
 # The root directory to server for the above web client.
 # If left undefined, synapse will serve the matrix-angular-sdk web client.
@@ -106,7 +106,7 @@
         # List of resources to host on this listener.
         names:
           - client     # The client-server APIs, both v1 and v2
-          - webclient  # The bundled webclient.
+            #- webclient  # The bundled webclient.
 
         # Should synapse compress HTTP responses to clients that support it?
         # This should be disabled if running synapse behind a load balancer
@@ -126,7 +126,8 @@
     x_forwarded: false
 
     resources:
-      - names: [client, webclient]
+      - names: [client]
+        #- names: [client, webclient]
         compress: true
       - names: [federation]
         compress: false

**Comment by aaronraimist** [comment] 2018-12-02 19:40
Duplicate of #1417

**Closed** 2018-12-04 10:11 UTC
