### ISSUE TITLE
Type-annotate all function arguments and internal variables

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8351] opened 2020-09-18 13:14 UTC
**Description:**

Related to #8347, ~~(partially) blocked till 3.5 is deprecated~~

The goal is to;
- [x] Convert existing `name = ... # type:` comments to `name: type = ...`. (see "`com2ann` progress" below)
- [ ] Put type annotations on every function's parameters and return type.
- [ ] Put `name: type` annotations on;
  - [ ] Every class variable.
  - [ ] Every instance variable (declared in `__init__()` functions), unless;
    - They're constructing another instance (`self.thing = Thing()`) (dubious, see https://github.com/matrix-org/synapse/pull/10382#discussion_r671357795)
    - They're getting assigned a non-container literal (`1`, `b""`, `""`, etc. but not `None`)
    - The assignment comes from a function/method call (`self.thing = hs.get_another_thing()`), given that the function signature is known and inferrable.

---

<details>
<summary><code>com2ann</code> progress</summary>

- [x] `tests/` (#10350)
- [x] `synapse/`
	- [x] #10382
	- [x] #10381
	- [x] #10380
- [x] Other (#10418)

(`com2ann` changes comment type annotations to inline type annotations, `name = ... # type:` to `name: type = ...`, this is possible since python 3.6, and standard across the python ecosystem.)

</details>

**Comment by clokep** [comment] 2020-09-18 13:21
> This could probably finally allow a `mypy` linter to run with CI, to catch future inconsistencies.

`mypy` runs in CI on a subset of the code-base, see https://github.com/matrix-org/synapse/blob/develop/mypy.ini#L9

**Comment by clokep** [comment] 2020-09-18 13:21
> blocked till 3.5 is deprecated

This isn't blocked? Python 3.5 supports type annotations.

**Comment by ShadowJonathan** [comment] 2020-09-18 14:41
> > blocked till 3.5 is deprecated
> 
> This isn't blocked? Python 3.5 supports type annotations.

not variable type annotations, but you're right about it not being completely blocked

**Comment by ShadowJonathan** [comment] 2021-04-05 11:54
A large portion of this can be fixed with `com2ann`, see https://github.com/matrix-org/synapse/issues/9131#issuecomment-776568681

**Comment by ShadowJonathan** [comment] 2021-07-09 11:46
Updated description, the previous one was vague and also implied setting type annotations for every variable inside non-init functions, which i think is overdoing it a little bit, type-annotating all other places noted should already correctly resolve those spots.

**Comment by ShadowJonathan** [comment] 2021-07-15 15:30
I found some interesting `mypy` optional errors that could be enabled to enforce type annotations;

https://mypy.readthedocs.io/en/stable/error_code_list2.html

- Check that type arguments exist [type-arg]
  (Errors on `List`, requires `List[<type>]`)
  
- Check that every function has an annotation [no-untyped-def]

- Check that comparisons are overlapping [comparison-overlap]

  ```py
  def is_magic(x: bytes) -> bool:
    # Error: Non-overlapping equality check 
    #        (left operand type: "bytes", right operand type: "str")  [comparison-overlap]
    return x == 'magic'
  ```

- (maybe) Check that no untyped functions are called [no-untyped-call]

- Check that function does not return Any value [no-any-return]

**Comment by clokep** [comment] 2022-08-15 11:13
I think this is essentially a duplicate of #11271.

**Closed by clokep** 2022-08-15 11:13 UTC
Labels: T-Task
