### ISSUE TITLE
[QUESTION] Why does the homeserver have data if the user is banned from an external server?

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [matrix-org/synapse#15125] opened 2023-02-21 18:01 UTC
**Description:**
Let's say that 
- A user (will be referred to as User A, is not registered on the main matrix.org homeserver) 
- Was testing the banning system on a relay(i am suggesting any forms of ban and then unban, but for now, i will go with this idea) from an external server  (may be any channel that is not in User A's homeserver, i.e. the matrix homeserver or any other server for that matter).
- "It Works!" he says after being banned
- He tried to unban himself from the relay (supported by the relay obviously), however he is still denied access
- He reaches out to a friend that is admin in the room, he says "but you aren't on the ban list!"
- After scouring the internet he found out that it was a bug in matrix-synapse and to workaround this bug he would be required to create a new account then rejoin that room to "refresh his homeserver of that server's banned members list" 
- He tries it, and it works, and he gets back in.
*real story btw*
##### Don't make the homeserver handle the ban list, just when a user joins, the homeserver should instead "ask the connecting server if this user is banned" then block/allow access, and if this is unfeasible by some technicality, then atleast make the homeserver refresh the status of their members every say 1 day or whatever the admin sets it up to

**Comment by reivilibre** [comment] 2023-02-21 18:22
By relay, I'm assuming you mean another homeserver?

I'll try and answer your question in more depth, though.

> Why should the homeserver handle the banned members list?

Because Matrix is decentralised in such a way that, once you're in a room, you (the homeserver) don't need to ask any other servers whether an event is allowed or not: you can determine it for yourself. (This also means that other servers can go offline and everything still works!)

Of course, homeservers can also handle rooms that only have one homeserver in them, so they need to be able to handle the ban lists for these cases.

> Don't make the homeserver handle the ban list, just when a user joins, the homeserver should instead "ask the connecting server if this user is banned" then block/allow access, and if this is unfeasible by some technicality, then atleast make the homeserver refresh the status of their members every say 1 day or whatever the admin sets it up to

There's no such thing as a 'connecting server'; all the servers that talk to each other in a room are homeservers. They're all equal in the system (caveat: some of them might have admin users).

Now, as for what I think your real concern is:

The homeserver doesn't get told when it's unbanned (because it's technically no longer in the room), but still enforces the existing ban.

It's a known issue — see https://github.com/matrix-org/synapse/issues/1563.

If you think it's not a duplicate of this issue, please comment and we can reopen.


P.S.

> real story btw

I'm glad you're not just making up a fake story for the sake of it. :P

**Closed by reivilibre** 2023-02-21 18:22 UTC

**Comment by Damaj301damaj-lol** [comment] 2023-02-21 18:40
> By relay, I'm assuming you mean another homeserver?
> 
> I'll try and answer your question in more depth, though.
> 
> > Why should the homeserver handle the banned members list?
> 
> Because Matrix is decentralised in such a way that, once you're in a room, you (the homeserver) don't need to ask any other servers whether an event is allowed or not: you can determine it for yourself. (This also means that other servers can go offline and everything still works!)
> 
> Of course, homeservers can also handle rooms that only have one homeserver in them, so they need to be able to handle the ban lists for these cases.
> 
> > Don't make the homeserver handle the ban list, just when a user joins, the homeserver should instead "ask the connecting server if this user is banned" then block/allow access, and if this is unfeasible by some technicality, then atleast make the homeserver refresh the status of their members every say 1 day or whatever the admin sets it up to
> 
> There's no such thing as a 'connecting server'; all the servers that talk to each other in a room are homeservers. They're all equal in the system (caveat: some of them might have admin users).
> 
> Now, as for what I think your real concern is:
> 
> The homeserver doesn't get told when it's unbanned (because it's technically no longer in the room), but still enforces the existing ban.
> 
> It's a known issue — see https://github.com/matrix-org/synapse/issues/1563.
> 
> If you think it's not a duplicate of this issue, please comment and we can reopen.
> 
> 
> P.S.
> 
> > real story btw
> 
> I'm glad you're not just making up a fake story for the sake of it. :P
> 

Thanks for contacting me!, i haven't checked if it was a known issue, sorry about that.
However isn't the idea that "a ban expires after X day,week, etc" then when the user wants to reconnect it can check if the user is still banned or not?
_P.S: if you haven't noticed already, i am not experienced in this :P, i am just saying things that i think might be possible, but amazing work yall are doing_
