### ISSUE TITLE
upload file 401 {"errcode":"M_UNKNOWN_TOKEN","error":"Access token has expired","soft_logout":true}

### ISSUE THREAD

**Issue by hafizworqapp** [matrix-org/synapse#11258] opened 2021-11-05 09:35 UTC
hi when do upload file inside  https://synapse.api.worqapp.com/_matrix/media/r0/upload with valid accesstoken is show error above. But when calling for api https://synapse.api.worqapp.com/_matrix/client/r0/sync?filter=%7B%22room%22%3A%7B%22state%22%3A%7B%22lazy_load_members%22%3Atrue%7D%7D%7D&set_presence=online&timeout=30000&since=s148768_997987_14124_382919_181953_6972_1_120454_1 (load member) with that accesstoken no problem? why?

my code as below :

`val clientBuilder = OkHttpClient.Builder()
            //
            val authToken = "Bearer ".plus(SessionHolder.currentSession?.sessionParams?.credentials?.accessToken)

            Timber.d("Authtoken: $authToken")
            //Create a new Interceptor.
            val headerAuthorizationInterceptor = Interceptor { chain ->
                var request = chain.request()
                val headers = request.headers.newBuilder()
                    .add("Authorization", authToken)
                    .build()
                request = request.newBuilder().headers(headers).build()
                chain.proceed(request)
            }

            // OkHttp Logging interceptor
            val logging = HttpLoggingInterceptor()
            logging.level = HttpLoggingInterceptor.Level.BODY

            clientBuilder
                .addInterceptor(logging)
                .addInterceptor(headerAuthorizationInterceptor)

            val retrofit = Retrofit.Builder()
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .client(clientBuilder.build())
                .baseUrl(baseUrl)
                .build()

            return retrofit.create(UploadMatrixAPI::class.java)`

calling function upload file

`@POST("/_matrix/media/r0/upload")
    fun uploadImageToMatirxServer(@Body file: RequestBody): Observable<UploadImageMatrixResp>`

file UploadImageMatrixResp
`data class UploadImageMatrixResp(val content_uri: String?, val smsSent: String?)`

set datatype:
`var file = PathUtils.fileFromContentUri(applicationContext, contentUriOfFile)
            var mime = PathUtils.getMimeType(applicationContext, contentUriOfFile)

            if(file.exists() && ((file.length() / 1024) / 1024) >10) {
                Toast.makeText(this, "Attachment exceeds the 10MB limit", Toast.LENGTH_LONG).show()
                finish()
                return Unit
            }
            val disposable = uploadManualMedia(file, mime).subscribe ({ onFirstSuccess: UploadImageMatrixResp? ->
                val firstMediaUrl = onFirstSuccess?.content_uri
                Timber.d("Uri : $firstMediaUrl")
                //val content = buildMediaContent(mime, filteredClipData.size, bitmap, file, firstMediaUrl)
                //remainingClipData = filteredClipData
                //room?.sendEvent(EventType.MESSAGE, content.toContent())
            },
                {onError ->
                    onError.message?.let {

                    }
                })`

function upload

` private fun uploadManualMedia(file: File, mimeType:String): Observable<UploadImageMatrixResp>{
        val body =  file.asRequestBody(mimeType.toMediaTypeOrNull())
        return matrixAPI.uploadImageToMatirxServer(body)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
    }`

initialize matrix lazy class

`private val matrixAPI by lazy {
        UploadMatrixAPI.createWithBasicAuth(Constants.SYNAPSE_BASE_URL, applicationContext)
    }`

Note: I try to received image from whatapps and I want to share image to my members in list of matrix member active.

**Comment by ShadowJonathan** [comment] 2021-11-05 09:38
What is the Synapse version of the server you're communicating with?

**Comment by hafizworqapp** [comment] 2021-11-05 09:52
implementation 'org.matrix.android:matrix-android-sdk2:1.2.1' i using this latest version

**Comment by ShadowJonathan** [comment] 2021-11-05 10:35
I'm asking for the version of the remote server, it's synapse 1.40.

Are you sure that your session hasn't been deleted by server? By an admin? Maybe even by you logging out the session from another client?

**Comment by reivilibre** [comment] 2021-11-05 11:34
Some questions to help us figure this out:

* What version of Synapse are you using?
* How are you obtaining the access token? For example, are you using the Admin API?
* Are you using the `session_lifetime` or `access_token_lifetime` configuration option in your homeserver configuration?

I don't know why the access token would work for one and not the other; are you sure it still works with `/sync` after it fails for `/upload`? Did it possibly expire between you trying `/upload` and `/sync`?

**Comment by hafizworqapp** [comment] 2021-11-08 01:41
those who has issue like me please dont use ` val lastAuthenticatedSession = matrixAuthService.getLastAuthenticatedSession()` in order to get accesstoken from last session because when time u refresh token in somewhere else this method make u access token is expired. Issue is solve, instead i use this method in order to get latest accesstoken :

`SessionHolder.currentSession`

**Comment by ShadowJonathan** [comment] 2021-11-08 07:58
@hafizworqapp are you saying that your issue is solved? Yes/no please.

**Comment by reivilibre** [comment] 2021-11-08 10:26
I believe you're saying the issue is resolved, so closing this. Thanks!

**Closed by reivilibre** 2021-11-08 10:26 UTC
Labels: X-Needs-Info

**Comment by hafizworqapp** [comment] 2021-11-09 01:45
Yes solve but i give guideline those who has problem same like me. Thank u. U guys awesome.
