### ISSUE TITLE
SAML Problem Login OK, but problem if user password is needed

### ISSUE THREAD

**Issue by vsatmydynipnet** [matrix-org/synapse#7705] opened 2020-06-16 07:36 UTC
Currently running 1.15.0, but server runs since 0.23.x on FreeBSD, using Postgresql.

- User Database on Wordpress
- SAML SSO using SimpleSAMLphp

All works, but problem occurs if trying to setup key backup or anything else requesting the password of the user.  Using the password which is valid for SSO, it fails to accept the password. 

So SSO works for login, but not for changing anything matrix related where password is required.

**Comment by clokep** [comment] 2020-06-16 10:54
This is a duplicate of #7559. The quick answer is to disable passwords in your config.

**Closed by clokep** 2020-06-16 10:54 UTC
